docs/pages_en/advanced/helm/configuration/secrets.md, docs/pages_ru/advanced/helm/configuration/secrets.md
=> docs: notice about .helm/secrets

multiwerf.json, trdl_channels.yaml
=> v1.2 alpha to 1.2.67

multiwerf.json, trdl_channels.yaml
=> v1.1 alpha to 1.1.30

docs/pages_en/advanced/bundles.md
=> docs(bundles): fix typo

pkg/build/conveyor.go, pkg/build/stage/conveyor.go, pkg/build/stage/dependencies.go
=> fix(build): werf does not reset stages storage cache when import source image not found

pkg/host_cleaning/host_cleanup.go
Due to enabled werf's "process exterminator", all werf processes started by the GitLab CI/CD system will watch for parent processes pids, and interrupt itself when one of the parents is gone. But this mechanics does not allow background `werf host cleanup` command to finish its job, so it has been disabled for host cleanup background cmd.
=> fix: host-cleanup procedure not running in gitlab-ci

pkg/host_cleaning/host_cleanup.go, pkg/host_cleaning/local_docker_server.go
=> fix(host-cleanup): host cleanup not working without --docker-server-storage-path option

pkg/storage/manager/storage_manager.go, pkg/storage/stages_storage.go
=> fix: more correct handling of storage.ErrBrokenImage

pkg/true_git/work_tree.go
=> chore: refactor true_git, lost error handler

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2 beta to 1.2.69

cmd/werf/bundle/export/export.go, cmd/werf/bundle/publish/publish.go, cmd/werf/cleanup/cleanup.go, cmd/werf/compose/main.go, cmd/werf/converge/converge.go, cmd/werf/dismiss/dismiss.go
Disable auto host cleanup when buildah mode is used.
=> fix: panic when auto host cleanup runs in some werf commands

pkg/deploy/helm/extra_annotations_and_labels_post_renderer.go
=> fix(helm): don't add annotations and labels to *List Kinds

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2 alpha to 1.2.70

multiwerf.json, trdl_channels.yaml
=> 1.1 alpha to 1.1.31, beta to 1.1.30

cmd/werf/bundle/apply/apply.go, cmd/werf/common/helm.go, cmd/werf/dismiss/dismiss.go, cmd/werf/helm/helm.go, cmd/werf/helm/migrate2to3.go, cmd/werf/render/render.go, go.mod, go.sum
=> fix: WERF_KUBE_CONFIG and WERF_KUBECONFIG environment variables not working

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.71 to 1.2 alpha

pkg/buildah/common.go, pkg/buildah/native_linux.go, pkg/container_runtime/buildah_runtime.go
=> fix(buildah): support Dockerfile builder target param to build specific stage

.github/workflows/docs_tests.yml, .github/workflows/multiwerf_release_publisher.yml
=> ci: use github actions/checkout@v2

go.mod, go.sum
feat(deploy): support server side validation in converge/dismiss commands
Refs: https://github.com/werf/3p-helm/pull/130
Fixes: https://github.com/werf/werf/issues/4191
=> feat(deploy): support server side validation in converge/dismiss commands

go.mod, go.sum
=> chore: up version of buildah and containerd

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2 alpha to 1.2.73

multiwerf.json, trdl_channels.yaml
=> chore(channels): revert 1.2 alpha to 1.2.72

go.mod, go.sum
Refs https://github.com/werf/3p-helm/pull/139.
=> fix(deploy): fix server side validation false positive failure case

pkg/git_repo/remote.go, pkg/ssh_agent/ssh_agent.go
Fixes https://github.com/werf/werf/issues/1948.
=> fix: broken --ssh-key option

go.mod, go.sum
Refs https://github.com/werf/3p-helm/pull/141
=> fix: server dry-run validation breaks helm 2 to 3 transition

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2 alpha to 1.2.75

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2 alpha to 1.2.76

pkg/cleaning/purge.go
=> fix(purge): fix final repo stages deletion

test/e2e/build/build_test.go, test/e2e/kube-run/_fixtures/state0/werf.yaml, test/e2e/kube-run/kube_run_test.go, test/e2e/kube-run/suite_test.go, test/pkg/werf/project.go
=> test: new command `werf kube-run`, refactor

pkg/docker_registry/generic_api.go
Init docker registry mirrors on demand.
=> fix: "unable to get docker system info" error when container runtime not used

go.mod, go.sum
Refs https://github.com/werf/3p-helm/pull/145
=> fix(deploy): fix --set-file giving []uint{} array intead of string

cmd/buildah-test/main.go
=> chore: buildah test update

cmd/werf/main.go
=> fix: temporarily disable broken server-dry-run

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.78 to alpha, 1.2.76+fix1 to beta

cmd/werf/common/common.go, cmd/werf/kube_run/kube_run.go, docs/_includes/reference/cli/werf_kube_run.md, docs/_includes/reference/cli/werf_kubectl_get.md
=> feat(kube-run): add --kube-config, fix --kube-context opts

cmd/werf/main.go, go.mod, go.sum
Refs https://github.com/werf/3p-helm/pull/146
=> fix(server-dry-run): fix "admission webhook ... does not support dry-run"

pkg/cleaning/cleanup.go
=> fix(cleanup): fail when no kubernetes configs available and no --without-kube option specified

.github/workflows/trdl_publisher.yml, scripts/werf-in-image/build-and-publish.sh
=> ci: store images in werf registry

.github/workflows/website_converge_tag.yml, .github/workflows/website_converge_test.yml, .github/workflows/website_review.yml, .github/workflows/website_review_dismiss.yml
This reverts commit b0c9eb261c7db0fad487842a67f6d6d3ac482a04.
=> Revert "chore: move werf.io images to registry.werf.io/werf/werfio"

.github/workflows/trdl_publisher.yml
=> ci: fix deploy multiwerf.json and trdl_channels.yaml

scripts/werf-in-image/build-and-publish.sh
=> ci: store werf images cache in ghcr

pkg/build/build_phase.go, pkg/build/builder/stage_builder.go, pkg/build/conveyor.go, pkg/build/export_phase.go, pkg/build/image.go, pkg/build/stage/base.go, pkg/build/stage/before_install.go, pkg/build/stage/before_setup.go, pkg/build/stage/dependencies.go, pkg/build/stage/dependencies_test.go, pkg/build/stage/docker_instructions.go, pkg/build/stage/dockerfile.go, pkg/build/stage/dockerfile_test.go, pkg/build/stage/from.go, pkg/build/stage/git.go, pkg/build/stage/git_archive.go, pkg/build/stage/git_cache.go, pkg/build/stage/git_latest_patch.go, pkg/build/stage/git_mapping.go, pkg/build/stage/git_mapping_test.go, pkg/build/stage/git_patch.go, pkg/build/stage/install.go, pkg/build/stage/interface.go, pkg/build/stage/setup.go, pkg/build/stage/stage_image.go, pkg/build/stage/user_with_git_patch.go, pkg/build/stages_iterator.go, pkg/container_runtime/legacy_stage_image.go, pkg/storage/manager/storage_manager.go
=> chore(refactor): introduced stage-builder interfaces and stage-image type

pkg/build/build_phase.go, pkg/build/builder/stage_builder.go, pkg/build/stage/data_test.go, pkg/build/stage/dependencies_test.go, pkg/build/stage/dockerfile.go, pkg/build/stage/dockerfile_test.go, pkg/build/stage/stage_image.go, pkg/build/stage/stubs_test.go, pkg/container_runtime/docker_server_runtime.go, pkg/container_runtime/dockerfile_image_builder.go, pkg/container_runtime/image_interface.go, pkg/container_runtime/legacy_interface.go, pkg/container_runtime/legacy_stage_image.go, pkg/storage/repo_stages_storage.go
=> chore(refactor): move DockerfileBuilder from LegacyStageImage to StageBuilderAccessor

pkg/build/stage/data_test.go
Bug in the test code, which was not checking anything related to build args and dependencies.
=> test: fix dependencies test for dockerfile

.github/workflows/trdl_publisher.yml
=> ci: slack notifications about publication of release channels

.github/workflows/trdl_publisher.yml, .github/workflows/website_deployment.yml
=> ci: run publication of release channels only on changes in channel files

pkg/build/build_phase.go, pkg/build/builder/ansible.go, pkg/build/builder/builder.go, pkg/build/builder/shell.go, pkg/build/builder/stage_builder.go, pkg/build/conveyor.go, pkg/build/stage/base.go, pkg/build/stage/before_install.go, pkg/build/stage/before_setup.go, pkg/build/stage/dependencies.go, pkg/build/stage/dependencies_test.go, pkg/build/stage/docker_instructions.go, pkg/build/stage/dockerfile.go, pkg/build/stage/dockerfile_test.go, pkg/build/stage/from.go, pkg/build/stage/git.go, pkg/build/stage/git_archive.go, pkg/build/stage/git_patch.go, pkg/build/stage/install.go, pkg/build/stage/interface.go, pkg/build/stage/setup.go, pkg/build/stage/stubs_test.go, pkg/build/stage/user_with_git_patch.go, pkg/container_runtime/buildah_runtime.go, pkg/container_runtime/docker_server_runtime.go, pkg/container_runtime/interface.go, pkg/container_runtime/perf_check_container_runtime.go
=> chore(stapel-to-buildah): refactor pkg/build/stages to select impelementation based on container-runtime type

cmd/werf/kube_run/kube_run.go
=> feat(kube-run): add --kube-config-base64

cmd/werf/kube_run/kube_run.go
=> fix(kube-run): broken --docker-config

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.80 to 1.2 alpha/beta

pkg/buildah/common.go, pkg/buildah/docker_with_fuse.go, pkg/buildah/native_linux.go
=> refactor(buildah): add Commit method

pkg/buildah/common.go, pkg/buildah/docker_with_fuse.go, pkg/buildah/native_linux.go
=> refactor(buildah): image should be optional for Commit()

pkg/buildah/common.go, pkg/buildah/docker_with_fuse.go, pkg/buildah/native_linux.go
=> refactor(buildah): add Rm method

pkg/buildah/common.go, pkg/buildah/docker_with_fuse.go, pkg/buildah/native_linux.go
=> refactor(buildah): add Config method

integration/suites/docs/cli_test.go
=> test(docs): ignore unreproducible werf-kubectl-get command description

pkg/buildah/common.go, pkg/buildah/docker_with_fuse.go, pkg/buildah/native_linux.go
"touch: cannot touch '/FILE': Permission denied" with Stapel Native
builder fixed.
=> refactor(buildah): add lots of missing parameters

pkg/cleaning/cleanup.go, pkg/cleaning/purge.go, pkg/storage/manager/storage_manager.go
=> refactor(cleanup): do custom tag deletion in parallel and support dry run

pkg/slug/slug.go, pkg/slug/slug_test.go
Sluggification did not work correctly in some cases, not providing idempotence for slugged data. As a result, cleanup failed on getting manifests for custom tag metadata because nonexistent tags were constructed with sluggification.
This PR fixes sluggification by supporting these cases.
=> fix(cleanup): fail on getting manifests for some custom tag metadata

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.82 to alpha, 1.2.81 to beta

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.83 to 1.2 alpha

pkg/docker_registry/api.go, pkg/docker_registry/default.go, pkg/docker_registry/generic_api.go, pkg/docker_registry/harbor.go, pkg/storage/repo_stages_storage.go
=> refactor(cr): handle 404 status code properly

pkg/docker_registry/api.go, pkg/docker_registry/docker_registry.go, pkg/docker_registry/generic_api.go
closes https://github.com/werf/werf/issues/4063
=> refactor(cr): validate stages storage repo address 

pkg/slug/slug.go
closes https://github.com/werf/werf/issues/4332
=> fix(slugification): kubernetes namespace and release name cannot contain dots

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.84+fix1 to 1.2 alpha

go.mod, pkg/build/stage/docker_instructions.go, pkg/buildah/common.go, pkg/buildah/native_linux.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/stapelstagetype.go
=> refactor(stapel-to-buildah): docker instructions stage 

pkg/build/stage/dependencies.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/stapelstagetype.go
Not implemented include-paths, exlclude-paths, owner and group params.
=> feat(stapel-to-buildah): basic implementation of dependencies* stages

pkg/buildah/common.go
=> fix(buildah): use crun instead of runc

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.85 to alpha, 1.2.83+fix1 to beta and ea

multiwerf.json, trdl_channels.yaml
=> chore(channels): v1.2.86 to alpha, v1.2.83+fix2 to beta and ea

.gitignore, Makefile, scripts/images/cloud-data/user-data, scripts/images/template.pkr.hcl
=> feat(buildah): build qemu image for mac

pkg/build/stage/git.go, pkg/build/stage/git_archive.go, pkg/build/stage/git_mapping.go, pkg/build/stage/git_patch.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/stapelstagetype.go
=> feat(stapel-to-buildah): git archive stage implementation

integration/suites/ansible/yarn/werf.yaml
=> fix(tests): fix ansible suite, change deprecated base image

pkg/container_backend/buildah_backend.go
Add support for includePaths, excludePaths, owner, group.
=> refactor(container_backend): support all dep imports parameters

pkg/build/build_phase.go, pkg/build/stage/base.go, pkg/build/stage/before_install.go, pkg/build/stage/before_setup.go, pkg/build/stage/conveyor.go, pkg/build/stage/dependencies.go, pkg/build/stage/dependencies_test.go, pkg/build/stage/docker_instructions.go, pkg/build/stage/dockerfile.go, pkg/build/stage/dockerfile_test.go, pkg/build/stage/from.go, pkg/build/stage/git_archive.go, pkg/build/stage/git_cache.go, pkg/build/stage/git_latest_patch.go, pkg/build/stage/install.go, pkg/build/stage/interface.go, pkg/build/stage/setup.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/docker_server_backend.go, pkg/container_backend/interface.go, pkg/container_backend/perf_check_container_backend.go
=> feat(stapel-to-buildah): implemented dependencies checksum using buildah container backend

cmd/werf/main.go
=> fix(server-dry-run): disable by default server-dry-run mode, enable with DISABLE_SERVER_DRY_RUN=0

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.80+fix3 into stable, 1.2.88 into alpha

pkg/build/build_phase.go
=> chore(refactor): removed unused code

go.mod, go.sum
Refs https://github.com/werf/3p-helm/pull/152
=> fix(deploy): remove server-dry-run helm extension to prevent possible bug

go.mod, go.sum
Refs https://github.com/werf/3p-helm/pull/152
=> [v1.2.83] fix(deploy): remove server-dry-run helm extension to prevent possible bug

go.mod, go.sum
Refs https://github.com/werf/3p-helm/pull/152
=> [v1.2.80] fix(deploy): remove server-dry-run helm extension to prevent possible bug

multiwerf.json, trdl_channels.yaml
=> chore(channels): v1.2.89 into alpha, v1.2.83+fix3 into beta and ea, v1.2.80+fix4 into stable

multiwerf.json, trdl_channels.yaml
=> chore(channels): v1.2.80+fix5 to stable

go.mod, go.sum, pkg/container_backend/buildah_backend.go
=> refactor(buildah_backend): switch to copy-recursive module

cmd/werf/kube_run/kube_run.go
=> feat(kube-run): set --overrides-type=strategic for better merges

go.mod, go.sum
=> fix(container_backend): broken build on windows because of copyrec

Makefile
=> chore: os-independent makefile to build werf target

cmd/werf/cleanup/cleanup.go, docs/_data/werf_yaml.yml, pkg/cleaning/cleanup.go, pkg/config/meta_cleanup.go, pkg/config/raw_meta_cleanup.go
=> feat(cleanup): managing cleanup policies in werf.yaml

multiwerf.json, trdl_channels.yaml
=> chore(channels): v1.2.93 to alpha

Makefile
=> ci(docs): use werf-without-cgo target to check broken links

go.mod, go.sum
Refs https://github.com/werf/3p-helm/pull/168
Refs https://github.com/werf/werf/issues/4155
=> fix(helm): solved broken 3 way merge case when pre-upgrade hook fails

go.mod, go.sum
Refs https://github.com/werf/3p-helm/pull/169
Refs https://github.com/werf/3p-helm/pull/170
=> fix(helm): fix export-values in subcharts case, improve broken 3wm case handling

pkg/build/build_phase.go
Mount ssh-auth-sock and set commit info environment variables when building stapel stage with buildah builder.
=> fix(stapel-to-buildah): added missing ssh-auth-sock and commit related envs, labels and volumes

go.mod, go.sum, pkg/build/publish_images_phase.go
=> fix(publish): override images when related stages are lost (1.1)

go.sum
=> test(docs): fix missing go.sum entry for module (1.1)

go.mod, go.sum
Improved:
* symlink handling
* destination parent dir handling
* recreating chains of (empty) directories in destination
=> fix(imports): recursive copying issues

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.1.32 to 1.1 ea

cmd/werf/kube_run/kube_run.go
=> refactor(kube-run): use native coders for pod overrides

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.101 to ea

cmd/werf/kube_run/kube_run.go, docs/_includes/reference/cli/werf_kube_run.md
=> feat(kube-run): add --copy-to; replace --copy-from-[file|dir] with --copy-from

cmd/werf/kube_run/kube_run.go, docs/_includes/reference/cli/werf_kube_run.md
=> docs(kube-run): fix reference/--help

docs/pages_en/reference/cheat_sheet.md
=> docs(cheat-sheet): add "kube-run --copy-from/to" examples

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.102 to alpha

cmd/werf/bundle/apply/apply.go, cmd/werf/bundle/export/export.go, cmd/werf/bundle/publish/publish.go, cmd/werf/bundle/render/render.go, cmd/werf/converge/converge.go, cmd/werf/dismiss/dismiss.go, cmd/werf/helm/helm.go, cmd/werf/render/render.go, pkg/deploy/helm/chart_extender/bundle.go, pkg/deploy/helm/chart_extender/chart_dependencies_loader.go, pkg/deploy/helm/chart_extender/werf_chart.go, pkg/deploy/helm/chart_extender/werf_chart_stub.go, pkg/deploy/helm/command_helpers/build_chart_dependencies.go, pkg/deploy/helm/extra_annotations_and_labels_post_renderer.go, pkg/deploy/helm/extra_annotations_and_labels_post_renderer_test.go, pkg/deploy/helm/suite_test.go, pkg/werf/global_warnings/global_warnings.go
=> fix: non-strict labels and annotations validation in werf's post-renderer

go.mod, go.sum
Update go-git to experimental unmerged PR with the fix: https://github.com/go-git/go-git/pull/485
=> fix(git): fix error "unable to clone repo: reference delta not found"

pkg/deploy/helm/maintenance_helper/maintenance_helper.go
=> fix(migrate2to3): new target namespace not respected in new Release

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.1.33 to 1.1 alpha, beta

.github/workflows/tests_cleaner.yml
=> ci(tests_cleaner): fix "Unable to resolve action `google-github-actions/setup-gcloud@master`, unable to find version `master`"

.github/workflows/daily_tests.yml
=> ci: fix "Error: The specified go version file at: go.mod does not exist" 

integration/suites/deploy/helm_values1-001/.helm/templates/templates.yaml, integration/suites/deploy/helm_values1-001/.helm/values.yaml, integration/suites/deploy/helm_values1-001/werf.yaml, integration/suites/deploy/helm_values1-002/.helm/templates/templates.yaml, integration/suites/deploy/helm_values1-002/werf.yaml, integration/suites/deploy/helm_values_test.go
Refs https://github.com/werf/werf/issues/4478
=> test: added test to reproduce values bug #4478

pkg/deploy/helm/extra_annotations_and_labels_post_renderer.go
=> fix(post-renderer): fix null value validation panic in annotations and labels

cmd/werf/render/render.go, docs/_includes/reference/cli/werf_render.md
=> fix(render): support for --kube-context param when --validate option used

.github/workflows/daily_tests.yml
=> ci(tests): try to fix daily tests failure

go.mod, go.sum, integration/suites/deploy/helm_values_test.go
Refs https://github.com/werf/kubedog/pull/251
=> fix(cleanup): fix cleanup not using in-cluster kube config when using in-cluster mode

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml, docs/pages_en/advanced/helm/deploy_process/resources_adoption.md, docs/pages_ru/advanced/helm/deploy_process/resources_adoption.md
https://werf.io/documentation/v1.2/advanced/helm/deploy_process/resources_adoption.html
=> feat(docs): New article about resources adoption

cmd/werf/bundle/apply/apply.go, cmd/werf/bundle/render/render.go, docs/_includes/reference/cli/werf_bundle_apply.md, docs/_includes/reference/cli/werf_kubectl_get.md, pkg/deploy/helm/chart_extender/bundle.go, pkg/deploy/helm/chart_extender/helpers/secrets/secrets_runtime_data.go, pkg/deploy/helm/chart_extender/werf_chart.go
=> feat(bundles): --secret-values option for werf-bundle-apply command

integration/suites/deploy/helm_values1-002/.helm/values.yaml
Refs https://github.com/werf/werf/issues/4478
=> test: fix test to reproduce values bug #4478

docs/pages_ru/reference/cheat_sheet.md
=> docs: update cheat sheet ru title

cmd/werf/kube_run/kube_run.go
=> fix(kube-run): better log message when command failed

pkg/deploy/helm/chart_extender/helpers/common_template_funcs.go, pkg/deploy/helm/chart_extender/werf_chart.go, pkg/deploy/helm/chart_extender/werf_chart_stub.go
=> fix(helm): fix werf_secret_file not working in werf helm template command

cmd/werf/dismiss/dismiss.go
=> fix(dismiss): --with-namespace creates empty namespace if release already uninstalled

go.mod, go.sum
When we defined some Values in the subchart and also some of these
Values defined in this chart's parents and we are passing some values
via export-values to the same keys, then the merge result was wrong.
=> fix(export-values): propagate result of export-values to all parent charts Values

multiwerf.json, trdl_channels.yaml
=> chore(channels): v1.2.112 into alpha

cmd/werf/bundle/export/export.go, cmd/werf/bundle/publish/publish.go, cmd/werf/converge/converge.go, cmd/werf/render/render.go, pkg/storage/manager/storage_manager.go
=> fix(final-repo): service values .Values.werf.repo should use --final-repo instead of --repo

scripts/werf-in-image/build-and-publish.sh, scripts/werf-in-image/werf.yaml
=> ci: publish rock-solid images

multiwerf.json, trdl_channels.yaml
=> chore(channels): v1.2.109+fix2 to stable,ea

cmd/werf/bundle/apply/apply.go, cmd/werf/converge/converge.go, cmd/werf/helm/helm.go, cmd/werf/helm/install.go, cmd/werf/helm/template.go, cmd/werf/helm/upgrade.go, pkg/deploy/helm/external_deps_generator.go
=> feat(external-deps): external dependencies now available for `werf helm`

multiwerf.json, trdl_channels.yaml
=> chore(channels): 1.2.116 to alpha, 1.2.115 to beta

pkg/host_cleaning/local_docker_server.go
=> fix(host-cleanup): do not remove v1.2 local storage images

pkg/util/linux_container.go
=> fix(buildah): improve whether we are in container detection

cmd/werf/bundle/apply/apply.go, cmd/werf/converge/converge.go, go.mod, go.sum
Refs https://github.com/werf/3p-helm/pull/187
=> refactor(helm): use new upgrade cmd IgnorePending option

scripts/werf-in-image/alpine.Dockerfile, scripts/werf-in-image/argocd-cmp-sidecar-ubuntu.Dockerfile, scripts/werf-in-image/centos.Dockerfile, scripts/werf-in-image/fedora.Dockerfile, scripts/werf-in-image/ubuntu.Dockerfile
=> fix: set WERF_CONTAINERIZED=yes env in images

cmd/werf/host/cleanup/cleanup.go, cmd/werf/host/purge/purge.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/docker_server_backend.go, pkg/container_backend/interface.go, pkg/container_backend/perf_check_container_backend.go, pkg/host_cleaning/host_cleanup.go, pkg/host_cleaning/host_purge.go, pkg/tmp_manager/gc.go, pkg/tmp_manager/purge.go, pkg/util/linux_container.go
=> fix(host-cleanup): host cleanup not working in buildah mode

go.mod, go.sum, pkg/deploy/helm/external_deps_generator.go, pkg/deploy/helm/gvk_builder.go, pkg/deploy/helm/resources_waiter.go
=> fix(external-deps): use Unstructured instead of builtin types

pkg/build/stage/docker_instructions.go, pkg/config/docker.go, pkg/config/raw_docker.go, pkg/container_backend/legacy_interface.go, pkg/container_backend/legacy_stage_image.go, pkg/container_backend/legacy_stage_image_container.go, pkg/container_backend/legacy_stage_image_container_options.go, pkg/container_backend/legacy_stage_image_container_options_test.go, pkg/container_backend/suite_test.go
=> fix(docker-instructions): exactOptionValues option to fix docker-server backend options evaluation

docs/_data/werf_yaml.yml, pkg/build/stage/docker_instructions.go
=> docs(docker-instructions): reference docs for exactValues option for docker-instructions-stage

cmd/werf/main.go, go.mod, go.sum, pkg/telemetry/event.go, pkg/telemetry/metric_exporter.go, pkg/telemetry/telemetry.go, pkg/telemetry/trace_exporter.go, scripts/local-telemetry/docker-compose.yaml, scripts/local-telemetry/otel-collector-config.yaml
=> feat(telemetry): experiments with opentelemetry, traces and clickhouse storage

pkg/deploy/helm/resources_waiter.go
Previously only Jobs were tracked, others ignored.
=> feat(helm): track Helm hooks of any kind

trdl_channels.yaml
=> chore(channels): add channel candidate meta field

go.mod, go.sum
=> fix(kubedog): non-blocking mode didn't work

pkg/telemetry/telemetrywerfio.go
=> chore(telemetry): refine telemetry span fields

cmd/werf/common/telemetry.go, cmd/werf/main.go, go.mod, go.sum, pkg/telemetry/event_type.go, pkg/telemetry/no_telemetrywerfio.go, pkg/telemetry/telemetry.go, pkg/telemetry/telemetrywerfio.go, scripts/local-telemetry/docker-compose.yaml, scripts/local-telemetry/otel-collector-config.yaml
Enchance debug logging on WERF_TELEMETRY_LOGS=1.
=> chore(telemetry.werf.io): WERF_TELEMETRY=1 sends data to https://telemetry.werf.io, refactor telemetry pkg

pkg/telemetry/telemetrywerfio.go
* use eventType and eventData for event-specific data;
* use attributes for common fields: os, arch, version (of werf), groupChannel (trdl use werf >1.2 alpha<).
=> chore(telemetry): use new telemetry schema version

pkg/telemetry/telemetrywerfio.go
=> feat(telemetry): use new telemetry with updated schema and projectID

pkg/secret/yaml_encoder.go
Convert non-string values to string during encryption, do not restore original value type after decryption — convert to string.
=> fix(secrets): compatible behaviour of secret values edit command with previous versions

go.mod, go.sum
https://github.com/werf/3p-helm/pull/194
=> feat(helm): `tpl` performance improved

cmd/werf/bundle/render/render.go, docs/_includes/reference/cli/werf_bundle_render.md, pkg/util/secretvalues/mask.go
+ Fix panic when null-value in secret-values.yaml exist.
=> fix(bundles): --secret-values option for bundle-render command

go.mod, go.sum
https://github.com/werf/3p-helm/pull/195
=> feat(helm): skip templating if plain text with no templates passed to `tpl`

pkg/secret/yaml_encoder.go, pkg/util/secretvalues/mask.go
* fix panic when null-value in secret-values.yaml exist;
* compatible behaviour of secret values edit command with previous versions.
=> [v1.2.117] Secrets bugfixes backport

pkg/secret/yaml_encoder.go, pkg/util/secretvalues/mask.go
* fix panic when null-value in secret-values.yaml exist;
* compatible behaviour of secret values edit command with previous versions.
=> [v1.2.122] Secrets bugfixes backport

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml, docs/_includes/reference/cli/werf_kubectl_get.md, docs/pages_en/advanced/helm/deploy_process/external_dependencies.md, docs/pages_en/advanced/helm/deploy_process/resource_order.md, docs/pages_en/advanced/helm/deploy_process/steps.md, docs/pages_en/reference/deploy_annotations.md
=> docs: external dependencies and resource weight

go.mod, go.sum
=> feat(kubedog): show Ready resources only once

cmd/werf/bundle/publish/publish.go, cmd/werf/common/conveyor_options.go, cmd/werf/converge/converge.go, docs/_includes/reference/cli/werf_bundle_publish.md, docs/_includes/reference/cli/werf_converge.md
=> feat(custom-tag): add custom tags params for converge and bundle-publish

pkg/secret/yaml_encoder_test.go
Provide compatible behaviour with previous versions.
=> test(secrets): ensure decoded values converted to strings, despite original type was not string

go.mod, go.sum
https://github.com/werf/kubedog/pull/262
https://github.com/werf/kubedog/pull/264
=> feat(kubedog): improve progress status + fix Job Duration not changed

go.mod, go.sum
https://github.com/werf/3p-helm/pull/199
=> fix(kubedog): 3way merge patches had missing fields

pkg/deploy/helm/annotations.go, pkg/deploy/helm/resources_waiter.go
=> feat(helm): `werf.io/no-activity-timeout` annotation

go.mod, go.sum
=> fix(kubedog): increase default NoActivityTimeout to 4min

go.mod, go.sum, pkg/deploy/helm/resources_waiter.go
=> fix(helm): skip delete if unmatched resource ownership metadata

multiwerf.json, trdl_channels.yaml
This reverts commit 8d938e5c84f32c4451749886a51814e3a317d705.
=> Revert "chore(channels): 1.2 ea to 1.2.126"

go.mod, go.sum
https://github.com/werf/3p-helm/pull/201
=> fix: revert "feat: tpl performance improved"

go.mod, go.sum
=> fix(kubedog): Generic tracker hangs if no list/watch access

.github/workflows/trdl_publisher.yml, .github/workflows/website_deployment.yml, ci/.helm/multiwerf.json, ci/.helm/templates/configmap.yaml
Get rid of using multiwerf.json
=> ci: remove multiwerf.json usage

go.mod, go.sum
=> fix(kubedog): generic tracker: improve logging + few possible fixes

pkg/buildah/native_linux.go
=> feat(buildah): configurable Ulimit via `$WERF_BUILDAH_ULIMIT`

cmd/werf/render/render.go
=> feat(render): print build log if failed

cmd/werf/build/main.go, cmd/werf/bundle/export/export.go, cmd/werf/bundle/publish/publish.go, cmd/werf/ci_env/ci_env.go, cmd/werf/cleanup/cleanup.go, cmd/werf/compose/main.go, cmd/werf/config/graph/graph.go, cmd/werf/config/list/list.go, cmd/werf/config/render/render.go, cmd/werf/converge/converge.go, cmd/werf/dismiss/dismiss.go, cmd/werf/export/export.go, cmd/werf/helm/secret/rotate_secret_key/rotate_secret_key.go, cmd/werf/host/cleanup/cleanup.go, cmd/werf/kube_run/kube_run.go, cmd/werf/managed_images/add/add.go, cmd/werf/managed_images/ls/ls.go, cmd/werf/managed_images/rm/rm.go, cmd/werf/purge/purge.go, cmd/werf/render/render.go, cmd/werf/run/run.go, cmd/werf/stage/image/main.go
=> refactor: show git output only in debug mode

cmd/werf/render/render.go
=> fix(render): live output in verbose/debug mode does not work properly

go.mod, go.sum
https://github.com/werf/kubedog/pull/275
https://github.com/werf/kubedog/pull/277
=> fix(kubedog): Generic Tracker won't hang on fatal errors + cosmetics

go.mod, go.sum
Rel: https://github.com/werf/3p-helm/pull/204
Template object Clone()'d instead of creating every time.
=> feat: `tpl` performance improved

.github/workflows/delayed_issue_close.yml
=> chore: add delayed issue closer bot

go.mod, go.sum
=> fix(helm): install ./crds fails after dismiss

go.mod, go.sum
=> fix(kubedog): generic: ignore jsonpath errs on Condition search

trdl_channels.yaml
=> chore(channels): 1.2.144>ea, 1.2.140+fix1>stable

pkg/telemetry/telemetrywerfio.go
=> feat(telemetry): add attributes related to the usage inside CI-systems

go.mod, go.sum, pkg/deploy/helm/external_deps_annotations_parser.go, pkg/deploy/helm/stages_splitter.go
=> fix(helm): properly initialize all slice structs

trdl_channels.yaml
=> chore(channels): 1.2.145>alpha

pkg/config/werf.go
=> fix(build): no imagename in error in image `from` directive

docs/pages_en/internals/telemetry.md, docs/pages_ru/internals/telemetry.md, pkg/telemetry/telemetrywerfio.go
=> docs(telemetry): actualize telemetry docs

pkg/build/build_phase.go, pkg/build/image.go
=> feat(build): add report Image.NAME.Rebuilt field

cmd/werf/kube_run/kube_run.go, docs/_includes/reference/cli/werf_kube_run.md
=> docs(kuberun): fix --copy-(to|from) description

docs/pages_en/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.md, docs/pages_en/advanced/ci_cd/run_in_container/use_kubernetes.md, docs/pages_ru/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.md, docs/pages_ru/advanced/ci_cd/run_in_container/use_kubernetes.md
=> docs: update code blocks format

trdl_channels.yaml
=> chore(channels): 1.2.147 to 1.2 alpha

Taskfile.dist.yaml
=> ci(taskfile): fix image tasks

trdl.yaml
=> build(trdl): add sha to docker image

trdl_channels.yaml
=> chore(channels): 1.2.149 to 1.2 alpha

pkg/build/stage/docker_instructions.go
=> fix(buildah): original ENTRYPOINT/CMD lost on build

trdl_channels.yaml
=> chore(channels): 1.2.150>alpha, 1.2.149>beta

.github/workflows/daily_tests.yml, .github/workflows/tests.yml, Taskfile.dist.yaml, go.mod
=> ci: fix ginkgo installation

Taskfile.dist.yaml
=> ci: fixes and new tasks for Taskfile

trdl_channels.yaml
=> chore(channels): 1.2.151>alpha

pkg/container_backend/legacy_stage_image.go, pkg/container_backend/legacy_stage_image_container.go
werf overrides LD_LIBRARY_PATH to prevent unexpected behavior (rel https://github.com/werf/werf/pull/4746).
To prevent backward compatibility werf exports the user's LD_LIBRARY_PATH first step.
=> fix(stapel): save backward compatibility for shell builder with custom LD_LIBRARY_PATH

docs/pages_en/advanced/ci_cd/gitlab_ci_cd.md, docs/pages_ru/advanced/ci_cd/gitlab_ci_cd.md
=> docs: remove unnecessary GitLab CI "dependencies"

pkg/telemetry/telemetrywerfio.go
This reverts commit c2d3fdd3594b1643f0e6904efda4650c8284e63a.
=> Revert "chore(telemetry): update schemaVersion"

trdl_channels.yaml
=> chore(channels): 1.2.153 to 1.2 alpha,beta

pkg/telemetry/telemetrywerfio.go
=> chore(telemetry): store extra attributes in the reserved field

trdl_channels.yaml
=> chore(channels): 1.2 alpha,beta,ea,stable,rock-solid

.github/workflows/docs_validate.yml, .github/workflows/issues_delayed-auto-close.yml, .github/workflows/release_release-please.yml, .github/workflows/release_trdl-publish.yml, .github/workflows/release_trdl-release.yml, .github/workflows/test_cr-cleanup.yml, .github/workflows/test_daily.yml, .github/workflows/test_main.yml, .github/workflows/test_pr.yml
=> ci: fix repository_dispatch

.github/workflows/_lint.yml
=> ci: fix lint job

.github/workflows/release_trdl-release.yml
=> ci: fix release:trdl-release

trdl_channels.yaml
=> chore(channels): 1.2.157>alpha,beta,ea,stable

scripts/werf-builder/Dockerfile
=> build: add "file" binary to builder image

scripts/werf-builder/Dockerfile
=> build: fix builder image Dockerfile

Taskfile.dist.yaml
=> ci: lint couldn't run in parallel

trdl_channels.yaml
=> chore(channels): 1.2.158>alpha,beta,ea,stable

.github/actions/set-up-prebuilt-werf-test-binary/action.yml, .github/workflows/_test_integration_per-container-registry.yml, .github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml, .github/workflows/_test_integration_regular.yml, .github/workflows/_test_unit.yml
=> ci: boolean inputs become strings

trdl.yaml
=> ci: update trdl werf builder image

.github/actions/get-commit-message/action.yml, .github/scripts/get-commit-mesage.js, .github/workflows/_notification.yml, .github/workflows/docs_validate.yml, .github/workflows/issues_delayed-auto-close.yml, .github/workflows/release_release-please.yml, .github/workflows/release_trdl-publish.yml, .github/workflows/release_trdl-release.yml, .github/workflows/test_cr-cleanup.yml, .github/workflows/test_daily.yml, .github/workflows/test_main.yml, .github/workflows/test_pr.yml, .github/workflows/website_converge_tag.yml, .github/workflows/website_converge_test.yml, .github/workflows/website_deployment.yml, .github/workflows/website_review.yml, .github/workflows/website_review_dismiss.yml
Mentions slack group of the developer's team if workflow fails.
=> ci: tune workflow notifications

.github/workflows/test_daily.yml
=> ci: coverage upload should not depend on lint job

.github/workflows/_lint.yml, Taskfile.dist.yaml
=> ci: fix broken lint job

.github/workflows/_docs_deploy.yml, .github/workflows/_notification.yml
=> ci: fix 'the workflow is not valid'

.github/workflows/_lint.yml, .github/workflows/_test_unit.yml
=> ci: "hide" internal workflows

.github/workflows/_lint.yml, .github/workflows/_test_unit.yml
=> ci: "hide" internal workflows 2

.github/workflows/_coverage_report.yml, .github/workflows/_docs_deploy.yml, .github/workflows/_lint.yml, .github/workflows/_notification.yml, .github/workflows/_test_integration_per-container-registry.yml, .github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml, .github/workflows/_test_integration_regular.yml, .github/workflows/_test_unit.yml
=> ci: "hide" internal workflows 3

.github/workflows/_coverage_report.yml, .github/workflows/_docs_deploy.yml, .github/workflows/_lint.yml, .github/workflows/_notification.yml, .github/workflows/_test_integration_per-container-registry.yml, .github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml, .github/workflows/_test_integration_regular.yml, .github/workflows/_test_unit.yml
=> ci: "hide" internal workflows 4

pkg/telemetry/telemetrywerfio.go
=> chore(telemetry): fix panic when an invalid extra attribute added

.github/actions/get-commit-message/dist/index.js, .github/actions/get-commit-message/index.js
=> ci(get-commit-message): return empty string if event not supported

trdl_channels.yaml
=> chore(channels): 1.2.160>stable

trdl_channels.yaml
=> chore(channels): 1.2 alpha,beta,ea,stable

.github/workflows/_lint.yml, .github/workflows/_test_unit.yml, .github/workflows/test_pr.yml
=> ci: test:pr doesnt always spawn nested jobs, thus breaking Required jobs

.github/workflows/test_pr.yml
=> ci: cancel concurrent test:pr workflows in the same PR

trdl_channels.yaml
=> chore(channels): 1.2.163>alpha

Taskfile.dist.yaml
=> ci(taskfile): avoid double format for default target

.prettierignore, docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml, scripts/docs/regen.sh
=> chore(docs): format sidebar partials

cmd/werf/common/helm.go, pkg/deploy/bundles/registry/client.go
=> fix(helm): use same docker-config as werf uses for helm OCI regsitry related operations

.github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml
Signed-off-by: Artem Kladov <artem.kladov@flant.com>
=> testing: add k8s 1.23 and 1.25 for testing

.github/actions/set-up-prebuilt-werf-test-binary/action.yml, .github/workflows/_test_e2e_regular.yml, .github/workflows/test_daily.yml, .github/workflows/test_main.yml, .github/workflows/test_pr.yml, Taskfile.dist.yaml
=> ci: enable e2e tests in pr/main/daily workflows

.github/workflows/_test_integration_per-container-registry.yml, .github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml, .github/workflows/_test_integration_regular.yml, .github/workflows/_test_unit.yml
Looks like it will print the full log in case of a failure anyways.
=> ci: disable verbose mode for tests

integration/suites/cleanup_after_converge/_fixtures/default/.helm/templates/090-frontend.yaml, integration/suites/deploy/custom_tag/.helm/templates/090-frontend.yaml, integration/suites/helm/deploy_rollback/_fixtures/chart_1/templates/ingress.yaml, integration/suites/helm/render/_fixtures/base/.helm/templates/090-frontend.yaml
=> test(integration): fix tests for new K8s 1.23/1.25

.github/workflows/_test_e2e_regular.yml, .github/workflows/docs_validate.yml, .github/workflows/test_main.yml, .github/workflows/test_pr.yml
=> ci: fix triggering workflows on paths

.github/workflows/_test_e2e_regular.yml
=> ci: fix e2e test jobs

test/e2e/build/_fixtures/complex/state0/werf.yaml, test/e2e/build/_fixtures/complex/state1/werf.yaml, test/e2e/build/complex_test.go, test/e2e/build/images_dependencies_test.go, test/e2e/build/simple_test.go, test/e2e/build/suite_test.go
=> test(e2e): fix build tests

.github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml
=> ci: too many params in matrix make job name unreadable

.github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml
=> ci: too many params in matrix make job name unreadable /2

.github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml
=> ci: too many params in matrix make job name unreadable /3

.github/workflows/_test_e2e_regular.yml
=> ci: install buildah for e2e tests

.github/workflows/test_main.yml
=> ci(integration): disable test coverage for main workflow

cmd/werf/bundle/download/download.go, docs/_includes/reference/cli/werf_bundle_download.md
=> fix(bundles): fix panic in bundle-download command

.github/workflows/test_daily.yml
=> ci(test): change order of running of daily tests suites

trdl_channels.yaml
=> chore(channels): 1.2.166 to alpha and beta

trdl_channels.yaml
=> chore(channels): 1.2.163 to ea

trdl_channels.yaml
=> chore(channels): add pre-rock-solid comment

CODEOWNERS, OWNERS
=> chore: use OWNERS file instead of CODEOWNERS

test/e2e/build/complex_test.go, test/e2e/build/simple_test.go
=> test: disable buildah e2e tests

trdl_channels.yaml
=> chore(channels): 1.2.167 to alpha

trdl_channels.yaml
=> chore(channels): 1.2.168 to alpha

trdl_channels.yaml
=> chore(channels): 1.2.168 to beta, 1.2.169 to alpha

.github/workflows/docs_deploy_pr.yml, .github/workflows/docs_validate.yml, .github/workflows/test_main.yml, .github/workflows/test_pr.yml
=> ci: disable slack notification for draft pull requests

trdl_channels.yaml
=> chore(channels): 1.2.170 to alpha

pkg/cleaning/allow_list/kubernetes.go
First query batch/v1, if server is not supports CronJobs in this group-version then fallback to batch/v1beta1.
Fixes https://github.com/werf/werf/issues/4896.
=> fix(cleanup): fallback to batch/v1beta1 when querying CronJobs for cleanup

pkg/telemetry/telemetry.go, pkg/util/env.go
=> fix(telemetry): repair turn-off telemetry switch

pkg/telemetry/telemetry.go, pkg/util/env.go
=> [v1.2.162] fix(telemetry): repair turn-off telemetry switch

pkg/telemetry/telemetry.go, pkg/util/env.go
=> [v1.2.163] fix(telemetry): repair turn-off telemetry switch

pkg/telemetry/telemetry.go, pkg/util/env.go
=> [v1.2.169] fix(telemetry): repair turn-off telemetry switch

CHANGELOG.md, pkg/telemetry/telemetry.go, pkg/util/env.go
=> chore: release 1.2.169+fix1

trdl_channels.yaml
=> chore(channels): alpha to 1.2.171, beta to 1.2.169+fix1

docs/_data/werf_yaml.yml, docs/pages_en/advanced/building_images_with_stapel/docker_directive.md, docs/pages_ru/advanced/building_images_with_stapel/docker_directive.md
=> docs: update reference for CMD and ENTRYPOINT directives

trdl_channels.yaml
=> chore(channels): ea to 1.2.163+fix1, stable to 1.2.163+fix1, rock-solid to 1.2.162+fix1

cmd/werf/run/run.go, docs/_includes/reference/cli/werf_run.md
=> fix(run): a container is not cleaned up after execution by default

cmd/werf/run/run.go
fixes https://github.com/werf/werf/issues/3504
=> fix(run): --bash and --shell depend on image entrypoint

pkg/deploy/bundles/copy_test.go, pkg/deploy/bundles/remote_bundle.go
=> test(bundles): test bundle-archive to registry copy, fix chart version bug

pkg/deploy/bundles/copy_test.go
=> test(bundles): test registry to bundle-archive copy

trdl_channels.yaml
=> chore(channels): 1.2.172 into alpha

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml
=> docs: reorder articles in the sidebar

integration/suites/deploy/helm_releases_manager_test.go
=> test: fix releases-history-max integration test case

pkg/build/build_phase.go
=> chore: format debug message

go.mod, go.sum
Fixes https://github.com/werf/werf/issues/4932
=> fix(helm): don't rely on resource Group for resources equality matching

trdl_channels.yaml
=> chore(channels): 1.2.173>alpha

pkg/deploy/helm/extra_annotations_and_labels_post_renderer.go, pkg/deploy/helm/extra_annotations_and_labels_post_renderer_test.go
=> fix(helm): empty resource annos/labels result in no service annos/labels

cmd/werf/host/purge/purge.go, docs/_includes/reference/cli/werf_host_purge.md, docs/_includes/reference/cli/werf_kubectl_get.md, pkg/buildah/native_linux.go, pkg/util/archive.go, test/e2e/build/_fixtures/complex/state0/werf.yaml, test/e2e/build/complex_test.go
=> fix(buildah): reimplement docker-backend logic in buildah for HEALTHCHECK stapel instruction

cmd/werf/common/common.go, docs/_includes/reference/cli/werf_bundle_apply.md, docs/_includes/reference/cli/werf_bundle_export.md, docs/_includes/reference/cli/werf_bundle_publish.md, docs/_includes/reference/cli/werf_bundle_render.md, docs/_includes/reference/cli/werf_converge.md, docs/_includes/reference/cli/werf_render.md
=> docs(cli): update --values option description

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml
=> docs(sidebar): remove experimental

cmd/werf/bundle/apply/apply.go, cmd/werf/bundle/export/export.go, cmd/werf/bundle/publish/publish.go, cmd/werf/bundle/render/render.go, cmd/werf/common/helm.go, cmd/werf/converge/converge.go, cmd/werf/dismiss/dismiss.go, cmd/werf/helm/helm.go, cmd/werf/helm/install.go, cmd/werf/helm/migrate2to3.go, cmd/werf/main.go, cmd/werf/render/render.go, pkg/deploy/helm/init.go, pkg/docker/config.go
Closes https://github.com/werf/werf/issues/4956
=> fix(helm): fix "missing registry client" error in werf-helm-\* commands

pkg/build/stage/git_mapping.go, pkg/buildah/base.go, pkg/container_backend/build_stapel_stage_options.go, pkg/container_backend/buildah_backend.go, pkg/util/archive.go, pkg/util/path.go, pkg/util/path_test.go, test/e2e/build/complex_test.go
=> fix(buildah): add support for git owner/group settings

trdl_channels.yaml
=> chore(channels): 1.2.175 into alpha

docs/_data/breadcrumbs.yml, docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml, docs/pages_ru/advanced/ci_cd/multiple_repositories_operation/bundles.md, docs/pages_ru/advanced/ci_cd/multiple_repositories_operation/gitlab_multiproject_pipelines.md, docs/pages_ru/advanced/ci_cd/multiple_repositories_operation/overview.md, docs/pages_ru/advanced/secrets_management/overview.md
* multiple repositories operation;
* secrets management.
=> chore(docs): added advanced docs sections empty pages

trdl_channels.yaml
=> chore(channels): 1.2.176 into alpha, beta and ea; 1.2.169+fix1 into stable

go.mod, go.sum
=> fix(dismiss): fix --with-namespace not deleting namespace in dismiss command

trdl_channels.yaml
=> chore(channels): 1.2.176 to alpha, 1.2.175+fix1 to beta and ea

trdl_channels.yaml
=> chore(channels): 1.2.177 to alpha

cmd/buildah-test/main.go, pkg/build/build_phase.go, pkg/build/stage/data_test.go, pkg/build/stage/dockerfile.go, pkg/buildah/common.go, pkg/buildah/native_linux.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/docker_server_backend.go, pkg/container_backend/dockerfile_commands.go, pkg/container_backend/interface.go, pkg/container_backend/perf_check_container_backend.go, pkg/container_backend/stage_builder/dockerfile_builder.go, pkg/container_backend/stage_builder/dockerfile_stage_builder.go, pkg/container_backend/stage_builder/stage_builder.go
=> feat(buildah): add low level dockerfile stage builder

test/e2e/converge/_fixtures/complex/state0/.helm/templates/deployment-app1.yaml, test/e2e/converge/_fixtures/complex/state0/.helm/templates/deployment-app2.yaml, test/e2e/converge/complex_test.go, test/pkg/werf/project.go
=> test(e2e): fix complex converge test

pkg/build/build_phase.go, pkg/build/image/dockerfile.go, pkg/build/image/stapel.go, pkg/build/stage/dockerfile_instruction.go, pkg/build/stage/full_dockerfile.go, pkg/build/stage/full_dockerfile_test.go, pkg/build/stage/stapel_docker_instructions.go, pkg/config/image_from_dockerfile.go, pkg/config/raw_image_from_dockerfile.go, pkg/container_backend/buildah_backend.go, pkg/dockerfile/dockerfile.go, pkg/dockerfile/dockerfile_stage.go, pkg/dockerfile/helpers.go, pkg/dockerfile/instructions.go
=> feat(staged-dockerfile): prepare conveyor, stage and dockerfile parser for new impl

pkg/util/archive.go
=> fix(buildah): git add result in broken symlinks

go.mod, go.sum
rel: https://github.com/werf/3p-helm/pull/227
=> fix(helm): keep all revisions since last succeeded release

trdl_channels.yaml
=> chore(channels): 1.2.180 to alpha

pkg/build/image/image.go
=> feat(staged-dockerfile): add optional image-from-dockerfile reference into Image obj

pkg/build/image/dockerfile.go
=> feat(staged-dockerfile): initialize dockerfile-images with werf.yaml configration section

cmd/werf/docs/replacers/helm/helm.go, cmd/werf/docs/replacers/helm/helm_docs.go, cmd/werf/helm/helm.go, cmd/werf/helm/install.go, cmd/werf/helm/lint.go
=> chore(lint): run task format

trdl_channels.yaml
=> chore(channels): 1.2.178 to ea, 1.2.180 to beta, 1.2.181 to alpha

trdl_channels.yaml
=> chore(channels): 1.2.178 to beta

cmd/werf/common/cmd_data.go, docs/_includes/reference/cli/werf_bundle_export.md, docs/_includes/reference/cli/werf_bundle_publish.md, docs/_includes/reference/cli/werf_converge.md, docs/_includes/reference/cli/werf_kubectl_get.md, docs/_includes/reference/cli/werf_render.md
=> fix: WERF_DISABLE_DEFAULT_SECRET_VALUES and WERF_DISABLE_DEFAULT_VALUES support for corresponding options

pkg/build/image/build_context_archive.go, pkg/build/image/dockerfile.go
=> fix(staged-dockerfile): fix docker ignore path matcher

go.mod, go.sum
https://github.com/werf/3p-helm/pull/231
=> fix(helm): keep all revisions if no succeeded release

trdl_channels.yaml
=> chore(channels): 1.2.182>alpha, 1.2.181>beta

go.mod, go.sum
refs https://github.com/werf/3p-helm/pull/231
=> [1.2.181]  fix(helm): keep all revisions if no succeeded release

go.mod, go.sum
=> [1.2.175] fix(helm): keep all revisions if no succeeded release and since last succeeded release

trdl_channels.yaml
=> chore(channels): 1.2.181+fix1 to beta and ea

trdl_channels.yaml
=> chore(channels): 1.2.183 into alpha, 1.2.181+fix2 into beta and ea

pkg/build/image/dockerfile.go, pkg/build/stage/instruction/add.go, pkg/build/stage/instruction/base.go, pkg/build/stage/instruction/cmd.go, pkg/build/stage/instruction/copy.go, pkg/build/stage/instruction/entrypoint.go, pkg/build/stage/instruction/env.go, pkg/build/stage/instruction/expose.go, pkg/build/stage/instruction/healthcheck.go, pkg/build/stage/instruction/label.go, pkg/build/stage/instruction/maintainer.go, pkg/build/stage/instruction/on_build.go, pkg/build/stage/instruction/run.go, pkg/build/stage/instruction/shell.go, pkg/build/stage/instruction/stop_signal.go, pkg/build/stage/instruction/user.go, pkg/build/stage/instruction/volume.go, pkg/build/stage/instruction/workdir.go
=> feat(staged-dockerfile): basic support of all dockerfile stages at conveyor level

pkg/util/path.go, pkg/util/path_unix_test.go, pkg/util/path_windows_test.go
=> fix: panic when calling SplitFilepath on windows (test included)

trdl_channels.yaml
=> chore(channels): 1.2.184 to alpha, 1.2.181+fix3 to beta and ea, 1.2.175+fix3 to stable

cmd/werf/converge/converge.go
By default `werf converge` command does not accept specific images positional params to enable building and verification of only specific images from the `werf.yaml`.
When `WERF_CONVERGE_ENABLE_IMAGES_PARAMS=1` is set it is possible to specify either positional images arguments or `--without-images` option:
```
export WERF_CONVERGE_ENABLE_IMAGES_PARAMS=1
werf converge IMAGE_A IMAGE_B [--without-images] [options]
```
This feature gate only needed due to historical compatibility issues with using positional arguments in converge command.
=> [1.2.175] fix(converge): feature gate for specific images params in werf-converge (due to compatibility issues)

trdl_channels.yaml
=> chore(channels): 1.2.175+fix4 into stable

cmd/buildah-test/main.go, pkg/build/image/dockerfile.go, pkg/build/stage/instruction/healthcheck.go, pkg/build/stage/instruction/maintainer.go, pkg/buildah/common.go, pkg/buildah/native_linux.go, pkg/buildah/thirdparty/healthcheck_linux.go, pkg/buildah/thirdparty/healthcheck_others.go, pkg/config/raw_image_from_dockerfile.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/instruction/add.go, pkg/container_backend/instruction/cmd.go, pkg/container_backend/instruction/copy.go, pkg/container_backend/instruction/entrypoint.go, pkg/container_backend/instruction/healthcheck.go, pkg/container_backend/instruction/maintainer.go, pkg/container_backend/instruction/run.go, pkg/dockerfile/dockerfile_stage.go, pkg/dockerfile/frontend/buildkit_dockerfile.go, pkg/dockerfile/instruction.go, pkg/dockerfile/instruction/healthcheck.go, test/e2e/build/common_test.go, test/e2e/build/complex_test.go, test/e2e/build/simple_test.go
=> feat(staged-dockerfile): all dockerfile instructions with options

pkg/build/image/build_context_archive.go, pkg/build/stage/instruction/add.go, pkg/build/stage/instruction/copy.go, pkg/container_backend/archive_interface.go
=> feat(staged-dockerfile): refactor calculateBuildContextGlobsChecksum

pkg/build/stage/instruction/env.go, pkg/build/stage/instruction/label.go, pkg/build/stage/instruction/run.go, pkg/util/map.go
=> feat(staged-dockerfile): refine dockerfile instructions digests calculations

pkg/build/stage/instruction/add_test.go, pkg/build/stage/instruction/cmd_test.go, pkg/build/stage/instruction/common_test.go, pkg/build/stage/instruction/copy_test.go, pkg/build/stage/instruction/stubs_test.go
=> test(staged-dockerfile): more stage instruction tests, enabled add tests

pkg/container_backend/docker_running_containers.go
=> fix(stapel): add log line about starting container cleanup

test/e2e/build/_fixtures/complex/state0/Dockerfile, test/e2e/build/_fixtures/complex/state1/Dockerfile, test/e2e/build/complex_test.go
=> test(e2e): extend complex build test

cmd/buildah-test/main.go, pkg/build/image/build_context_archive.go, pkg/build/stage/instruction/run.go, pkg/build/stage/instruction/stubs_test.go, pkg/buildah/common.go, pkg/buildah/native_linux.go, pkg/container_backend/archive_interface.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/instruction/run.go
=> feat(staged-dockerfile): implement Run mounts

test/e2e/build/common_test.go, test/e2e/build/complex_test.go, test/e2e/build/simple_test.go, test/pkg/contback/common.go
=> test(e2e): add BuildKit Docker backend to build tests

test/e2e/build/_fixtures/complex/state0/Dockerfile, test/e2e/build/_fixtures/complex/state1/Dockerfile, test/e2e/build/complex_test.go
=> test(e2e): remove RUN --mount's as not supported by Vanilla Docker

pkg/buildah/common.go, pkg/buildah/thirdparty/healthcheck_linux.go, pkg/buildah/thirdparty/healthcheck_others.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/instruction/healthcheck.go
=> fix(buildah): broken build on mac/win

trdl_channels.yaml
=> chore(channels): 1.2.186>alpha

pkg/build/build_phase.go, pkg/build/image/image.go, pkg/dockerfile/frontend/buildkit_dockerfile.go, pkg/image/info.go, pkg/storage/manager/storage_manager.go
=> feat(staged-dockerfile): support ONBUILD instructions (part 1, preparations)

docs/pages_en/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.md, docs/pages_ru/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.md
=> docs(buildah): fix gitlab with kubernetes pod annotation gitlab runner configuration

trdl_channels.yaml
=> chore(channels): 1.2.191 to alpha and beta

docs/_layouts/default.html
=> site: update yandex metrika counter

.github/workflows/docs_deploy_pr.yml, .github/workflows/test_main.yml
=> ci: fix docs:deploy:pr and test:main workflows do not run by label

docs/pages_en/index.md, docs/pages_ru/index.md
=> docs(overview): fix landing tiles

docs/_data/breadcrumbs.yml
=> docs(build): fix /usage/build_draft not defined

docs/_data/sidebars/documentation.yml
=> chore(docs): regen sidebar

pkg/build/image/stapel.go
=> fix(shallow-clone): enable auto unshallow unless force-shallow option used

pkg/build/build_phase.go, pkg/build/image/stapel.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/docker_server_backend.go, pkg/container_backend/legacy_base_image.go, pkg/container_backend/legacy_interface.go, pkg/container_backend/legacy_stage_image.go, pkg/image/info.go, pkg/image/stage.go, pkg/storage/manager/storage_manager.go, pkg/util/copy.go
* Inconsistent build images report when final-repo param used fix (+ fix related panic).
* Hotfix shallow-clone unshallowing not enabled by default.
=> Backports to 1.2.188

pkg/build/build_phase.go, pkg/build/image/stapel.go, pkg/container_backend/legacy_base_image.go, pkg/container_backend/legacy_interface.go, pkg/storage/manager/storage_manager.go
* Final-repo and report related panic.
* Fix auto unshallow not enabled by default.
=> Backports to 1.2.186

pkg/build/build_phase.go, pkg/build/image/stapel.go, pkg/container_backend/legacy_base_image.go, pkg/container_backend/legacy_interface.go, pkg/storage/manager/storage_manager.go
* Final-repo and report related panic.
* Fix auto unshallow not enabled by default.
=> Backports to 1.2.184

trdl_channels.yaml
Set next backport versions notes comments
=> chore(channels): 1.2.193 to alpha, beta and ea

docs/pages_ru/usage/deploy/charts.md
=> docs: rewrite "charts" doc /2

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml
=> docs: regen sidebar

trdl_channels.yaml
=> chore(channels): 1.2.188+fix1 into stable

pkg/build/image/dockerfile.go, trdl_channels.yaml
=> fix(giterminism): false warning about ignoring Dockerfile when using non-root project directory

trdl_channels.yaml
=> chore(channels): 1.2.194 into alpha, beta and ea; 1.2.184+fix2 into rock-solid

docs/_data/sidebars/documentation.yml, docs/_includes/reference/cli/werf_kubectl_get.md
=> fix(docs): actualize sidebar in usage docs

trdl_channels.yaml
=> chore(channels): 1.2.195 into alpha, beta and ea

docs/pages_ru/resources/how_to_migrate_from_v1_1_to_v1_2.md, docs/pages_ru/usage/deploy/values.md
=> docs(usage): new RU Values chapter

Taskfile.dist.yaml
=> ci(Taskfile): add nocgo dev build task for Linux

docs/pages_en/usage/deploy/values.md, docs/pages_ru/reference/deploy_annotations.md, docs/pages_ru/usage/deploy/deployment_order.md
=> docs(usage): new RU "deployment order" chapter

docs/pages_ru/usage/deploy/tracking.md
=> docs(usage): new RU "tracking" chapter

docs/pages_ru/usage/deploy/intro.md, docs/pages_ru/usage/deploy/releases.md
=> docs(usage): new RU "intro" chapter

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml, docs/pages_ru/usage/deploy/intro.md
=> docs(usage): update RU "deployment intro" chapter

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml, docs/pages_ru/usage/build/process.md
=> docs(usage): refine usage/build titles

.github/workflows/_lint.yml, .github/workflows/_test_e2e_per-k8s-version.yml, .github/workflows/_test_e2e_regular.yml, .github/workflows/_test_integration_per-container-registry.yml, .github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml, .github/workflows/_test_integration_regular.yml, .github/workflows/_test_unit.yml, .github/workflows/docs_validate.yml
=> ci: fix API rate limit exceeded for arduino/setup-task

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml, docs/pages_en/usage/deploy/charts.md, docs/pages_en/usage/distribute/charts.md, docs/pages_ru/usage/deploy/charts.md, docs/pages_ru/usage/distribute/charts.md
=> docs(deploy): update charts article title

docs/pages_en/usage/build/stapel/instructions.md, docs/pages_ru/usage/build/stapel/instructions.md
=> ci(docs): fix broken links

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml, docs/pages_ru/usage/build/images.md
=> docs(build): update images article

cmd/werf/common/synchronization.go, pkg/container_backend/buildah_backend.go, pkg/deploy/bundles/publish.go
- hide push image layer messages when using Buildah mode (show in verbose);
- hide synchronization messages (show in verbose);
=> fix(logging): simplify logs, remove excess messages

docs/pages_ru/usage/project_configuration/overview.md
=> docs(project_configuration): update overview

docs/pages_ru/usage/deploy/deployment_scenarios.md, docs/pages_ru/usage/distribute/bundles.md
=> docs(usage): minor updates

docs/pages_ru/usage/deploy/deployment_scenarios.md
=> docs(usage): update RU deployment/deployment_scenarios chapter

trdl_channels.yaml
=> chore(channels): downgrade 1.2 alpha,beta,ea to 1.2.197

docs/_data/sidebars/_documentation.yml, docs/pages_en/usage/integration_with_ci_cd_systems.md, docs/pages_ru/usage/integration_with_ci_cd_systems.md
Signed-off-by: Zhbert <zhbert@yandex.ru>
=> [docs] Review pages in the "Integration with CI/CD systems" section

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml, docs/pages_en/resources/how_to_migrate_from_v1_1_to_v1_2.md, docs/pages_en/usage/distribute/bundles.md, docs/pages_en/usage/distribute/charts.md
=> docs(usage): hide distribute section

trdl_channels.yaml
=> chore(channels): 1.2 all

docs/pages_en/usage/build/overview.md, docs/pages_en/usage/build/stapel/instructions.md, docs/pages_en/usage/deploy/deployment_scenarios.md, docs/pages_ru/usage/deploy/deployment_scenarios.md
Signed-off-by: Zhbert <zhbert@yandex.ru>
=> [docs] Small fixes in the "Usage" section

cmd/werf/compose/main.go
Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>
=> fix(compose): redundant image building with compose down command

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml
Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>
=> docs(deploy): add deployment scenarios to sidebar

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml, docs/_includes/reference/cli/werf_kubectl_get.md
Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>
=> docs(distribute): fix images url in sidebar

cmd/werf/build/main.go, cmd/werf/bundle/apply/apply.go, cmd/werf/bundle/export/export.go, cmd/werf/bundle/publish/publish.go, cmd/werf/common/cmd_data.go, cmd/werf/common/common.go, cmd/werf/common/conveyor_options.go, cmd/werf/converge/converge.go, cmd/werf/render/render.go, docs/_includes/reference/cli/werf_build.md, docs/_includes/reference/cli/werf_bundle_apply.md, docs/_includes/reference/cli/werf_bundle_export.md, docs/_includes/reference/cli/werf_bundle_publish.md, docs/_includes/reference/cli/werf_converge.md, docs/_includes/reference/cli/werf_render.md
=> fix: rework build/deploy report options

pkg/build/image/image.go
Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>
=> fix(build): TOOMANYREQUESTS error occurs for the built images

cmd/werf/common/cmd_data.go, cmd/werf/common/common.go, cmd/werf/dismiss/dismiss.go, docs/_includes/reference/cli/werf_build.md, docs/_includes/reference/cli/werf_bundle_apply.md, docs/_includes/reference/cli/werf_bundle_export.md, docs/_includes/reference/cli/werf_bundle_publish.md, docs/_includes/reference/cli/werf_converge.md, docs/_includes/reference/cli/werf_dismiss.md, docs/_includes/reference/cli/werf_render.md
Either specify --release and --namespace or use --use-deploy-report.
=> feat(dismiss): add two ways to run without git

docs/pages_ru/usage/deploy/deployment_scenarios.md
=> doc(usage): add information about deploy report /RU

.github/workflows/_lint.yml, .github/workflows/_test_e2e_per-k8s-version.yml, .github/workflows/_test_e2e_regular.yml, .github/workflows/_test_integration_per-container-registry.yml, .github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml, .github/workflows/_test_integration_regular.yml, .github/workflows/_test_unit.yml, .github/workflows/docs_validate.yml, .github/workflows/release_trdl-publish.yml, .github/workflows/test_main.yml, .github/workflows/test_pr.yml
=> Revert "Revert "ci: update runners to speed up workflows" "

docs/_layouts/sidebar-nosidebar.html, docs/_layouts/sidebar.html
=> Revert "docs: remove guide banner"

cmd/werf/kube_run/kube_run.go, cmd/werf/run/run.go, cmd/werf/stage/image/main.go, pkg/config/raw_meta_build.go
Also fixed build.platform directive in the werf.yaml
=> fix(multiarch): fix panics in werf kube-run, run and stage image commands [1.2.214]

cmd/werf/common/repo_data.go, pkg/build/build_phase.go, pkg/build/conveyor.go
Bug was introduced after moving managed-images-adding procedure into AfterImages phase hook.
=> fix(multiarch): managed images adding bug fix

cmd/werf/common/common.go, pkg/buildah/common.go, pkg/buildah/native_linux.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/docker_server_backend.go
Also fixed buildah non-staged dockerfile builder: labels were not applied to the built images.
=> feat(buildah): enable :local mode for buildah backend

pkg/build/conveyor.go
=> chore(logging): add build summary block

docs/_config.yml
PR#5564 broke assets compilation
=> fix: revert precompile stanza

pkg/build/image/dockerfile.go
Remove doubles of dockerfile-stages which already built in one of the previous images sets.
=> fix(staged-dockerfile): optimize stages dependencies tree builder

.github/workflows/test_pr.yml, pkg/build/build_phase.go, pkg/build/conveyor.go, pkg/build/image/dockerfile.go, pkg/build/image/image.go, pkg/build/stage/base.go, pkg/build/stage/instruction/from.go, pkg/build/stage/interface.go, pkg/buildah/common.go, pkg/buildah/native_linux.go, pkg/container_backend/buildah_backend.go, pkg/container_backend/docker_server_backend.go, pkg/container_backend/stage_builder/dockerfile_builder.go, pkg/docker/image_info.go, pkg/docker_registry/api.go, pkg/docker_registry/image_info.go, pkg/image/info.go, pkg/image/manifest_cache.go, pkg/image/summary.go, pkg/storage/manager/storage_manager.go, pkg/werf/main.go, pkg/werf/staged_dockerfile.go
Also fixed panic on single FROM instruction stage.
Added possibility to reset FROM instruction stage cache.
=> fix(staged-dockerfile): separate FROM stage with caching in the container-registry

.github/workflows/_docs_deploy.yml, .github/workflows/docs_deploy_latest.yml, docs/.helm/templates/20-ingress.yaml, docs/.werf/nginx.conf
Modify CI workflow and Ingress template to deploy documentation from the main branch as "/latest/" location.
=> ci: deploy the latest doc from the main branch

pkg/docker_registry/aws_ecr.go, pkg/docker_registry/default.go, pkg/docker_registry/gitlab_registry.go, pkg/docker_registry/selectel.go, pkg/image/info.go
- fix construction of the image name with the digest for default implementation
=> fix: integration tests should not fail

cmd/werf/kube_run/kube_run.go
=> chore(logging): remove redundant info in kube-run command

pkg/true_git/merge.go, pkg/true_git/service_branch.go
fixes https://github.com/werf/werf/issues/5544
=> fix(dev): precommit git hooks are not ignored

go.mod, go.sum
=> fix(exp-engine): parallel GET/dry-APPLY finishing before results received

cmd/werf/ci_env/ci_env.go
Added "git tag" annotation for GitHub and GitLab CI
=> [ci-env] Added "git tag" annotation

docs/.helm/templates/10-app.yaml
Actualization apiVersion of PodDisruptionBudget to policy/v1
=> doc: update PodDisruptionBudget apiVersion

go.mod, go.sum
Strategic patch might not work for custom resources
=> fix(exp-engine): replace strategic patch with merge patch

go.mod, go.sum
+ show live version diff instead of local diff for deleted resource
=> feat(exp-engine): hide sensitive Secret's diff in werf plan

CONTRIBUTING.md
Ginkgo should be mentioned as a requirement to run tests locally
=> docs: mention ginkgo as requirement for testing in CONTRIBUTING

pkg/secret/yaml_encoder.go
Use deep copy of yaml_v3.Node objects everywhere.
=> fix(secrets): fix double decryption error when decrypting a yaml with multiple references to the same anchor

pkg/build/stage/git_mapping.go
Labels with actual git-commit was not written into labels for git mappings which has empty git-patch.
=> fix(buildah): fix digest change on rebuild of install/beforeSetup/setup stage when using multiple git-mappings in the same image

docs/Gemfile.lock
This reverts commit 4781eb8d182f127a7858d1298c12e5f2d3eb8deb.
=> fix: site deployment failed

go.mod, go.sum
fixes https://github.com/werf/werf/issues/5961
=> fix: --wait-for-jobs did not use Kubedog

pkg/build/build_phase.go
The stage digest remains the same, but the content digest may differ (e.g., the content digest of git and some user stages depends on the git commit).
=> fix(stapel): using suitable stage might break reproducibility of subsequent stages

docs/.werf/nginx.conf
Add a redirect rule for the getting started
=> chore(site): Add a redirect rule for the getting started

docs/.werf/nginx.conf
=> Revert "chore(site): Add a redirect rule for the getting started"

docs/.werf/nginx.conf, docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml
Refs:
- https://github.com/werf/website/pull/707
- https://github.com/werf/werf/pull/6014
- https://github.com/werf/website/pull/722
- https://github.com/werf/werf/pull/6021
=> chore(site): add redirects for the new getting started URL

docs/_data/sidebars/_documentation.yml, docs/_data/sidebars/documentation.yml
This reverts commit 0418d2b604a3782d71c8253994d213e9c2a08ffc.
=> chore(site): Fix link to getting started

.github/actions/get-commit-message/action.yml, .github/actions/get-commit-message/dist/index.js, .github/actions/get-commit-message/index.js, .github/actions/get-commit-message/package-lock.json, .github/actions/get-commit-message/package.json, .github/workflows/_lint.yml, .github/workflows/_notification.yml, .github/workflows/_test_e2e_per-k8s-version.yml, .github/workflows/_test_e2e_regular.yml, .github/workflows/_test_integration_per-container-registry.yml, .github/workflows/_test_integration_per-k8s-version-and-container-registry.yml, .github/workflows/_test_integration_per-k8s-version.yml, .github/workflows/_test_integration_regular.yml, .github/workflows/_test_unit.yml, .github/workflows/docs_validate.yml, .github/workflows/test_pr.yml
Fix the notification action in the CI.
Bump arduino/setup-task action to v2
=> chore(ci): fix notifications

cmd/werf/compose/main.go, docs/_includes/reference/cli/werf_compose_config.md, docs/_includes/reference/cli/werf_compose_down.md, docs/_includes/reference/cli/werf_compose_run.md, docs/_includes/reference/cli/werf_compose_up.md, pkg/build/build_phase.go, pkg/build/conveyor.go
- Auto-extract used images from Docker Compose file if not specified.
- Fix require arbitrary values for service values to run the down command.
- Improve logging.
=> feat(compose): small improvements

cmd/werf/compose/main.go
werf was unable to detect environment variables due to the lack of support for the extends functionality in docker-compose files. This commit addresses the issue by properly handling the extends keyword when extracting image names, ensuring that environment variables are correctly detected and processed.
fix #6308
=> fix(compose): detect werf environment variables when extends functionality used

cmd/werf/compose/main.go
Previously, the logic only processed the first file when multiple compose files were passed with the -f/--file option, ignoring the others. This fix ensures that all specified compose files are correctly processed during auto-extraction.
=> fix(compose): correctly handle multiple compose files with -f/--file option

scripts/werf-builder/Dockerfile, trdl.yaml
=> chore(build): up builder image

scripts/werf-in-image/alpine.Dockerfile, scripts/werf-in-image/centos.Dockerfile, scripts/werf-in-image/fedora.Dockerfile, scripts/werf-in-image/ubuntu.Dockerfile
fixes https://github.com/werf/werf/issues/6200 https://github.com/werf/werf/discussions/6199
=> fix(release): fix /home/build/.werf: permission denied when volume is used with werf images

cmd/werf/build/main.go, cmd/werf/bundle/publish/publish.go, cmd/werf/cleanup/cleanup.go, cmd/werf/common/storage.go, cmd/werf/compose/main.go, cmd/werf/converge/converge.go, cmd/werf/export/export.go, cmd/werf/helm/get_autogenerated_values.go, cmd/werf/host/purge/purge.go, cmd/werf/kube_run/kube_run.go, cmd/werf/plan/plan.go, cmd/werf/purge/purge.go, cmd/werf/render/render.go, cmd/werf/run/run.go, cmd/werf/stage/image/main.go, pkg/build/conveyor_with_retry.go
Added constructor for storage manager and deduplicated related code
=> refactor(cli): refactor storage manager

.github/workflows/_docs_deploy.yml, .github/workflows/release_trdl-publish.yml
=> Revert "refactor(ci): replace action converge with werf command"

cmd/werf/common/container_backend.go, pkg/docker/main.go
=> fix(buildah): set docker config for buildah backend

cmd/werf/bundle/apply/apply.go, cmd/werf/bundle/render/render.go
Fix error `Error: pull bundle: error decoding secrets: error loading secret files data: error decoding secret/secret-config.txt: decryption failed: check encryption key and data: inconsistent data, unpad failed`
=> fix(deploy): `inconsistent data, unpad failed` error in bundle apply/render

cmd/werf/cleanup/cleanup.go, pkg/cleaning/cleanup.go
=> Revert "refactor(cleanup): add parallel execution for git history-based cleanup"

docs/pages_en/resources/telemetry.md, docs/pages_ru/resources/telemetry.md
fixes https://github.com/werf/werf/issues/6663
=> docs(telemetry): actualize

pkg/deploy/bundles/copy_test.go, pkg/deploy/bundles/registry/reference.go, pkg/deploy/bundles/remote_bundle.go
```
Error: error parsing bundle ref "registry.com/project/repo:96442577": ref may only contain a single colon character (:) unless specifying a port number
```
=> fix(bundle): incorrect parsing of image reference with colon in tag

pkg/build/build_phase.go, pkg/build/image/image.go, pkg/build/image/image_tree.go, pkg/build/image/multiplatform_image.go, pkg/cleaning/cleanup.go, pkg/logging/image.go
=> feat(logging): show image index and total to indicate build progress

pkg/build/build_phase.go
=> chore(logging, multiplatform): fix title message

go.mod, go.sum
=> Revert "chore(kubedog): update kubedog"

pkg/buildah/native_linux.go
=> refactor(build, buildah): up MaxPullPushRetries (3->10) and PullPushRetryDelay (2->5)
