- lib/dapp/build/stage/base.rb
- lib/dapp/version.rb
- Используются mount-ы, которые присутствуют в Dappfile и в лейблах базового образа.
- Эти же mount-ы добавляются в лейблы конечного образа и переиспользуются в других проектах, где этот образ будет использован в качестве базового.
> Изменена логика наследования mount-ов

- lib/dapp/artifact.rb
- lib/dapp/build/stage/mod/logging.rb
- lib/dapp/cli/build.rb
- lib/dapp/dimg.rb
- Опция при сборке '--introspect-artifact-stage STAGE'.
- При существовании нескольких артефактов:
- Интроспект отрабатывает для STAGE каждого артефакта.
- Для того, чтобы перейти к интроспекции STAGE конкретного артефакта, необходимо вручную выходить из интроспекции предыдущих (exit).
> Добавлена возможность интроспекции стадий артефактов

- lib/dapp/build/stage/ga_dependencies_base.rb
- lib/dapp/build/stage/ga_latest_patch.rb
- lib/dapp/build/stage/install/ga_pre_install_patch_dependencies.rb
- spec/integration/dimg_spec.rb
- spec/spec_helper/common.rb
- git artifact стадии собираются только если существуют:
- git artifact-ы.
- Cоответствующие зависимости.
- Дополнительным условием для стадий ga_latest_patch и ga_artifact_patch является наличие изменений, непустых патчей.
Уменьшен потенциальный размер собираемого кеша.
> Изменены зависимости у git artifact стадий

- lib/dapp/build/stage/base.rb
- lib/dapp/build/stage/build_artifact.rb
- lib/dapp/build/stage/import_artifact.rb
- lib/dapp/build/stage/install/install.rb
- lib/dapp/build/stage/setup/setup.rb
- отказ от кеширования *_dependencies_files_checksum в пользу кеширование signature.
- signature используется многократно;
- кешируются вычисления сразу всех dependencies.
> Доработано кеширование атрибутов стадий

- lib/dapp/dimg/build/stage/base.rb
- lib/dapp/dimg/build/stage/ga_archive.rb
- lib/dapp/dimg/build/stage/ga_artifact_patch.rb
- lib/dapp/dimg/build/stage/ga_base.rb
- lib/dapp/dimg/build/stage/ga_latest_patch.rb
- lib/dapp/dimg/build/stage/install/ga_post_install_patch.rb
- lib/dapp/dimg/build/stage/install/ga_post_install_patch_dependencies.rb
- lib/dapp/dimg/build/stage/install/ga_pre_install_patch.rb
- lib/dapp/dimg/build/stage/install/ga_pre_install_patch_dependencies.rb
- lib/dapp/dimg/build/stage/setup/ga_post_setup_patch.rb
- lib/dapp/dimg/build/stage/setup/ga_post_setup_patch_dependencies.rb
- lib/dapp/dimg/build/stage/setup/ga_pre_setup_patch.rb
- lib/dapp/dimg/build/stage/setup/ga_pre_setup_patch_dependencies.rb
- lib/dapp/dimg/dimg/stages.rb
* доступ к стадии dimg-а по имени.
* введение метода g_a_stage?, который позволил унифицировать переход к соседним git-артефакт стадиям.
> Рефакторинг взаимодействия между стадиями

- .gitignore
- lib/dapp/dapp.rb
- lib/dapp/dimg/git_artifact.rb
- lib/dapp/dimg/git_repo/own.rb
- spec/chef/testproject2/.chefinit/Berksfile
- spec/chef/testproject2/Dappfile
* GitRepo::Own#diff:  в diff-e между деревом определённого комита и деревом рабочей директории отсутствовали опции.
* GitArtifact#exclude_paths: лишние преобразования путей системных файлов.
* Dapp#local_git_artifact_exclude_paths: пути системных файлов были относительно директории с Dappfile-ом, а не родительской директории .git.
> Правки связанные с работой git-артефакта

- .gitignore
- spec/chef/testproject2/.chefinit/Berksfile
- spec/chef/testproject2/Dappfile
Тестовый проект spec/chef/testproject2 для установки chefinit cookbook'ов через артефакт.
closes #106
Рассматривать и принимать после решения проблем: #116, #118.
> Пример использования артефакта для установки chefinit

- lib/dapp/dimg/build/stage/from.rb
* отключается монтирование внешних директорий на стадии from.
* mount-ы из label-ов базового образа могут пересекаться с Dappfile mount-ами, что может привести к удалению данных из временных директорий используемых между сборками.
> Доработана логика очищения mount-ов

- lib/dapp/dimg/builder/chef.rb
Контрольная сумма кешировалась без учета разделения кеша по разным dimg. Из-за этого возникала проблема с тем, что пересборка не запускалась для тех dimg, которые стоят в конфигурации после неизмененного dimg.
> Ошибка в кешировании контрольной суммы стадии chef сборщика

- spec/chef/testproject2/.chefinit/Berksfile
- spec/chef/testproject2/.chefinit/Berksfile.lock
- spec/chef/testproject2/Dappfile
Тестовый проект spec/chef/testproject2 содержит Dappfile, в котором описан артефакт, производящий установку кукбуков при изменении файлов из git-репо Berksfile или Berksfile.lock. Cookbook'и устанавливаются в прежнее местоположение в /usr/share/dapp/chef_repo/cookbooks/ в конечном
образе.
resolve #129
> Замена стадии chef_cookbooks: пример

- lib/dapp/dimg/builder/chef/cookbook_metadata.rb
Решение проблемы с неработающими cookbook'ами, которые указали в зависимостях. Не хватало генерации директивы depends для metadata.rb для указанных в Dappfile зависимостей. dimod-cookbook'и в depends не добавляются, т.к. рецепты оттуда указываются напрямую в runlist.
Проявляется, когда указываешь coobook-зависимость и пытаешься использовать из рецепта проекта (не dimod) — падает.
> Генерация директивы depends для metadata.rb

- lib/dapp/dapp/deps/base.rb
- lib/dapp/dimg/builder/chef.rb
* Актуализирована версия chefdk до 1.2.22
* Версии dappdeps образов
* dappdeps/base:0.1.15
* dappdeps/chefdk:1.2.22-1
* Открывает возможность использования, например ubuntu:10.04 и centos:5 в качестве базового образа в docker.from
> Использование dappdeps слинкованных с glibc 2.5

- lib/dapp/dimg/build/stage/ga_artifact_patch.rb
* в отличие от GALatestPatch, базового класса GAArtifactPatch, стадия не должна зависить от наличия изменений в git-репозиториях.
> Поправлено условие сборки стадии g_a_artifact_patch

- config/en/net_status.yml
- lib/dapp/dimg/image/docker.rb
Поменялся формат поля Size для образов — убрали пробел
* Переделан парсер
* Исправлен баг в методе сброса кеша
* Использование return внутри begin..end не дает ожидаемого
результата, а выбрасывает из метода.
* Баг с неполным заполнением кеша мог проявляться,
если в системе существует хотя бы один образ с размером меньше килобайта.
> Исправлена ошибка при использовании docker 17.04.0

- lib/dapp/dimg/docker_registry.rb
- lib/dapp/dimg/image/docker.rb
- spec/unit/docker_registry_spec.rb
- spec/unit/image_docker_spec.rb
resolves #143
* имя репозитория не может содержать прописных букв.
* имя репозитория может состоять из одного символа.
> Поправлено регулярное выражение проверки docker репозитория

- config/en/net_status.yml
- lib/dapp/image/docker.rb
Поменялся формат поля Size для образов — убрали пробел
* Переделан парсер
* Исправлен баг в методе сброса кеша
* Использование return внутри begin..end не дает ожидаемого результата, а выбрасывает из метода.
* Баг с неполным заполнением кеша мог проявляться, если в системе существует хотя бы один образ с размером меньше килобайта.
> Исправлена ошибка при использовании docker 17.04.0 (backport из 0.10)

- lib/dapp/build/stage/artifact_default.rb
- lib/dapp/version.rb
Переделан механизм копирования файлов артефакта на использование rsync.
* Symlink'и копируются "как есть", чтобы они работали в директории назначения — надо использовать относительные пути.
* Убрано ограничение на спец. символы в именах файлов в артефакте.
* Теоретически повышена производительность для больших артефактов (не проверено).
> Возможность создавать symlink'и в артефактах

- lib/dapp/dimg/cli/mrproper.rb
> Fixed a typo

- lib/dapp/deployment/kube_base.rb
В дополнение к перехвату статуса ErrImagePull. Данный статус устанавливается после некоторого времени после ErrImagePull.
В dapp мы можем застать pod с контейнером уже в состоянии ImagePullBackOff, пропустив ErrImagePull, если не успеем.
> 20: Перехват ImagePullBackOff для job контейнеров

- lib/dapp/deployment/dapp/command/apply.rb
- lib/dapp/deployment/kube_app.rb
* Kubernetes Deployment
* Возвращена удаленная по неосмотрительности логика обновления объекта в Kubernetes
* Читаем текущую версию spec, в которой есть ResourceVersion
* Обновляем, новый spec, в котором указан ResourceVersion
* Таким образом в kubernetes срабатывает защита от непредусмотренного обновления (ResourceVersion, optimistic-locking)
* Логика проверки существования и защита от обновления уже актуального объекта перенесена в KubeApp
* Kubernetes Service
* Добавлено логирование по аналогии с Deployment
* Не найдено возможности отслеживать статус, возможно в этом и нет необходимости
> 21: Корректное обновление Deployment, лог обновления Service

- config/en/net_status.yml
- lib/dapp/deployment/app.rb
- lib/dapp/deployment/config/directive/expose.rb
- spec/unit/config/deployment/expose_spec.rb
- spec/unit/config/deployment/group_spec.rb
* в качестве параметре принимается единственный порт;
* добавлена необязательная поддиректива `target`.
> 22: Изменена директива expose.port

- lib/dapp/deployment/kube_app.rb
- lib/dapp/deployment/kubernetes.rb
* При смене NodePort или LoadBalancer на ClusterIP в spec ресурса оставалось старое поле nodePort
* Это поле устанавливает сам kubernetes для NodePort или LoadBalancer
* А когда меняется type на ClusterIP — kubernetes ругается на наличие этого поля в replace-операции
* Сделано ручное удаление специально для данной ситуации
* Замена labels и selector при обновлении Service
* Когда обновляется kubernetes Service те metadata.labels и spec.selector, которые были указаны в текущей версии объекта перетираются значениями, соответсвующими текущей конфигурации из Dappfile.
* Рефакторинг kubernetes клиента
* Данные для ошибок
* Попытка распарсить json когда возможно
* Если не получается распарсить — в ошибке будет http body
* Это сделано, чтобы ошибки стали более читаемыми
* Пользовательские ошибки …
> 27: Возможность менять NodePort на ClusterIP для Service и рефакторинг kubernetes клиента

- lib/dapp/deployment/app.rb
- lib/dapp/deployment/kube_app.rb
Авто монтирование директории узла `/var/lib/dapp/deployment/volumes/<dapp-name>/<app-name>` в директорию `/.data` всех контейнеров всех Pod'ов одного app из Dappfile (через kubernetes  hostPath).
Сделано для непредусмотренных ситуаций, когда очень нужна возможность хранения данных.
Фикс критерия ожидания выката kube Deployment по полю `deployment.kubernetes.io/revision`. Ранее ожидалась смена этой ревизии. Но это не работает при изменении кол-ва replicas — ревизия остается старой.
На данный момент используется следующий костыль:
* При обновлении ревизия сбрасывается.
* Ожидается переустановка этого поля.
* При этом значение ревизии может остаться старым, важен лишь факт ее появления у ресурса.
> 28: Авто-том /.data монтируется во все Pod'ы app, ожидание Deployment при изм. replicas исправлено

- lib/dapp/build/stage/artifact_default.rb
- lib/dapp/version.rb
Логическая ошибка в указании параметов в rsync: надо указывать позитивные фильтры для всех элементов каждого пути из include_paths.
> Исправление нерабочего include_paths для артефактов

- lib/dapp/build/stage/artifact_default.rb
- lib/dapp/dimg.rb
- lib/dapp/dimg/path.rb
- lib/dapp/version.rb
- spec/chef/testproject/.dapp_chef/recipes/build_artifact/myartifact.rb
Те owner/group, которые были проставлены при создании файлов артефакта будут использованы и при импорте артефакта в образ в случае если owner и group не указаны явно в Dappfile.
Очистка tmp-dir сделана через docker-контейнер под пользователем root, т.к. в этой директории могут быть произвольные владельцы и права после копирования файлов из артефакта.
> Экспорт файлов артефакта без изменения owner/group

- lib/dapp/kube/dapp/command/deploy.rb
- lib/dapp/kube/dapp/command/secret_file_encrypt.rb
Если используется команда `dapp kube secret file encrypt` без параметра `-o`, то зашифрованные данные пишутся на stdout. Скопировав их оттуда и вставив в редактор в конце будет вставлен перенос строки в половине существующих тектовых редакторов. Также перенос строки будет вставлен в файл output и при использовании такой записи: `dapp kube secret file encrypt mysecret > output`.
Недоработка была в том, что при чтении секрета из файла хвостовой перенос строки не отрезался.
При этом при использовании параметра `-o` хвостовой перенос строки не вставлялся и поэтому с этим параметром все работало.
Переделано так, что при использовании параметра `-o` обязательно вставляется хвостовой перенос строки. И этот перенос строки отрезается при расшифровке файла.
* Права только на чтение только …
> Фикс протокола записи секретов в файлы; безопасные права доступа к расшифрованым секретам

- lib/dapp/dapp.rb
Имя проекта определяется как имя директории, содержащей Dappfile. В этом случае Dapp::name возвращал Pathname вместо строки.
> Исправление ошибки при запуске сборки chef-проекта без git-репо

- lib/dapp/kube/kubernetes/client.rb
- lib/dapp/kube/kubernetes/client/error.rb
- lib/dapp/kube/kubernetes/manager/container.rb
- lib/dapp/kube/kubernetes/manager/deployment.rb
- lib/dapp/kube/kubernetes/manager/job.rb
Любой запрос на получение лога контейнера в pod'е может упасть с ошибкой, если контейнер еще не запущен. Даже если перед запросом логов проверить состояние контейнера — это не гарантирует, что контейнер не будет остановлен прямо перед запросом логов.
> Обработка ошибок запросов на получение логов контейнеров

- lib/dapp/kube/dapp/command/deploy.rb
После завершения работы helm хуки должны быть выполнены, следовательно и поток для вывода логов должен завершиться.
Но в коде вывода логов вероятно есть баг, который блокирует выход этого потока.
Как защита от этого на данный момент поток вывода логов принудительно завершается после выхода helm.
> Принудительный выход из потока для dapp/watch-logs

- lib/dapp/dimg/git_artifact.rb
- lib/dapp/dimg/git_repo/base.rb
* Создание содержимого стадии архива без использования патчей в rugged, а через api для обхода деревьев.
* Рефакторинг
* Кода создания tar-архива для archive-стадии, использование repo.entries вместо repo.patches
* Кода расчета stage-dependencies стадий от git-артефактов
> Фикс падения dapp на больших git-артефактах

- lib/dapp/dimg/build/stage/ga_related_dependencies_base.rb
Раньше если стадия пустая, то изменение файлов из stage_dependecies для этой стадии ни на что не влияло. Теперь, если указать stage_dependencies для стадии, то она начнет собираться и пересобираться при изменении указанных файлов, но т.к. в ней нет инструкций -- это лишнее действие.
> Revert "Фикс stage_dependencies для пересборки стадий install,setup"

- lib/dapp/helper/trivia.rb
При исползовании опции --use-system-tar git-архив создавался без использования временной директории, а прямо в корне системы, где запущен dapp. Если dapp был запущен под root — все работало "незаметно", если не root — был permission denied.
Вывод: никогда не использовать `Pathname::+` и `Pathname::join`, а использовать только `File.join`.
> Фикс проблемы с созданием git-архива + --use-system-tar (permission denied)

- lib/dapp/helper/trivia.rb
Косяк с выравниванием, потенциальный косяк с передачей аргументов в File.join массивом, а не отдельными аргументами. Хотя File.join работает по-всякому.
> Фикс проблемы с созданием git-архива + --use-system-tar (permission denied) [2]

- config/en/common.yml
- lib/dapp/dimg/build/stage/base.rb
- lib/dapp/dimg/build/stage/ga_base.rb
- lib/dapp/dimg/build/stage/ga_dependencies_base.rb
- lib/dapp/dimg/build/stage/import_artifact.rb
- lib/dapp/dimg/build/stage/mod/logging.rb
- lib/dapp/dimg/build/stage/setup/ga_post_setup_patch_dependencies.rb
- lib/dapp/dimg/image/docker.rb
На текущий момент пересборка необходима в тех случаях, когда в лейблах образов кеша содержатся несуществующие комиты (rebase).
> Зачем делать image_reset для всех последующих образов?
* После того, как стадия была пересобрана, необходимо актуализировать закешированные данные в связанных стадиях:
* Сбросить образ из кеша `Image::Stage.images` (никак не связан с образами хранящимися в docker, `Image::Stage.cache`). Таким образом, обновив from, пересобранным образом. 
* Сбросить dependencies. В случае, если зависимости основываются на комитах (актуально для `setup/ga_post_setup_patch_dependencies` при подсчёте размеров патчей, и последующих стадий, так как изменяется сигнатура).
* Сбросить закешированные git-комиты для git-стадий.
> Зачем делать image_untag для всех последующих собранных …
> Пересборка невалидных стадий во время сборки

- lib/dapp/dapp/shellout/base.rb
- lib/dapp/dimg/build/stage/base.rb
- lib/dapp/dimg/dimg.rb
- lib/dapp/dimg/image/docker.rb
Использование `docker inspect` вместо `docker images`.
> Ускорение работы внутреннего кеша образов сборщика dimg

- lib/dapp/dimg/build/stage/import_artifact.rb
Нельзя было указывать пути со слешами в export'ах артефактов
> Возможность собирать scratch-образы

- lib/dapp/kube/cli/command/kube/render.rb
- lib/dapp/kube/dapp/command/render.rb
* позволяет вывести определённую группу спеков;
* в качестве параметра указывается шаблон пути (`-t .helm/templates/*_custom`) или имени спека (`-t *_custom`).
* ко всем шаблонам в конец добавляется `*`.
> dapp kube render command: добавлена опция `--template GLOB_PATTERN`

- lib/dapp/kube/dapp/command/render.rb
- lib/dapp/kube/helm/release.rb
* независимость от Chart.Name;
* изменена логика выборочного вывода spec-ов (`--template GLOB_PATTERN`):
* в качестве параметра указывается шаблон пути до spec-ов:
* chart-a `-t .helm/templates/*_custom`;
* subchart-a `-t .helm/charts/custom_chart/templates/*_custom`.
* в качестве параметра указывается шаблон пути генерируемого `helm template` (# Source Chart.Name/templates/custom_name.yaml);
* пути могут быть как относительными, так и абсолютными.
> dapp kube render command: изменена логика

- lib/dapp/dimg/build/stage/base.rb
- lib/dapp/dimg/dimg.rb
* при вызове с опцией сохраняется обычный кэш, а не dev, как ранее.
> dapp dimg build command: изменена логика опции `--force-save-cache`

- lib/dapp/dimg/build/stage/base.rb
- lib/dapp/dimg/build/stage/before_install.rb
- lib/dapp/dimg/build/stage/before_install_artifact.rb
- lib/dapp/dimg/build/stage/from.rb
- lib/dapp/dimg/build/stage/ga_base.rb
* так как комиты стали использоваться из лейблов образов предыдущих стадий (#443), возможна такая ситуация, что невалидные комиты содержатся в обычных стадиях, а идущие до них `g_a` стадии находятся в состоянии `NOT_PRESENT`, пересборка не выполнится. Таким образом, невалидные комиты надо проверять во всех стадиях, где они хранятся. Исключением являются стадии `from`, `before_install` и `before_install_artifact`.
> Правила пересборки для стадий

- lib/dapp/dimg/git_repo/remote.rb
- spec/unit/git_repo_spec.rb
* исключена зависимость от указанного url (token-а, пользователя).
> Кэширование git-репозиториев по группе и имени

- lib/dapp/dimg/build/stage/base.rb
Проверка по image.built? вместо image.tagged? при получении коммита стадии.
> Фикс проблемы с отсутствием файлов после наложения latest патча (0.19 backport)

- lib/dapp/dimg/builder/chef.rb
- lib/dapp/dimg/git_repo/remote.rb
Поменялась структура кеша git-remote-repository в build-dir, но продолжали использоваться старые каталоги, которые создавал dapp.
Для решения были переименованы актуальные каталоги с кешом, оставлена возможность менять версию кеша из исходников dapp.
На данный момент кеш git-remote-repository находится в `<build-dir>/remote_git_repo/<cache-version=1>/<group>/<name>`.
> DAPP_CHEF_DEBUG=yes для debug-вывода в chef, (fix) После обновления с 0.21.2 на 0.21.3 перестала работать конструкция с внешним гитом

- lib/dapp/cli/command/base.rb
- lib/dapp/dapp.rb
- lib/dapp/dimg/cli/command/base.rb
- lib/dapp/kube/cli/command/kube/deploy.rb
- lib/dapp/kube/cli/command/kube/lint.rb
- lib/dapp/kube/cli/command/kube/render.rb
- lib/dapp/kube/kubernetes/client.rb
* Автологин в docker
* Перенесен из ns=dimg на уровень выше в dapp
* Отрабатывает при наличии параметра repo и параметров registry-*
* Не отрабатывает в режиме --without-registry (для dapp kube deploy)
* Исправлен баг в использовании excon
* 2 параллельных потока пользовались excon
* один из потоков менял глобальные параметры Excon.defaults
* другой поток использовал эти параметры
* проявлялось как "невозможно проверить сертифкат" при запуске деплоя
> (fix) Проверка сертификатов на deploy сервере в 22версии не работала

- lib/dapp/dapp/option_tags.rb
- lib/dapp/kube/dapp/command/common.rb
- lib/dapp/kube/dapp/command/lint.rb
* Использование consistent-uniq-slug для:
* параметра --tag (тег docker образа)
* параметра --namespace (kubernetes).
* Зачем сделано:
* Т.к. эти параметры не имею смысла без slug.
* Для параметров указанных пользователем будет сохранена совместимость с текущими конфигурациями.
* Т.е. если в gitlab-ci написано --tag <branch-name> и кто-то коммитнул имя бранча, которое надо прогнать через slug, то все сработает без изменения конфигурации.
* Имя helm релиза не использует slug, т.к. состоит из компонентов, которые гарантированно уже slug'нутые (имя dapp и namespace).
> (fix) Использование slug для всех docker тегов из любых параметров

- lib/dapp.rb
- lib/dapp/cli/command/base.rb
- lib/dapp/dapp.rb
- lib/dapp/dimg/cli/command/dimg/push.rb
- lib/dapp/dimg/cli/command/dimg/stages/pull.rb
- lib/dapp/dimg/cli/command/dimg/stages/push.rb
- lib/dapp/dimg/docker_registry/base/authorization.rb
- lib/dapp/kube/cli/command/kube/deploy.rb
- lib/dapp/kube/cli/command/kube/lint.rb
- lib/dapp/kube/cli/command/kube/render.rb
* до полного перехода на использование api используется в следующих командах:
* dapp dimg push/spush;
* dapp dimg stages pull/push.
* для аутентификации docker registry api использует:
* значения пользовательских опций `--registry-username`, `--registry-password`;
* переменная окружения CI_JOB_TOKEN;
* полученный token из конфига docker-а.
> Выпилено использование бинарника docker для login в registry на deploy-сервере

- lib/dapp/dimg/config/directive/dimg/instance_methods.rb
- lib/dapp/dimg/config/directive/dimg_group.rb
- spec/unit/config/dimg/artifact_spec.rb
- spec/unit/config/dimg/dimg_group_spec.rb
* артефакты на одном уровне не наследуются;
* зависимость артефактов достигается за счёт вложенности (dimg_group).
close #404
> Изменена логика наследования артефактов

- bin/dapp
- lib/dapp/helper/yaml.rb
- lib/dapp/kube/dapp/command/lint.rb
* Игнорирование пустых yaml файлов в рамках команд развёртки (close https://github.com/flant/dapp/issues/457).
* dapp kube lint command: fix (close https://github.com/flant/dapp/issues/456):
* cистемные глобальные опции перетирали пользовательские.
* Обработка прерывания соединения при перенаправлении вывода dapp (close https://github.com/flant/dapp/issues/455).
> Мелкие правки

- lib/dapp/dimg/build/stage/artifact_default.rb
- lib/dapp/dimg/builder/chef/cookbook.rb
Опция --inplace для rsync, чтобы не создавать временные файлы.
Файлы, начинающиеся на .wh в aufs являются служебными.
> Фикс проблемы с копированием файлов типа wh.jpg

- lib/dapp/dapp.rb
- lib/dapp/dimg/cli/command/dimg/cleanup_repo.rb
Передумали использовать DAPP_CI_JOB_TOKEN, поэтому он выпилен за ненадобностью.
> DAPP_DIMG_CLEANUP_REGISTRY_PASSWORD используется для dapp dimg cleanup repo

- lib/dapp/kube/helm/values.rb
В случае использования dapp только для deploy в docker-registry не будет в наличии dimg'ей.
В этом случае определение docker-image-id и docker-image-labels опционально и при недоступности docker-registry в helm values <dimg>.docker_image_id, <dimg>.git.<ga>.commit_id будут значения "-".
refs #486
> Игнорирование недоступности docker-registry в deploy

- lib/dapp/kube/helm/release.rb
Если в шаблонах есть 2 yaml-разделителя `---` подряд без текста между ними, то dapp kube render падает с ошибкой:
```
lib/dapp/kube/helm/release.rb:81:in `map': undefined method `join' for nil:NilClass (NoMethodError)
```
> (fix) kube render undefined method `join' for nil

- bin/dapp
- config/en/net_status.yml
- lib/dapp/dapp/logging/process.rb
- lib/dapp/kube/dapp/command/deploy.rb
- lib/dapp/kube/kubernetes/manager/container.rb
Если допущена ошибка в указанной команде для entrypoint контейнера helm-hooks-job'а, то ранее выводилось сообщение:
```
failed to open log file "/var/log/pods/b757f56b-f777-11e7-8176-0800276846e1/migrate_5.log": open /var/log/pods/b757f56b-f777-11e7-8176-0800276846e1/migrate_5.log: no such file or directory
```
Теперь полный вывод в такой ситуации будет таким:
```
$ dapp kube deploy :minikube --namespace my --timeout 15
Deploy release ex-dapp-25-my                                                                                                 [RUNNING]
Delete hooks job `migrate` ...                                                                                                  [OK] 0.05 sec
Run helm …
```
> (fix) failed to open log file ... для helm-hooks-job

- lib/dapp/dimg/dapp/command/stages/cleanup_local.rb
Починен dapp dimg stages cleanup local.
> (fix) stages_cleanup_by_repo': undefined method `dimg_registry' for #<Dapp

- lib/dapp/dimg/dapp/command/common.rb
- lib/dapp/dimg/dapp/command/stages/cleanup_local.rb
*  dapp dimg stages cleanup local command: фикс очистки с опцией `--proper-cache-version`;
*  dapp dimg stages cleanup local command: debug переменная окружения 
* `DAPP_STAGES_CLEANUP_LOCAL_DISABLED_DATE_POLICY` для отключения игнорирования образов младше двух часов при очистке с опцией `--improper-repo-cache`.
> dapp dimg stages cleanup local command: правки

- config/en/net_status.yml
- lib/dapp/dapp.rb
- lib/dapp/dapp/option_tags.rb
- lib/dapp/dimg/config/directive/git_artifact_remote.rb
- lib/dapp/dimg/dapp/command/cleanup_repo.rb
- lib/dapp/dimg/dimg/git_artifact.rb
- lib/dapp/dimg/git_artifact.rb
- lib/dapp/dimg/git_repo/base.rb
- lib/dapp/dimg/git_repo/own.rb
- lib/dapp/dimg/git_repo/remote.rb
- lib/dapp/helper/trivia.rb
- lib/dapp/kube/helm/values.rb
- spec/integration/chef_spec.rb
- spec/integration/submodule_spec.rb
- spec/spec_helper.rb
- spec/spec_helper/common.rb
- spec/spec_helper/dimg.rb
- spec/spec_helper/git.rb
- spec/unit/git_artifact_spec.rb
> Поддержка git submodules
* git-артефакт рекурсивно пораждает артефакты submodule-й:
* submodule-артефакт идентичен описанному в Dappfile удалённому git-репозиторию;
* при создании дочерних артефактов преобразуются параметры базового:
* наследуются `owner`, `group`;
* наращивается `cwd`;
* преобразуются `include_paths`, `exclude_paths`, `stages_dependencies`.
* добавление/исключение submodule-й не отличается от обычных файлов и директорий в git-артефакте.
> Тесты
* интеграционные тесты для git submodules:
* проверка на добавление по типу submodule url: `https`, `relative_path`, `local_path`;
* проверка вложенных submodule-й;
* проверка submodule branch.
* юнит-тесты для git submodules
* проверка преобразования url submodule в зависимости от репозитория, в том числе проверка …
> Поддержка git submodules

- lib/dapp/dimg/dimg/git_artifact.rb
- lib/dapp/dimg/git_artifact.rb
- lib/dapp/dimg/git_repo/remote.rb
* при инициализации git-артефактов в dimg и артефакт-dimg мог использоваться один и тот же GitRepo::Remote;
* использовался объект GitRepo::Remote, который связан с dimg, объявленным при первом обращении;
* это приводило к ошибкам при наложении патчей и создании артефактов (из-за несоответствующих tmp-путей у dimg-ей).
> Fix: отказ от кеширования GitRepo::Remote по url и branch

- config/en/net_status.yml
- lib/dapp/dimg/config/directive/artifact_dimg.rb
- lib/dapp/dimg/config/directive/dimg/instance_methods.rb
- lib/dapp/dimg/config/directive/dimg/validation.rb
* Config: добавлен auto excluding для артефактов артефактов.
* Config: фикс валидации путей артефактов:
* не учитывался случай, когда артефакты:
* добавляются по одному и тому же пути;
* имеют `exclude_paths`;
* не имеют `include_paths`.
* Config: рефакторинг
* Config: при конфликте артефактов генерируются соответствующие директивы.
```
Conflict between artifacts!
git('https://github.com/group/project.git').add('/directory') do
exclude_paths 'examples'
to '/app'
end
artifact.export('/app') do
to '/app'
end
```
> Config: обработка артефактов

- config/en/net_status.yml
- lib/dapp/kube/dapp/command/deploy.rb
- lib/dapp/kube/helm/release.rb
- lib/dapp/kube/kubernetes/client/resource/pod.rb
- lib/dapp/kube/kubernetes/manager/container.rb
- lib/dapp/kube/kubernetes/manager/deployment.rb
- lib/dapp/kube/kubernetes/manager/pod.rb
Зависело от того, насколько быстро выполняется хук. Если "очень быстро", то dapp ничего не выводил.
Также:
* Улучшена синхронизация вывода helm stdout/stderr в процессе деплоя с выводом логов: все выводится строго по-очереди, сначал watch-logs, затем helm output.
* User-friendly ошибки при возникновении ImagePullBackOff, ErrImagePull, CrashLoopBackOff для отслеживания Deployment и Job'ов с dapp/watch-logs.
* В случае, если под еще не перешел в кондицию "Ready", при каждом перевыкате через dapp будут выводится все логи всех контейнеров пода для удобства пользователя. Ранее эти логи при повторном запуске не выводились, надо было лезть на сервер. Для ready-подов так не делается, чтобы не выводить при каждом последующем выкате все предыдущие логи пода, если он не был пересоздан, вместо этого …
> (fix) Иногда не выводятся логи для dapp/watch-logs

- go-build.sh
- go-get.sh
Use go.uuid v1.2.0 in go-get.sh
> (fix build) multiple-value uuid.NewV4() in single-value context

- lib/dapp/dapp/deps/base.rb
- lib/dapp/dapp/deps/gitartifact.rb
- lib/dapp/dapp/deps/toolchain.rb
- lib/dapp/dapp/lock.rb
- lib/dapp/dimg/builder/chef.rb
- lib/dapp/dimg/builder/chef/cookbook.rb
- lib/dapp/dimg/git_repo/remote.rb
Changed default lock timeout:
* For stages (affects build & push): 24 hours (was 5 minutes)
* For dappdeps downloading: 10 minutes (was 2-5 minutes)
* For git fetch operations: 10 minutes (was 2 minutes)
* For berks deps installation: 10 minutes (was 2 minutes)
> (fix) Could not obtain lock for `...` within 300 seconds!

- lib/dapp/dapp.rb
- lib/dapp/dimg/dapp/dimg.rb
- lib/dapp/dimg/dimg.rb
- spec/spec_helper/dimg.rb
`/tmp/dapp-<date>-<random>` was not cleaned up after `dimg push` & `kube deploy` commands.
Now cleanup is durably called on every dapp termination.
> (fix) /tmp/dapp-<date>-<random> dirs cleanup

- lib/dapp/dapp/option_tags.rb
--tag-ci was broken when CI_BUILD_TAG and CI_BUILD_REF_NAME available at the same time.
--tag-ci will use only one of tag-scheme or branch-scheme now.
> (fix) dapp kube deploy: Expected only one tag

- lib/dapp/dimg/dimg/git_artifact.rb
- lib/dapp/dimg/git_artifact.rb
* git-артефакт считается пустым, если в репозитории отсутствуют файлы удовлетворяющие конфигурации;
* dev-режим не работает в пустых git-артефактах, т.к. необходим тип (:directory, :file), который определяется исходя из существующих в репозитории файлов.
> Игнорирование пустых git-артефактов

- lib/dapp/dapp.rb
- lib/dapp/dimg/build/stage/from.rb
* попытка авторизации выполняется, если имя базового образа dimg-а, `docker.from`, начинается c `$CI_REGISTRY`.
> GITLAB: docker login перед pull-ом базового образа

- pkg/config/common.go
- pkg/config/raw_dimg.go
Unknown field `field` errors fix.
> (yaml) Do not double-print cfg when error is in yaml-doc toplevel key

- .gitignore
- pkg/config/errors.go
- playground/test2/dappfile.yml
Blocks are indented by space-only to allow posting dapp errors to slack inside block:
```
Bad dappfile /home/distorhead/go-workspace/src/github.com/flant/dapp/playground/test2/dappfile.yml: Unsupported ansible task!
file: path=/etc mode=0777
Supported modules list:
* command
* shell
* copy
* debug
* apk
* apt
* apt_key
* apt_repository
* yum
* yum_repository
/home/distorhead/go-workspace/src/github.com/flant/dapp/playground/test2/.dappfile.render.yml
4  dimg: hello
5  from: ubuntu:16.04
6  ansible:
7    beforeInstall:
8      - debug: msg='Start install'
9      - debug: msg='Hello install'
10      - file: path=/etc mode=0777
11      #- copy:
12          #src: /bin/sh
13          #dest: /bin/sh.orig
14    install:
15      - apk:
16          name: curl
17          update_cache: yes
18 …
```
> (yaml) Remove ``` from yml errors

- lib/dapp/dimg/dapp/command/cleanup.rb
- lib/dapp/dimg/dapp/command/common.rb
- lib/dapp/dimg/dapp/command/mrproper.rb
- lib/dapp/dimg/dapp/command/stages/cleanup_local.rb
- lib/dapp/dimg/dimg.rb
* dangling образы могут оставаться при неуспешных сборках по аналогии с docker build;
* контейнеры могут оставаться при некорректном завершении сборки;
* чистка выполняется по умолчанию;
* добавлен label `dapp=#{project_name}` в запускаемых контейнер, отвечающего за очистку временной директории приложения проекта.
> dapp dimg stages cleanup local: чистка dangling образов и контейнеров

- config/en/net_status.yml
- docs/pages/command/debugging.md
- lib/dapp/dimg/cli/command/base.rb
- lib/dapp/dimg/cli/command/dimg/build.rb
- lib/dapp/dimg/cli/command/dimg/run.rb
- lib/dapp/dimg/dapp/command/run.rb
- lib/dapp/dimg/dimg.rb
- spec/unit/cli_spec.rb
- spec/unit/dapp_spec.rb
* если `DOCKER ARGS` не переданы, то используются значения по умолчанию и результирующая команда принимает следующий вид: `docker run -ti --rm <stage-image-id> /bin/bash`;
* команду можно вызвать для конкретной собранной стадии (опция `--stage STAGE), при этом сам dimg может быть собран частично.
> dapp dimg run command: аргументы по умолчанию и опция '--stage STAGE'

- lib/dapp/kube/kubernetes/manager/deployment.rb
Do not wait for updatedReplicas, availableReplicas, readyReplicas when target replicas = 0.
> (fix) Deploy hangs on zero Deployment replicas

- lib/dapp/dimg/build/stage/ga_latest_patch.rb
* обработка ситуации, когда в `ga_post_setup_patch` стадии несуществующий комит в лейбле.
> Дополнение к пересборке стадий при несуществующих комитах в лейблах

- lib/dapp/dimg/docker_registry/base.rb
* blobs should be deleted by gitlab-ctl registry-garbage-collect
> DockerRegistry API: deleting tag without blobs

- lib/dapp/dapp/sentry.rb
- lib/dapp/kube/dapp/command/deploy.rb
* All CI-env variables extra data.
* Dapp version tags data.
* Docker version tags data.
* Additional capture for deploy jobs-watcher Default exceptions from parallel thread.
* Because these exceptions will not pass through bin/dapp main exception capture point.
> (sentry) Capture more data for sentry

- lib/dapp/cli/command/base.rb
- lib/dapp/dapp/sentry.rb
- lib/dapp/dimg/cli/command/base.rb
- lib/dapp/dimg/dimg.rb
* manual usage info message if dapp isn't used by CI
* tags: error-code, dapp-command
> sentry: add info message and tags

- lib/dapp/dapp/sentry.rb
After sentry_message call all password-related data stored in ruby hashes changes to `*` symbols.
> `user not authorized` on dapp dimg cleanup repo

- lib/dapp/dimg/dapp/command/cleanup_repo.rb
- lib/dapp/dimg/dapp/command/common.rb
- lib/dapp/dimg/dapp/command/stages/cleanup_local.rb
- lib/dapp/dimg/dapp/command/stages/common.rb
- lib/dapp/dimg/git_repo/base.rb
* store 10 images per dimg sorted by creation date for `commit` && `tag` schemes
closes https://github.com/flant/dapp/issues/669
> dapp dimg cleanup repo: change limit policy logic

- lib/dapp/kube/helm/values.rb
* each variable available by key like `.Values.global.ci.CI_<VARIABLE_NAME>`
closes #707
> deploy commands: support ci environment variables in helm templates

- dapp.gemspec
- lib/dapp/dimg/dimg/git_artifact.rb
- lib/dapp/dimg/git_artifact.rb
- lib/dapp/dimg/git_repo/base.rb
- lib/dapp/dimg/git_repo/local.rb
- lib/dapp/dimg/git_repo/remote.rb
- spec/integration/submodule_spec.rb
- spec/spec_helper/dimg.rb
- spec/unit/git_artifact_spec.rb
- spec/unit/git_repo_spec.rb
* dapp.gemspec: up rugged
* git remote: fetch all instead of specific branch
* Update submodule logic: always use superproject’s recorded submodule SHA-1
* dapp dimg build: up logging
closes https://github.com/flant/dapp/issues/671
> Update submodule logic: always use superproject’s recorded submodule SHA-1

- lib/dapp/dimg/cli/command/dimg/cleanup_repo.rb
- lib/dapp/dimg/dapp/command/cleanup_repo.rb
- lib/dapp/kube/cli/command/kube/deploy.rb
- lib/dapp/kube/cli/command/kube/dismiss.rb
- lib/dapp/kube/cli/command/kube/minikube_setup.rb
- lib/dapp/kube/dapp/command/common.rb
- lib/dapp/kube/dapp/command/minikube_setup.rb
- lib/dapp/kube/kubernetes/client.rb
* Set connection, read and write timeouts to the value specified in option `--kubernetes-timeout`.
* Auto retry all GET requests to kubernetes api-server. 6 retry attempts with 5 seconds pause in between.
> [kube] Kubernetes tcp timeouts option and auto-retry requests

- lib/dapp/kube/dapp/command/deploy.rb
- lib/dapp/kube/kubernetes/manager/deployment.rb
By default dapp will watch all deployments rolling oout status after calling helm.
If Deployment has annotation dapp/watch=false or dapp/watch-logs=false,
then dapp will not watch this deployment.
> [kube] dapp/watch=false to disable Deployment watch during deploy

- lib/dapp/kube/helm/values.rb
Exclude .Values.global.ci.CI_ENVIRONMENT_URL variable.
This variable can have broken unexpanded value.
> [fix] Error: failed parsing --set data: ... has no value

- lib/dapp/kube/kubernetes/client.rb
GCE Kubernetes somehow send a minor version with +. Example:
```
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
> GCE kubernetes return minor version as 10+

- lib/dapp/kube/helm/release.rb
The problem arises when using `.Release.Name`
helm value in subchart for example.
Pass real release name to `helm template` invocation,
which used to render yaml-specs of resources being deployed
for internal dapp usage.
> [deploy] Fix 404 NotFound `.../deployments/RELEASE-NAME-...`

- lib/dapp/dapp/slug.rb
* environment variable `DAPP_SLUG_V2` turns on limit of 53 symbols
closes https://github.com/flant/dapp/issues/781
> Optional slug limit length of 53 symbols

- lib/dapp/dimg/dapp/command/stages/common.rb
- lib/dapp/dimg/docker_registry/base.rb
- lib/dapp/dimg/docker_registry/base/authorization.rb
- lib/dapp/dimg/docker_registry/dimg.rb
Use absolute constants paths in all DockerRegistry::Error related `raise` and `rescue`.
> [cleanup] Fix `uninitialized constant Dapp::Dimg::DockerRegistry::Error::NotFound`

- pkg/git_artifact/git_artifact.go
- pkg/git_repo/base.go
- pkg/git_repo/git_repo.go
- pkg/git_repo/remote.go
* remote git artifact uses latest origin/branch commit if branch/tag/commit isn't specified
> (way2go) git artifact: up latest commit logic

- lib/dapp/dimg/git_artifact.rb
Error was introduced in golang git-artifact cmd.
> (build) Fixed build error `syntax error near unexpected token `&&'`

- pkg/git_repo/archive.go
- pkg/git_repo/base.go
- pkg/git_repo/patch.go
- pkg/git_repo/remote.go
Switched to github.com/flant/go-git fork with bugfix in git library.
> Fix `fatal: corrupt patch` build error

- .travis.yml
- publish.sh
* Cache gopath directory using travis.
* Do not double run go-get and go-build.
> (publish) Optimize publishing process

- docs/pages/faq.md
> [docs]  Why dapp doesn’t save cache on failed builds by default?

- pkg/git/diff.go
Disable renames in git diff patches.
Rename-diffs are not possible with include-paths/exclude-paths and base-path params of dapp git-artifacts (the same applies for copy-diffs).
> (go-deeper) Fix `error parsing diff line: unexpected diff line: "similarity index ..."`

- lib/dapp/dimg/build/stage/base.rb
* stage should be present if next stage should be rebuild (e.g. g_a stage after git-repository rebase)
> Fix stage not_present condition

- pkg/docker_registry/main.go
go-containerregistry api change
> (go-deeper) Fixup travis build error `undefined: remote.DeleteOptions`

- pkg/config/parser.go
* dapp crashes with trace if dappfile.yaml ends with following (+ without newline at the end):
```
---
---
```
> Improve dappfile doc splitter

- pkg/true_git/archive.go
> (go-deeper) Preemptive memleak fix in git archive creation

- pkg/true_git/diff_parser.go
Bad patch for empty file delete or create.
> (go-deeper) Fix `git apply: bad git-diff - inconsistent old filename`

- lib/dapp/dapp.rb
- lib/dapp/dapp/git_artifact.rb
- lib/dapp/dimg/git_artifact.rb
- lib/dapp/dimg/git_repo/own.rb
- pkg/build/git_artifact.go
- pkg/git_repo/base.go
- pkg/git_repo/git_repo.go
* Include/exclude paths does not work when cwd has been specified.
* Include/exclude paths does not affect stageDependencies checksum.
closes #997
> (go-deeper) Fix GitArtifact include/exclude paths bugs

- lib/dapp/dapp/sentry.rb
Remove git info from sentry report.
> Fix `No such file or directory @ rb_sysopen - /tmp/dapp-ruby2go`

- cmd/deploy-watcher/main.go
- go-build.sh
- go-env
- lib/dapp/dapp/ruby2go.rb
- lib/dapp/kube/dapp/command/deploy.rb
Only enabled when `KUBEDOG=1` environment variable is set.
> [kubedog] Use kubedog to watch job/deploy

- lib/dapp/dapp/sentry.rb
Error in error handling code related to the sentry reports.
> Fix2 `No such file or directory @ rb_sysopen - /tmp/dapp-ruby2go...`

- pkg/true_git/archive.go
Do not exclude .gitignore, .gitmodules and .gitkeep from git archive.
> [go-deeper] Fix `error: /app/.gitignore: No such file or directory`

- bin/dapp
- lib/dapp/kube/dapp/command/deploy.rb
- pkg/kill_cord/kill_cord.go
- pkg/ruby2go/ruby2go.go
* Gitlab Cancel Button will kill not only ruby-dapp, but also
all child processes spawned by ruby-dapp. Fixed the case, when
ruby-dapp has been killed, but ruby2go watcher process
continues to work in background.
* Wait job-watcher only when helm release succeeded.
Kill job-watcher otherwise.
> Added "kill cord" to kill process when one of the parents is dead

- cmd/dapp/bp/bp.go
- cmd/dapp/build/build.go
- cmd/dapp/cleanup/cleanup.go
- cmd/dapp/common/common.go
- cmd/dapp/deploy/deploy.go
- cmd/dapp/flush/flush.go
- cmd/dapp/gc/gc.go
- cmd/dapp/main.go
- cmd/dapp/push/push.go
- cmd/dapp/secret/edit/edit.go
- cmd/dapp/sync/sync.go
- pkg/cleanup/lost_tmp_files.go
- pkg/cleanup/reset.go
- pkg/dapp/dapp.go
- pkg/dappdeps/base.go
- pkg/project_tmp_dir/project_tmp_dir.go
Dapp will remove tmp dirs from builds in special "garbage collection" procedure. Which will occur when there are more than 50 tmp dirs accumulated.
To remove such a dir dapp needs to run special service container. This procedure consumes some time, valuable for best the user experience. This is why dapp removes such folders in delayed manner.
---
Also added special `dapp gc` command to force removal of:
- build/deploy tmp dirs, that are not being used;
- lost git patches and archives generated by dapp;
- lost dapp temporal secret edit files.
This command can be safely run during any other dapp command is working.
---
Remove `/tmp/dapp*` files in `dapp reset`
Action may require root privileges.
Action will remove not only project tmp dirs, but also:
- lost git patches and archives …
> Remove project tmp dir properly

- lib/dapp/dimg/docker_registry/base/authorization.rb
GitLab authorization service doesn't support full implementation of Docker registry scope (JWT authentication), including 'delete' action since docker registry 2.7+ (https://github.com/docker/distribution/commit/ccb839e0e30c3b6992fb4084dfd6550d0ddd4d1a)
> Fix gitlab authentication problem with docker registry 2.7+ (0.31)

- lib/dapp/dimg/docker_registry/base/authorization.rb
GitLab authorization service doesn't support full implementation of Docker registry scope (JWT authentication), including 'delete' action since docker registry 2.7+ (https://github.com/docker/distribution/commit/ccb839e0e30c3b6992fb4084dfd6550d0ddd4d1a)
> Fix gitlab authentication problem with docker registry 2.7+ (0.32)

- docs/_data/sidebars/reference.yml
- docs/_data/topnav.yml
- docs/pages/how_to/artifacts.md
- docs/pages/how_to/deploy_into_kubernetes.md
- docs/pages/how_to/getting_started.md
- docs/pages/how_to/mounts.md
- docs/pages/how_to/multi_images.md
- docs/pages/reference/build/assembly_instructions.md
- docs/pages/reference/config.md
- docs/pages/reference/deploy/deploy_to_kubernetes.md
- pkg/config/parser.go
- pkg/config/raw_meta.go
- pkg/slug/slug.go
* Describe meta config.
* Move config article onto toplevel reference.
* Fix howto's werf.yaml to include meta configuration doc with project name.
> Docs: fix reference config article

- docs/pages/reference/deploy/chart_configuration.md
- pkg/deploy/werf_chart_helpers.go
> `werf_container_env` always returns block with DOCKER_IMAGE_ID variable

- cmd/werf/ci_env/ci_env.go
Init docker twice: 1) before tmp_manager docker-config creation with default config; 2) after docker-config dir has been created in tmp_manager.
> Fix GC panic in 'werf ci-env'

- pkg/build/initialization_phase.go
- pkg/build/stage/git_patch.go
- pkg/true_git/diff_parser.go
Patch stage could apply archive instead of patch, if patch contains binary files. Mount host archives dir for the patches stage.
> Fixes: allow spaces in git files, patch stage with binary files

- pkg/cleaning/common_repo.go
- pkg/docker/main.go
Fix nameless images cleaning.
Fix named images cleaning: trim images repo slashes on the right side.
Fix docker package initialization: additionally initialize DOCKER_CONFIG for the docker/docker package.
Rework of commits:
commit a48cdb4a1b6af42b569722778d79abe8a20ca86f
Author: Alexey igrychev <alexey.igrychev@flant.com>
Date:   Thu Feb 28 21:05:25 2019 +0300
--docker-config option overrides $DOCKER_CONFIG
commit 944902551e1ecd2c34451419a6ac5d0b064f5426
Author: Alexey igrychev <alexey.igrychev@flant.com>
Date:   Thu Feb 28 20:42:20 2019 +0300
Fix getting nameless repo images
commit 6e315b2c99ec7890ac14b6f3a57aa3dcb763e63e
Author: Alexey igrychev <alexey.igrychev@flant.com>
Date:   Thu Feb 28 20:35:32 2019 +0300
Trim images repo slashes on the right side
> Fix 'UNAUTHORIZED: authentication required; [map[Type:repository Class'

- cmd/werf/ci_env/ci_env.go
- cmd/werf/common/tags.go
- pkg/tmp_manager/gc.go
\+ Do apply docker-tag werf slug automatically only in 'werf ci-env' command and do not apply this algorithm for the specified parameters --tag-git-branch, --tag-git-tag and --tag-git-commit.
> Fix 'werf ci-env' + 'werf deploy' gives error 'exactly one tag should be specified for deploy'

- pkg/deploy/helm.go
fix: rollout track for sts hangs in particular situations
- support for partition: 0, no hang in this situation
- support for automatic actions in case of OnDelete, no error
- debug messages for sts are more clearer
- final status works in debug mode
> Enable StatefulSet tracking (kubedog updated)

- pkg/deploy/helm/release.go
- pkg/deploy/helm/templates.go
```
Error: parsing file .helm/templates/hooks.yaml failed: yaml: line 7: found a tab character that violates indentation
1  apiVersion: batch/v1
2  kind: Job
3  metadata:
4    name: test-job
5    annotations:
6      "helm.sh/hook": post-install,post-upgrade
7  	"helm.sh/hook-weight": "1"
8      # "werf/track": "false"
9      # "werf/track": "till_done"
10  spec:
11    #activeDeadlineSeconds: 10
12    template:
13      metadata:
14        name: test-job
15      spec:
16        restartPolicy: OnFailure
17        containers:
18        - name: main
19          image: ubuntu:16.04
20          command: [ '/bin/bash', '-l', '-c', 'for i in {1..3}; do date; sleep 1; done' ]
```
> [deploy] Verbose parsing helm template error

- go.mod
- go.sum
- pkg/deploy/helm/tiller.go
* Helm master is broken due to mandatory validation https://github.com/helm/helm/pull/5576.
* Enable helm kube-client lowlevel logs output on failure.
> Use helm version without mandatory validation

- docs/pages/how_to/multi_images.md
Use exact path in `to`:
```
import:
- artifact: X
add: PATH_TO_FILE
to: PATH_TO_FILE
```
Non exact path will work only in 1.0.2 (which is alpha now).
refs #1561
> Fix multi-images howto: use portable syntax for artifacts imports

- docs/pages/how_to/multi_images.md
This reverts commit 80ee500ef1bbffbe7b5b7a238121c651994490f8.
refs #1561
> Revert "Fix multi-images howto: use portable syntax for artifacts imports"

- pkg/deploy/werf_chart/werf_chart.go
"1.0 alpha" for "v1.0.2-alpha.13" for example.
> Write stripped version into werf.io/version anno

- docs/pages/how_to/gitlab_ci_cd_integration.md
`sudo usermod -Ga docker gitlab-runner` is erroneous, should be `-aG`
> [docs] ci cd integration typo

- lib/dapp/dapp/dappfile.rb
Without fix:
```
distorhead@werf:~/workspace/eh" lo' $dollar!$ bundle exec dapp dimg build
Running time 0.0 seconds
Stacktrace dumped to /tmp/dapp-stacktrace-e44e910a-09b8-4e2f-a87a-eb48a0f6bedb.out
>>> START STREAM
Expected process to exit with [0], but received '2'
---- Begin output of /home/distorhead/go/bin/dappfile-yml -dappfile /home/distorhead/workspace/eh" lo' $dollar!/dappfile.yml ----
STDOUT: 
STDERR: sh: 1: Syntax error: Unterminated quoted string
---- End output of /home/distorhead/go/bin/dappfile-yml -dappfile /home/distorhead/workspace/eh" lo' $dollar!/dappfile.yml ----
Ran /home/distorhead/go/bin/dappfile-yml -dappfile /home/distorhead/workspace/eh" lo' $dollar!/dappfile.yml returned 2
>>> END STREAM
```
With fix:
```
distorhead@werf:~/workspace/eh" lo' $dollar!$ bundle …
```
> Fix 0.36 dappfile-yml exec argument: support spaces and other specialsymbols in the project name

- pkg/true_git/archive.go
- pkg/true_git/patch.go
- pkg/true_git/work_tree.go
Do not use work tree caching for now in true-git when switching work tree to different commit.
> Fix unexpected signature change when using stageDependencies with '*' pattern

- docs/pages/reference/build/artifact.md
- docs/pages/reference/build/git_directive.md
- docs/pages/reference/build/image_directives.md
Original
```
git:
- add: <absolute path>
to: <absolute path>
owner: <owner>
group: <group>
includePaths:
- <relative path or glob>
excludePaths:
- <relative path or glob>
stageDependencies:
install:
- <relative path or glob>
beforeSetup:
- <relative path or glob>
setup:
- <relative path or glob>
```
Changed:
```
git:
- add: <absolute path in git repository>
to: <absolute path inside image>
owner: <owner>
group: <group>
includePaths:
- <path or glob relative to path in add>
excludePaths:
- <path or glob relative to path in add>
stageDependencies:
install:
- <path or glob relative to path in add>
beforeSetup:
- <path or glob relative to path in add>
setup:
- <path or glob relative to path in add>
```
And same for the remote tab.
> docs: more descriptive values for git summary section

- cmd/werf/deploy/main.go
Error occurs during deployment without werf images. Images repo manager is used in service values preparation.
> [deploy] Fix "runtime error: invalid memory address or nil pointer dereference"

- pkg/config/raw_docker.go
- pkg/image/stage_image_container.go
- pkg/image/stage_image_container_options.go
* force reset CMD if a user specifies ENTRYPOINT (to ignore inherited CMD value from base image)
* reset CMD only with "[]" for all docker versions
* skip auto-resetting CMD if ENTRYPOINT is inherited or specified
close https://github.com/flant/werf/issues/1709
> [stapel image] Fix CMD and ENTRYPOINT logic

- docs/_data/sidebars/documentation.yml
- docs/pages/reference/deploy_process/experimental_three_way_merge.md
Incorrect YAML fixed in the sidebar and the Three way merge article.
> [doc] fix YAML in the sidebar and the Three way merge article.

- cmd/werf/common/kubedog.go
refs https://github.com/flant/kubedog/issues/134
closes #1703
> Suppress klog INFO and WARNING streams to disable excess messages from client-go

- docs/pages/reference/deploy_process/deploy_into_kubernetes.md
- pkg/deploy/service_values.go
- pkg/deploy/werf_chart/helpers.go
* werf_container_image: add `imagePullPolicy: Always` for custom tag strategy
* werf_container_env: set `DOCKER_IMAGE_ID` only for git branch and custom tag strategies
> [deploy] Update chart templates werf helpers

- pkg/image/stage_image_container_options.go
* support old and new reset ENTRYPOINT value formats for CE and EE Docker Engine
* use new one for other solutions from docker (e.g. UCP)
> [stapel image] Fix empty ENTRYPOINT processing for UCP

- docs/pages/reference/build_process.md
How stapel builder processes CMD and ENTRYPOINT
> [docs] Reference/Build process: add section

- pkg/build/builder/ansible.go
Old LOGBOEK_SO_PATH=/.werf/ansible-workdir/lib/werf/.logboek.so variable has been defined in the cached image layers.
The new default logboek.so location is: /.werf/stapel/embedded/lib/python2.7/_logboek.so.
So force setting of LOGBOEK_SO_PATH to /.werf/stapel/embedded/lib/python2.7/_logboek.so for compatibility with old stages cache.
> Fix /.werf/ansible-workdir/lib/werf/.logboek.so: cannot open shared: no such file

- docs/_includes/readme/installation.md
Added note about bash limitations for users with versions before 4, for example, it can be MacOS users with default bash or gitlab-runner mounted from MacOS
> Added note about bash limitations

- cmd/werf/common/common.go
- cmd/werf/deploy/main.go
- cmd/werf/helm/deploy_chart/main.go
- go.mod
- go.sum
- pkg/deploy/deploy.go
- pkg/deploy/helm/release.go
- pkg/deploy/helm/tiller.go
- 3wm modes dates: onlyNewReleases 15.11, enabled 5.12;
- Helm updated to v2.16.0.
> [backport to v1.0.4][3-way-merge] Update option to use 3 way merge patch, ability to adopt existing resources

- go.sum
- pkg/git_repo/base.go
- pkg/git_repo/local.go
- pkg/git_repo/work_tree.go
- pkg/lock/base.go
- pkg/true_git/archive.go
- pkg/true_git/patch.go
- pkg/true_git/submodule.go
- pkg/true_git/work_tree.go
Git work tree switch strikes back: rework and speedup git work tree cache
- One work tree belongs only to one git repo on localhost. Multiple repos (as in gitlab with parallel builds) will have multiple uniq work trees, one per repo.
- Optimized work tree switch procedure in the case when work tree is already in the desired commit state.
- New cache files structure:
```
~/.werf/local_cache/git_worktrees/2/local/REPO_ID_HASH/
worktree # actual work tree directory in the state corresponding to some commit
current_commit # file contains commit hash corresponding to the worktree state
git_dir # path to the git dir to which this work tree belongs
```
REPO_ID is unique per each local repo clone.
During switch from OLD_COMMIT to NEW_COMMIT procedure …
> Git work tree switch strikes back: rework and speedup git work tree cache

- pkg/true_git/work_tree.go
Remove invalid work tree cache dir in that case and retry switch.
> [git] Handle invalid work tree cache when git repo of the work tree gone

- pkg/deploy/deploy.go
- pkg/deploy/helm/lint.go
- pkg/deploy/helm/release.go
- pkg/deploy/helm/render.go
- pkg/deploy/helm/templates.go
- pkg/deploy/helm/tiller.go
- pkg/deploy/lint.go
- pkg/deploy/render.go
- pkg/deploy/werf_chart/werf_chart.go
- pkg/util/secretvalues/mask.go
- Mask errors in deploy and lint commands, render is not masked.
- Optionally generate masks for json-values in the secret itself.
- Mask errors in service release-log of tiller.
> [deploy] Pass secret values as a separate argument to values-merger and fix masking of secret values

- pkg/stapel/stapel.go
- stapel/omnibus/config/software/ansible.rb
Due to the issue with the config:
```
project: test
---
image: ~
from: alpine
ansible:
install:
- shell: |
ls
```
Which works with the 2.7, but does not work with the 2.8 or 2.9.
Stapel image: flant/werf-stapel:0.3.1.
> [stapel] Downgrade ansible to 2.7.15

- go.mod
- go.sum
Support for "deleted resource" state of the tracker: do not show "resource deleted" error
https://github.com/flant/kubedog/pull/152
> [deploy] Do not show errors for deleted old pods

- README.md
- README_ru.md
- docs/_config.yml
- docs/_includes/readme/docs_and_support.md
- docs/_includes/topnav.html
- docs/pages/index.md
The telegram channel for English speaking users could be misleading, and we decided to delete it.
It will be more convenient to communicate in one place - CNCF slack. Please join!
Badges were also updated.
> [docs] Removed telegram channel for English speaking users

- .codeclimate.yml
- .github/workflows/site.yml
- .github/workflows/tests.yml
- README.md
- README_ru.md
- cmd/werf/main_test.go
- go.mod
- go.sum
- integration/ansible/common_test.go
- integration/ansible/setup_test.go
- integration/releaseserver/common_test.go
- pkg/testing/utils/command.go
- pkg/testing/utils/suite.go
- scripts/ci/codeclimate.sh
- scripts/ci/parallel.sh
- scripts/ci/unit_tests_runner.sh
- scripts/tests/precompiled_tests_binaries.sh
- scripts/tests/werf_with_coverage.sh
* Precompiled test binaries
* Simplified use of werf binary with coverage
* binary improvements: handle os.Exit (coverage++) and small refactoring
* adding extra option with coverage path in tests (with WerfBinArgs function) instead of in bash script wrapping
> [tests] Coverage for all supported operating systems 

- pkg/testing/utils/suite.go
- pkg/tmp_manager/common.go
- pkg/werf/main.go
https://github.com/docker/for-win/issues/1560#issuecomment-577371228
> Fix Docker on windows does not support mount with short filename

- pkg/build/conveyor.go
- pkg/build/initialization_phase.go
Optimize usage of `git fsck` command for the local repository: run only once for all images and artifacts instead of for each as before
> Cache local git repo object between images and artifacts

- pkg/build/signatures_phase.go
- pkg/build/stage/base.go
- pkg/build/stage/git_archive.go
- pkg/build/stage/interface.go
- pkg/build/stage/user_with_git_patch.go
Introduce new hook Stage.GetNextStageDependencies to get from stage dependencies for the next stage signature.
GetNextStageDependencies returns commit from stage-image labels or latest commit (which will be used during stage build).
Use sha256 for signature part of stage-image name.
> Signatures and stages storage rework: commit affects next stages signatures

- pkg/build/build_phase.go
- pkg/build/conveyor.go
- pkg/build/image.go
- pkg/build/signatures_phase.go
- pkg/image/base.go
- pkg/image/interface.go
- pkg/util/hashsum.go
- Discard already built temporary image when saving into stages storage if there is existing suitable image for this signature.
- Generate image id as: <sha-3-224>-<time-up-to-millisecs>
> Signatures and stages storage rework: implement optimistic locking

- integration/ansible/ansible_test.go
Remove _repo suffixed dir before test. This dir may exist if previous tests has been killed for some reason.
> [tests] Fix python_encoding_repo/yarn_repo not a git repository

- cmd/werf/build_and_publish/main.go
- cmd/werf/images/publish/cmd_factory/main.go
- pkg/build/build_phase.go
- pkg/build/conveyor.go
- pkg/build/publish_images_phase.go
- Reset image context in build-phase when processing next image.
- Fix panic when images for cmd specified.
> Signatures and stages storage rework: fix panics and errors

- pkg/build/build_phase.go
- pkg/build/stage/docker_instructions.go
Also remove dockerInstructions legacy signature dependency.
> Signatures and stages storage rework: fix dockerInstructions signature does not depend on prev stage signature

- pkg/build/build_phase.go
```
Set prev stage = "from" 2b804703146bc600187dacd735a9cae470a9d2102f6ee3f9b1709784
Set prev image = "3bb0140e-aebb-48f4-8a59-37be9f4c17c3"
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x18ef83c]
github.com/flant/werf/pkg/build.(*BuildPhase).calculateStageSignature(0xc000a40780, 0xc0008c27e0, 0x26ff8a0, 0xc00086a240, 0x0, 0xc00029fc00)
/home/ubuntu/actions-runner/_work/werf/werf/pkg/build/build_phase.go:269 +0x74c
github.com/flant/werf/pkg/build.(*BuildPhase).OnImageStage(0xc000a40780, 0xc0008c27e0, 0x26ff8a0, 0xc00086a240, 0x3, 0xc000556bc0, 0x2)
/home/ubuntu/actions-runner/_work/werf/werf/pkg/build/build_phase.go:178 +0xd3 …
```
> Signatures and stages storage rework: fix panic 

- cmd/werf/cleanup/cleanup.go
- cmd/werf/stages/cleanup/cleanup.go
Dry-run mode is forced by default for stages-cleanup procedure in commands: `werf stages cleanup`, `werf cleanup`.
Images cleanup is not affected and enabled as always in `werf cleanup`.
To enable stages-cleanup forcefully set: `WERF_STAGES_CLEANUP_ENABLED=1`.
Dry-run by default will be disabled when stages-cleanup procedure bug is fixed.
> Temporarily disable stages cleanup by default due to the bug

- cmd/werf/ci_env/ci_env.go
- cmd/werf/helm/secret/common/edit.go
- go.mod
- go.sum
- pkg/config/parser.go
- pkg/config/raw_ansible_task.go
- pkg/deploy/helm/render.go
- pkg/deploy/helm/templates.go
- pkg/deploy/secret/base_manager.go
- pkg/deploy/werf_chart/werf_chart.go
- Update flant/helm to the version with strict unmarshal.
- Update gopkg/yaml to v3.
- Update github.com/ghodss/yaml to v1.0.
- Use yaml.UnmarshalStrict everywhere in the werf codebase.
> Use yaml strict unmarshal everywhere

- go.mod
- go.sum
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-001/.helm/templates/templates.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-001/werf.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-002/.helm/templates/templates.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-002/werf.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-003/.helm/templates/templates.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-003/werf.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_test.go
- fix "resource already exists" error on redeploy when new resource with an error has been added to the chart,
refs https://github.com/flant/helm/pull/40
- fix "resource already exists" error message when creating a helm.sh/hook that already exists,
refs https://github.com/flant/helm/pull/41
- do not allow resource adoption during initial release installation, fix error messages,
refs https://github.com/flant/helm/pull/42
> Fixes related to the "Resource already exists" deploy error, tests included

- go.mod
- go.sum
- integration_k8s/releaseserver/resources_adopter_app1-001/.helm/templates/templates.yaml
- integration_k8s/releaseserver/resources_adopter_app1-003/.helm/templates/templates.yaml
- integration_k8s/releaseserver/resources_adopter_app1-003/werf.yaml
- integration_k8s/releaseserver/resources_adopter_test.go
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-001/.helm/templates/templates.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-001/werf.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-002/.helm/templates/templates.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-002/werf.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-003/.helm/templates/templates.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_app3-003/werf.yaml
- integration_k8s/releaseserver/three_way_merge_patches_creator_test.go
- fix "resource already exists" error on redeploy when new resource with an error has been added to the chart,
refs flant/helm#40
- fix "resource already exists" error message when creating a helm.sh/hook that already exists,
refs flant/helm#41
- do not allow resource adoption during initial release installation, fix error messages,
refs flant/helm#42
> [1.0] Fixes related to the "Resource already exists" deploy error

- cmd/werf/cleanup/cleanup.go
- cmd/werf/stages/cleanup/cleanup.go
- integration/cleanup/_fixtures/default/werf.yaml
- integration/cleanup/_fixtures/stages_cleanup/werf.yaml
- integration/cleanup/images_cleanup_test.go
- pkg/build/conveyor.go
- pkg/build/stage/conveyor.go
- pkg/build/stage/imports.go
- pkg/cleaning/stages_cleanup.go
The import stage image has a specific label that is used during stages cleanup procedure. In this commit, related image/artifact signature which stored in the label is replaced on image ID.
The signature does not identify the stage since we started to use not only signature in an image tag. From v1.1, werf is building stages consistently so related image/artifact image ID is available when werf is preparing import stage.
> Fix import stage logic and stages cleanup

- docs/js/customscripts.js
The 'stable' update channel is set by default in a version menu on the site.
> [doc] Fix site version menu

- cmd/werf/build_and_publish/main.go
- cmd/werf/cleanup/cleanup.go
- cmd/werf/common/common.go
- cmd/werf/deploy/main.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/helm/get_autogenerated_values/main.go
- cmd/werf/helm/get_namespace/main.go
- cmd/werf/helm/get_release/main.go
- cmd/werf/helm/lint/lint.go
- cmd/werf/helm/render/render.go
- cmd/werf/images/cleanup/cleanup.go
- cmd/werf/images/publish/cmd_factory/main.go
- cmd/werf/images/purge/purge.go
- cmd/werf/purge/purge.go
- cmd/werf/run/run.go
- cmd/werf/stage/image/main.go
- cmd/werf/stages/build/cmd_factory/main.go
- cmd/werf/stages/cleanup/cleanup.go
- cmd/werf/stages/purge/purge.go
- go.mod
- go.sum
- pkg/build/conveyor.go
- pkg/deploy/deploy.go
- pkg/deploy/dismiss.go
- pkg/deploy/helm/release.go
- pkg/deploy/helm/resources_waiter.go
- pkg/deploy/helm/tiller.go
- pkg/deploy/werf_chart/werf_chart.go
- werf run, werf deploy, werf dismiss commands will not print stages-related info by default (signatures checks, printed only in verbose mode);
- werf deploy/dismiss output reformed.
> Revise v1.1 default logging output for main commands: build, publish, run, cleanup, deploy, dismiss; disable debug logs by default

- pkg/stapel/stapel.go
- pkg/true_git/work_tree.go
Moved 'Switch work tree to commit' git message from default log to verbose.
> [logs] Update stapel image to include newer logboek, remove excess git log msg in default log

- pkg/build/conveyor.go
- pkg/build/stage/dockerfile.go
Docker parser coverts dockerfile stage name (AS) to lowercase but in places of the name usage (COPY --from) does not.
This affected dockerfile stage signature calculation and occurred false warning messages.
> [dockerfile] Fix dockerfile stage name from "COPY --from" is not detected

- pkg/deploy/helm/templates.go
Change `gopkg.in/yaml.v2` to `github.com/ghodss/yaml` in custom werf templates engine,
as `github.com/ghodss/yaml` is used everywhere in the helm 2.
In the helm 3 `sigs.k8s.io/yaml` is used, but it is not possible for now to switch to `sigs.k8s.io/yaml` before switching to helm 3 codebase.
https://github.com/helm/helm/blob/master/pkg/engine/funcs.go#L27
> [deploy] Hotfix werf helm render: fix problem with '|' rendered as '|-'

- pkg/build/build_phase.go
- pkg/build/conveyor.go
- pkg/build/image.go
- pkg/build/publish_images_phase.go
- pkg/build/should_be_built_phase.go
- pkg/build/stage/base.go
- pkg/build/stage/git.go
- pkg/build/stage/git_cache.go
- pkg/build/stage/git_latest_patch.go
- pkg/build/stage/git_mapping.go
- pkg/build/stage/git_patch.go
- pkg/build/stage/interface.go
- pkg/build/stage/user_with_git_patch.go
- pkg/container_runtime/base_image.go
- pkg/container_runtime/container_runtime.go
- pkg/container_runtime/interface.go
- pkg/container_runtime/stage_image.go
- pkg/image/info.go
- pkg/storage/local_docker_server_stages_storage.go
- pkg/storage/repo_stages_storage.go
- pkg/storage/stages_storage.go
- LocalStagesStorage renamed to LocalDockerServerStagesStorage, because implementation of stages storage for kaniko-like builds will change from LocalStagesStorage implementation;
- Added new StagesStorage interface methods ShouldFetchImage, ShouldCleanupLocalImage, implemented fetch&cleanup base stage logic when building a new stage;
- Fixed container_runtime RefreshImageObject bug when inspect is nil;
- Refactored Conveyor PrevImage, PrevBuiltImage, PrevStage, PrevNonEmptyStage, etc.
- Removed PrevImage and PrevBuiltImage references, added methods to dynamically fetch image object;
- Explicit if-s for "from" stage to differentiate a situation when previous image for stage "from" is needed;
- Added PrevBuiltStage reference;
- Refactored OnStageImage so that PrevStage references are …
> Remote storages support: adopt build conveyor for distributed builds and fixes - part 2

- cmd/werf/common/common.go
- pkg/build/build_phase.go
- pkg/build/conveyor.go
- pkg/build/image.go
- pkg/build/publish_images_phase.go
- pkg/build/stage/base.go
- pkg/container_runtime/container_runtime.go
- pkg/image/info.go
- pkg/storage/local_docker_server_stages_storage.go
- pkg/storage/repo_stages_storage.go
- pkg/storage/stages_storage.go
- added Signature and UniqueID fields to image.Info and changed StagesStorage.GetImageInfo interface to accept signature and unique-id params;
- fixed panic 'should_be_built_phase.go:47 +0x45';
- implemented fetch-previous-stage+build-current-stage+cleanup-previous-stage procedure, so that build that uses repo-stages-storage does not leave local docker images.
> Remote storages support: first working build with --stages-storage=REPO + fixes

- go.mod
- pkg/build/build_phase.go
- pkg/build/conveyor.go
- pkg/build/image.go
- pkg/build/phase.go
- pkg/build/publish_images_phase.go
- pkg/build/should_be_built_phase.go
- pkg/build/stages_iterator.go
- pkg/build/stages_storage.go
- pkg/container_runtime/container_runtime.go
- pkg/storage/local_docker_server_stages_storage.go
- pkg/storage/repo_stages_storage.go
- pkg/storage/stages_storage.go
- do not cleanup built and fetched stages from localhost — these will be reused as a cache on retries;
- refactor build-phase: use separate StagesIterator when iterating stages;
- move stages-storage common functions into separate stages_storage.go file.
> Remote storages support: optimize distributed builds

- cmd/werf/ci_env/ci_env.go
- cmd/werf/common/common.go
- cmd/werf/common/storage_repo_data.go
- cmd/werf/main.go
- cmd/werf/stages/mv/main.go
- pkg/container_runtime/container_runtime.go
- pkg/container_runtime/dockerfile_image_builder.go
- pkg/container_runtime/interface.go
- pkg/container_runtime/stage_image.go
- pkg/storage/repo_stages_storage.go
- Use `${CI_REGISTRY_IMAGE}/stages` by default as stages storage in `werf ci-env gitlab` command.
- Refactored stages-storage and images-repo related cli options preparation.
- 'werf stages mv' command to copy existing stages to another storage and switch werf project between different stage-storages.
Multithreaded implementation of sync-stages procedure.
**NOTE** that already existing installations that use `-s :local` explicit param will continue to use local stages storage as long as this param is specified.
> Remote storages support: remote stages storage usage in ci-env and 'werf stages mv' command prototype

- pkg/deploy/helm/templates.go
Annotation format for github.com/ghodss/yaml is not compatible with gopkg.in/yaml.v2: `json:"name,omitempty"` instead of `yaml:"name,omitempty"`
> Fix failed to prepare update: unable to decode "": Object 'Kind' is missing

- pkg/build/stage/git_latest_patch.go
- gitLatestPatch stage was not isolated between different branches when the same changes
has been made in two different commits: added commits ancestry check when selecting
suitable stage from cache for gitLatestPatch. The signature of gitLatestPatch stage
has not been changed.
- Stages-signature was not isolated between different branches when the same
changes has been maed in two different commits. **IMPORTANT** stages-signature
calculation algorithm has been changed, stages-signature will change for all projects
that use stages-signature tagging strategy (content-based).
> **INCOMPATIBLE CHANGE** Fix stages and images isolation problem for git-latest-patch and stages-signature

- cmd/werf/run/run.go
- cmd/werf/stage/image/main.go
- pkg/build/build_phase.go
- pkg/build/conveyor.go
- pkg/build/image.go
- pkg/build/publish_images_phase.go
- pkg/build/stage/base.go
- pkg/build/stage/conveyor.go
- pkg/build/stage/from.go
- pkg/build/stage/imports.go
- pkg/build/stage/interface.go
- pkg/config/import.go
- pkg/config/raw_import.go
Added ability to specify `stage` directive in the import directive to perform import from certain artifact or image stage:
```
import:
- add: /file
to: /file
artifact: myartifact
before: setup
stage: install
```
Note that image which imports some files from another image _stage_ will be rebuild only if this specified stage has been rebuilt.
This feature allows to avoid unnecessary imports of unchanged files.
*Implementation details*
- image stages-signature has been renamed to image content-signature;
- added content-signature to each stage, which differs from regular signature and represents content of the stage.
> Support import from certain artifact/image stage

- pkg/path_matcher/base_path_matcher.go
- pkg/path_matcher/dockerfile_ignore.go
- pkg/path_matcher/git_mapping.go
- pkg/path_matcher/git_mapping_test.go
- pkg/path_matcher/simple.go
- pkg/path_matcher/simple_test.go
* Clean Path Matcher fields values during initialization: base path, include/exclude paths and so on
* Clean matched path
> [dockerfile] Fix COPY/ADD source path with trailing backslash is not counted in the signature

- go.mod
- go.sum
https://github.com/flant/lockgate/pull/9
> Hotfix go-build: remove lockgate replace from go.mod and update to actual master

- cmd/werf/common/synchronization.go
- pkg/storage/kubernetes_helpers.go
- pkg/storage/kubernetes_lock_manager.go
- pkg/storage/kubernetes_stages_storage_cache.go
- Store stages-storage-cache in ns/werf-synchronization cm/werf-PROJECT_NAME
when `--synchronization=:kubernetes` has been specified.
- The same ConfigMap also used for kubernetes-based locks in annotations
when `--synchronization=:kubernetes` has been specified.
> Remote storages support: implement stages-storage-cache in ConfigMap

- cmd/werf/main.go
- cmd/werf/stages/common/sync_and_switch.go
- cmd/werf/stages/switch_from_local/main.go
- cmd/werf/stages/sync/main.go
- pkg/stages_manager/stages_manager.go
- pkg/stages_manager/sync_stages.go
werf switch-from-local --to registry.mycompany.com/mygroup/myproject
This command will:
1. Sync existing local stages to the specified stages storage.
2. Globally lock stages and images after sync.
3. Set block to prevent any werf-command with --stages-storage=:local:
user should change this param to the new stages-storage repo.
4. Sync existing local stages to the specified stages storage second time.
> Remote storages support: 'werf switch-from-local' command implemented

- pkg/build/stage/dockerfile.go
* dockerfile stage signature should take into account ONBUILD value;
* dockerfile stage that uses another one with ONBUILD instructions should calculate files checksum for COPY/ADD trigger instruction in addition to ONBUILD value.
> [dockerfile] Fix ONBUILD instruction processing

- pkg/build/build_phase.go
- pkg/build/conveyor.go
- pkg/build/stage/base.go
- pkg/build/stage/conveyor.go
- pkg/build/stage/git.go
- pkg/build/stage/git_patch.go
- pkg/build/stage/interface.go
- pkg/build/stage/user_with_git_patch.go
- pkg/build/stages_iterator.go
- remove git-building-stage map from Conveyor;
- remove AfterSignatureCalculated Stage hook.
> [v1.1.9] Fix gitLatestPatch not built when previous stage has been discarded during build

- pkg/build/build_phase.go
- pkg/build/conveyor.go
- pkg/build/stage/base.go
- pkg/build/stage/conveyor.go
- pkg/build/stage/git.go
- pkg/build/stage/git_patch.go
- pkg/build/stage/interface.go
- pkg/build/stage/user_with_git_patch.go
- remove git-building-stage map from Conveyor;
- remove AfterImageSyncDockerStateHook Stage hook.
> [v1.1.8] Fix gitLatestPatch not built when previous stage has been discarded during build

- pkg/build/stage/dockerfile.go
* dockerfile stage signature should take into account ONBUILD value;
* dockerfile stage that uses another one with ONBUILD instructions should calculate files checksum for COPY/ADD trigger instruction in addition to ONBUILD value.
> [v1.1.9][dockerfile] Fix ONBUILD instruction processing

- cmd/werf/build_and_publish/main.go
- cmd/werf/deploy/main.go
- cmd/werf/images/publish/cmd_factory/main.go
- cmd/werf/run/run.go
- cmd/werf/stage/image/main.go
- cmd/werf/stages/build/cmd_factory/main.go
- pkg/build/conveyor.go
- pkg/build/conveyor_with_retry.go
- pkg/stages_manager/stages_manager.go
- pkg/storage/file_stages_storage_cache.go
- pkg/storage/kubernetes_stages_storage_cache.go
- pkg/storage/stages_storage_cache.go
- Added conveyor wrapper that catches stages-storage-cache should be reset error,
deletes stages-storage cache for the project and then automatically restarts an action.
- Added DeleteAllStages method for StagesStorageCache, implemented for
file cache and kubernetes cache.
> Remote storages support: auto reset stages-storage-cache and retry action

- cmd/werf/build_and_publish/main.go
- cmd/werf/cleanup/cleanup.go
- cmd/werf/common/common.go
- cmd/werf/common/synchronization.go
- cmd/werf/deploy/main.go
- cmd/werf/host/project/purge/purge.go
- cmd/werf/images/cleanup/cleanup.go
- cmd/werf/images/publish/cmd_factory/main.go
- cmd/werf/images/purge/purge.go
- cmd/werf/managed_images/add/add.go
- cmd/werf/managed_images/ls/ls.go
- cmd/werf/managed_images/rm/rm.go
- cmd/werf/purge/purge.go
- cmd/werf/run/run.go
- cmd/werf/stage/image/main.go
- cmd/werf/stages/build/cmd_factory/main.go
- cmd/werf/stages/cleanup/cleanup.go
- cmd/werf/stages/purge/purge.go
- cmd/werf/stages/switch_from_local/main.go
- cmd/werf/stages/sync/main.go
- pkg/stages_manager/stages_manager.go
- pkg/stages_manager/sync_stages.go
- pkg/storage/local_docker_server_stages_storage.go
- pkg/storage/stages_storage.go
- `-S` shorthand;
- synchronization=:local when stages-storage=:local by default;
- synchronization=kubernetes://werf-synchronization when stages-storage != :local;
- ability to specify arbitrary namespace with `--synchronization kubernetes://mynamespace`.
> Remote storages support: refactor --synchronization param

- go.mod
- go.sum
- pkg/build/conveyor_with_retry.go
- pkg/storage/repo_stages_storage.go
- Fixed locks release and added shared mode for kubernetes locks in lockgate:
- https://github.com/flant/lockgate/pull/10
- https://github.com/flant/lockgate/pull/11
- Fixed managed images race condition when repo-stages-storage is used (fixed by using local host locks).
- Fixed conveyor retry termination: always immediately terminate old conveyor before retrying with new conveyor.
> Remote storages support: fix kubernetes locks, conveyor termination and managed-images race condition

- go.mod
- go.sum
- pkg/werf/main.go
https://github.com/flant/lockgate/pull/12
Refactor and fix kubernetes cm key name
- Renamed LockHandle.ID to LockHandle.UUID to be more clear.
- Use "lockgate.io/SHA3_224(lock-name)" for ConfigMap key names
due to ConfigMap names restrictions.
> Remote storages support: fix lockgate ConfigMap data key invalid

- cmd/werf/common/common.go
- cmd/werf/deploy/main.go
- cmd/werf/dismiss/dismiss.go
- docs/_includes/cli/werf_dismiss.md
- go.mod
- go.sum
- pkg/deploy/dismiss.go
- pkg/deploy/helm/tiller.go
- pkg/storage/generic_lock_manager.go
- pkg/storage/kubernetes_lock_manager.go
- pkg/werf/main.go
- update lockgate to latest version, use legacy murmurhash flag for files locker;
- changed deploy locks name;
- --stages-storage is an optional parameter for deploy and dismiss commands,
it is used to determine --synchronization param default value,
synchronization param value also can be specified explicitly;
- regenerate dismiss cli docs.
> Remote storages support: fix deploy/dismiss stages-storage param and update locking

- README.md
- cmd/werf/ci_env/ci_env.go
Fix cleanup fails to delete stages from repo stages storage
Automatically set gitlab repo implementation option (`--stages-storage-repo-implementation=gitlab`) in `werf ci-env gitlab`.
[docs] Fix README coming soon and features list
> Fix cleanup fails to delete stages from repo stages storage, fix readme

- pkg/build/stage/git_cache.go
gitCache should give commit-id as next-stage-dependencies, which will affect dockerInstructions signature and cause correct rebuild of dockerInstructions in the case when multiple gitCache stages with the same signature exists.
> [v1.1.8] FIX dockerInstructions stage not isolated when used after gitCache stage

- pkg/build/stage/git_cache.go
gitCache should give commit-id as next-stage-dependencies, which will affect dockerInstructions signature and cause correct rebuild of dockerInstructions in the case when multiple gitCache stages with the same signature exists.
> [v1.1.9] FIX dockerInstructions stage not isolated when used after gitCache stage

- pkg/build/stage/git_cache.go
gitCache should give commit-id as next-stage-dependencies, which will affect dockerInstructions signature and cause correct rebuild of dockerInstructions in the case when multiple gitCache stages with the same signature exists.
> FIX dockerInstructions stage not isolated when used after gitCache stage

- .github/workflows/docs_tests.yml
After adding new articles, test for broken links may fail because it tries to check external links for new articles on the site.
> [test] Test "Check broken links" hase been updated

- pkg/build/import_server/rsync_server.go
The error occurs when artifact image does not contain "nogroup" group, which was used by default when running rsync server. For example when using "maven:3.6.3-jdk-13" as artifact base image.
Fixed by running rsync server using root group.
> Fix "@ERROR: invalid gid nogroup" on imports stage

- docs/_data/sidebars/documentation.yml
- docs/pages/guides/github_ci_cd_integration.md
- docs/pages/guides/gitlab_ci_cd_integration.md
For gitlab there is a temporal link to russian version of the article.
For github there is a link to russian article, which is also WIP.
> [docs] Added github and gitlab ci/cd guide articles stubs

- pkg/build/stage/base.go
Closes #2407
The problem only reproduces when multiple git-mappings by the same url is used and these git-mappings use different commit.
> Fix git-related stages selection when multiple git-mappings by the same url used

- pkg/build/stage/base.go
The problem only reproduces when multiple git-mappings by the same url is used and these git-mappings use different commit.
> [v1.1.8] Fix git-related stages selection when multiple git-mappings by the same url used

- pkg/build/stage/base.go
The problem only reproduces when multiple git-mappings by the same url is used and these git-mappings use different commit.
> [v1.1.9] Fix git-related stages selection when multiple git-mappings by the same url used

- pkg/build/import_server/rsync_server.go
The error occurs when artifact image does not contain "nogroup" group, which was used by default when running rsync server. For example when using "maven:3.6.3-jdk-13" as artifact base image.
Fixed by running rsync server using root group.
> [v1.1.8] Fix "@ERROR: invalid gid nogroup" on imports stage

- pkg/build/import_server/rsync_server.go
The error occurs when artifact image does not contain "nogroup" group, which was used by default when running rsync server. For example when using "maven:3.6.3-jdk-13" as artifact base image.
Fixed by running rsync server using root group.
> [v1.1.9] Fix "@ERROR: invalid gid nogroup" on imports stage

- cmd/werf/converge/converge.go
- cmd/werf/main.go
- pkg/deploy/helm/release.go
- pkg/deploy/helm/tiller.go
Shortcut for 'werf stages build', 'werf images publish' and 'werf deploy' commands.
Command always builds all images defined in the werf.yaml and uses content-based-tagging and three-way-merge mode.
> Added 'werf converge' command

- pkg/git_repo/base.go
- pkg/git_repo/git_repo.go
- pkg/git_repo/local.go
- pkg/git_repo/remote.go
- pkg/git_repo/work_tree.go
- pkg/true_git/merge.go
- pkg/true_git/patch.go
- pkg/true_git/submodule.go
- pkg/true_git/work_tree.go
- playground/virtual_merge_commit/virtual_merge_commit.go
1. New way of creating worktree for git-worktree-cache: use "git worktree add" tool.
- This way of creating worktrees is native for git and prevent main worktree corruption.
2. New true_git.CreateDetachedMergeCommit function which operates within the git-worktree-cache, creates and returns some commit id, which can be used later until this commit is pruned (because it is detached).
3. Playground demo cli tool which creates diff between two virtual-merge-commits: specify 4 commits on input, get a patch between virtual merge commits of 1 into 2 and 3 into 4.
> Virtual merge commit support for git_repo and true_git

- pkg/docker_registry/api.go
- pkg/docker_registry/default.go
- pkg/stages_manager/stages_manager.go
Error: reading image "docker.pkg.github.com/user/repo/stages:de07eea0119baca706320aa6b7f32f887f5700b6fd82e1864867a1ee-1590064872402": GET
https://docker.pkg.github.com/v2/user/repo/stages/manifests/de07eea0119baca706320aa6b7f32f887f5700b6fd82e1864867a1ee-1590064872402: NAME_UNKNOWN: docker package "stages" does not exist under owner "user/repo"
> Fix GetStageDescription when docker registry repo is not exist

- cmd/werf/build_and_publish/main.go
- cmd/werf/common/common.go
- cmd/werf/images/publish/cmd_factory/main.go
- pkg/build/conveyor.go
- pkg/build/publish_images_phase.go
Write publish report when `--publish-report-path PATH` option has been given.
There is `--publish-report-format` options which accepts only `json` for now.
> Ability to write published images report json to the file

- docs/pages/configuration/introduction.md
- docs/pages_ru/configuration/introduction.md
- pkg/config/parser.go
The function supports shell pattern matching + `**`. Results can be merged with `merge` sprig function (e.g `{{ $filesDict := merge (.Files.Glob "*/*.txt") (.Files.Glob "app/**/*.txt") }}`)
> [config] .Files.Glob: add ability to merge results

- pkg/build/conveyor.go
- pkg/git_repo/git_repo.go
- pkg/git_repo/remote.go
- pkg/git_repo/work_tree.go
- pkg/true_git/merge_base.go
- pkg/true_git/patch.go
- pkg/true_git/work_tree.go
- do not write excess files `werf_work_tree_cache_dir` in the git-repo dir;
- new work tree validation procedure: check work tree list of the repo;
- this procedure is needed to check if repo has been recreated to recreate a related work tree in this case;
- store cloned repos in the cache dirs like: `~/.werf/local_cache/git_repos/2/protocol-https/mydomain.mygitlab.com/grp/proj.git`.
- store worktrees in the dirs like: `~/.werf/local_cache/git_worktrees/5/protocol-git/mydomain.mygitlab.com:22/grp/proj.git`.
> [git] Refine git worktree switch procedure, fix remote git-mapping clone on every build if token has been specified

- pkg/build/stage/git_cache.go
- pkg/build/stage/git_latest_patch.go
- pkg/build/stage/git_mapping.go
- pkg/build/stage/git_patch.go
- pkg/true_git/merge.go
* Set user.email and user.name when creating a temporal detached merge commits.
* Fix detached merge commit creation condition.
* Do not create detached merge commit for the previous built image when previously built image contains latest commit.
> Fix virtual merge commits creation

- pkg/storage/kubernetes_lock_manager.go
- pkg/werf/locker_with_retry/locker_with_retry.go
- Use LockerWithRetry wrapper for all kubernetes locks in werf (5 attempts for acquire/release operations are configured).
- Log all failed attempts to the stderr.
> [distributed builds] Implement lockgate.Locker compatible LockerWithRetry wrapper

- pkg/build/conveyor.go
- pkg/build/publish_images_phase.go
- pkg/build/stage/base.go
- pkg/build/stage/conveyor.go
- pkg/build/stage/from.go
- pkg/docker_registry/api.go
- pkg/docker_registry/docker_registry.go
- pkg/docker_registry/manifest_only_image.go
- pkg/image/const.go
- pkg/stages_manager/stages_manager.go
- pkg/storage/local_docker_server_stages_storage.go
- pkg/storage/repo_stages_storage.go
- pkg/storage/stages_storage.go
- Store metadata for images in the stages storage: map stages-signature by commit-id and image-name.
- Add new methods StagesStorage interface: PutImageCommit, RmImageCommit, GetImageMetadataByCommit, GetImageCommits.
- Implemented fully only for repo-stages-storage.
- Store project repository commit in the separate dedicated label: werf-project-repo-commit.
> Rework publish procedure for cleanup (part 1)

- pkg/true_git/work_tree.go
This option is not avaiable in the v2.17.1 version of git, which is the latest avaiable version for 18.04 lts ubuntu.
Specify target commit instead (which is by the way a faster and more precise approach).
> [git] Do not use 'git worktree add --no-checkout' option

- pkg/docker_registry/api.go
- pkg/docker_registry/docker_registry.go
- pkg/docker_registry/manifest_only_image.go
- pkg/storage/repo_stages_storage.go
- New method DockerRegistry.SetLabelsIntoImage.
- Removed DockerRegistry.GetMetadata method: use DockerRegistry.TryGetRepoImage instead.
> [publish-for-cleanup] Refactor DockerRegistry methods to store labels into manifest_only_image

- pkg/docker/image.go
- pkg/docker_registry/api.go
- pkg/docker_registry/docker_registry.go
- pkg/storage/local_docker_server_stages_storage.go
- pkg/storage/repo_stages_storage.go
- Rename DockerRegistry.SetLabelsIntoImage to more generic DockerRegistry.PushImage.
- PushImage now supports only creation of manifest-only-images with labels.
- Refactor managed-image store procedure for repo-stages-storage to use DockerRegistry.PushImage instead of docker-push.
> [publish-for-cleanup] Implement metadata store for local stages storage

- pkg/git_repo/local.go
- pkg/true_git/repository.go
fatal: 'remote.git' does not appear to be a git repository
> [git_repo] Fix local repo cannot be treated as a remote repo

- go.mod
- go.sum
The hanging case was in the lockgate library, described in the https://github.com/werf/lockgate/pull/24.
> Fix distributed werf hangs sometimes

- go.mod
- go.sum
The hanging case was in the lockgate library, described in the https://github.com/werf/lockgate/pull/24.
> [backport v1.1.19] Fix distributed werf hangs sometimes

- go.mod
- go.sum
The hanging case was in the lockgate library, described in the https://github.com/werf/lockgate/pull/24.
> [backport v1.1.16] Fix distributed werf hangs sometimes

- go.mod
- go.sum
- pkg/cleaning/images_cleanup.go
- pkg/cleaning/stages_cleanup.go
- pkg/cleaning/stages_purge.go
- pkg/container_runtime/stage_image.go
- pkg/git_repo/remote.go
- pkg/host_cleaning/host_cleanup.go
- pkg/image/manifest_cache.go
- pkg/stages_manager/stages_manager.go
- pkg/stapel/container.go
- pkg/storage/file_stages_storage_cache.go
- pkg/storage/generic_lock_manager.go
- pkg/storage/kubernetes_lock_manager.go
- pkg/storage/lock_manager.go
- pkg/storage/repo_stages_storage.go
- pkg/tmp_manager/gc.go
- pkg/true_git/work_tree.go
- pkg/werf/main.go
The hanging case was in the lockgate library, described in the https://github.com/werf/lockgate/pull/24.
> [backport v1.1.14] Fix distributed werf hangs sometimes

- pkg/stages_manager/stages_manager.go
- pkg/storage/repo_stages_storage.go
- Only enable strict checking of stage manifest existance when getting stage from stages-storage-cache.
- Ignore bad stages without manifests otherwise
- Print warning for these stages
> [build] Fix 'Stage is no longer available in the repo stages storage' on stages cleanup

- cmd/werf/common/common.go
- cmd/werf/common/synchronization.go
- cmd/werf/main.go
- cmd/werf/synchronization/main.go
- pkg/storage/generic_lock_manager.go
- pkg/storage/kubernetes_lock_manager.go
- pkg/storage/lock_manager.go
- pkg/storage/synchronization_server/http_helpers.go
- pkg/storage/synchronization_server/lock_manager_http_client.go
- pkg/storage/synchronization_server/lock_manager_http_handler.go
- pkg/storage/synchronization_server/stages_storage_cache_http_client.go
- pkg/storage/synchronization_server/stages_storage_cache_http_handler.go
- pkg/storage/synchronization_server/synchronization_server.go
- pkg/util/serializable_error.go
- playground/synchronization_client/main.go
- playground/synchronization_server/main.go
- werf synchronization command
- Implement LockManagerHttpClient LockManager interface compatible.
- Implement LockManagerHttpHandler which respond to corresponding methods of LockManager interface.
- Implement StagesStorageCacheHttpClient StagesStorageCache interface compatible.
- Implement StagesStorageCacheHttpHandler which respond to corresponding methods of StagesStorageCache interface.
- Http handlers can be initialized with arbitrary lock-manager or stages-storage-cache implementation by interface param.
- werf synchronization --local --local-lock-manager-base-dir --local-stages-storage-cache-base-dir (store locks and cache in local filesystem, this server will not keep data on restarts).
- werf synchronization --kubernetes --kubernetes-namespace-prefix="werf-synchronization-" …
> New synchronization http server with configurable backend

- cmd/werf/helm/common/common.go
Error: bad Helm release 'project-ENV' rendered by template '[[ project ]]-[[ env ]]': helm release name should be a valid DNS-1123 subdomain and be maximum 53 chars: a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
> [render] Fix stub env value ENV

- integration/cleanup/_fixtures/git_history_based_cleanup/werf.yaml
- integration/cleanup/images_cleanup_test.go
- integration/cleanup/suite_test.go
- pkg/cleaning/images_cleanup.go
- pkg/cleaning/images_cleanup_reference_to_scan.go
- pkg/cleaning/images_cleanup_scanner.go
- pkg/config/meta_cleanup.go
- pkg/config/raw_meta_cleanup.go
- pkg/stages_manager/stages_manager.go
* Add opportunity to keep images by publishing period.
* Update default policies
* Update cleanup section configuration:
```
cleanup:
keepPolicies:
- references:
branch: /.*/
tag: /.*/
limit:
last: 10
createdIn: 168h
operator: And
imagesPerReference:
last: 10
publishedIn: 168h
operator: And
```
> [cleanup] Git history based cleanup: improve algorithm

- cmd/werf/build_and_publish/main.go
- cmd/werf/cleanup/cleanup.go
- cmd/werf/common/common.go
- cmd/werf/common/synchronization.go
- cmd/werf/converge/converge.go
- cmd/werf/deploy/main.go
- cmd/werf/diff/diff.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/helm/deploy_chart/main.go
- cmd/werf/helm/rollback/rollback.go
- cmd/werf/host/project/purge/purge.go
- cmd/werf/images/cleanup/cleanup.go
- cmd/werf/images/publish/cmd_factory/main.go
- cmd/werf/images/purge/purge.go
- cmd/werf/managed_images/add/add.go
- cmd/werf/managed_images/ls/ls.go
- cmd/werf/managed_images/rm/rm.go
- cmd/werf/purge/purge.go
- cmd/werf/run/run.go
- cmd/werf/stage/image/main.go
- cmd/werf/stages/build/cmd_factory/main.go
- cmd/werf/stages/cleanup/cleanup.go
- cmd/werf/stages/purge/purge.go
- cmd/werf/stages/switch_from_local/main.go
- cmd/werf/stages/sync/main.go
- cmd/werf/synchronization/main.go
- go.mod
- go.sum
- pkg/storage/synchronization.go
- pkg/storage/synchronization_test.go
- Reworked --syncrhonization param (WERF_SYNCHRONIZATION env var): specify all kube-related params in the URI-like string:
- kubernetes://NAMESPACE[:CONTEXT][@(base64:BASE64_CONFIG_DATA)|CONFIG_PATH]
- Added --kube-config-base64 param (or WERF_KUBECONFIG_BASE64, or WERF_KUBE_CONFIG_BASE64, or KUBECONFIG_BASE64 env var) support.
- Werf does not generate config file and unpacks specified base64 yaml config into memory.
> Rework synchronization param, add base64 support for kubernetes-params

- pkg/build/publish_images_phase.go
- pkg/docker_registry/api.go
- pkg/docker_registry/container_registry_extensions/manifest_only_image.go
- pkg/docker_registry/container_registry_extensions/uncompressed_layer.go
- pkg/storage/repo_stages_storage.go
Create empty zero-bytes layer for manifest-only images: managed images records and image metadata by commit id records.
> Fix AWS ECR build/publish problem 'Image has to have at least 1 layer'

- docs/_includes/slack_popup.html
- docs/_includes/topnav.html
As SonarCloud [recommends](https://sonarcloud.io/component_measures?id=werf_werf&metric=security_rating&selected=werf_werf%3Adocs%2F_includes%2Ftopnav.html&view=list):
> Add rel="noopener noreferrer" to this link to prevent the original page from being modified by the opened link.
> Adding rels to docs links for security

- cmd/werf/build_and_publish/main.go
- cmd/werf/cleanup/cleanup.go
- cmd/werf/common/common.go
- cmd/werf/common/conveyor_options.go
- cmd/werf/converge/converge.go
- cmd/werf/deploy/main.go
- cmd/werf/diff/diff.go
- cmd/werf/images/cleanup/cleanup.go
- cmd/werf/images/publish/cmd_factory/main.go
- cmd/werf/run/run.go
- cmd/werf/stage/image/main.go
- cmd/werf/stages/build/cmd_factory/main.go
- docs/_includes/cli/werf_build.md
- docs/_includes/cli/werf_build_and_publish.md
- docs/_includes/cli/werf_cleanup.md
- docs/_includes/cli/werf_converge.md
- docs/_includes/cli/werf_deploy.md
- docs/_includes/cli/werf_diff.md
- docs/_includes/cli/werf_images_cleanup.md
- docs/_includes/cli/werf_images_publish.md
- docs/_includes/cli/werf_publish.md
- docs/_includes/cli/werf_run.md
- docs/_includes/cli/werf_stages_build.md
- pkg/build/conveyor.go
- pkg/cleaning/images_cleanup.go
- pkg/git_repo/local.go
* Ignore git shallow clone when it is possible
* Force using git shallow clone despite restrictions with option --allow-git-shallow-clone
> Optimistic git shallow clone handling

- docs/pages_ru/configuration/cleanup.md
- integration/cleanup/_fixtures/git_history_based_cleanup/werf.yaml
- integration/cleanup/images_cleanup_test.go
- pkg/cleaning/images_cleanup_reference_to_scan.go
- pkg/cleaning/images_cleanup_scanner.go
- pkg/config/meta_cleanup.go
- pkg/config/raw_meta_cleanup.go
```
cleanup:
keepPolicies:
- references:
branch: <string|/REGEXP/>
tag: <string|/REGEXP/>
limit:
last: <int>
in: <duration string>
operator: <And|Or>
imagesPerReference:
last: <int>
in: <duration string>
operator: <And|Or>
```
> [cleanup] Change configuration syntax: replace createdIn/publishedIn with in

- pkg/build/build_phase.go
- pkg/image/manifest_cache.go
- pkg/stages_manager/stages_manager.go
Store manifest of newly built stage into manifest stage immediately after building, before storing this stage into stages storage.
> Fix manifest-cache not filled with manifests of newly built stages

- cmd/werf/build_and_publish/main.go
- cmd/werf/ci_env/ci_env.go
- cmd/werf/common/common.go
- cmd/werf/common/conveyor_options.go
- cmd/werf/converge/converge.go
- cmd/werf/deploy/main.go
- cmd/werf/diff/diff.go
- cmd/werf/images/publish/cmd_factory/main.go
- cmd/werf/run/run.go
- cmd/werf/stage/image/main.go
- cmd/werf/stages/build/cmd_factory/main.go
- docs/_includes/cli/werf_build.md
- docs/_includes/cli/werf_build_and_publish.md
- docs/_includes/cli/werf_converge.md
- docs/_includes/cli/werf_deploy.md
- docs/_includes/cli/werf_diff.md
- docs/_includes/cli/werf_images_publish.md
- docs/_includes/cli/werf_publish.md
- docs/_includes/cli/werf_run.md
- docs/_includes/cli/werf_stages_build.md
- pkg/build/conveyor.go
* Add --git-unshallow option to regulate shallow git clone handling. If it is true, git clone will be converted to a full one (git fetch --unshallow), otherwise, the command will fail with the warning message.
* Substitute --git-history-synchronization option with --git-unshallow in all commands except images cleanup.
* By default git unshallow procedure is enabled with werf ci-env (WERF_GIT_UNSHALLOW=1).
> Fix redundant fetching of origin within CI jobs

- cmd/werf/cleanup/cleanup.go
- cmd/werf/images/cleanup/cleanup.go
Note: by default werf uses all contexts for fetching used images that will be kept during cleanup
> [cleanup] Fix the certain kube context is not supported

- pkg/build/stage/git_mapping.go
`"virtual-merge-commit": "true"` label in the docker image of the stage was not reset to false when building a new image for regular commit (not virtual merge commit).
> Fix 'patch does not apply' error in github actions

- pkg/cleaning/images_cleanup.go
- pkg/storage/repo_stages_storage.go
Ignore unknown-manifest tags from docker-registry tags list when quering image metadata records.
> Fix cleanup panic "image ... metadata was not found"

- cmd/werf/common/kubedog.go
Suppress klog info/warning log levels. Print error level through logboek.
> Fix klog warning messages

- cmd/werf/cleanup/cleanup.go
- pkg/cleaning/images_cleanup.go
My case: there are several projects in one cluster, each project has access only to certain namespaces. Therefore, the werf cleanup does not work as it tries to extract images from the entire cluster. For example:
```bash
627.191299ms Using werf config render file: /private/var/folders/82/qx_s8s_n3c3016fsx1rbbjsh0000gn/T/werf-config-render-088482510
633.265926ms Using images repo docker registry implementation: default
633.301918ms Using images repo mode: multirepo
633.337162ms -- LocalDockerServerStagesStorage.GetManagedImages cross-stitch
792.055737ms Managed images names: [backend migrations notifications static]
851.228204ms 
851.264639ms ┌ Running images cleanup
863.395068ms │ ┌ Fetching repo images data
863.425751ms │ │ ┌ Fetching repo images
2m42.6553478 │ │ └ Fetching repo images …
```
> Ability to enable/disable checking of all kube namespaces during cleaning images from registry

- cmd/werf/cleanup/cleanup.go
- cmd/werf/common/cleanup_namespaces_scan.go
- cmd/werf/common/common.go
- cmd/werf/images/cleanup/cleanup.go
- docs/_includes/cli/werf_cleanup.md
- docs/_includes/cli/werf_images_cleanup.md
- go.mod
- go.sum
- pkg/cleaning/images_cleanup.go
- Option renamed to `--scan-context-namespace-only=true|false` (false by default).
- Refactored scanning for available contexts, added support for in-cluster configs.
- Added option to the both commands: `werf cleanup` and `werf images cleanup`.
refs https://github.com/werf/kubedog/pull/179
refs https://github.com/werf/werf/pull/2660
> Refactor `--check-all-namespaces` cleanup option

- pkg/build/import_server/rsync_server.go
Use 0:0 instead of root:root symbolic names in rsyncd which runs inside artifact.
Issue reproduces when artifact image does not have root line in the `/etc/passwd` file.
Refs https://github.com/werf/werf/issues/2762
> Fix artifact import error '@ERROR: invalid uid root'

- pkg/deploy/werf_chart/service_values.go
- pkg/deploy/werf_chart/template_helpers.go
- do not use .Values.global.werf section, use .Values.werf instead (subcharts does not need to have an access for image-related info);
- change image-related values format: `.Values.werf.image.NAME` or `.Values.werf.image` (for nameless images);
- use `werf_image` as a main way to generate full image name.
> Change service values format

- go.mod
- go.sum
- pkg/build/build_phase.go
- pkg/docker_registry/api.go
- pkg/image/info.go
- pkg/image/manifest_cache.go
- Reset manifests cache due to the error in the current cached data.
- Set Size field for manifests from docker-registries.
- Update google/go-containerregistry library.
- Always set stage description from stages-storage (it will differ for local and repo stages storage).
> Fix zero stage size logging when using --repo images storage and other related changes

- pkg/build/conveyor.go
- pkg/build/stage/dockerfile.go
- pkg/util/cast.go
According to:
* [Understand how ARG and FROM interact](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact)
* [Using ARG variables](https://docs.docker.com/engine/reference/builder/#using-arg-variables)
* [Impact on build caching](https://docs.docker.com/engine/reference/builder/#impact-on-build-caching)
* [Environment replacement](https://docs.docker.com/engine/reference/builder/#environment-replacement)
* [Using ARG variables](https://docs.docker.com/engine/reference/builder/#using-arg-variables)
fixes https://github.com/werf/werf/issues/2771
> [dockerfile, digest] Fix ENV/ARG replacement for dockefile instructions

- cmd/werf/render/render.go
- pkg/deploy/werf_chart/werf_chart.go
Werf-render command now does not need a connection to the Kubernetes cluster.
> Disable kubernetes connection in the werf-render command

- cmd/werf/build/main.go
- cmd/werf/ci_env/ci_env.go
- cmd/werf/cleanup/cleanup.go
- cmd/werf/common/common.go
- cmd/werf/common/deploy_params.go
- cmd/werf/compose/main.go
- cmd/werf/config/list/list.go
- cmd/werf/config/render/render.go
- cmd/werf/converge/converge.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/helm/get_autogenerated_values.go
- cmd/werf/helm/get_namespace.go
- cmd/werf/helm/get_release.go
- cmd/werf/helm/helm.go
- cmd/werf/helm/secret/rotate_secret_key/rotate_secret_key.go
- cmd/werf/managed_images/add/add.go
- cmd/werf/managed_images/ls/ls.go
- cmd/werf/managed_images/rm/rm.go
- cmd/werf/purge/purge.go
- cmd/werf/render/render.go
- cmd/werf/run/run.go
- cmd/werf/stage/image/main.go
- go.mod
- go.sum
- pkg/config/meta.go
- pkg/config/meta_deploy.go
- pkg/config/raw_meta.go
- pkg/config/raw_meta_deploy.go
```
deploy:
helmChartDir: .helm
```
There is no more `--helm-char-dir` option.
Refs https://github.com/werf/werf/issues/2874.
Fixes https://github.com/werf/werf/issues/2897.
> Define --helm-chart-dir in the werf.yaml

- docs/_includes/head.html
Replace `<page.title> / <breadcrumbs ...>` template with `<page.title> / <reversed breadcrumbs ...>` template
> [docs] Fix title generation

- pkg/image/info.go
Due to pulled image may have an empty Parent field
> Fix getting of parentID from image manifest

- cmd/werf/build/main.go
- cmd/werf/ci_env/ci_env.go
- cmd/werf/cleanup/cleanup.go
- cmd/werf/compose/main.go
- cmd/werf/config/list/list.go
- cmd/werf/config/render/render.go
- cmd/werf/converge/converge.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/helm/get_autogenerated_values.go
- cmd/werf/helm/get_namespace.go
- cmd/werf/helm/get_release.go
- cmd/werf/helm/secret/rotate_secret_key/rotate_secret_key.go
- cmd/werf/managed_images/add/add.go
- cmd/werf/managed_images/ls/ls.go
- cmd/werf/managed_images/rm/rm.go
- cmd/werf/purge/purge.go
- cmd/werf/render/render.go
- cmd/werf/run/run.go
- cmd/werf/stage/image/main.go
- pkg/config/parser.go
Use `{{ .Env }}` to get an environment value which passed to the werf by --env option or WERF_ENV env var.
> [determinism] Add --env support to werf.yaml config render

- pkg/git_repo/archive_file.go
- pkg/git_repo/base.go
- pkg/git_repo/git_data_manager.go
- pkg/git_repo/local.go
- pkg/git_repo/remote.go
- created GitDataManager object;
- store tmp patches and archive in the `~/.werf/local_cache/git_data/1/tmp/` instead of `/tmp`;
- store patches cache in the `~/.werf/local_cache/git_data/1/patches/` (inactive now);
- store archives cache in the `~/.werf/local_cache/git_data/1/archives` (inactive now);
> Refactor git patches and archives generation

- pkg/build/stage/dockerfile.go
There is currently no ability to specify Dockerfile outside of build context
> Use Dockerfile only from context when context specified, fix Dockerfile not found error

- cmd/werf/common/common.go
- cmd/werf/common/deploy_params.go
- cmd/werf/converge/converge.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/helm/helm.go
- cmd/werf/helm/install.go
- cmd/werf/helm/template.go
- cmd/werf/helm/upgrade.go
- cmd/werf/helm/werf_chart.go
- cmd/werf/render/render.go
- go.mod
- go.sum
- pkg/build/conveyor.go
- pkg/config/parser.go
- pkg/deploy/secret_manager.go
- pkg/deploy/werf_chart/git_loader.go
- pkg/deploy/werf_chart/secret_values.go
- pkg/deploy/werf_chart/werf_chart.go
- pkg/git_repo/base.go
- pkg/git_repo/git_repo.go
- pkg/git_repo/helpers.go
- pkg/git_repo/local.go
- Read `--values`, `--secret-values`, `--set-file` and `.helm/secret/*` files from the local git repo in the determinism mode.
- Implement git_repo ReadFile and IsFileExists operations so that it automatically resolve symlinks. Implement git_repo CheckAndReadSymlink operation.
- Fixed deterministic chart loader for the werf-render command.
- Fix some grammar in errors.
Refs https://github.com/werf/werf/issues/2874
> [determinism] Read values-related helm data from the local git repo and some fixes

- pkg/git_repo/base.go
Error: phase build on image ~ stage dockerfile handler failed: error preparing stage dockerfile: unable to create archive: unable to rename C:\Users\test\.werf\service\tmp\git_data\d236b334-bccb-470b-bec0-18f79384679e to C:\Users\test\.werf\local_cache\git_archives\1\700ddbcae629cc7d90c6dcfda2bd10ee2997fefcc8a5a0588b8cb74e0edb53a4_d3f909c8cb82d2c44976def5298d3373c5a37de5bae71de6cfbb1dc99e760931.tar: rename C:\Users\test\.werf\service\tmp\git_data\d236b334-bccb-470b-bec0-18f79384679e C:\Users\test\.werf\local_cache\git_archives\1\700ddbcae629cc7d90c6dcfda2bd10ee2997fefcc8a5a0588b8cb74e0edb53a4_d3f909c8cb82d2c44976def5298d3373c5a37de5bae71de6cfbb1dc99e760931.tar: The process cannot access the file because it is being used by another process.
> [windows] Fix unable to rename archive

- cmd/werf/helm/secret/decrypt/decrypt.go
- cmd/werf/helm/secret/encrypt/encrypt.go
- cmd/werf/helm/secret/file/decrypt/decrypt.go
- cmd/werf/helm/secret/file/edit/edit.go
- cmd/werf/helm/secret/file/encrypt/encrypt.go
- cmd/werf/helm/secret/values/decrypt/decrypt.go
- cmd/werf/helm/secret/values/edit/edit.go
- cmd/werf/helm/secret/values/encrypt/encrypt.go
- cmd/werf/host/cleanup/cleanup.go
- cmd/werf/host/project/list/list.go
- cmd/werf/host/project/purge/purge.go
- cmd/werf/host/purge/purge.go
- cmd/werf/synchronization/main.go
- docs/_includes/documentation/reference/cli/werf_helm_secret_decrypt.md
- docs/_includes/documentation/reference/cli/werf_helm_secret_encrypt.md
- docs/_includes/documentation/reference/cli/werf_helm_secret_file_decrypt.md
- docs/_includes/documentation/reference/cli/werf_helm_secret_file_edit.md
- docs/_includes/documentation/reference/cli/werf_helm_secret_file_encrypt.md
- docs/_includes/documentation/reference/cli/werf_helm_secret_values_decrypt.md
- docs/_includes/documentation/reference/cli/werf_helm_secret_values_edit.md
- docs/_includes/documentation/reference/cli/werf_helm_secret_values_encrypt.md
- docs/_includes/documentation/reference/cli/werf_host_cleanup.md
- docs/_includes/documentation/reference/cli/werf_host_project_list.md
- docs/_includes/documentation/reference/cli/werf_host_project_purge.md
- docs/_includes/documentation/reference/cli/werf_host_purge.md
- docs/_includes/documentation/reference/cli/werf_synchronization.md
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x2bd88e3]
github.com/werf/werf/cmd/werf/helm/secret/file/encrypt.runSecretEncrypt(0xc0001220b0, 0x6, 0x0, 0x3528840)
.../werf/cmd/werf/helm/secret/file/encrypt/encrypt.go:75 +0xe3
> [cli] Fix --non-strict-determinism-inspection is not defined for command

- cmd/werf/helm/werf_chart.go
- docs/_includes/documentation/reference/cli/werf_helm_install.md
- docs/_includes/documentation/reference/cli/werf_helm_template.md
- docs/_includes/documentation/reference/cli/werf_helm_upgrade.md
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20445eb]
github.com/werf/werf/cmd/werf/helm.InitWerfChartParams(0x2ba0b20, 0xc0007d9470, 0x3f81d80, 0xc00059fee0, 0x7ffc81549e21, 0x1e, 0x7ffc81549e21, 0x1e)
/home/user/workspace/werf/cmd/werf/helm/werf_chart.go:46 +0x21b
> [helm] Fix disable-determinism flag is not added to commands 

- docs/_includes/en/installation/multiwerf_windows.md
- docs/_includes/installation/binary_windows.md
- docs/_includes/ru/installation/multiwerf_windows.md
- docs/pages/documentation/quickstart.md
- docs/pages_ru/documentation/quickstart.md
- Make a separate instructions list for Windows, MacOS and Linux OS in the quickstart guide.
- Require for werf dependencies installation explicitly.
> [docs] Fix quickstart minikube setup guides for MacOS and Windows

- cmd/werf/converge/converge.go
- cmd/werf/helm/helm.go
- cmd/werf/helm/install.go
- cmd/werf/helm/template.go
- cmd/werf/helm/upgrade.go
- cmd/werf/render/render.go
- docs/_includes/documentation/reference/cli/werf_helm_dependency_build.md
- go.mod
- go.sum
- pkg/deploy/werf_chart/werf_chart.go
- Take Chart.yaml from the repository if exists.
- Override metadata.name field with werf project name from the werf.yaml.
- Set metadata.version = 1.0.0 if not set.
- Set custom werf-chart loader globally for all `werf helm *` commands.
This makes Chart.yaml optional, but werf will use it when it exists.
Refs https://github.com/werf/helm/pull/68.
Refs https://github.com/werf/helm/pull/69
> Fix auto generation of Chart.yaml during werf-converge; update helm to v3.4.1

- pkg/build/conveyor.go
- pkg/cleaning/cleanup.go
- pkg/cleaning/purge.go
- pkg/storage/generic_lock_manager.go
- pkg/storage/kubernetes_lock_manager.go
- pkg/storage/lock_manager.go
- stages_and_images read only lock is preventive measure against running cleanup and build commands at the same time;
- this lock creates unnecessary load on the synchronization server, because this lock working all the time the build process is active for each build process;
- it is mostly safe to just omit this lock completely;
- also removed unused "image" lock from the lock manager (legacy from v1.1).
- also renamed kubernetes-related stage and stage-cache locks to include project name (just for more correctness, incompatible with v1.1 change).
> [build] Remove stages_and_images read-only lock during build process

- cmd/werf/common/deploy_params.go
- go.mod
- go.sum
- pkg/deploy/werf_chart/git_loader.go
- Read committed dependencies lock file (requirements.lock or Chart.lock).
- Scan local filesystem for the charts specified in the lock-file and use these charts in the giterminism mode.
No auto `werf helm dependency build` yet.
> [giterminism] Support subcharts loading from the local filesystem in the giterminism mode

- docs/_includes/head.html
Set absolute url for `og:url` and `twitter:url` meta tags
> [web] Update metainfo in page template.

- cmd/werf/ci_env/ci_env.go
- Remove `/werf` repo suffix for GitLab CI/CD;
- Remove `-werf` repo suffix for GitHub Actions.
> [ci-env] Change default werf images storage: remove "/werf" repo suffix

- cmd/werf/bundle/publish/publish.go
- cmd/werf/common/common.go
- cmd/werf/common/synchronization.go
- cmd/werf/converge/converge.go
- cmd/werf/helm/get_autogenerated_values.go
- cmd/werf/helm/helm.go
- cmd/werf/main.go
- docs/_data/sidebars/_cli.yml
- docs/_data/sidebars/documentation.yml
- docs/_includes/documentation/reference/cli/werf_bundle.md
- docs/_includes/documentation/reference/cli/werf_bundle.short.md
- docs/_includes/documentation/reference/cli/werf_bundle_publish.md
- docs/_includes/documentation/reference/cli/werf_bundle_publish.short.md
- docs/pages/documentation/reference/cli/overview.md
- docs/pages/documentation/reference/cli/werf_bundle.md
- docs/pages/documentation/reference/cli/werf_bundle_publish.md
- go.mod
- go.sum
- pkg/deploy/helm/extra_annotations_and_labels_post_renderer.go
- pkg/deploy/werf_chart/bundle.go
- pkg/deploy/werf_chart/service_values.go
- pkg/deploy/werf_chart/werf_chart.go
- werf_chart.WerfChart is chart.ChartExtender compatible object, which could generate a werf_chart.Bundle object. This object will keep all custom values and templates, chart config file (Chart.yaml) and other data (extra annotations/labels, extra templates).
- werf_chart.Bundle object is also chart.ChartExtender compatible object which could be deployed using the same helm install/upgrade procedure as for werf_chart.WerfChart.
- werf_chart.Bundle is compatible with standard helm-chart files structure, but contains some extensions (extra labels and annotations are saved into chart for example — these will be used only when deploying bundle using werf and ignored if deploying bundle using default helm).
- werf_chart.Bundle could be dumped into directory, packed, pushed into the container …
> Introduce initial `werf bundle publish` command

- pkg/true_git/dev_branch.go
SyncDevBranchWithStagedFiles function creates commit but does not prepare worktree for it. Staged files may include submodule changes that require special handling
> [dev] Full support for submodules

- pkg/docker/main.go
Support following environment variables:
- DOCKER_TLS
- DOCKER_TLS_VERIFY
- DOCKER_CERT_PATH
> Support docker client compatible tls docker server settings

- cmd/werf/bundle/download/download.go
- cmd/werf/bundle/export/export.go
- cmd/werf/main.go
- go.mod
- go.sum
`werf bundle export` — creates resulting bundle chart directory without publishing this chart into the docker registry.
`werf bundle download` — downloads previously published chart into the directory without applying it into the kubernetes.
> [bundle] Export and download bundle commands

- cmd/werf/bundle/apply/apply.go
- cmd/werf/bundle/download/download.go
- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/cleanup/cleanup.go
- cmd/werf/common/ondemand_kube_initializer.go
- cmd/werf/converge/converge.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/helm/helm.go
- cmd/werf/helm/install.go
- cmd/werf/helm/upgrade.go
- cmd/werf/render/render.go
- docs/_data/sidebars/_cli.yml
- docs/_data/sidebars/documentation.yml
- docs/_includes/documentation/reference/cli/werf_bundle_download.md
- docs/_includes/documentation/reference/cli/werf_bundle_download.short.md
- docs/_includes/documentation/reference/cli/werf_bundle_export.md
- docs/_includes/documentation/reference/cli/werf_bundle_export.short.md
- docs/pages/documentation/reference/cli/werf_bundle_download.md
- docs/pages/documentation/reference/cli/werf_bundle_export.md
- pkg/deploy/helm/init.go
- pkg/deploy/helm/kube_initializer.go
- pkg/deploy/helm/resources_waiter.go
- Added OndemandKubeInitializer interface and object to init kubernetes ondemand only for 'werf helm *' commands.
- Removed usage of kube-config and resources-waiter related options for the werf-render command.
NOTE:  OndemandKubeInitializer is not a perfect solution to the service initialization problem, but we need it due to the way helm commands are initialized.
> Fix werf-helm-template and werf-helm-lint commands try to load kube config; fix werf-render command excess options

- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/common/common.go
- cmd/werf/common/deploy_params.go
- go.mod
- pkg/build/conveyor.go
- pkg/config/mount.go
- pkg/config/parser.go
- pkg/giterminism_inspector/config/config.go
- pkg/giterminism_inspector/config/main.go
- pkg/giterminism_inspector/config/openapi_spec.go
- pkg/giterminism_inspector/config/openapi_spec.yaml
- pkg/giterminism_inspector/giterminism_inspector.go
werf-giterminism.yaml
```
giterminismConfigVersion: 1
config:
allowUncommitted: true
goTemplateRendering:
allowEnvVariables:
- VARIABLE_X
- /CI_*/
stapel:
mount:
allowBuildDir: true 
allowFromPaths:     
- PATH1
- /**/*/
dockerfile:
allowUncommitted:
- Dockerfile
- /**/*/
allowUncommittedDockerignoreFiles:
- .dockerignore
- /**/*/
allowContextAddFile:
- aaa
```
rel https://github.com/werf/werf/issues/3046
> Implement fine-grained giterminism config (part 1)

- cmd/werf/bundle/apply/apply.go
- cmd/werf/common/helpers.go
- cmd/werf/converge/converge.go
- Fix default helm 5 min timeout => infinite.
- Fix any timeout other than default results in 'context deadline' error.
> Fix deadline-exceeded when hook job took more than 5 min

- pkg/config/stapel_image_base.go
- pkg/giterminism_inspector/config/config.go
- pkg/giterminism_inspector/config/openapi_spec.go
- pkg/giterminism_inspector/config/openapi_spec.yaml
- pkg/giterminism_inspector/giterminism_inspector.go
werf-giterminism.yaml
```
giterminismConfigVersion: "1"
config:
stapel:
allowFromLatest: true
```
rel https://github.com/werf/werf/issues/3046
> [giterminism, stapel] Allow fromLatest

- pkg/cleaning/cleanup.go
One checksum can be associated with many stages, so it is necessary to exclude the stage itself before processing linked imports
> [cleanup] Fix goroutine stack exceeds limit

- pkg/config/parser.go
- pkg/giterminism_inspector/config/config.go
- pkg/giterminism_inspector/config/openapi_spec.go
- pkg/giterminism_inspector/config/openapi_spec.yaml
- pkg/giterminism_inspector/giterminism_inspector.go
`werf-giterminism.yaml`:
```
giterminismConfigVersion: 1
config:
goTemplateRendering:
allowUncommittedFiles:
- /**/*/
- .werf/nginx.conf
```
rel https://github.com/werf/werf/issues/3046
> [giterminism, config] Allow uncommitted files in .Files.Get/Glob 

- pkg/git_repo/git_repo.go
- pkg/git_repo/remote.go
- pkg/git_repo/work_tree.go
Rework `~/.werf/local_cache/git_*` caches files structure.
> Fix remote git for stapel builder error: error writing ... meta.json: no such file or directory

- pkg/config/raw_meta_cleanup.go
- pkg/giterminism_inspector/config/config.go
After that, each user regexp value will be wrapped with `^` and `$`.
The change affects the following directives:
- werf.yaml: 
- `cleanup.keepPolicies.[*].references.branch`
- `cleanup.keepPolicies.[*].references.tag`
- werf-giterminism.yaml: 
- `config.allowUncommittedTemplates`
- `config.goTemplateRendering.allowEnvVariables`
- `config.dockerfile.allowUncommitted`
- `config.dockerfile.allowUncommittedDockerignoreFiles`
- `helm.allowUncommittedFiles`
> [config] Cast a user regexp value to full match regexp

- pkg/config/parser.go
All files in the werf config templates directory (.werf by default) were treated as templates.
The template file must have `.tmpl` extension.
> [config] Fix werf config templates reading (.werf/**/*.tmpl)

- pkg/giterminism/file_reader/config_templates.go
- pkg/giterminism/interface.go
The template name is the path relative to the templates directory.
{{ include ".werf/templates/1.tmpl" . }} => {{ include "templates/1.tmpl" . }}
> [config] Fix naming for the user template

- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/common/deploy_params.go
- cmd/werf/converge/converge.go
- cmd/werf/render/render.go
- pkg/deploy/helm/command_helpers/build_chart_dependencies.go
- pkg/deploy/werf_chart/git_loader.go
- automatically perform dependency build operation for provided Chart.lock;
- the result of dependency build is cached by the Chart.lock's digest;
- load standard `.helm/charts` dir and charts dir using dependency build operation result.
> [giterminism] Change helm giterministic files loader logic for subcharts

- cmd/werf/bundle/apply/apply.go
- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/cleanup/cleanup.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/host/cleanup/cleanup.go
- cmd/werf/host/purge/purge.go
- cmd/werf/purge/purge.go
- cmd/werf/render/render.go
- cmd/werf/synchronization/main.go
Found by `gocritic`
```
cmd/werf/bundle/export/export.go:71:33: unlambda: replace `func() error {
return runExport()
}` with `runExport` (gocritic)
cmd/werf/synchronization/main.go:53:33: unlambda: replace `func() error {
return runSynchronization()
}` with `runSynchronization` (gocritic)
cmd/werf/bundle/download/download.go:53:33: unlambda: replace `func() error {
return runApply()
}` with `runApply` (gocritic)
cmd/werf/dismiss/dismiss.go:65:33: unlambda: replace `func() error {
return runDismiss()
}` with `runDismiss` (gocritic)
cmd/werf/purge/purge.go:47:33: unlambda: replace `func() error {
return runPurge()
}` with `runPurge` (gocritic)
cmd/werf/cleanup/cleanup.go:46:33: unlambda: replace `func() error {
return runCleanup()
}` with `runCleanup` (gocritic) …
```
> unlambda in cmd

- pkg/deploy/helm/chart_extender/helm_chart_loader.go
- pkg/deploy/helm/chart_extender/werf_chart.go
- pkg/giterminism/file_reader/helm_chart_extender.go
- pkg/giterminism/interface.go
- Added 3 new methods to the giterminism.FilesReader: LocateChart, LoadChartDir, ReadChartFile. These methods implement file-access related methods for the helm chart.ChartExtender.
- Use current implementation of these methods from chart_extender package.
> [giterminism] Implement chart extender loading functions in giterminism manager

- pkg/config/stapel_image_base.go
```
WARNING: Do not use artifacts as a base for other images and artifacts. The feature is deprecated, and the directive 'fromArtifact' will be completely removed in version v1.3.
Careless use of artifacts may lead to difficult to trace issues that may arise long after the configuration has been written. The artifact image is cached after the first build and ignores any changes in the project git repository unless the user has explicitly specified stage dependencies. As found, this behavior is completely unexpected for users despite the fact that it is absolutely correct in the werf logic.
```
> Update deprecation warning for fromArtifact directive

- pkg/deploy/helm/chart_extender/common_template_funcs.go
- pkg/giterminism_manager/manager.go
- werf_image will be removed in the v1.3;
- DEPRECATION WARNING instead of WARNING for --loose-giterminism, will be removed in the v1.2.
> Small changes for DEPRECATION WARNINGS

- pkg/build/conveyor.go
- pkg/deploy/lock_manager/lock_manager.go
- pkg/path_matcher/git_mapping.go
- pkg/true_git/ls_tree/result.go
```
pkg/true_git/ls_tree/result.go:69:4: SA4006: this value of `err` is never used (staticcheck)
pkg/build/conveyor.go:1235:16: printf: Errorf format %s reads arg #4, but call has 3 args (govet)
pkg/deploy/lock_manager/lock_manager.go:39:58: SA1012: do not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use (staticcheck)
pkg/path_matcher/git_mapping.go:93:28: unslice: could simplify f.includePaths[:] to f.includePaths (gocritic)
pkg/path_matcher/git_mapping.go:94:28: unslice: could simplify f.excludePaths[:] to f.excludePaths (gocritic)
```
> small cleanups and fixes

- pkg/deploy/helm/chart_extender/chart_template_helpers.go
- pkg/deploy/helm/chart_extender/service_values.go
Pass nameless image as .Values.werf.nameless_image instead of .Values.werf.image.
.Values.werf.image is always map[string]string and will only contain named images names.
As nameless image is being deprecated in the v1.2 there is no "normal" way to get nameless image from values, that's why we use "special" value .Values.werf.nameless_image for now. In the v1.3 nameless images will be completely removed.
> [deploy] werf_image and nameless image deprecation fix

- integration/suites/giterminism/config_dockerfile_test.go
- integration/suites/giterminism/config_go_template_test.go
- integration/suites/giterminism/config_templates_dir_test.go
- integration/suites/giterminism/config_test.go
- integration/suites/giterminism/giterminism_config_test.go
- integration/suites/giterminism/helm_test.go
- pkg/giterminism_manager/file_reader/config.go
- pkg/giterminism_manager/file_reader/config_go_template.go
- pkg/giterminism_manager/file_reader/config_templates.go
- pkg/giterminism_manager/file_reader/configuration.go
- pkg/giterminism_manager/file_reader/dockerfile.go
- pkg/giterminism_manager/file_reader/errors.go
- pkg/giterminism_manager/file_reader/file_reader.go
- pkg/giterminism_manager/file_reader/git.go
- pkg/giterminism_manager/file_reader/giterminism_config.go
- pkg/giterminism_manager/file_reader/helm_chart_extender.go
```
the <config type> '<path>' not found in the project git repository
=>
unable to read <config type>: the file "<path>" not found in the project git repository
the uncommitted configuration found in the project directory: the <config type> '<path>' must be committed
=>
unable to read <config type>: the file "<path>" must be committed
```
> [giterminism] Refactoring: simplify error messages and the corresponding code

- cmd/werf/common/common.go
- pkg/build/stage/dockerfile.go
- pkg/giterminism_manager/file_reader/file_reader.go
- pkg/giterminism_manager/file_reader/git.go
- pkg/giterminism_manager/interface.go
- pkg/giterminism_manager/manager.go
```
\# docs/werf.yaml
project: docs
---
image: docs
dockerfile: ./Dockerfile
```
When running werf from docs folder werf's dockerfile builder will use `docs` dir — project dir — as build dockerfile build context root for the context tar archive, not git work tree root.
> Fix dockerfile-not-found error when running werf not from the root of the git work tree

- pkg/git_repo/base.go
- pkg/git_repo/local.go
- pkg/git_repo/remote.go
NOTE. yieldRepositoryBackedByWorkTree differs for Local and Remote git repo:
- Local yieldRepositoryBackedByWorkTree will prepare ~/.werf/local_cache/git_worktrees/... only in the case when submodules are used in the repo.
- Remote yieldRepositoryBackedByWorkTree will always prepare ~/.werf/local_cache/git_worktrees/... work tree.
> [git_repo] Fix: do not use ~/.werf/local_cache/git_worktrees for git_repo.Local operations if no submodules are used

- integration/suites/giterminism/config_dockerfile_test.go
- integration/suites/giterminism/config_go_template_test.go
- integration/suites/giterminism/config_templates_dir_test.go
- integration/suites/giterminism/config_test.go
- integration/suites/giterminism/giterminism_config_test.go
- integration/suites/giterminism/helm_test.go
- pkg/git_repo/local.go
- pkg/git_repo/status/result.go
- pkg/git_repo/status/status.go
- pkg/giterminism_manager/config/config.go
- pkg/giterminism_manager/file_reader/config.go
- pkg/giterminism_manager/file_reader/config_go_template.go
- pkg/giterminism_manager/file_reader/configuration.go
- pkg/giterminism_manager/file_reader/dockerfile.go
- pkg/giterminism_manager/file_reader/errors.go
- pkg/giterminism_manager/file_reader/fs.go
- pkg/giterminism_manager/file_reader/git.go
- pkg/giterminism_manager/file_reader/giterminism_config.go
- pkg/giterminism_manager/file_reader/helm_chart_extender.go
- Read the configuration file from fs if not resolved path accepted by giterminism config:
- the file must exist in the project git work tree directory;
- the path must be fully accepted by giterminism config (each resolved symlink target must be accepted).
- Read the configuration file from commit:
- the file must exist in the current commit;
- the path must not have any uncommitted changes locally (each symlink target).
Improve resolve symlink failed error messages:
- fs symlink:
- `unable to read <config type>: accepted symlink "<symlink path>" check failed: too many levels of symbolic links`
- `unable to read <config type>: accepted symlink "<symlink path>" check failed: the link target "<target path>" should be also accepted by giterminism config`
- commit symlink:
- `unable to read …
> [giterminism] Improve feedback and manager logic 

- .github/workflows/daily_tests.yml
- .github/workflows/tests.yml
- integration/ci_suites/default/render
- integration/ci_suites/k8s_per_version/deploy
- integration/ci_suites/k8s_per_version/releaseserver
- integration/pkg/suite_init/container_registry_per_implementation_data.go
- integration/suites/bundles/bundles_test.go
- integration/suites/bundles/suite_test.go
- integration/suites/deploy/resources_adopter_test.go
- pkg/secret/aes_encoder_test.go
- pkg/secret/yaml_encoder_test.go
[tests] Fix pkg/secret tests not compiling.
[tests] Use the same layout for k8s + registry by implementation as PR tests workflow use.
[tests] Rename releaseserver to deploy suite for CI, added render suite into default CI test layout
[tests] Refactor bundles test and container-registry-per-implementation-data initialization for repo
- Use SetupRepo and TeardownRepo to setup all werf repo-related environment params for selected implementation.
- SetupRepo and TeardownRepo will create and remove repo in the registry.
[tests][deploy] Fix failing resource adopter test due to lint-rename-refactoring
[tests][bundles] Add skips due to unresolved issues for github, dockerhub and quay
https://github.com/werf/werf/issues/3182
https://github.com/werf/werf/issues/3184 …
> [tests] Fix daily tests, not compiling and failing tests, refactor tests precompile

- pkg/git_repo/local.go
- pkg/git_repo/status/result.go
- pkg/git_repo/status/status.go
- pkg/giterminism_manager/file_reader/errors.go
- pkg/giterminism_manager/file_reader/git.go
- pkg/giterminism_manager/inspector/build_context.go
- pkg/giterminism_manager/inspector/inspector.go
- Ignore user work tree submodule directory if a submodule ".git" directory not found
- Return a detailed error if a work tree submodule directory is not clean:
```
the submodule "<submodule path>" is not clean and must be committed. Do not forget to push the current commit to the submodule remote If this commit exists only locally
Details:
commit:                 "0000000000000000000000000000000000000000"
currentWorktreeCommit:  "d9243a9a45b10e6b7d985322b8108897626a25a6"
expectedWorktreeCommit: "d9243a9a45b10e6b7d985322b8108897626a25a6"
You might also be interested in developer mode (activated with --dev option) that allows you to work with staged changes without doing redundant commits. Just use "git add <file>..." to include the changes that should be used.
```
- Return a detailed …
> [giterminism] Improve feedback if a related submodule is not clean or has changes

- integration/suites/build/stapel_image/base_image/from_image_test.go
- pkg/config/parser.go
- pkg/giterminism_manager/interface.go
- The used environment variable can be empty but must be set (ENV_NAME="").
- Otherwise, an error `executing "werfConfig" at <env "test">: error calling env: the environment variable "<ENV_NAME>" must be set` will be returned
> [config] The env function requires the set environment variable 

- pkg/config/parser.go
The required function gives developers the ability to declare a value entry as required for config rendering. If the value is empty, the config will not render and will return an error message supplied by the developer.
```
{{ required "A valid <anything> value required!" <anything> }}
```
> [config] The required function to declare a variable as required

- pkg/cleaning/images_cleanup.go
- pkg/docker_registry/api.go
- pkg/docker_registry/default.go
- Consider image is not exists in that case.
- Log warnings on BLOB_UNKNOWN and MANIFEST_UNKNOWN for default docker registry impl.
> [BLOB_UNKNOWN] Completely ignore images with BLOB_UNKNOWN errors from the registry

- pkg/docker_registry/api.go
- pkg/docker_registry/default.go
Ignore silently without warnings until werf-cleanup does not delete these broken images.
> [v1.2] Ignore BLOB_UNKNOWN registry errors

- go.mod
- go.sum
- pkg/config/parser.go
Added only new functions from Sprig v3 (so as not to break the reproducibility of current configurations):
```
add1f
addf
all
any
bcrypt
chunk
concat
decryptAES
deepCopy
deepEqual
dig
divf
duration
durationRound
encryptAES
fromJson
genCAWithKey
genSelfSignedCertWithKey
genSignedCertWithKey
get
getHostByName
htpasswd
maxf
minf
mulf
mustAppend
mustChunk
mustCompact
mustDateModify
mustDeepCopy
mustFirst
mustFromJson
mustHas
mustInitial
mustLast
mustMerge
mustMergeOverwrite
mustPrepend
mustPush
mustRegexFind
mustRegexFindAll
mustRegexMatch
mustRegexReplaceAll
mustRegexReplaceAllLiteral
mustRegexSplit
mustRest
mustReverse
mustSlice
mustToDate
mustToJson
mustToPrettyJson
mustToRawJson
mustUniq
mustWithout
must_date_modify
osBase
osClean
osDir
osExt
osIsAbs
randBytes
randInt
regexQuoteMeta
seq …
```
> [v1.1, config] Mix Sprig V2 and V3 functions

- pkg/config/parser.go
```
Error: unable to load werf config: template: werfConfig:8:9: executing "werfConfig" at <.Files.Glob>: error calling Glob: {{ .Files.Glob "path" }}: no matches found
```
> [config] .Files.Glob fails with an error instead of a warning message if no matches found

- pkg/giterminism_manager/file_reader/git.go
- pkg/giterminism_manager/inspector/build_context.go
- pkg/giterminism_manager/inspector/inspector.go
А few words on the issue:
```
$ git status
On branch master
nothing to commit, working tree clean
$ werf build
...
Running time 1.05 seconds
Error: phase build on image x stage gitArchive handler failed: the file "broken_symlink" must be committed
You might also be interested in developer mode (activated with --dev option) that allows you to work with staged changes without doing redundant commits. Just use "git add <file>..." to include the changes that should be used.
To provide a strong guarantee of reproducibility, werf reads the configuration and build's context files from the project git repository and eliminates external dependencies. We strongly recommend to follow this approach. But if necessary, you can allow the reading of specific files directly from the file system and enable …
```
> [giterminism] Fix broken symlinks are processed incorrectly

- pkg/util/file.go
А few words on the issue:
```
$ werf build
...
Error: phase build on image x stage gitArchive handler failed: error preparing stage gitArchive: error creating archive for commit "9ddc6d4ad22f4745e958864b2fded5dcf42a8fea": base path broken_symlink entry not found repo
$ cat werf.yaml
project: broken_symlink
---
image: test
from: alpine
git:
- add: /broken_symlink
to: /link
```
When adding a file to an assembly container, it doesn't matter which file the symlink points to.
> [stapel, git] Fix adding a broken symlink does not work

- pkg/build/stage/git_mapping.go
- pkg/git_repo/git_data_manager.go
- pkg/git_repo/work_tree.go
- pkg/true_git/common.go
- pkg/true_git/dev_branch.go
- pkg/true_git/dot_git.go
- pkg/true_git/merge.go
- pkg/true_git/merge_base.go
- pkg/true_git/patch.go
- pkg/true_git/repository.go
- pkg/true_git/show_ref.go
- pkg/true_git/submodule.go
- pkg/true_git/work_tree.go
The root of the issue: werf have added file converted from LF to CRLF into built image under windows due to some local git autocrlf settings. Then werf cannot apply patch to the file with CRLF's inside the build container.
1. Fix werf to always add files into image from git without any conversions from LF to CRLF, or from CRLF to LF. Take files from the git as-is.
2. Fix patches applier for files with CRLF already added into the built images for some reason (images built with an older werf version with this bug).
> [win][git] Fix CRLF issues and patch-does-not-apply errors

- pkg/git_repo/local.go
- pkg/git_repo/status/result.go
- pkg/giterminism_manager/config/config.go
- pkg/giterminism_manager/file_reader/config.go
- pkg/giterminism_manager/file_reader/config_go_template.go
- pkg/giterminism_manager/file_reader/config_templates.go
- pkg/giterminism_manager/file_reader/configuration.go
- pkg/giterminism_manager/file_reader/errors.go
- pkg/giterminism_manager/file_reader/file_reader.go
- pkg/giterminism_manager/file_reader/fs.go
- pkg/giterminism_manager/file_reader/git.go
- pkg/giterminism_manager/file_reader/giterminism_config.go
- pkg/giterminism_manager/file_reader/helm_chart_extender.go
- pkg/giterminism_manager/inspector/dockerfile.go
- pkg/giterminism_manager/inspector/inspector.go
- pkg/giterminism_manager/inspector/stapel.go
- pkg/path_matcher/stub_path_matcher.go
Skip the file when reading a group of configurations from the FS if:
- not accepted by giterminism config
- not changed locally
- ignored by .gitignore
- not inside an unclean submodule repository
> [giterminism] Fix .gitignore rules are not fully supported

- pkg/config/parser.go
- fromYAML(str string) (map[string]interface{}, error)
- return error if unmarshalling failed
werf.yaml
```
...
{{- $values := .Files.Get "werf_values.yaml" | fromYaml -}} // or fromYaml (.Files.Get "werf_values.yaml")
from: {{- $values.image.from }}
```
werf_values.yaml
```
image:
from: alpine
```
> [v1.1, config] Add fromYaml function

- pkg/config/parser.go
- fromYAML(str string) (map[string]interface{}, error)
- return error if unmarshalling failed
werf.yaml
```
...
{{- $values := .Files.Get "werf_values.yaml" | fromYaml -}} # or fromYaml (.Files.Get "werf_values.yaml")
from: {{ $values.image.from }}
```
werf_values.yaml
```
image:
from: alpine
```
> [config] Add fromYaml function

- cmd/werf/ci_env/ci_env.go
Ignore only if the old form of the command call is used: `source <(werf ci-env gitlab --tagging-strategy=...)`
> [ci_env] Ignore the non-existent --tagging-strategy option

- pkg/tmp_manager/docker_config_dir.go
```
Error: unable to create tmp docker config: unable to copy /home/user/.docker to /tmp/werf-docker-config-780142139: open /home/user/.docker/run/docker-cli-api.sock: no such device or address
```
> [ci_env] Fix unable to create tmp docker config based on the user's one

- cmd/werf/converge/converge.go
- go.mod
- go.sum
- pkg/deploy/helm/maintenance_helper/migrate2to3.go
If for some unknown and unexpected by werf migration workflow reason there is helm 2 and helm 3 releases at the moment,
then ignore helm 2 release and continue deploy process into helm 3 release, but print a WARNING about existing helm 2 release.
To disable this warning user should possible cleanup helm 2 metadata by kubectl -n kube-system delete cm RELEASE.VERSION.
> [migrate 2 to 3] Print warning when helm 2 and helm 3 releases exists at the same time

- docs/pages_ru/documentation/advanced/ci_cd/gitlab_ci_cd.md
Since gitlab 11.9 `CI_MERGE_REQUEST_LABELS` is available.
So if we want to determine if label "review" is present for MR, we can use this variable. 
This solutions makes project configuration easier since we don't need to issue PRIVATE_TOKEN and declare it as CI variable, also this is faster because we don't make any API call
> [docs] Change api call to CI variable

- pkg/build/conveyor.go
- pkg/build/stage/dockerfile.go
- pkg/build/stage/git_archive.go
- pkg/context_manager/context_manager.go
- pkg/git_repo/base.go
- pkg/git_repo/local.go
- pkg/git_repo/status/result.go
- pkg/git_repo/status/status.go
- pkg/giterminism_manager/config/config.go
- pkg/giterminism_manager/file_reader/config_go_template.go
- pkg/giterminism_manager/file_reader/configuration.go
- pkg/giterminism_manager/file_reader/fs.go
- pkg/giterminism_manager/file_reader/git.go
- pkg/giterminism_manager/file_reader/helm_chart_extender.go
- pkg/path_matcher/dockerfile_ignore.go
- pkg/path_matcher/dockerfile_ignore_test.go
- pkg/path_matcher/git_mapping.go
- pkg/path_matcher/git_mapping_test.go
- pkg/path_matcher/multi_path_matcher.go
- pkg/path_matcher/path_matcher.go
- pkg/path_matcher/path_matcher_test.go
- pkg/path_matcher/simple.go
- pkg/path_matcher/simple_test.go
- pkg/path_matcher/stub_path_matcher.go
- pkg/true_git/archive.go
- pkg/true_git/diff_parser.go
- pkg/true_git/ls_tree/ls_tree.go
- pkg/true_git/ls_tree/result.go
**[ls_tree] Remove the strict option in LsTree function**
The option allowed to run ls tree for work tree with uninitialized submodules. We always work with the service work tree in current versions, where the submodules must be initialized.
**[path_matcher] Remove the greedySearch parameter and change interface**
There are the following changes in the PathMatcher interface:
- Rename the MatchPath method to IsPathMatched.
- Split the ProcessDirOrSubmodulePath method into ShouldGoThrough and IsDirOrSubmodulePathMatched methods.
```
// IsPathMatched checks for a complete matching of the path
IsPathMatched(string) bool
// ShouldGoThrough indicates that the directory or submodule path is not completely matched but may include matching files among the child files.
// The method returns false …
```
> Rework ls tree and path matcher interface

- docs/_data/breadcrumbs.yml
- docs/_data/sidebars/_documentation.yml
- docs/_data/sidebars/documentation.yml
- docs/pages/documentation/whats_new_in_v1_2/changelog.md
- docs/pages/documentation/whats_new_in_v1_2/howto_from_v1_1_to_v1_2.md
Chapter consists of 2 articles:
- Changelog — full descriptive list of key changes since v1.1, explaining what and why.
- How to migrate from v1.1 to v1.2 — fast guide to migrate your project from v1.1 to v1.2 without excess explanations.'
This change is part 1 of the following changes:
1. english version of changelog;
2. english and russian version of migration guide and russian version of changelog.
> [docs] "What's new in v1.2" documentation chapter (part 1/2)

- pkg/path_matcher/git_mapping.go
Several sets of globes are used when comparing paths:
- The universal part `**/*` is added to all globes (as before).
- From all globes, all asterisks to the right are cut off.
> [path_matcher] Update Simple/GitMappingPathMatcher.IsMatched method logic

- pkg/path_matcher/git_mapping.go
Several sets of globes are used when comparing paths:
- The globes as they are.
- The globes without asterisks on the right (`path/*/dir/**/*`, `path/*/dir/**`, `path/*/dir/*/*/**` -> `path/*/dir`).
- The globes from the previous set with the universal part `**/*` (`path/*/dir/**/*`).
> [path_matcher] Fix Simple/GitMappingPathMatcher.IsMatched method logic

- pkg/true_git/dev_branch.go
Create a single commit for changes in the worktree instead of two separate commits for index and worktree changes.
> [dev] Change the cache logic in simple development mode

- .github/workflows/website_converge-tag.yml
- .github/workflows/website_converge.yml
- Don't deploy web backend to the test env
- Deploy documentation from a tag in a separate job
> [ci][docs] Don't deploy backend to the test env

- cmd/werf/compose/main.go
- pkg/build/conveyor.go
1. This will detect deleted stage image from the storage and cause werf to rebuild this image automatically (when stages-storage-cache is invalid).
2. This allows setting LRU meta info for the stage image, which will be used by build-host GC of images.
> [compose] Fetch last stages of built images before running compose

- pkg/git_repo/base.go
- pkg/git_repo/git_repo.go
- pkg/true_git/archive.go
- pkg/true_git/ls_tree/ls_tree.go
- pkg/true_git/patch.go
The cache IDs broke in v1.2.10.
> [git_repo] Fix LsTree/Patch/Archive cache ID

- cmd/werf/build/main.go
- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/cleanup/cleanup.go
- cmd/werf/common/common.go
- cmd/werf/common/storage.go
- cmd/werf/converge/converge.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/host/cleanup/cleanup.go
- cmd/werf/purge/purge.go
- docs/_includes/documentation/reference/cli/werf_build.md
- docs/_includes/documentation/reference/cli/werf_bundle_export.md
- docs/_includes/documentation/reference/cli/werf_bundle_publish.md
- docs/_includes/documentation/reference/cli/werf_cleanup.md
- docs/_includes/documentation/reference/cli/werf_converge.md
- docs/_includes/documentation/reference/cli/werf_dismiss.md
- docs/_includes/documentation/reference/cli/werf_host_cleanup.md
- docs/_includes/documentation/reference/cli/werf_purge.md
- pkg/host_cleaning/gc.go
- pkg/host_cleaning/host_cleanup.go
- Added --allowed-volume-usage-margin param which sets target volume usage after cleanup: allowed-volume-usage - allowed-volume-usage-margin.
- Delete 10 images minimal in each GC iteration to speed up cleanup.
> [GC] Host cleanup garbage collection refinements

- pkg/docker/image.go
- pkg/util/parallel/constant/constant.go
- pkg/util/parallel/parallel.go
- By default werf disables BuildKit when building dockerfiles.
- If the user explicitly activates BuildKit (`DOCKER_BUILDKIT=1`), werf enables it but without output in the background builds due to https://github.com/docker/cli/issues/2889.
> [dockerfile] The BuildKit support with explicit user activation

- .github/workflows/daily_tests.yml
- .github/workflows/tests.yml
The `always` function returns true even when canceled, or the previous tasks skipped.
> [ci] Workflows: replace always with success || failure condition

- .github/workflows/docs_tests.yml
- scripts/tests/precompiled_tests_binaries.sh
- [ci] Fix tests
```
Run # unit tests binaries
?   	github.com/werf/werf/cmd/werf	[no test files]
go: directory integration/ci_suites/default/docs/_fixtures/cli/docs/site/backend is outside main module
Error: Process completed with exit code 1.
```
- [ci] Documentation Validation: fix `chmod: Gemfile.lock: No such file or directory`
> [ci] Fix tests and Documentation Validation workflow

- cmd/werf/common/storage_repo_data.go
```
DEPRECATION WARNING: The option --repo-implementation ($WERF_REPO_IMPLEMENTATION) is renamed to --repo-container-registry ($WERF_REPO_CONTAINER_REGISTRY) and will be removed in v1.3!
```
> Deprecation warning for the --repo-implementation option

- pkg/build/stage/git_mapping.go
- pkg/git_repo/base.go
- pkg/git_repo/git_data_gc.go
- pkg/git_repo/git_data_manager.go
- pkg/git_repo/git_repo.go
- pkg/git_repo/local.go
- pkg/git_repo/remote.go
- pkg/git_repo/work_tree.go
- pkg/host_cleaning/host_cleanup.go
- pkg/host_cleaning/local_docker_server.go
- pkg/tmp_manager/gc.go
- pkg/true_git/work_tree.go
- pkg/util/timestamps/timestamp_file.go
- pkg/volumeutils/volume_usage.go
- pkg/werf/last_werf_run_at.go
- Remove ~/.werf/local_cache/{git_patches|git_archives|git_worktrees|git_repos} completely when volume usage exceeds allowed level, smart GC for git-data will be added in a separate PR.
- Added last-used-timestamps into git_patches, git_archives, git_worktrees and git_repos caches.
- Refactored git_patches and git_archives files structure in ~/.werf/local_cache to reduce number of files which stored in the cache dir at the same time (use first byte of sha256 hash as a directory).
> [GC] Added basic support for cached git-data cleaning into host cleanup procedure

- pkg/util/timestamps/timestamp_file.go
- pkg/werf/last_werf_run_at.go
- pkg/werf/main.go
This info needed for v1.2's host cleanup procedure.
> [GC][v1.1] Save last/first werf run timestamps for v1.1

- cmd/werf/cleanup/cleanup.go
- cmd/werf/images/cleanup/cleanup.go
- docs/_includes/cli/werf_cleanup.md
- docs/_includes/cli/werf_images_cleanup.md
--git-history-based-cleanup-v1.2 option has been enabled by default: use git history based cleanup and delete images tags without related image metadata (default $WERF_GIT_HISTORY_BASED_CLEANUP_v1_2).
> [cleanup][v1.1] Enable v1.2 werf-cleanup mode for v1.1 by default

- .github/workflows/validate_repo.yml
- docs/site/js/installation.js
Select `ea` as the default channel for v1.2, otherwise - select `stable`.
Drop status to default when the version changes.
> [web] Fix installation page tab logic

- cmd/werf/build/main.go
- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/cleanup/cleanup.go
- cmd/werf/common/common.go
- cmd/werf/common/host_cleanup.go
- cmd/werf/converge/converge.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/host/cleanup/cleanup.go
- cmd/werf/purge/purge.go
- docs/documentation/_includes/reference/cli/werf_build.md
- docs/documentation/_includes/reference/cli/werf_bundle_export.md
- docs/documentation/_includes/reference/cli/werf_bundle_publish.md
- docs/documentation/_includes/reference/cli/werf_cleanup.md
- docs/documentation/_includes/reference/cli/werf_converge.md
- docs/documentation/_includes/reference/cli/werf_dismiss.md
- docs/documentation/_includes/reference/cli/werf_host_cleanup.md
- docs/documentation/_includes/reference/cli/werf_purge.md
- pkg/git_repo/gitdata/gc.go
- pkg/host_cleaning/host_cleanup.go
- pkg/host_cleaning/local_docker_server.go
- --allowed-docker-storage-volume-usage and --allowed-docker-storage-volume-usage-margin to configure docker-storage host cleanup;
- --allowed-local-cache-volume-usage and --allowed-local-cache-volume-usage-margin to configure local-storage host cleanup (including git-data).
> [GC] Renamed allowed-volume-usage related options and enabled auto host cleanup by default

- pkg/stapel/stapel.go
Example for use it without access to docker.io, from local registry.
> [stapel] Add ability to set werf-stapel image name

- .github/workflows/tests.yml
- pkg/cleaning/cleanup.go
- pkg/cleaning/stage_manager/manager.go
- Take into account the images used in k8s when applying policies. Previously, these images were not counted, and policies excluded images in addition to them.
- Keep the images used in k8s and related to nonexistent commits.
- Improve debugging: log the number of images that are deleted and saved by policies.
> [cleanup] Improvements

- pkg/host_cleaning/images.go
- pkg/host_cleaning/local_docker_server.go
- pkg/storage/repo_stages_storage.go
- Fix StagesStorage ShouldFetch method: perform fresh docker-inspect, do not use cached inspection result from the previous inspect.
- Fix host cleanup procedure: do not delete <none:none> orphan images created less than 3 hours ago to prevent deletion of freshly built stage images, which are not saved into the stages storage yet.
> [GC] Prevent host cleanup procedure from deleting images which are in use

- pkg/build/conveyor.go
Fetch operation will check that image exists correctly and will reset stages building conveyor to rebuild this stage if needed.
> [stapel] Fix: fetch artifact/image stage before running imports rsync server

- pkg/stapel/stapel.go
Example for use it without access to docker.io, from local registry.
> [v1.1] Add ability to set werf-stapel image name

- pkg/build/conveyor.go
- pkg/build/import_server/rsync_server.go
- pkg/container_runtime/container_runtime.go
- pkg/storage/local_docker_server_stages_storage.go
- pkg/storage/manager/stages_storage.go
- pkg/storage/repo_stages_storage.go
- pkg/storage/stages_storage.go
* Fix saving stages-ids into the stages-storage-cache
* Support for rejected stages in the stages storage
* [stapel] Fix: fetch artifact/image stage before running imports rsync server
* Fix: print rsync server docker run command on failure
> Port last builder related changes from v1.1 to v1.2

- pkg/docker_registry/api.go
- pkg/storage/manager/stages_storage.go
- pkg/storage/repo_stages_storage.go
Do not reject stage when manifest-unknown or name-unknown errors detected. Only reject images with blob-unknown errors.
> [builder] Proper rejection of blob-unknown stages

- cmd/werf/bundle/apply/apply.go
- cmd/werf/bundle/download/download.go
- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/common/helm.go
- cmd/werf/converge/converge.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/helm/helm.go
- cmd/werf/helm/migrate2to3.go
- cmd/werf/render/render.go
- go.mod
- go.sum
- pkg/deploy/helm/chart_extender/bundle.go
- pkg/deploy/helm/chart_extender/chart_dependencies_loader.go
- pkg/deploy/helm/chart_extender/werf_chart.go
- pkg/deploy/helm/command_helpers/build_chart_dependencies.go
- pkg/deploy/helm/init.go
- Panic was due to uninitialized helm registry client.
Fixes https://github.com/werf/werf/issues/3415
Refs https://github.com/werf/helm/pull/92
- Updated helm to v3.5.3.
> [helm] Add support for oci registries in Chart.yaml: fix panic

- pkg/deploy/helm/chart_extender/helpers/service_values.go
- pkg/deploy/helm/chart_extender/werf_chart_stub.go
- Fix panic on werf-helm-dep-update when secret-values are used (fixes https://github.com/werf/werf/issues/3443).
- Set .Values.werf.env="" stub werf service value in werf-helm-* commands.
> [helm] Werf-helm fixes

- docs/.gitignore
- docs/site/.werf/nginx-dev.conf
- docs/site/docker-compose.yml
- docs/site/werf.yaml
To run documentation locally, use:
```
cd docs/site &&
werf compose up --follow --docker-compose-command-options="-d"
```
Open http://localhost
To stop:
```
cd docs/site &&
werf compose down
```
You should commit main site files (site/*) into git to see changes.
Documentation files changes will be almost immediately available.
> [CI] Documentation local development

- .github/workflows/release_publisher.yml
- scripts/publish_release.sh
Perform automatic creation of github release, only not publish bintray packages automatically.
> [v1.1,ci] Fix release publisher

- docs/documentation/pages_ru/advanced/cleanup.md
1.because it is not created automatically and the task does not work out because of this
2.if you create such a file, it will not be rotated and will overwhelm the entire disk
> [docs] remove in cleanup  /var/log/werf-host-cleanup.log

- pkg/git_repo/base.go
- pkg/git_repo/local.go
- pkg/git_repo/remote.go
- pkg/git_repo/repo_handle/handle.go
- pkg/git_repo/repo_handle/interface.go
- pkg/true_git/archive.go
- pkg/true_git/ls_tree/ls_tree.go
- pkg/true_git/ls_tree/result.go
- pkg/util/sync.go
**Implement git repository handle**
A solution to get away from the worktree when working with the git repository, caching the necessary data from the worktree during initialization, and then working exclusively with git objects.
> [stapel, git] Fix submodule not initialized

- pkg/path_matcher/base_path.go
- pkg/path_matcher/common.go
- pkg/path_matcher/dockerfile_ignore.go
- pkg/path_matcher/exclude.go
- pkg/path_matcher/include.go
- pkg/path_matcher/multi.go
The identifiers included paths but did not include path matcher type. 
Since identifiers were used for caching, this could lead to invalid caching.
For example, the following path mappings were cached using the same key:
```
git:
- add: /
to: /app
includePaths:
- go.mod
- go.sum
git:
- add: /
to: /app
excludePaths:
- go.mod
- go.sum
```
> [path_matcher] Fix incorrect path matcher IDs

- cmd/werf/compose/main.go
- docs/documentation/_includes/reference/cli/werf_compose_down.md
- docs/documentation/_includes/reference/cli/werf_compose_run.md
- docs/documentation/_includes/reference/cli/werf_compose_run.short.md
- docs/documentation/_includes/reference/cli/werf_compose_up.md
- docs/documentation/pages_en/reference/cli/werf_compose_run.md
- pkg/build/conveyor.go
If one or more IMAGE_NAME parameters specified, werf will build and forward only these images
```shell
werf compose run [IMAGE_NAME...] [options] [--docker-compose-options="OPTIONS"] [--docker-compose-command-options="OPTIONS"] -- SERVICE [COMMAND] [ARGS...]
```
> [compose] Support for positional arguments to build and forward specific images

- pkg/docker_registry/api.go
The user may have encountered related issues when using the base image (`from`) with digest (`REPO@DIGEST`, `REPO:TAG@DIGEST`).
```
WARNING: cannot get base image id (alpine@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f): can not get base image id from registry (alpine@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f): repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: alpine@sha256
WARNING: using existing image alpine@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f without pull
```
> [container registry] Fix processing of reference with digest

- cmd/werf/common/common.go
- pkg/deploy/helm/command_helpers/build_chart_dependencies.go
- Internal helm-dependency-build process error was shadowed and not affected anything.
- `werf render (--verbose|--debug)` should enable verbose or debug mode, but it was not happened.
> Fix werf-render command error shadowing and logging

- pkg/build/stage/git_archive.go
- pkg/build/stage/git_mapping.go
- pkg/git_repo/archive_file.go
- pkg/git_repo/base.go
- pkg/git_repo/git_repo.go
- pkg/git_repo/gitdata/git_data_manager.go
- pkg/true_git/archive.go
- pkg/true_git/diff_parser.go
- pkg/true_git/patch.go
Fix git.add single file rename not working
This previously resulted in `/dir/oldfilename` in an image, but now results in
`/dir/newfilename` as supposed to:
```
git:
- add: /dir/oldfilename
to: /dir/newfilename
```
Fixes: #1741, #3180
> Fix git.add single file rename not working

- docs/documentation/pages_en/quickstart.md
- docs/documentation/pages_ru/quickstart.md
- docs/site/css/index.css
- docs/site/pages_en/index.md
- docs/site/pages_ru/index.md
- Use Giterminism instead of GitOps in title.
- Add usage workflows supported by the werf (converge and bundles).
- Add note about the way werf used (manually, CI/CD, etc.).
> [site][landing] Reword GitOps section

- pkg/storage/manager/stages_storage.go
Disable caching when stages storage local or special flag (`WERF_STAGES_STORAGE_DISABLE_IMAGE_METADATA_CACHE=1`) set
> [v1.1.23, storage] Optional use of caching for image metadata

- cmd/werf/converge/converge.go
- go.mod
- go.sum
- pkg/kubeutils/configmap.go
Werf internally uses `--create-namespace` flag of helm, which is broken.
Fixed in the werf/helm fork for now: https://github.com/werf/helm/pull/96.
> Fix werf automatical namespace creation RBAC issue

- pkg/true_git/dev_branch.go
```
Error: unable to sync staged changes: git command /usr/local/bin/git -C ~/.werf/local_cache/git_worktrees/9/local/9787063286a09974befa8dc3de81e63edb79c5304621035136d181f2ca792dd7/worktree -c core.autocrlf=false -c user.email=werf@werf.io -c user.name=werf commit -m 2021-06-03 20:00:52.409615 +0400 +04 m=+1.173176433 failed: exit status 1
On branch werf-dev-b90c24d97bcca2b4a69c4f78e85507fe925ab3f0
Nothing to commit, working tree clean
```
> [dev] Fix incorrect behavior when project repository has a dirty submodule

- go.mod
- go.sum
- integration/suites/deploy/kubedog_multitrack_test.go
Updated kubedog: https://github.com/werf/kubedog/pull/208.
> Fix werf resources tracker exits before resources are ready

- go.mod
- go.sum
Updated kubedog: https://github.com/werf/kubedog/pull/209.
> [v1.1] Fix werf resources tracker exits before resources are ready

- pkg/build/stage/git_mapping.go
Replace the relative dependency path with the absolute one in git repo.
Previously, the message used a relative path (stageDependencies value) and the warning was less informative.
```
WARNING: stage install dependency path <STAGE_DEPENDENCY_PATH> has not been found in own git
```
=>
```
WARNING: stage install dependency path "<ADD_PATH/STAGE_DEPENDENCY_PATH>" has not been found in own git
```
> [stapel, git] Update warn message when a stage dependency not found in git

- go.mod
`.Release.IsInstall` will be true until we successfully installed release..
https://github.com/werf/helm/pull/97
> Fix .Release.IsInstall for a release which has not been installed successfully yet

- pkg/deploy/helm/chart_extender/werf_chart.go
`.helm/files` for example will be published into the bundle.
Fixes https://github.com/werf/werf/issues/3593
> feat(bundles): add ability to publish miscellaneous files existing in .helm dir

- go.mod
- go.sum
- pkg/deploy/helm/chart_extender/helpers/service_values.go
- pkg/deploy/helm/extra_annotations_and_labels_post_renderer.go
- pkg/util/yaml.go
Only for helm-related part, do not change legacy ansible pkg which uses ghodss.
> [helm] Remove usage of ghodss yaml, use sigs.k8s.io/yaml instead

- pkg/host_cleaning/images.go
- pkg/host_cleaning/local_docker_server.go
Remove images that do not have any tags and digests instead of dangling.
**Details**
Images pulled by full name `REPO:TAG@DIGEST` do not have tags and are considered dangling.
> fix(cleanup): host cleanup removes base images pulled by full name (REPO:TAG@DIGEST)

- .github/workflows/trdl_releaser.yml
- .gitignore
- trdl.yaml
Use https://github.com/werf/trdl-actions library to release werf with trdl server.
> ci: trdl releaser workflow

- pkg/cleaning/cleanup.go
- pkg/docker_registry/docker_hub.go
- pkg/docker_registry/github_packages.go
- pkg/docker_registry/harbor.go
- pkg/docker_registry/quay.go
```
Error: unable to remove repo image meta-798e6f97_3892ca702554b834870c7f00f3da90d6087ee823_29f5d2380bb079154881174870da00972fb1050e79179638533ffd41-1628241422196: gitHub packages forbidden: GET https://api.github.com/orgs/ORG/packages/container/actions-test%!F(MISSING)test/versions?page=REDACTED&per_page=REDACTED: unexpected status code 403 Forbidden (body: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/packages#get-all-package-versions-for-a-package-owned-by-an-organization"})
You should specify a token with delete:packages and read:packages scopes to remove package versions.
Check --repo-github-token option.
Be aware that the token provided to GitHub Actions workflow is not enough to remove package versions.
Read more …
```
> chore: fix cleanup deletion error format

- .github/workflows/tests_cleaner.yml
rel https://github.com/google-github-actions/setup-gcloud#use-google-github-actionssetup-gcloud
> ci(actions): fix setup-gcloud not available

- go.mod
- go.sum
- pkg/docker_registry/github_packages.go
The workaround is no longer needed.
rel https://github.community/t/pagination-when-listing-image-tags-does-not-work/194586
> chore(container_registry): ghcr.io tag list pagination has been fixed

- scripts/lib/release/build.sh
- scripts/werf-builder/Dockerfile
- scripts/werf-builder/build.sh
- scripts/werf-builder/publish.sh
- trdl.yaml
Use golang 1.17 and alpine based image.
> infra: update ghcr.io/werf/builder image building scripts and use latest builder in the trdl.yaml

- pkg/true_git/service_branch.go
Add --no-verify option creating service commit to skip the pre-commit and commit-msg hooks.
> fix(dev): commit hooks are executed when creating service commits

- pkg/true_git/ls_tree/result.go
Parameter order in the function was mixed up.
Possible error when using a submodule with a name that is not equal to the path:
```
Error: unable to read dockerfile "<submodule_name>/Dockerfile": unable to get tree entry <submodule_name>/Dockerfile
```
> fix(git_repo): unable to get a configuration file from a submodule

- pkg/git_repo/local.go
- pkg/true_git/service_branch.go
- pkg/true_git/service_branch_test.go
- pkg/true_git/status/result.go
- do nothing if there are no changes
- avoid the time-consuming execution of the "Updating files" and "Refresh index" phases of git
> fix(dev): creating service commits in large projects is too slow

- scripts/build_release_v3.sh
- scripts/werf-builder/Dockerfile
- scripts/werf-builder/build.sh
- scripts/werf-builder/publish.sh
- trdl.yaml
- New script scripts/build_release_v3.sh uses gox build tool to create release binaries.
- Tag werf-builder images by the commit in the scripts/werf-builder/{build|publish}.sh scripts.
- Update trdl.yaml to use new build tool and new base image.
> infra: use gox parallel release build tool, update base builder image

- cmd/werf/bundle/publish/publish.go
- cmd/werf/common/synchronization.go
- pkg/storage/synchronization.go
Hello.
On latest version, when `WERF_SYNCHRONIZATION` is specified in short fomat(like `kubernetes://default`) i get error, if i'm using custom kubeconfig path(defined over `KUBECONFIG` env var).
> Fixing kubernetes synchronization short notation bug

- docs/site/.werf/artifacts/channels_versions.json
- docs/site/_includes/installation/binary_linux.md
- docs/site/_includes/installation/binary_macos.md
- docs/site/_includes/installation/binary_windows.md
- docs/site/pages_en/installation.md
- docs/site/pages_ru/installation.md
- scripts/build_release_v3.sh
- fix binary download urls: tuf.werf.dev -> tuf.werf.io and remove 'v' letter;
- store release binaries in the bin dir for trdl.
> fix: broken release building script, fix site installation instructions

- .github/workflows/daily_tests.yml
- .github/workflows/tests.yml
1.16, 1.17 and 1.18 has been reached official end of support date.
> test: disabled old k8s versions

- go.sum
Fix broken go build, add missing modules into go.sum
> test: fix kube config connection when KUBECONFIG variable set (2)

- pkg/build/stage/imports.go
Changes in files were not taken into account if paths were not specified explicitly:
```
import:
- ...
includePaths:
- dir/file
```
or using asterisks:
```
import:
- ...
includePaths:
- dir/*
```
Thus, imports that contained `includePaths` or `excludePaths` with directories did not work correctly and related changes did not trigger importing of actual files.
> fix(stapel): changes in directories of import.include/excludePaths not triggered import

- integration/pkg/suite_init/container_registry_per_implementation_data.go
```
/home/ubuntu/actions-runner/_work/_tool/go/1.14.15/x64/src/runtime/panic.go:212
Full Stack Trace
github.com/werf/werf/pkg/docker_registry.IsAzureCrRepositoryNotFoundErr(0x0, 0x0, 0xc000128010)
/home/ubuntu/actions-runner/_work/werf/werf/pkg/docker_registry/azure_cr.go:30 +0x2c
```
> tests: fix invalid memory address or nil pointer dereference

- cmd/werf/dismiss/dismiss.go
- cmd/werf/helm/migrate2to3.go
- docs/documentation/_includes/reference/cli/werf_dismiss.md
- docs/documentation/_includes/reference/cli/werf_helm_migrate2to3.md
- docs/documentation/_includes/reference/cli/werf_helm_show_all.md
- docs/documentation/_includes/reference/cli/werf_helm_show_chart.md
Added missing --insecure-helm-dependencies flag into werf-dismiss command.
> fix: panic in dismiss command, helm regsitry client initialization failure

- pkg/build/build_phase.go
- pkg/build/image.go
- pkg/container_runtime/buildah_runtime.go
- pkg/container_runtime/docker_server_runtime.go
- pkg/container_runtime/interface.go
- pkg/container_runtime/legacy_base_image.go
- pkg/container_runtime/legacy_interface.go
- pkg/container_runtime/legacy_stage_image.go
- pkg/container_runtime/legacy_stage_image_container.go
- pkg/storage/docker_server_stages_storage.go
- pkg/storage/manager/storage_manager.go
- pkg/storage/repo_stages_storage.go
- pkg/storage/stages_storage.go
1. Removed excess container_runtime.DockerImage and container_runtime.Image. Use LegacyImageInterface instead for legacy container-runtime operations.
2. Make build conveyor indepdenent of DockerServerRuntime implementation, use generic ContainerRuntime interface instead everywhere.
3. Renamed legacy GetImageInspect to GetImageInfo and refactored LegacyImageInterface and all other code to use this new method.
4. Added necessary Tag and Push operations into the ContainerRuntime interface.
> feat(buildah): refactor container-runtime interface and fix usage of runtime

- go-build.sh
- go.mod
- pkg/buildah/docker_with_fuse_buildah.go
- pkg/buildah/native_rootless_buildah_linux.go
- pkg/container_runtime/buildah_runtime.go
- pkg/container_runtime/docker_server_runtime.go
```
containers_image_openpgp: Use a Golang-only OpenPGP implementation for signature verification instead of the default cgo/gpgme-based implementation; the primary downside is that creating new signatures with the Golang-only implementation is not supported.
```
> feat(buildah): fix go-build, do not use gpgme, use opengpg golang impl. instead

- cmd/werf/common/container_runtime.go
- pkg/build/conveyor.go
- pkg/build/stage/dockerfile.go
- pkg/container_runtime/buildah_runtime.go
- pkg/container_runtime/docker_server_runtime.go
- pkg/container_runtime/legacy_stage_image.go
- pkg/container_runtime/legacy_stage_image_container.go
- pkg/image/info.go
* Guard all legacy image methods to work only when DockerServer runtime is used.
* Remove excess container-runtime convertions to DockerServer.
> feat(buildah): debug werf-build with buildah container runtime

- pkg/git_repo/gitdata/git_data_manager.go
- pkg/true_git/archive.go
This change enables working images building in the werf-build command with docker-with-fuse buildah runtime.
> feat(buildah): fix git-archives tar creation procedure to include parent directories of added files

- .gitignore
- cmd/buildah-test/main.go
- pkg/buildah/buildah.go
- pkg/buildah/buildah_test/Dockerfile.simple.1
- pkg/buildah/native_rootless_buildah_linux.go
Use containers/storage/pkg/reexec instead of docker/docker/pkg/reexec (typo).
> fix(buildah): fix native-rootless buildah mode init procedure

- cmd/werf/bundle/publish/publish.go
- pkg/slug/slug.go
Werf bundle publish command automatically generates chart.version metadata field, which equals 0.0.0-TIMESTAMP-SLUG(TAG), when TAG is not a valid semver by itself.
> fix(bundles): fix werf-bundle-publish command error when --tag contains underscore chars

- go.mod
- scripts/build_release.sh
- scripts/do_build_release.sh
- scripts/publish_release.sh
- trdl.yaml
* added script to manually build release in the docker;
* fixed invalid trdl.yaml build script;
* fixed old outdated publish script (do not use bintray).
> ci: fix 1.0 releaser workflows and scripts

- CHANGELOG.md
- cmd/werf/common/common.go
- cmd/werf/common/container_runtime.go
- pkg/build/conveyor.go
- pkg/buildah/native_rootless_buildah_linux.go
- pkg/docker/main.go
- pkg/docker_registry/generic_api.go
* Use "chroot" isolation instead of "rootless" in werf's native-rootless buildah mode.
* Fix initialization of werf process with reexec.
> feat(buildah): working native-rootless buildah mode inside docker container

- Makefile
- cmd/buildah-test/main.go
- go.mod
- pkg/buildah/buildah.go
- pkg/buildah/docker_with_fuse_buildah.go
- pkg/buildah/native_rootless_buildah_linux.go
- pkg/config/werf.go
- pkg/container_runtime/buildah_runtime.go
* Mounts of host files into the build containers is supported [check].
* Mount container root into the host and perform golang code file operations over this root [check].
* Small refactor of buildah pkg.
* Added project makefile with basic tasks: werf and buildah-test cmds build, lint, fmt, clean.
> feat(buildah-for-stapel): added buildah-test subcommand to experiment with buildah abilities for stapel

- pkg/docker_registry/api.go
- pkg/docker_registry/default.go
- pkg/docker_registry/generic_api.go
- pkg/storage/repo_stages_storage.go
These errors may occur when harbor configured to use S3 backend, which may respond with the following error:
```
GET https://domain/harbor/s3/object/name/prefix/docker/registry/v2/blobs/sha256/2d/3d8c68cd9df32f1beb4392298a123eac5
8aba1433a15b3258b2f3728bad4b7d1/data?X-Amz-Algorithm=REDACTED&X-Amz-Credential=REDACTED&X-Amz-Date=REDACTED&X-Amz-Expire
s=REDACTED&X-Amz-Signature=REDACTED&X-Amz-SignedHeaders=REDACTED: unsupported status code 404; body: <?xml version="1.0"
encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/harbor/s3/object/name/pr
efix/docker/registry/v2/blobs/sha256/3d/3d8c68cd9df32f1beb4392298a123eac58aba1433a15b3258b2f3728bad4b7d1/data</Resource>
<RequestId>c5bb943c-1e85-5930-b455-c3e8edbbaccd</RequestId></Error> …
```
> fix(cleanup): ignore harbor "unsupported 404 status code" errors

- pkg/build/publish_images_phase.go
- pkg/cleaning/images_purge.go
- pkg/docker_registry/api.go
- pkg/docker_registry/default.go
- pkg/storage/repo_stages_storage.go
These errors may occur when harbor configured to use S3 backend, which may respond with the following error:
```
GET https://domain/harbor/s3/object/name/prefix/docker/registry/v2/blobs/sha256/2d/3d8c68cd9df32f1beb4392298a123eac58aba1433a15b3258b2f3728bad4b7d1/data?X-Amz-Algorithm=REDACTED&X-Amz-Credential=REDACTED&X-Amz-Date=REDACTED&X-Amz-Expires=REDACTED&X-Amz-Signature=REDACTED&X-Amz-SignedHeaders=REDACTED: unsupported status code 404; body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/harbor/s3/object/name/prefix/docker/registry/v2/blobs/sha256/3d/3d8c68cd9df32f1beb4392298a123eac58aba1433a15b3258b2f3728bad4b7d1/data</Resource><RequestId>c5bb943c-1e85-5930-b455-c3e8edbbaccd</RequestId></Error>
```
> fix(cleanup, v1.1): ignore harbor "unsupported 404 status code" errors

- .gitignore
- Makefile
- cmd/werf/common/container_runtime.go
- pkg/build/conveyor.go
- pkg/buildah/base.go
- pkg/buildah/buildah.go
- pkg/buildah/docker_with_fuse_buildah.go
- pkg/buildah/native_rootless_buildah_linux.go
- pkg/buildah/types/isolation.go
- pkg/buildah/types/storageoptions.go
- pkg/buildah/types/storageoptions_linux.go
- pkg/util/linux_container.go
- test/e2e/build/build_test.go
- test/pkg/contruntime/base.go
- test/pkg/contruntime/basebuildah.go
- test/pkg/contruntime/docker.go
- test/pkg/contruntime/dockerwithfusebuildah.go
- test/pkg/contruntime/interface.go
- test/pkg/contruntime/nativerootlessbuildah.go
Done:
* Added native OCI rootless Buildah mode. Provides more isolation and security in comparison to chroot mode. Works only outside of containers.
* $WERF_BUILDAH_MODE instead of $WERF_CONTAINER_RUNTIME_BUILDAN for Buidah mode/isolation configuration.
* VFS storage driver now available in addition to OverlayFS for both native and docker-with-fuse Buildah modes. Configurable via $WERF_BUILDAH_STORAGE_DRIVER.
* Lots of bugfixes. Minor refactoring. Tests.
Work in progress:
Trying to get rid of a need in external configuration, external dependencies and work environment preparations to run `werf` in
Buildah mode, especially when running `werf` in containers. As of now no /etc/containers/* configs needed anymore, lots of 
configuration built-in, some autodetection/autoconfiguration …
> feat(buildah): native OCI rootless mode; vfs storage driver; bugfixes

- pkg/buildah/native_rootless_buildah_linux.go
- scripts/werf-in-docker/alpine.Dockerfile
- scripts/werf-in-docker/centos.Dockerfile
- scripts/werf-in-docker/fedora.Dockerfile
- scripts/werf-in-docker/ubuntu.Dockerfile
Alpine, Ubuntu, CentOS, Fedora-based images to run werf in Buildah mode
in them. External dependencies for werf were minimized as much as
possible previously, no improvements here.
> feature(buildah): 4 new base Docker images to run werf

- docs/documentation/_data/sidebars/_documentation.yml
- docs/documentation/_data/sidebars/documentation.yml
- docs/documentation/pages_en/advanced/buildah_mode.md
- docs/documentation/pages_en/advanced/ci_cd/run_in_container/how_it_works.md
- docs/documentation/pages_en/internals/build_process.md
* separate advanced article about buildah mode;
* build process refers to buildah mode article in advanced;
* how-it-works article only describes 3 variants to run werf+buildah in containers and troubleshooting.
> docs(buildah): improve buildah docs

- scripts/werf-in-image/fedora.Dockerfile
Might fix an issue with microdnf error about being unable to create pthreads.
> fix(buildah): switch fedora-minimal image to fedora image

- pkg/deploy/helm/tiller.go
Log internal tiller messages on release failure only in verbose mode.
> fix(deploy): remove debug-info on release failure from default logger

- pkg/docker_registry/aws_ecr.go
- pkg/docker_registry/azure_cr.go
- pkg/docker_registry/default.go
- pkg/docker_registry/docker_hub.go
- pkg/docker_registry/gcr.go
- pkg/docker_registry/github_packages.go
- pkg/docker_registry/gitlab_registry.go
- pkg/docker_registry/harbor.go
- pkg/docker_registry/quay.go
Added warning when an error occurs which is known to be an error from the harbor.
This warning instructs user to specify --repo-container-registry=harbor option (possibly forgotten).
> fix(harbor): detect usage of harbor without --repo-container-registry=harbor option

- cmd/werf/cr/login/login.go
- cmd/werf/cr/logout/logout.go
- cmd/werf/helm/secret/common/common.go
- cmd/werf/helm/secret/decrypt/decrypt.go
- cmd/werf/helm/secret/encrypt/encrypt.go
- cmd/werf/main.go
- docs/_data/sidebars/_cli.yml
- docs/_data/sidebars/documentation.yml
- docs/_includes/reference/cli/werf_cr.md
- docs/_includes/reference/cli/werf_cr.short.md
- docs/_includes/reference/cli/werf_cr_login.md
- docs/_includes/reference/cli/werf_cr_login.short.md
- docs/_includes/reference/cli/werf_cr_logout.md
- docs/_includes/reference/cli/werf_cr_logout.short.md
- docs/pages_en/reference/cli/overview.md
- docs/pages_en/reference/cli/werf_cr.md
- docs/pages_en/reference/cli/werf_cr_login.md
- docs/pages_en/reference/cli/werf_cr_logout.md
- go.mod
- go.sum
* `werf cr login REGISTRY` — to login;
* `werf cr logout REGISTRY` — to logout.
There will be more `werf cr` commands to work with container registries, like getting manifests, listing tags and deleting tags (`cr` stands for "container registry").
> feat: Added login and logout cli commands for container registry

- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/converge/converge.go
- cmd/werf/helm/get_autogenerated_values.go
- cmd/werf/helm/helm.go
- cmd/werf/render/render.go
- pkg/deploy/helm/chart_extender/helpers/service_values.go
New Values available:
* `$.Values.werf.commit.hash`
* `$.Values.werf.commit.date.human`
* `$.Values.werf.commit.date.unix`
> feat(deploy): expose commit info in Helm templates

- docs/.helm/templates/20-ingress.yaml
Update Ingress resources API version to get rid of using deprecated CRD APIs on the site.
> site: update ingress API version

- pkg/true_git/work_tree.go
- pkg/util/lines.go
Automatically invalidate inconsistent service git worktree which werf creates in the ~/.werf/local_cache/git_worktrees.
> fix: "unable to switch worktree" in gitlab

- .gitignore
* fix(helm-v3): fixed panic in 'werf helm-v3 *' commands
* fix(helm): change broken default charts repo (use bitnami).
* fix(cleanup): ignore harbor "unsupported 404 status code" errors
These errors may occur when harbor configured to use S3 backend, which may respond with the following error:
```
GET https://domain/harbor/s3/object/name/prefix/docker/registry/v2/blobs/sha256/2d/3d8c68cd9df32f1beb4392298a123eac58aba1433a15b3258b2f3728bad4b7d1/data?X-Amz-Algorithm=REDACTED&X-Amz-Credential=REDACTED&X-Amz-Date=REDACTED&X-Amz-Expires=REDACTED&X-Amz-Signature=REDACTED&X-Amz-SignedHeaders=REDACTED: unsupported status code 404; body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not …
```
> fix: add lost fixes from v1.1.23+fix51, v1.1.23+fix52 and v1.1.23+fix53

- multiwerf.json
- trdl_channels.yaml
> chore(channels): v1.2 alpha to 1.2.69, beta and ea to 1.2.67+fix1, stable to 1.2.62+fix1, rock-solid to 1.2.59+fix1

- pkg/cleaning/cleanup.go
> fix: add werf-cleanup command warning when no kube configs available

- go.sum
- pkg/cleaning/cleanup.go
Remove import checksum-based policy and, as a result, use only git history-based policy for such images.
> feat(cleanup): optimization of cleaning images which are used when importing

- pkg/build/build_phase.go
- pkg/storage/manager/storage_manager.go
~* By default in 'werf converge', 'werf bundle publish', 'werf bundle export', 'werf export', 'werf render' and 'werf run' commands.~
~* In the 'werf build' command only when `--verify-built-images` option specified.~
* Respect --skip-build option when final-repo is used:
* do not push into final repo built images from the primary repo;
* only check stage image existance in the final repo in such case.
> fix(build): do not store images into final repo when --skip-build is set

- pkg/util/archive.go
Context extraction error may occur when an archive contains file node without parent directory node.
Fixes https://github.com/werf/werf/issues/4260.
> fix: context extraction error

- .github/workflows/docs_tests.yml
> ci(docs): fix "internally linking to kubernetes.io/cluster-service=true, which does not exist"

- pkg/container_backend/buildah_backend.go
Run build of stapel image with buildah with the following command:
```
WERF_BUILDAH_MODE=native-rootless WERF_BUILDAH_FOR_STAPEL_ENABLED=1 werf build --repo REPO
```
> fix(stapel-to-buildah): working build of 'from' stage

- pkg/build/builder/ansible.go
- pkg/build/builder/shell.go
- pkg/build/stage/base.go
- pkg/build/stage/from.go
- pkg/container_backend/buildah_backend.go
* Working beforeInstall, install, beforeSetup, setup stages building.
* Run each instruction from werf.yaml in the separate shell session for now.
* Fixed mountpoints cleaning in the 'from' stage.
* Added usage of mounts for user stages.
> feat(stapel-to-buildah): support user stages and mounts

- pkg/build/stage/dependencies.go
By default xargs splits input files list by "space or newline", use "newline" delimiter instead.
> fix(dependencies): broken imports checksum when files names contain spaces

- pkg/cleaning/cleanup.go
- pkg/cleaning/purge.go
- pkg/cleaning/stage_manager/manager.go
- pkg/storage/manager/storage_manager.go
Keep set of custom tags without associated existent stage while any of them used in Kubernetes.
> fix(cleanup): manage custom tags that do not have associated existent stages

- go.mod
- go.sum
* Rework dry-run resource lists preparations, refs https://github.com/werf/3p-helm/pull/148.
* Update helm 3.8.0 to 3.8.1.
> fix(server-dry-run): possible fix for 'unable to recognize ...: no matches for kind ... in version ...' (part 2)

- go.mod
- go.sum
* Rework dry-run resource lists preparations, refs https://github.com/werf/3p-helm/pull/148.
* Update helm 3.8.0 to 3.8.1.
> [v1.2.80] fix(server-dry-run): possible fix for 'unable to recognize ...: no matches for kind ... in version ...' (part 2)

- go.mod
- go.sum
* Rework dry-run resource lists preparations, refs https://github.com/werf/3p-helm/pull/148.
* Update helm 3.8.0 to 3.8.1.
> [v1.2.83] fix(server-dry-run): possible fix for 'unable to recognize ...: no matches for kind ... in version ...' (part 2)

- cmd/werf/kube_run/kube_run.go
Failed with error:
```
Error: error running pod: fork/exec werf-in-a-user-namespace: no such file or directory
```
> fix(kube-run): didn't work in Native Buildah mode

- pkg/deploy/helm/chart_extender/werf_chart.go
By default werf uses `project` directive value as a `{{ .Chart.Name }}` when no .helm/Chart.yaml exist.
User can redefine chart name with the following `.helm/Chart.yaml`:
```
apiVersion: v2
name: custom-chart-name
```
Fixes https://github.com/werf/werf/issues/4376
> fix: .helm/Chart.yaml chart name redefines project name from werf.yaml

- pkg/true_git/work_tree.go
Invalidation loop of cached git worktree on every werf invocation may occur when WERF_HOME (`~/.werf`) is a symlink to another volume.
> fix: git worktree switch invalidation loop

- cmd/werf/render/render.go
- docs/_includes/reference/cli/werf_kubectl_get.md
- docs/_includes/reference/cli/werf_render.md
- go.mod
- go.sum
* Pass either `-s templates/*ingress*.yaml` path (helm compatible) or use `-s .helm/templates/*ingress*.yaml` with full path in local filesystem (with bash completion convenience).
* `export-values` in subcharts and sub-subcharts (and sub-sub-subcharts etc.) are processed now as expected.
Refs https://github.com/werf/3p-helm/pull/162
Refs https://github.com/werf/3p-helm/pull/161
> [v1.2.80] feat: support --show-only|-s helm-style render option + export-values chaining

- cmd/werf/render/render.go
- docs/pages_ru/advanced/ci_cd/github_actions.md
- docs/pages_ru/internals/how_ci_cd_integration_works/github_actions.md
- go.mod
- go.sum
* Pass either `-s templates/*ingress*.yaml` path (helm compatible) or use `-s .helm/templates/*ingress*.yaml` with full path in local filesystem (with bash completion convenience).
* `export-values` in subcharts and sub-subcharts (and sub-sub-subcharts etc.) are processed now as expected.
Refs https://github.com/werf/3p-helm/pull/162
Refs https://github.com/werf/3p-helm/pull/161
> feat: support --show-only|-s helm-style render option + export-values chaining

- go.mod
- go.sum
Error was introduced in the https://github.com/werf/3p-helm/pull/161, which is temporarily reverted now (https://github.com/werf/3p-helm/pull/163).
> fix: broken export-values

- scripts/werf-builder/Dockerfile
- trdl.yaml
Rebuilt werf builder image: registry.werf.io/werf/builder:adfeb920ae92a9c07c78a3b65ace081aff883df5@sha256:7e55db7338976dff07a611a2bf9c14f50836e8ef081efca05155448ec6693ce5
> chore(trdl): update werf builder image to use golang 1.18

- integration/suites/deploy/helm_values_test.go
- pkg/cleaning/allow_list/kubernetes.go
- pkg/cleaning/cleanup.go
Images that are used by completed or failed Jobs could be safely removed by the cleanup, because Job is a oneshot resource.
Refs https://github.com/werf/werf/issues/4411
> feat(cleanup): optimize cleanup deployed resources images scanning regarding Jobs

- pkg/build/build_phase.go
- pkg/build/image.go
- pkg/container_backend/buildah_backend.go
- pkg/container_backend/legacy_interface.go
- pkg/container_backend/legacy_stage_image.go
- pkg/storage/manager/storage_manager.go
```
goroutine 1623 [running]:
github.com/werf/werf/pkg/build/stage.(*BaseStage).getServiceMountsFromLabels(0xc0016ed300?, 0xc001b00100)
/home/distorhead/werf/pkg/build/stage/base.go:283 +0xc4
github.com/werf/werf/pkg/build/stage.(*BaseStage).getServiceMounts(0xc000e50d80?, 0x3bde920?)
/home/distorhead/werf/pkg/build/stage/base.go:274 +0x36
github.com/werf/werf/pkg/build/stage.(*FromStage).PrepareImage(0xc0014c5140, {0xc001508420?, 0x3be22c8?}, {0x3be06b0, 0xc0006ac2c0}, {0x3bde920, 0xc000f622e0}, 0x0?, 0xc001b01640)
/home/distorhead/werf/pkg/build/stage/from.go:82 +0x194
github.com/werf/werf/pkg/build.(*BuildPhase).prepareStageInstructions(0xc00188a2d0, {0x3bcc730?, 0xc001858300}, 0xc001508420, {0x3be22c8, 0xc0014c5140})
/home/distorhead/werf/pkg/build/build_phase.go:693 +0xdff
...
``` …
> fix(cache-repo): panic when using cache repo and fromImage directive

- pkg/storage/manager/storage_manager.go
```
panic: interface conversion: container_backend.ContainerBackend is *container_backend.BuildahBackend, not *container_backend.DockerServerBackend
goroutine 29 [running]:
github.com/werf/werf/pkg/storage/manager.(*StorageManager).FetchStage.func1({0x3be8f20, 0xc00145cae0})
/home/distorhead/werf/pkg/storage/manager/storage_manager.go:438 +0xb97
github.com/werf/werf/pkg/storage/manager.(*StorageManager).FetchStage(0xc0014660b0, {0x3bcc950?, 0xc00162e0f0}, {0x3bdeb40?, 0xc000a968a0}, {0x3be2310, 0xc000c02ff0})
/home/distorhead/werf/pkg/storage/manager/storage_manager.go:516 +0x1738
...
```
Removed legacy interface conversion which is not needed now.
> fix(cache-repo): panic when using cache-repo and building images existing in cache

- integration/suites/bundles/bundles_test.go
- integration/suites/bundles/suite_test.go
- pkg/deploy/helm/chart_extender/bundle_test.go
- pkg/deploy/helm/chart_extender/stage_suite_test.go
* test bundle-apply with the --secret-values param in the integration test;
* test secret values loading in unit test of chart-extender.
> test(bundles): integration and unit test for secret-values feature in bundles

- pkg/deploy/helm/chart_extender/chart_dependencies_loader.go
Error may occur when concurrent processes fulfill cache directory.
Fixed by additional check of directory existance after lock has been acquired.
> fix(helm): fix 'error preparing chart dependencies... file exists'

- pkg/build/dockerfile_helpers/dockerfile_helpers.go
- pkg/build/stage/dependencies_test.go
- pkg/build/stage/dockerfile.go
- pkg/build/stage/dockerfile_test.go
- pkg/build/stage/stubs_test.go
When the following instruction used:
RUN --mount=type=bind,from=build,source=/usr/local/test_project/dist,target=/usr/test_project/dist \
cp -v /usr/test_project/dist/prog.py /usr/local/bin/prog
— change image digest when `from=build` stage digest has changed.
> fix(dockerfile): support RUN with --mount from another stage

- go.mod
- go.sum
Refs: https://github.com/werf/kubedog/pull/253
Refs: https://github.com/kubernetes/client-go/issues/1109
> fix(helm): `unable to recognize "": no matches for kind "..." in version "..."` errors when base64 kubeconfig used

- go.mod
- go.sum
Refs: https://github.com/werf/kubedog/pull/253
Refs: https://github.com/kubernetes/client-go/issues/1109
> [v1.2.109] fix(helm): `unable to recognize "": no matches for kind "..." in version "..."` errors when base64 kubeconfig used

- cmd/werf/helm/helm.go
* Initialize global 'werf helm *' flags early, the same way as original helm does.
* Fix 'werf helm PLUGIN' not uses --namespace param.
* Fix 'werf helm *' commands not to print help on command failure.
Fixes https://github.com/werf/werf/issues/4524
> fix(helm): fix 'werf helm *' commands to correctly initialize namespace

- cmd/werf/bundle/apply/apply.go
- cmd/werf/bundle/download/download.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/bundle/render/render.go
- docs/_includes/reference/cli/werf_bundle_apply.md
- docs/_includes/reference/cli/werf_bundle_download.md
- docs/_includes/reference/cli/werf_bundle_render.md
* support --final-repo in the "werf bundle publish" param:
* store all images in the final repo and the bundle itself;
* remove --final-repo for "werf bundle apply/download/render" commands.
> fix(bundles): cleanup --final-repo param usage in bundles

- cmd/werf/bundle/apply/apply.go
- cmd/werf/bundle/render/render.go
- cmd/werf/converge/converge.go
- cmd/werf/dismiss/dismiss.go
- cmd/werf/helm/helm.go
- cmd/werf/helm/install.go
- cmd/werf/helm/template.go
- cmd/werf/helm/upgrade.go
- cmd/werf/render/render.go
- go.mod
- go.sum
- pkg/deploy/helm/annotations.go
- pkg/deploy/helm/external_deps_annotations_parser.go
- pkg/deploy/helm/external_deps_generator.go
- pkg/deploy/helm/gvk_builder.go
- pkg/deploy/helm/resources_waiter.go
- pkg/deploy/helm/stages_splitter.go
https://github.com/werf/3p-helm/pull/184
Added a way to express external dependencies for the new release resource,
so that we will wait until the external dependency resource is ready and
only after that we will try to deploy the new release resource.
Example usage:
```yaml
metadata:
annotations:
app1.external-dependency.werf.io/resource: "deployment/app1"
app1.external-dependency.werf.io/namespace: "default"  # optional
```
> feat(helm): external-dependencies for resources

- cmd/werf/ci_env/ci_env.go
WERF_ADD_ANNOTATION_WERF_RELEASE_CHANNEL="werf.io/release-channel=1.2 alpha"
> chore(ci-env): add extra annotation with werf release channel

- pkg/git_repo/base.go
- pkg/true_git/diff_parser.go
When "commits not present" error occurs during patch creation between FROM and TO commits,
then reset service git worktree to the FROM commit (which in turn fetches lost submodule commit)
and retry patch creation procedure.
> fix(submodules): auto handle "commits not present" patch creation error

- pkg/true_git/git_cmd_test.go
- pkg/true_git/service_branch_test.go
- pkg/true_git/work_tree.go
- pkg/true_git/work_tree_test.go
* Use git worktree add with double `--force` argument. From git docs:
> To add a missing but locked working tree path, specify --force twice.
* Added test for locked worktree case.
> fix(git-worktree): ignore existing locked service worktree when re-adding

- cmd/werf/common/telemetry.go
- cmd/werf/main.go
- pkg/telemetry/telemetry.go
- pkg/telemetry/telemetrywerfio.go
* Optionally write telemetry log to the provided WERF_TELEMETRY_LOG_FILE.
* Introduce ignore commands list, werf will not send telemetry for following commands:
* werf version;
* werf completion;
* werf synchronization.
* Lower overall sending timeout to 1sec.
> feat(telemetry): fix telemetry lags; telemetry logs; ignore commands list

- cmd/werf/common/telemetry.go
- pkg/telemetry/event.go
- pkg/telemetry/event_type.go
- pkg/telemetry/helpers.go
- pkg/telemetry/no_telemetrywerfio.go
- pkg/telemetry/telemetrywerfio.go
* Send CommandStarted event with additional data: list of cli options names that has been specified (without values).
* Send CommandExited event with exit code.
* Lower telemetry conn timeouts to 800ms.
> feat(telemetry): anonimized cli options usage, exit-code event, tune timeouts

- docs/pages_en/reference/deploy_annotations.md
- docs/pages_ru/reference/deploy_annotations.md
> docs(helm): `werf.io/no-activity-timeout` annotation

- pkg/git_repo/gitdata/gc.go
- pkg/git_repo/gitdata/git_archive.go
- pkg/git_repo/gitdata/git_data_entry.go
- pkg/git_repo/gitdata/git_patch.go
- pkg/git_repo/gitdata/git_repo.go
- pkg/git_repo/gitdata/git_worktree.go
Do not remove base cache dirs, which could result in recreation of these base dirs with root-permissions.
> fix(local-cache-cleanup): more correct GC for ~/.local_cache/git_* data

- pkg/telemetry/telemetry.go
Disable by explicitly setting WERF_TELEMETRY=0
> chore: enable telemetry by default

- pkg/container_backend/legacy_stage_image_container.go
werf overrides LD_LIBRARY_PATH to prevent unexpected behavior but only for Stapel with Docker-daemon builds.
fixes #4745
> fix(stapel): custom LD_LIBRARY_PATH in the base image might lead to failed builds

- pkg/build/builder/shell.go
- pkg/stapel/stapel.go
- Do not process the user's commands as service ones because all commands are executed as follows:
```
run service commands
export custom LD_LIBRARY_PATH from the base image (optional)
run the user's commands
```
- Remove useless shebang with stapel bash path from the script with the user's commands because re-execution of stapel bash with custom LD_LIBRARY_PATH might lead to a crash (e.g., segfault).
> fix(stapel): the user cannot use custom LD_LIBRARY_PATH with shell builder

- pkg/telemetry/telemetrywerfio.go
The user can define extra attributes for telemetry with environment variables (`WERF_TELEMETRY_EXTRA_ATTRIBUTE_<any>="<key>=<value>"`).
> chore(telemetry): support extra attributes

- .github/workflows/test_pr.yml
Workflow should always be run in order to Required jobs to function
properly.
> ci: always run test:pr workflow, but skip jobs if no changes

- pkg/buildah/common.go
- pkg/buildah/native_linux.go
- pkg/container_backend/buildah_backend.go
Those were inherited from the original container, which is not what we want
most of the time. Now they are always set to safe defaults, but only for
stages commands.
> fix(buildah): wrong UID/GID/workdir/entrypoint/cmd in stages

- pkg/deploy/helm/chart_extender/helpers/service_values.go
Make werf render work the same way without --repo param as with this param.
Closes https://github.com/werf/werf/issues/4659
> fix(render): do not set empty env in werf render without repo param

- go.mod
- go.sum
- pkg/deploy/helm/command_helpers/build_chart_dependencies.go
If unknown repository used in the `.helm/Chart.yaml` dependencies then `werf converge` command will work the same way as `helm dependency update` does — it does not require repositories to be registered in the helm and query all such repositories on demand.
If you need to pass credentials though you have to use `werf helm repo add` prior running converge. But it is ok, giving that regular chart repositories become obsolete in the face of OCI helm charts published into container registries — for such charts there is no need to perform `werf helm repo add`.
Closes https://github.com/werf/werf/issues/4190
Closes https://github.com/werf/werf/issues/4761
> feat(converge): do not require to helm-repo-add repositories

- cmd/werf/cleanup/cleanup.go
- cmd/werf/common/cleanup_namespaces_scan.go
- docs/_includes/reference/cli/werf_cleanup.md
Use werf cleanup `--scan-context-only` option (or `--kube-context` alias) or `WERF_SCAN_CONTEXT_ONLY` environment variable to scan for deployed images only in the specified kube config context. By default werf cleanup will scan all kube contexts available in the kube config.
> fix(cleanup): ignore WERF_KUBE_CONTEXT env var, support option --scan-context-only

- .github/workflows/_test_integration_per-k8s-version-and-container-registry.yml
- .github/workflows/_test_integration_per-k8s-version.yml
We somewhat broke werf for 1.20-, but won't plan to do anything with it
since its EOL.
> test(integration): don't run tests on K8s 1.19 anymroe

- cmd/werf/helm/lint.go
- cmd/werf/render/render.go
- docs/_includes/reference/cli/werf_helm_lint.md
- pkg/deploy/helm/chart_extender/helpers/service_values.go
- pkg/deploy/helm/chart_extender/werf_chart_stub.go
* `werf helm *` commands set stub empty string into .Values.global.env and .Values.werf.env.
* `werf helm lint` command respects --env / WERF_ENV param to allow more correct usage in CI/CD params due to the lack of `werf lint` command.
* `werf render` command behaves the same way as `werf converge` command: set .Values.global.env and .Values.werf.env to nil (not empty string).
Closes https://github.com/werf/werf/issues/4659
> fix(helm): restore 'werf helm *' commands behavior for an env value

- cmd/werf/bundle/copy/copy.go
- cmd/werf/common/repo_data.go
- docs/_includes/reference/cli/werf_bundle_copy.md
- go.mod
- go.sum
- pkg/deploy/bundles/addr.go
- pkg/deploy/bundles/addr_test.go
- pkg/deploy/bundles/bundle.go
- pkg/deploy/bundles/chart_helpers.go
- pkg/deploy/bundles/copy.go
- pkg/deploy/bundles/suite_test.go
- pkg/docker_registry/api.go
- pkg/docker_registry/interface.go
* `werf bundle copy` command:
* `--repo` param has been deprecated in favor of new `--from=ADDR` param
* `--tag` param has been deprecated in favor of new `--from=ADDR` param
* `--to-tag` param has been deprecated in favor of `--to=ADDR` param new format
* New `--from=ADDR` and `--to=ADDR` params accept addr in different formats:
* `archive:PATH_TO_ARCHIVE.tar.gz` — bundle archive
* `docker://registry.example.com/group/project` — remote bundle in container registry
* without explicitly specified schema address parsed also as a remote bundle in container registry
* Bundle archive has following structure:
* `chart.tar.gz` — regular helm chart archive
* `images/TAG.tar.gz` — dir contains all werf images referenced from chart values `.Values.werf.image.NAME`, named by tags
> feat(bundle): introduce bundle archive format, implement copy command to convert archive to registry and vice versa

- cmd/werf/bundle/download/download.go
- cmd/werf/bundle/export/export.go
> fix(bundles): deprecate bundle export/download commands in favor of new copy command abilities

- pkg/build/stage/docker_instructions.go
Respect CMD/ENTRYPOINT command in shell form.
> fix(buildah): different processing of CMD/ENTRYPOINT by Stapel and Buildah backend

- cmd/werf/common/common.go
- docs/_includes/reference/cli/werf_bundle_apply.md
- docs/_includes/reference/cli/werf_converge.md
- docs/_includes/reference/cli/werf_dismiss.md
- docs/_includes/reference/cli/werf_helm.md
- docs/_includes/reference/cli/werf_render.md
> fix(deploy): lower releases-history-max default to 5 releases (was 10)

- pkg/deploy/bundles/bundle_archive.go
- pkg/deploy/bundles/bundle_archive_writer.go
- pkg/deploy/bundles/chart_helpers.go
- pkg/deploy/bundles/copy_test.go
- pkg/deploy/bundles/remote_bundle.go
* Refactor bundle archive writer/reader to gzip/unzip image archives in write/read operations.
* Improve tests to check validity of chart to catch incorrect-values-bug.
> fix(bundles): bundle copy from archive to remote incorrect values

- cmd/werf/dismiss/dismiss.go
- go.mod
- go.sum
- pkg/deploy/helm/init.go
- pkg/deploy/lock_manager/lock_manager.go
* Better logging when checking existance of release and namespace.
* Fix case when release not exists, but namespace exists and --with-namespace option specified (previously namespace was not removed in such case).
* Do not create namespace when it was not existed before running werf-dismiss.
Refs https://github.com/werf/3p-helm/pull/218/commits
> fix(dismiss): rework uninstall-with-namespace procedure

- pkg/container_backend/buildah_backend.go
- test/e2e/build/complex_test.go
Imported directory is not renamed when includePaths param used.
> fix(buildah): import from image with rename not working when using includePaths

- trdl_channels.yaml
> chore(channels): rollback alpha, beta and ea to 1.2.175

- cmd/werf/converge/converge.go
- docs/_includes/reference/cli/werf_converge.md
By default `werf converge` command does not accept specific images positional params to enable building and verification of only specific images from the `werf.yaml`.
When `WERF_CONVERGE_ENABLE_IMAGES_PARAMS=1` is set it is possible to specify either positional images arguments or `--without-images` option:
```
export WERF_CONVERGE_ENABLE_IMAGES_PARAMS=1
werf converge IMAGE_A IMAGE_B [--without-images] [options]
```
This feature gate only needed due to historical compatibility issues with using positional arguments in converge command.
> fix(converge): feature gate for specific images params in werf-converge (due to compatibility issues)

- pkg/deploy/helm/chart_extender/bundle.go
- pkg/deploy/helm/chart_extender/werf_chart.go
* Only publish builtin helm chart files such as README.md, values.schema.json, LICENSE etc.
* Do not publish arbitrary files from .helm dir, because these could contain custom secret-values and other unnecessary files
* Do publish .helm/charts/CHART dir content in the case when CHART specified as a local dependency
> fix(bundles): fix subcharts dependencies not published, and excess files published into the bundle

- pkg/deploy/helm/chart_extender/bundle.go
.helm/files directory should be used to store various configuration files which can be included into resources templates with .Files.Get or .Files.Glob directives. .helm/files is widely used across official helm charts and bitnami helm charts, but it is just a convention directory.
> feat(bundles): publish .helm/files into bundle

- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/common/cmd_data.go
- cmd/werf/converge/converge.go
- cmd/werf/render/render.go
- docs/_includes/reference/cli/werf_bundle_export.md
- docs/_includes/reference/cli/werf_bundle_publish.md
- docs/_includes/reference/cli/werf_converge.md
- docs/_includes/reference/cli/werf_render.md
- pkg/deploy/helm/chart_extender/bundle.go
- pkg/deploy/helm/chart_extender/werf_chart.go
`--disable-default-values` and `--disable-default-secret-values` options supported for:
* werf bundle publish
* werf converge
* werf render
> feat: added options to disable usage of default values (and secret values)

- docs/pages_en/advanced/buildah_mode.md
- docs/pages_ru/advanced/buildah_mode.md
* Stapel and Dockerfile builders supported for buildah
* Kernel checks related instructions fixed
> docs(buildah): buildah-mode docs fixes

- pkg/deploy/helm/chart_extender/bundle.go
> fix(bundles): fix bundle-render and bundle-apply commands could not access .Values.werf.images service values

- pkg/deploy/helm/chart_extender/bundle.go
> [1.2.181] fix(bundles): fix bundle-render and bundle-apply commands could not access .Values.werf.images service values

- pkg/build/build_phase.go
- pkg/build/image/dockerfile.go
- pkg/build/stage/instruction/add.go
- pkg/build/stage/instruction/base.go
- pkg/build/stage/instruction/cmd.go
- pkg/build/stage/instruction/copy.go
- pkg/build/stage/instruction/entrypoint.go
- pkg/build/stage/instruction/env.go
- pkg/build/stage/instruction/expose.go
- pkg/build/stage/instruction/healthcheck.go
- pkg/build/stage/instruction/label.go
- pkg/build/stage/instruction/maintainer.go
- pkg/build/stage/instruction/on_build.go
- pkg/build/stage/instruction/run.go
- pkg/build/stage/instruction/shell.go
- pkg/build/stage/instruction/stop_signal.go
- pkg/build/stage/instruction/user.go
- pkg/build/stage/instruction/volume.go
- pkg/build/stage/instruction/workdir.go
- pkg/dockerfile/frontend/buildkit_dockerfile.go
This fixes panic when trying to use uninitialized build-context because of unimplemented UsesBuildContext method at the pkg/build/stage/instruction level. Also refactored pkg/build/stage/instruction a bit: common PrepareImage method implementation in Base.
> feat(staged-dockerfile): implement whether stage uses build-context correctly

- pkg/build/image/dockerfile.go
- pkg/build/stage/instruction/healthcheck.go
- pkg/build/stage/instruction/maintainer.go
- pkg/dockerfile/dockerfile_stage.go
- pkg/dockerfile/instruction.go
1. Panics occured in Healthcheck and Maintainer instructions because of nil param instead of corresponding backend-instruction.
2. Duplicates was in images-sets when several dockerfile-stage instructions refer to the same stage.
refs #2215
> fix(staged-dockerfile): panics on Healthcheck and Maintainer instructions and no duplicates in images-sets

- go.mod
- go.sum
- pkg/build/image/build_context_archive.go
- pkg/build/stage/instruction/add.go
- pkg/build/stage/instruction/add_test.go
- pkg/build/stage/instruction/base.go
- pkg/build/stage/instruction/cmd.go
- pkg/build/stage/instruction/copy.go
- pkg/build/stage/instruction/entrypoint.go
- pkg/build/stage/instruction/env.go
- pkg/build/stage/instruction/expose.go
- pkg/build/stage/instruction/healthcheck.go
- pkg/build/stage/instruction/label.go
- pkg/build/stage/instruction/maintainer.go
- pkg/build/stage/instruction/on_build.go
- pkg/build/stage/instruction/run.go
- pkg/build/stage/instruction/shell.go
- pkg/build/stage/instruction/stop_signal.go
- pkg/build/stage/instruction/user.go
- pkg/build/stage/instruction/volume.go
- pkg/build/stage/instruction/workdir.go
- pkg/buildah/common.go
- pkg/buildah/native_linux.go
- pkg/dockerfile/frontend/buildkit_dockerfile.go
- pkg/util/hashsum.go
* Refactored stage instructions: save backend instruction type by using generics.
* Implemented generic instruction "expansion" mechanism, which should resolve refs to docker dependency stages to built images refs
* Changed digests in all instructions: prepend field name when calculating field digest.
refs #2215
> feat(staged-dockerfile): implement COPY --from stage to image name expansion

- pkg/build/stage/instruction/add_test.go
- pkg/build/stage/instruction/cmd_test.go
- pkg/build/stage/instruction/copy_test.go
- pkg/build/stage/instruction/stubs_test.go
- pkg/dockerfile/frontend/buildkit_dockerfile.go
- pkg/dockerfile/instruction.go
First stage: standard expansion on dockerfile parsing stage.
Second stage: expand dependencies build-args.
* Added universal method for expansion any instruction, which would be needed for second-stage inspection, which mutates instruction data in place.
* Implemented meta-args expansion and per-stage args expansion.
> feat(staged-dockerfile): implement first stage of build-args expansion

- pkg/build/stage/git_mapping.go
Bug occurs when there are more than one git-mapping exists in the werf.yaml, and we create a patch with binary files. In such case there was patch-paths-list name conflict between different git-mappings.
> fix(build): fix git-patch-* stages mechanics when patches contains binaries

- pkg/build/build_phase.go
- pkg/build/image/dockerfile.go
- pkg/build/image/image.go
- pkg/build/stage/base.go
- pkg/build/stage/dependencies_utils.go
- pkg/build/stage/full_dockerfile.go
- pkg/build/stage/instruction/base.go
- pkg/build/stage/instruction/copy.go
- pkg/container_backend/instruction/run.go
- pkg/dockerfile/dockerfile.go
- pkg/dockerfile/dockerfile_stage.go
- pkg/dockerfile/frontend/buildkit_dockerfile.go
- pkg/dockerfile/frontend/shlex_expander.go
- pkg/dockerfile/instruction.go
- test/e2e/build/_fixtures/complex/state0/Dockerfile
- test/e2e/build/_fixtures/complex/state0/werf.yaml
- test/e2e/build/_fixtures/complex/state1/Dockerfile
- test/e2e/build/_fixtures/complex/state1/werf.yaml
- test/e2e/build/complex_test.go
Implemented 2-stage build-args expansion:
1. Expand all build-args except dependencies-args on early dockerfile parsing stage.
2. Expand dependencies-args when dependencies images names are available during image conveyor processing.
refs https://github.com/werf/werf/issues/2215
> feat(staged-dockerfile): support werf images dependencies build-args

- pkg/build/build_phase.go
- pkg/container_backend/buildah_backend.go
- pkg/container_backend/docker_server_backend.go
- pkg/container_backend/legacy_stage_image.go
- pkg/image/info.go
- pkg/image/stage.go
- pkg/util/copy.go
- Fix image descriptors copying: deep copy image.StageDescription and image.Info.
- Set final image info into report when final-repo specified.
- Fix inconsistent image rename in container backend implementations.
> fix(build): inconsistent report path when final-repo used

- pkg/build/build_phase.go
- pkg/container_backend/buildah_backend.go
- pkg/container_backend/docker_server_backend.go
- pkg/container_backend/legacy_stage_image.go
- pkg/image/info.go
- pkg/image/stage.go
- pkg/util/copy.go
- Fix image descriptors copying: deep copy image.StageDescription and image.Info.
- Set final image info into report when final-repo specified.
- Fix inconsistent image rename in container backend implementations.
> [1.2.181] fix(build): inconsistent report path when final-repo used

- pkg/build/build_phase.go
- pkg/container_backend/buildah_backend.go
- pkg/container_backend/docker_server_backend.go
- pkg/container_backend/legacy_stage_image.go
- pkg/image/info.go
- pkg/image/stage.go
- pkg/util/copy.go
- Fix image descriptors copying: deep copy image.StageDescription and image.Info.
- Set final image info into report when final-repo specified.
- Fix inconsistent image rename in container backend implementations.
> [1.2.184] fix(build): inconsistent report path when final-repo used

- pkg/build/build_phase.go
- pkg/container_backend/buildah_backend.go
- pkg/container_backend/docker_server_backend.go
- pkg/container_backend/legacy_stage_image.go
- pkg/image/info.go
- pkg/image/stage.go
- pkg/util/copy.go
- Fix image descriptors copying: deep copy image.StageDescription and image.Info.
- Set final image info into report when final-repo specified.
- Fix inconsistent image rename in container backend implementations.
> [1.2.186] fix(build): inconsistent report path when final-repo used

- scripts/werf-in-image/alpine.Dockerfile
- scripts/werf-in-image/centos.Dockerfile
- scripts/werf-in-image/fedora.Dockerfile
- scripts/werf-in-image/ubuntu.Dockerfile
Fix problem with git submodules fetching over ssh when running werf in the registry.werf.io/werf/werf image.
> fix: fix ssh not available in registry.werf.io/werf images

- scripts/werf-in-image/alpine.Dockerfile
- scripts/werf-in-image/centos.Dockerfile
- scripts/werf-in-image/fedora.Dockerfile
- scripts/werf-in-image/ubuntu.Dockerfile
This reverts commit 50454937890778b2ffe146195c2ccebb505791f6.
> Revert "fix: fix ssh not available in registry.werf.io/werf images"

- docs/_layouts/default.html
Adding Google Tag Manager include to the footer of documentation pages.
> docs: add Google Tag

- pkg/build/build_phase.go
- pkg/build/image/dockerfile.go
- pkg/build/image/image.go
- pkg/build/stage/base.go
- pkg/build/stage/instruction/add.go
- pkg/build/stage/instruction/add_test.go
- pkg/build/stage/instruction/base.go
- pkg/build/stage/instruction/cmd.go
- pkg/build/stage/instruction/cmd_test.go
- pkg/build/stage/instruction/copy.go
- pkg/build/stage/instruction/copy_test.go
- pkg/build/stage/instruction/entrypoint.go
- pkg/build/stage/instruction/env.go
- pkg/build/stage/instruction/expose.go
- pkg/build/stage/instruction/healthcheck.go
- pkg/build/stage/instruction/label.go
- pkg/build/stage/instruction/maintainer.go
- pkg/build/stage/instruction/on_build.go
- pkg/build/stage/instruction/run.go
- pkg/build/stage/instruction/shell.go
- pkg/build/stage/instruction/stop_signal.go
- pkg/build/stage/instruction/user.go
- pkg/build/stage/instruction/volume.go
- pkg/build/stage/instruction/workdir.go
- pkg/dockerfile/dockerfile_stage.go
* Do not store non-target Dockerfile stages in the final-repo, nor set custom tags on non-target stages.
* Changed staged-dockerfile builder digest calculation algorithm: do not use instruction number in digest input calculation, only instruction name.
refs https://github.com/werf/werf/issues/2215
> fix(staged-dockerfile): do not store non-target Dockerfile stages in the final-repo

- pkg/werf/main.go
Globally disable all lock-related messages in default output, only print 'Wait for locked ...' message in --verbose mode.
> fix: broken render output due to lock-related message

- pkg/deploy/helm/chart_extender/bundle.go
Set WERF_BUNDLE_SCHEMA_NONSTRICT=1 to include all files in the .helm into the published bundle.
> feat(bundle): allow non strict bundle publishing

- docs/_data/werf_yaml.yml
- docs/pages_en/usage/build/images.md
- docs/pages_ru/usage/build/images.md
- pkg/build/conveyor.go
- pkg/build/stage/conveyor.go
- pkg/build/stage/data_test.go
- pkg/build/stage/dependencies.go
- pkg/build/stage/dependencies_test.go
- pkg/build/stage/dependencies_utils.go
- pkg/build/stage/instruction/stubs_test.go
- pkg/build/stage/stubs.go
- pkg/config/dependency_import.go
- pkg/config/dependency_import_type.go
- pkg/config/raw_image_from_dockerfile_test.go
- pkg/config/raw_stapel_image_test.go
ImageID mode uses local docker image id which is useless and should be deprecated. ImageDigest mode uses manifest checksum (repo-digest) of image published into container registry.
> fix(dependencies): introduce ImageDigest mode, deprecate ImageID mode

- cmd/werf/build/main.go
- cmd/werf/bundle/apply/apply.go
- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/common/cmd_data.go
- cmd/werf/common/common.go
- cmd/werf/common/conveyor_options.go
- cmd/werf/converge/converge.go
- cmd/werf/render/render.go
- docs/_includes/reference/cli/werf_build.md
- docs/_includes/reference/cli/werf_bundle_apply.md
- docs/_includes/reference/cli/werf_bundle_export.md
- docs/_includes/reference/cli/werf_bundle_publish.md
- docs/_includes/reference/cli/werf_converge.md
- docs/_includes/reference/cli/werf_helm_install.md
- docs/_includes/reference/cli/werf_helm_rollback.md
- docs/_includes/reference/cli/werf_helm_template.md
- docs/_includes/reference/cli/werf_helm_upgrade.md
- docs/_includes/reference/cli/werf_kubectl_get.md
- docs/_includes/reference/cli/werf_render.md
- go.mod
- go.sum
--build-report-path does the same as --report-path and deprecates it
> feat: add --deploy-report-path, --build-report-path

- cmd/werf/helm/helm.go
- pkg/deploy/helm/chart_extender/chart_dependencies_loader.go
- pkg/deploy/helm/command_helpers/build_chart_dependencies.go
1. fix(helm-dependencies): automatically fill ~/.werf/local_cache on 'werf helm dependency update' command
2. fix(helm-dependencies): enable loading of .helm/charts/CHART-VERSION.tgz charts. Do not download into ~/.werf/local_cache those dependencies charts which are listed in the .helm/Chart.lock and already exists in the .helm/charts directory.
> fix(helm-dependencies): enable loading of .helm/charts/CHART-VERSION.tgz charts; enable werf cache on deps update

- docs/pages_en/usage/deploy/deployment_order.md
Get rid of the RU snippet in the EN documentation (as per this [message](https://t.me/werf_io/658) in the Telegram channel).
> [docs] translate RU text in EN docs

- pkg/deploy/helm/chart_extender/bundle.go
- pkg/deploy/helm/chart_extender/bundle_test.go
- pkg/deploy/helm/chart_extender/werf_chart.go
* Include all files from .helm/ (.helm/secret-values.yaml also included) when publishing bundle into the container registry.
* Enable decryption of secret-values.yaml packed with the bundle during 'werf bundle apply' invocation.
> feat(bundles): enable secrets for bundle publish and apply

- pkg/build/image/images_sets.go
Fix images tree merging procedure in the case when merging multistaged dockerfile images sets.
> fix(staged-dockerfile): fix panic which occurs when using dependencies between images with multistages

- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/bundle/render/render.go
- cmd/werf/converge/converge.go
- cmd/werf/render/render.go
- docs/_includes/reference/cli/werf_bundle_export.md
- docs/_includes/reference/cli/werf_bundle_render.md
- pkg/deploy/helm/chart_extender/bundle.go
- pkg/deploy/helm/chart_extender/helpers/chart_extender_values_merger.go
- pkg/deploy/helm/chart_extender/helpers/secrets/chart_secrets_loader.go
- pkg/deploy/helm/chart_extender/helpers/secrets/secrets_runtime_data.go
- pkg/deploy/helm/chart_extender/helpers/util.go
- pkg/deploy/helm/chart_extender/werf_chart.go
- pkg/deploy/helm/chart_extender/werf_subchart.go
Decode secret-values.yaml included into the bundle when converging a werf project with bundle enabled as a chart dependency.
> feat(bundles): allow usage of bundles with included secret-values as oci chart dependencies

- cmd/werf/docs/replacers/kubectl/kubectl.go
- cmd/werf/docs/replacers/kubectl/kubectl_docs.go
- cmd/werf/docs/replacers/kubectl/kubectl_test.go
- docs/_includes/reference/cli/werf_kubectl_alpha_auth_whoami.md
- docs/_includes/reference/cli/werf_kubectl_events.md
- docs/_includes/reference/cli/werf_kubectl_get.md
After updating the dependencies, some `kubectl` commands changed, which led to a crash of unit tests — the generator ignored them and didn't add documentation.
Added replacers for `kubectl` commands:
* `events`;
* `token`;
* `whoami`.
Fixed the replacer for the `get` command.
> Fix documentation generator

- pkg/build/stage/stapel_docker_instructions.go
Make dockerInstructions stapel stage digest fully compatible between different container-backends (buildah or docker-server).
> fix(buildah): usage of docker.exactValues affects digest the same way for buildah and docker-server backends

- pkg/build/build_phase.go
- pkg/build/image/image_tree.go
Only first specified target platform will be used during converge, so publish commit-stageID metadata only for this first target platform image.
Also added assertion to check all final built images built for all target platforms and there is no mismatch between Image.TargetPlatform setting and target platforms.
> fix(multiarch): do not override image metadata for secondary platforms

- pkg/build/build_phase.go
- pkg/build/image/image_tree.go
Only first specified target platform will be used during converge, so publish commit-stageID metadata only for this first target platform image.
Also added assertion to check all final built images built for all target platforms and there is no mismatch between Image.TargetPlatform setting and target platforms.
> fix(multiarch): do not override image metadata for secondary platforms [1.2.214]

- pkg/build/build_phase.go
- pkg/build/image/image_tree.go
Only first specified target platform will be used during converge, so publish commit-stageID metadata only for this first target platform image.
Also added assertion to check all final built images built for all target platforms and there is no mismatch between Image.TargetPlatform setting and target platforms.
> fix(multiarch): do not override image metadata for secondary platforms [1.2.217]

- pkg/build/build_phase.go
- pkg/build/image/image_tree.go
- pkg/build/image/multiplatform_image.go
Introduced MultiplatformImage descriptor to manage multiplatform images and maintain list of multiplatform images in the ImagesTree primitive.
> fix(multiarch): publish git metadata for multiplatform mode images

- pkg/build/stage/dependencies.go
- pkg/path_matcher/common.go
- pkg/util/path.go
- pkg/util/path_test.go
includePaths/excludePaths were mishandled if their file or directory name contained a glob. E.g.: "directory/pathprefix-*".
> fix(stapel/imports): processing of includePaths/excludePaths with globs in file/directory name

- docs/Gemfile
- docs/Gemfile.lock
- docs/_config.yml
- Pin jekyll
- Pin jekyll-sass-converter to older 2.0 version
- Remove assets.precompile (fix for jekyll-assets plugin to work in updated jekyll/sprockets)
> fix: update ruby gems

- pkg/build/build_phase.go
- pkg/docker_registry/interface.go
- pkg/storage/local_stages_storage.go
- pkg/storage/primary_stages_storage.go
- pkg/storage/repo_stages_storage.go
Fixed panic and incorrect publishing of manifest list in case of custom tags usage. Now first publish manifest list by digest, then post custom tag as an alias to this digest tag.
> fix(multiarch): custom tags not working

- integration/suites/build/stapel_image/build_phase/build_phase_test.go
- integration/suites/build/stapel_image/git/stages_test.go
- pkg/build/build_phase.go
- pkg/storage/manager/storage_manager.go
- test/e2e/build/complex_test.go
- test/e2e/build/simple_test.go
Use the term 'built image' to not confuse users.
Werf cache consists of 'real' images in repo, it is different from the local docker build cache.
> fix: use 'built image' instead of 'cache image'

- cmd/werf/bundle/export/export.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/compose/main.go
- cmd/werf/converge/converge.go
- cmd/werf/kube_run/kube_run.go
- cmd/werf/render/render.go
- cmd/werf/run/run.go
- pkg/logging/main.go
- Use --log-verbose to see full log anyway
- Use --log-quiet to hide build log without --require-built-images
> feat: hide build logs if --require-built-images is in use, show logs on error

- .golangci.yaml
- Taskfile.dist.yaml
- pkg/buildah/common.go
- pkg/buildah/thirdparty/docker.go
- pkg/cleaning/stage_manager/manager.go
- pkg/config/raw_stapel_image.go
- pkg/docker_registry/docker_hub.go
- pkg/docker_registry/github_packages.go
- pkg/docker_registry/selectel.go
- pkg/storage/kubernetes_stages_storage_cache.go
- Update golangci-lint to 1.52.1 to support Go 1.20 (See https://github.com/golangci/golangci-lint/pull/3414)
- Remove abandoned linters
- Add 'nolint' pragmas, should refactor in the future.
- Enable nolintlint linter.
- Add max-* settings to show all errors at once.
Abandoned linters gave this warnings:
```
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [linters_context] structcheck is disabled because of …
```
> fix: remove abandoned linters, use unused linter

- .github/workflows/test_main.yml
- new github-script versions move issues client to rest.issues
- add try-catch block, ignore remove label error
> fix(ci): unlabel job should not fail

- pkg/build/build_phase.go
- pkg/build/image/image.go
- pkg/build/stage/base.go
- pkg/build/stage/full_dockerfile.go
- pkg/build/stage/instruction/from.go
- pkg/build/stage/interface.go
- pkg/build/stage/stubs.go
- pkg/docker_registry/api.go
- pkg/docker_registry/debug.go
- pkg/docker_registry/docker_registry.go
- pkg/docker_registry/interface.go
- pkg/docker_registry/main.go
- pkg/storage/manager/storage_manager.go
Manifest getter used to fetch base image manifest needed to use base ENV-variables and ONBUILD instructions. Now werf uses manifest of FROM1 stage for ENV-vars and ONBUILD instructions instead of base image manifest.
Additionally added debug tracer messages to log all requests to docker-registry api. Enable debug by setting WERF_DOCKER_REGISTRY_DEBUG=1.
> fix(staged-dockerfile): eliminate excess manifest get request from base image registry

- cmd/werf/build/main.go
This commit addresses an issue where the 'build' command was failing when using a custom synchronization server in Kubernetes. It ensures that the necessary initialization is performed, consistent with other commands, to prevent failures.
> fix(build): initialize ondemandKubeInitializer for custom sync server in Kubernetes

- docs/.helm/templates/20-ingress.yaml
- docs/pages_en/configurator.md
- docs/pages_ru/configurator.md
Route all /configurator/*.html pages to a single configurator page in werf-docs which will ssi-include target page.
> docs(configurator-separate-pages): serve /documentation/X/configurator/*.html pages

- pkg/build/image/dockerfile.go
Print explanatory error for user to enable WERF_STAGED_DOCKERFILE_VERSION=v2 when Dockerfile contains only single FROM instruction.
> fix(staged-dockerfile): explanatory error message when building unsupported Dockerfile conf

- pkg/true_git/diff_parser.go
Error was due to strange git-patch format for such files wihch contain \t symbol at the end of such lines: '--- a/aaa/bbb/path with spaces/hello.sql\t'.
> fix(build): files from git with spaces in path not removed on install/beforeSetup/setup patch-stages

- .github/workflows/_docs_deploy.yml
- .github/workflows/docs_deploy_latest.yml
- .github/workflows/docs_deploy_pr.yml
- .github/workflows/docs_deploy_tag.yml
- .github/workflows/release_trdl-publish.yml
- Use enterprise runners for the documentation deployment.
- Use secrets for K8s context.
> ci: use enterprise runners for docs

- cmd/werf/bundle/apply/apply.go
- cmd/werf/bundle/publish/publish.go
- cmd/werf/bundle/render/render.go
- cmd/werf/helm/secret/common/edit.go
- go.mod
- go.sum
- pkg/context_manager/context_manager.go
- pkg/deploy/helm/chart_extender/chart_dependencies_loader.go
- pkg/git_repo/gitdata/git_data_manager.go
- pkg/ssh_agent/ssh_agent.go
Currently we are using two UUID packages:
1. `github.com/satori/go.uuid`
2. `github.com/google/uuid`
`github.com/satori/go.uuid` is no longer being actively maintained (last commit was 5 years ago [^1]). So we should just use the newer `github.com/google/uuid`.
[^1]: https://github.com/satori/go.uuid/commits/master/
> chore: replace satori/go.uuid with google/uuid

- pkg/storage/manager/storage_manager.go
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x31c9217]
github.com/werf/werf/pkg/cleaning/stage_manager.(*Manager).InitFinalStages(0xc0011ce5a0, {0x4a176a8?, 0xc0012be360?}, {0x4a48428?, 0xc000cca0b0?})
/git/pkg/cleaning/stage_manager/manager.go:88 +0x97
github.com/werf/werf/pkg/cleaning.(*cleanupManager).init.func2()
/git/pkg/cleaning/cleanup.go:90 +0x2d
github.com/werf/logboek/internal/stream.(*LogProcess).DoError(0xc000da3d80, 0xc00002d3e0)
/go/pkg/mod/github.com/werf/logboek@v0.6.1/internal/stream/process_types.go:195 +0xd5
github.com/werf/werf/pkg/cleaning.(*cleanupManager).init(0xc0011ce5a0, {0x4a176a8?, 0xc0012be360})
/git/pkg/cleaning/cleanup.go:89 +0x1c6
```
> fix(cleanup): panic related to corrupted images in the final repo

- pkg/buildah/native_linux.go
- pkg/container_backend/buildah_backend.go
- pkg/docker/image_info.go
- pkg/docker_registry/api.go
- pkg/image/const.go
Issue occurred when using images built with werf using the buildah backend as base images in a project using werf with the Docker backend.
Fixed getting image parent ID logic.
> fix(cleanup): issue with incorrect exclusion of ancestors for retained images

- integration/suites/deploy/helm_hooks_deleter_test.go
- integration/suites/deploy/kubedog_multitrack_test.go
- integration/suites/deploy/resources_adopter_test.go
These integration (e2e) tests heavily depend on parsing werf log output. Going to be easier to just disable them for now and rework later, implementing them as as a part of a new test/e2e suite.
> chore(tests): disable old integration tests broken by enabling Nelm

- integration/suites/deploy/helm_releases_manager_test.go
These integration (e2e) tests heavily depend on parsing werf log output. Going to be easier to just disable them for now and rework later, implementing them as as a part of a new test/e2e suite.
> chore(tests): disable old integration tests broken by enabling Nelm /2

- .github/workflows/_test_e2e_per-k8s-version.yml
- .github/workflows/_test_e2e_regular.yml
- .github/workflows/_test_integration_per-k8s-version-and-container-registry.yml
- .github/workflows/_test_integration_per-k8s-version.yml
Add configuration to run integration and e2e tests on Kubernetes 1.27 and 1.29.
> tests: Update e2e and integration tests for Kubernetes

- pkg/docker_registry/api.go
- pkg/docker_registry/common_api.go
- pkg/docker_registry/docker_hub_api.go
- pkg/docker_registry/github_packages_api.go
- pkg/docker_registry/gitlab_registry.go
- pkg/docker_registry/harbor_api.go
- pkg/docker_registry/quay_api.go
Previously, a new HTTP transport was created for each request to container registry, leading to an excessive number of open TCP connections that were not properly reused. This commit addresses the issue by introducing a shared HTTP transport that is reused for all requests, thus improving resource management and connection reuse.
> fix: prevent growing TCP connections by using a shared HTTP transport

- pkg/true_git/common.go
Fixed an issue where GPG failed to sign the data during the commit process, resulting in the following error:
```
Error: unable to sync worktree with service branch "_werf-dev": unable to commit new changes in service branch: git commit command failed: error running command "/usr/bin/git -c core.autocrlf=false -c gc.auto=0 -c user.email=werf@werf.io -c user.name=werf commit --no-verify -m 2024-06-06 18:58:25.200251041 +0100 WEST m=+0.157575259": exit status 128
Stdout:
Stderr:
error: gpg failed to sign the data
fatal: failed to write commit object
```
> fix(dev): disable signing for service commits

- pkg/build/image/dockerfile.go
- pkg/build/stage/full_dockerfile.go
- pkg/container_backend/thirdparty/platformutil/platformutil.go
- pkg/dockerfile/dockerfile.go
- pkg/dockerfile/frontend/buildkit_dockerfile.go
Added support for automatic platform ARGs that can be used when configuring images in the Dockerfile.
Supported ARGs:
- TARGETPLATFORM: platform of the build result. E.g., linux/amd64, linux/arm/v7, windows/amd64.
- TARGETOS: OS component of TARGETPLATFORM.
- TARGETARCH: architecture component of TARGETPLATFORM.
- TARGETVARIANT: variant component of TARGETPLATFORM.
- BUILDPLATFORM: platform of the node performing the build.
- BUILDOS: OS component of BUILDPLATFORM.
- BUILDARCH: architecture component of BUILDPLATFORM.
- BUILDVARIANT: variant component of BUILDPLATFORM.
Reference: https://docs.docker.com/reference/dockerfile/#automatic-platform-args-in-the-global-scope
This allows the use of platform arguments in the global scope of the Dockerfile for enhanced multi-platform image …
> feat(build, dockerfile, multiplatform): support automatic platform ARGs

- pkg/build/build_phase.go
- pkg/build/image/image.go
Tagging did not account for the base Dockerfile stage, resulting in rebuilds not being triggered.
For werf.StagedDockerfileV2, the new logic should be the default. However, to avoid breaking tag reproducibility, this logic is currently enabled only for the multi-stage case. Eventually, this behavior should be the default for all versions without the extra if condition.
> fix(build, buildah, dockerfile): fix multi-stage does not work properly

- README.md
Adding a Stack Overflow link (similar to https://github.com/werf/website/pull/738) and a Slack channel + making tiny related rewordings in README.
> docs: add StackOverflow to README

- pkg/image/info.go
There was an issue where users would receive a value in the format `<cache-repo-address>@<digest>` instead of `<digest>`.
> fix(build): fix invalid image digest when cache repo used

- pkg/docker_registry/api.go
- pkg/docker_registry/common_api.go
- pkg/werf/user_agent_transport.go
```
User-Agent: werf/v2.7.3
User-Agent: werf/v2.7.3 go-containerregistry/v0.19.1
```
> feat(docker-registry): use werf user agent for requests to container registry API

- pkg/git_repo/gitdata/gc.go
- pkg/git_repo/gitdata/git_archive.go
- pkg/git_repo/gitdata/git_patch.go
- pkg/git_repo/gitdata/git_repo.go
- pkg/git_repo/gitdata/git_worktree.go
E.g.:
```
Version: v1.2.317
┌ Running GC for tmp data
└ Running GC for tmp data (0.00 seconds)
┌ Running GC for git data
│ ┌ Git data storage check
│ │ Werf local cache dir: /home/user/.werf/local_cache
│ │ Volume usage: 876 GB / 926 GB
│ │ Allowed percentage level exceeded: 94.53% > 70.00% — HIGH VOLUME USAGE
│ │ Target percentage level after cleanup: 70.00% - 5.00% (margin) = 65.00%
│ │ Needed to free: 274 GB
│ └ Git data storage check
└ Running GC for git data (0.30 seconds) FAILED
Running time 0.30 seconds
Error: git repo GC failed: error getting existing git repos from "/home/user/.werf/local_cache/git_patches/6": error unmarshalling json from "/home/user/.werf/local_cache/git_patches/6/99ded8ecb2d5b367b3ba1f28a1631e124bf129229f4e99b63a977ff4ec4bb2e8/94/94fb8623fb405d780b6bb30a5ca06f5 …
```
> fix(host-cleanup): remove invalid entries from git cache

- pkg/build/image/image_tree.go
Add RWMutex to ImagesTree to synchronize concurrent access of the "multiplatformImages" array. This is done to prevent race conditions where an image is not stored in the array because it is overwritten by a parallel task.
Closes https://github.com/werf/werf/issues/6315
> fix(build/stages): Add RWMutex to ImagesTree

- cmd/werf/build/main.go
- cmd/werf/compose/main.go
- cmd/werf/config/graph/graph.go
- cmd/werf/kube_run/kube_run.go
- cmd/werf/run/run.go
- cmd/werf/stage/image/main.go
Enabled non-final images for `build`, `run`, `kube-run`, and `compose` commands.
> fix(build): allow usage of non-final images for specific commands

- go.mod
- go.sum
Reverts go-git to v5.10.1 because v5.11.0 introduced breaking changes that affect backward compatibility, especially in relation to specific requirements for alternates.
> fix: revert go-git to v5.10.1 due to broken backward compatibility

- cmd/werf/root/root.go
- docs/_includes/reference/cli/werf_cr.md
- docs/_includes/reference/cli/werf_cr.short.md
Hi there,
I started working with Werf and noticed that the werf cr --help message does not accurately reflect the available actions; currently, only “login” and “logout” are supported. This pull request updates the help message to align with the actual functionality.
Regards,
Ilya
> refactor(docs): actualise cr cli param help message

- test/e2e/compose/complex_test.go
- test/pkg/utils/docker/docker_registry.go
This is fixing the issue with empty host port from docker inspect of registry container both on Mac and Linux
> refactor(test): set predefined host port for registry container

- pkg/deploy/bundles/registry/cache.go
- pkg/deploy/bundles/registry/constants.go
This fix allow "application/vnd.cncf.helm.chart.content.v1.tar+gzip" MIME type to `KnownMediaTypes` method and resolves situation, when some other instruments fetch bundle chart from registry and push chart artifact to another registry. This case in some banks, where dev registry is separated from prod registry.
> fix(cache): allow application/vnd.cncf.helm.chart.content.v1.tar+gzip media type.

- cmd/werf/common/common.go
- pkg/config/meta_deploy.go
- pkg/config/raw_meta_deploy.go
- pkg/deploy/helm/chart_extender/helpers/chart_metadata_autosetter.go
- pkg/deploy/helm/chart_extender/werf_chart.go
Implements #6390
The current implementation scope:
* Add `applicationVersion` global param support to `werf.yml`
* Add `applicationVersionFile` global param support to `werf.yml` 
* Plain/text, JSON, YAML files can be used as `applicationVersionFile` params
* Giterminism is enforced for `applicationVersionFile` param
* Giterminism dev mode is supported for `applicationVersionFile` param
* Handle corner case when both `applicationVersion` and `applicationVersionFile` params are set
* `applicationVersion` value is available in nelm templates by using `$.Values.werf.applicationVersion` variable
`werf.yaml` file content:
```
project: demo-app
applicationVersion: v0.0.1
---
image: backend
dockerfile: backend.Dockerfile
---
image: frontend
dockerfile: frontend.Dockerfile
``` …
> feat(werf): add application version param support

- cmd/werf/helm/helm.go
This week I stuck with a pretty ugly YAML formatting issue that took me quite some time to figure out what was the problem about. During troubleshooting I was using `werf render --debug`, but the error message (something like _"error converting YAML to JSON"_)
was not the one that clearly says what should be done to fix the issue.. It was not an issue with `werf` at all, it is more about human factor :))
So, I did some research regarding YAML troubleshooting and `helm template --debug` comes to play. It was the thing that in my opition makes the troubleshooting process a way simpler, because it does not just return errors, but shows the YAML dump, so you can clearly see what is wrong with templating.
Next, I found that during `werf helm template --debug`, the debug flag was not passed to …
> fix(helm): pass --debug option to helm

- docs/_data/werf_yaml.yml
- docs/pages_en/usage/build/process.md
- docs/pages_ru/usage/build/process.md
- pkg/config/meta_build.go
- pkg/config/parser.go
- pkg/config/raw_image_from_dockerfile.go
- pkg/config/raw_meta_build.go
> **What this PR does / why we need it**:
>
> feat #5974
>
> **Special notes for your reviewer**:
>
> **If applicable**:
>
> * [x] this PR contains documentation
> * [x] this PR has been tested for backwards compatibility
>
> I have thoroughly tested it locally. Please take a review at this pr.
>
> ## How to Test This Modification Locally
>
> 1. Init demo
>
>    ```
>    Initialize the demo project on the local machine:
>    
>    git clone https://github.com/werf/examples
>    cp -rf examples/local-dev example
>    cd example
>    git init
>    ```
>
> 2. Edit a `werf.yaml`
>
> ```yaml
> project: demo-app
> configVersion: 1
> build:
>   staged: true
> 
> ---
> image: backend
> dockerfile: backend.Dockerfile
> 
> ---
> image: frontend
> dockerfile: frontend.Dockerfile
> ```
>
> 3. Git …
> feat(build): add global staged directive

- .github/workflows/release_release-please.yml
- README.md
- docs/DEVELOPMENT.md
We provide actual instructions for installing werf in the [Getting Started guide](https://werf.io/getting_started/). This PR updates all old links leading to the non-existing `/installation.html` page. Additionally, we removed the Quickstart guide a while ago.
> docs: update the werf installation link

- pkg/container_backend/legacy_stage_image.go
```
│ ┌ Building stage common/relocate-artifact/from
│ │ common/relocate-artifact/from  docker: Error response from daemon: No such image: sha256:8c6ead2bd8a90a3969dc9fd39513bcf332ca130d44ac9791b7536e78440198f1. │ │ common/relocate-artifact/from  See 'docker run --help'.
...
Error: phase build on image common/relocate-artifact stage from handler failed: failed to build image for stage from with digest 999f9fefd1e9ad7092be30c38711c041bb8c922125e32b1fe74bd64c: error building stage from: unable to remove container (original error container run failed: Status: , Code: 125): unable to remove container werf.build.awnree2bxr: Error response from daemon: No such container: werf.build.awnree2bxr
```
> fix(build): fix no such image error

- pkg/build/stage/image_spec.go
panic: assignment to entry in nil map
goroutine 13229 [running]:
github.com/werf/werf/v2/pkg/build/stage.(*ImageSpecStage).PrepareImage(0xc000e99660, {0x4ead678, 0xc003309980}, {0x10?, 0x2c?}, {0x30?, 0x30?}, 0xc001d454c0?, 0xc0072c25a0, {0x0, ...})
/git/pkg/build/stage/image_spec.go:67 +0x6d5
> fix(build): panic: assignment to entry in nil map

- pkg/docker/image.go
Disable provenance to avoid creating an index manifest (result of Buildx build), which is not handled correctly with the current code.
```
panic: expected stage "dockerfile" content digest label to be set!
github.com/werf/werf/v2/pkg/build.(*BuildPhase).calculateStage(0x14000cf0a00, {0x104100598, 0x14000b12090}, 0x14000371680, {0x10412ad20, 0x1400095f800})
/git/pkg/build/build_phase.go:985 +0xb68
github.com/werf/werf/v2/pkg/build.(*BuildPhase).onImageStage(0x14000cf0a00, {0x104100598, 0x14000b12090}, 0x14000371680, {0x10412ad20, 0x1400095f800})
/git/pkg/build/build_phase.go:744 +0xf8
```
> fix(build, docker, dockerfile): fix panic expected stage "dockerfile" content digest label to be set!

- pkg/config/raw_meta_cleanup.go
```
Error: invalid value "/(?!main$|release-).*/" for `branch`: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
branch: /(?!main$|release-).*/
/private/var/folders/58/893r9slj6lsc19mrn19vjp180000gn/T/werf-config-render-4202248949
1  project: echoserver
2  configVersion: 1
3  cleanup:
4    keepPolicies:
5      - references:
6          branch: "/(?!main$|release-).*/"
7  build:
8    imageSpec:
9      config:
10        labels: 
11          OLOLO: x
12 
```
> refactor(cleanup): add detailed error for invalid regex in config

- pkg/buildah/native_linux.go
Due to we don't set logger in run options a panic occurs when running this code
https://github.com/werf/3p-buildah/blob/5b80b7b735de074279ceabad77697d1fe54fafab/run_linux.go#L350-L354
It can't take a global logger since it uses pointer to logger from options struct, so we need to set it in the run options.
> fix(build, buildah, staged): fix panic in run instruction

- cmd/werf/common/common.go
- cmd/werf/common/deploy_params.go
- cmd/werf/export/export.go
- docs/_includes/reference/cli/werf_bundle_apply.md
- docs/_includes/reference/cli/werf_bundle_publish.md
- docs/_includes/reference/cli/werf_bundle_render.md
- docs/_includes/reference/cli/werf_converge.md
- docs/_includes/reference/cli/werf_export.md
- docs/_includes/reference/cli/werf_helm_install.md
- docs/_includes/reference/cli/werf_helm_lint.md
- docs/_includes/reference/cli/werf_helm_template.md
- docs/_includes/reference/cli/werf_helm_upgrade.md
- docs/_includes/reference/cli/werf_kube_run.md
- docs/_includes/reference/cli/werf_plan.md
- docs/_includes/reference/cli/werf_render.md
Previously, the separator option only worked in the `werf export` command and the default was `\n`.
In other commands, separator options had no effect, and the default separator was `,`.
This PR unifies the behavior: `,` is now used as the default separator across all commands, and the separator options are respected consistently. Backward compatibility is broken only for `werf export`, but the behavior is now consistent and predictable.
> fix: label/annotation separator options behaviour 

- pkg/logging/logger.go
> fix(logging): use yellow color for warnings to distinguish them from errors

- pkg/true_git/common.go
If the user has `untrackedCache=true` in their global or repo config, the service worktree created by werf ends up using a Git index format unsupported by go-git (see https://github.com/go-git/go-git/issues/180). This leads to errors like:
```
Error: unable to read werf giterminism config: unable to get submodule "name" status: invalid checksum
```
To prevent this, we now explicitly disable both `untrackedCache` and `splitIndex` via `-c` options when creating the service worktree. This ensures compatibility with go-git's index parser and avoids checksum-related failures.
> fix: avoid checksum errors in service worktree when core.untrackedCache is enabled

- pkg/build/stage/git_mapping.go
- pkg/container_backend/errors.go
- pkg/container_backend/legacy_stage_image_container.go
- pkg/stapel/stapel.go
```
│ ┌ Building stage a/setup
│ │ a/setup  error: patch failed: /my_file:1
│ │ a/setup  error: /my_file: patch does not apply
│ ├ Info
│ └ Building stage a/setup (0.40 seconds) FAILED
└ 🛳️  (1/1) image a [linux/amd64] (0.53 seconds) FAILED
Running time 1.01 seconds
Error: phase build on image a stage setup handler failed: failed to build image for stage setup with digest c0f00bbf9c2743ed26e5c4dbcc515ec3c00b1358f687cf0bdceeb266: error building stage setup: container run failed: Status: , Code: 1
```
=>
```
│ ┌ Building stage a/setup
│ │ a/setup  error: patch failed: /my_file:1
│ │ a/setup  error: /my_file: patch does not apply
│ ├ Info
│ └ Building stage a/setup (0.30 seconds) FAILED
└ 🛳️  (1/1) image a [linux/amd64] (0.40 seconds) FAILED
Running time 0.83 seconds
Error: phase build on …
```
> fix(build, stapel): fix service git apply patch failed

- cmd/werf/common/common.go
Traces can be shown now with `export WERF_NELM_TRACE=1`
Fixes #6880
> fix(deploy): hide traces from `--log-debug` output by default

- docs/pages_en/usage/distribute/bundles.md
- docs/pages_ru/usage/distribute/bundles.md
There was a typo in the documentation: 
one mentioned option -`-use-custom-tag` but  snippet had example with `--tag`
> docs(bundles): fix custom tag usage example

- docs/pages_en/usage/cleanup/cr_cleanup.md
Adding backticks to the `--keep-list` param mentioned in the documentation to render it properly.
> chore(docs): add backticks to --keep-list

- CONTRIBUTING.md
Add GOTOOLCHAIN=local setup instructions to contributing.md to block 
Go from automatically adding the toolchain directive.
> chore(dev): prevent auto toolchain in go.mod
