lib/dapp/build/stage/base.rb
lib/dapp/build/stage/from.rb
lib/dapp/build/stage/mod/logging.rb
lib/dapp/image/docker.rb
lib/dapp/image/stage.rb

- образ в кеше однозначно определяется именем, сигнатурой стадии.

Добавлен кеш образов стадий

---

lib/dapp/git_artifact.rb

Работа над ошибками для #31 в рамках версии 0.8

Продолжение выпиливания Project::system_files

---

docs/_data/stages.yml
lib/dapp/dapp/deps/base.rb
lib/dapp/dimg/build/stage/base.rb
lib/dapp/dimg/build/stage/from.rb
lib/dapp/dimg/image/argument.rb
lib/dapp/dimg/image/stage.rb

* добавлена зависимость от mount-ов из Dappfile во from стадию;
* очистка/добавление mount-директорий происходит на стадии from.

Очистка/добавление mount директорий

---

config/en/net_status.yml
docs/_data/stages.yml
docs/pages/directive/artifact.md
lib/dapp/dimg/build/stage/base.rb
lib/dapp/dimg/build/stage/before_setup.rb
lib/dapp/dimg/config/directive/git_artifact_local.rb
lib/dapp/dimg/git_artifact.rb
spec/integration/dimg_spec.rb
spec/unit/config/git_artifact_spec.rb

Добавлена зависимость от файлов git-артефактов в стадию before_setup

---

config/en/net_status.yml
lib/dapp/dimg/build/stage/ga_latest_patch.rb
lib/dapp/dimg/config/directive/git_artifact_remote.rb
lib/dapp/dimg/git_repo/own.rb
lib/dapp/dimg/git_repo/remote.rb

* отлажена работа с пользовательскими опциями `branch` и `commit`.

Доработка git-артефактов

---

config/en/net_status.yml
lib/dapp/config/directive/git_artifact_remote.rb
lib/dapp/git_artifact.rb
lib/dapp/git_repo/own.rb
lib/dapp/git_repo/remote.rb

* отлажена работа с пользовательскими опциями `branch` и `commit`.

Доработка git-артефактов (0.7)

---

lib/dapp/deployment/app.rb
lib/dapp/deployment/config/directive/expose.rb
lib/dapp/deployment/kube_app.rb
spec/unit/config/deployment/expose_spec.rb
spec/unit/config/deployment/group_spec.rb

Также сделан суммарный вывод информации о задеплоенном Service для пользователя (поля nodePort, clusterIp и пр.).

23: Поддержка NodePort, LoadBalancer типов Service

---

lib/dapp/config/directive/base.rb
spec/chef/testproject/.dapp_chef/recipes/build_artifact/install_version.rb
spec/chef/testproject/Dappfile

Также добавлен пример настройки такого артефакта в spec/chef/testproject/Dappfile.

Исправление настроек копирования артефакта для возможности устанавливать version.txt через артефакт

---

lib/dapp/git_artifact.rb
spec/unit/git_artifact_spec.rb

* add prefix `/` to tar files and excluding paths

Fix excluding files of git artifact archive

---

lib/dapp/kube/cli/command/kube/deploy.rb
lib/dapp/kube/dapp/command/deploy.rb

kube deploy command: add `--set STRING_ARRAY` option

---

lib/dapp/kube/dapp/command/deploy.rb

kube deploy command: add `templates/_dapp_helpers.tpl` generation

---

docs/_data/sidebar.yml
docs/pages/command/kube.md
lib/dapp/kube/cli/command/kube/secret_file_encrypt.rb

https://alexey-igrychev.github.io/dapp/kube_commands.html

Kube doc reference

---

lib/dapp/dapp.rb
lib/dapp/dapp/chef.rb
lib/dapp/dimg/dimg/path.rb
lib/dapp/kube/dapp/command/common.rb
lib/dapp/kube/dapp/command/deploy.rb
lib/dapp/kube/dapp/command/secret_key_generate.rb

kube `DAPP_SECRET_KEY`

---

docs/_data/sidebar.yml
docs/pages/deploy/secrets.md

https://alexey-igrychev.github.io/dapp/secrets_for_deploy.html

kube doc secrets guide

---

config/en/net_status.yml
docs/pages/command/kube.md
lib/dapp/kube/cli/command/kube/deploy.rb
lib/dapp/kube/dapp/command/deploy.rb

kube deploy command: add `--secret-values FILE_PATH` option

---

config/en/net_status.yml
lib/dapp/dimg/dapp/command/common.rb
lib/dapp/dimg/dapp/command/stages/cleanup_local.rb

* fix dimg stages cleanup local command
* add info message
#51

safe dimg clear commands

---

lib/dapp/dimg/dimg/git_artifact.rb

git artifact: reusing git repo

---

config/en/common.yml
lib/dapp/dimg/git_artifact.rb
lib/dapp/dimg/git_repo/remote.rb

add git_artifact warning: stage dependencies not found in repo

---

lib/dapp/cli.rb
lib/dapp/deployment/cli/command/deployment.rb
lib/dapp/dimg/cli/command/dimg.rb
lib/dapp/kube/cli/command/kube.rb

sub-command -> subcommand

---

lib/dapp/dimg/dapp/command/mrproper.rb

dimg mrproper command: add removing build directory

---

config/en/common.yml
lib/dapp/dapp/logging/process.rb
lib/dapp/dapp/shellout/base.rb
lib/dapp/deployment/dapp/command/apply.rb
lib/dapp/deployment/dapp/command/minikube_setup.rb
lib/dapp/deployment/kube_app.rb
lib/dapp/deployment/kube_base.rb
lib/dapp/dimg/build/stage/artifact_base.rb
lib/dapp/dimg/build/stage/base.rb
lib/dapp/dimg/build/stage/mod/group.rb
lib/dapp/dimg/build/stage/mod/logging.rb
lib/dapp/dimg/builder/chef/cookbook.rb
lib/dapp/dimg/dapp/command/stages/cleanup_repo.rb
lib/dapp/dimg/image/docker.rb
lib/dapp/dimg/image/stage.rb
lib/dapp/kube/dapp/command/deploy.rb
lib/dapp/kube/dapp/command/dismiss.rb

verbose mode -> usual mode

---

config/en/common.yml
lib/dapp/dimg/build/stage/base.rb

modify instrospection

---

lib/dapp/dimg/cli/command/dimg/build.rb
lib/dapp/helper/cli.rb

modify intropect stage options info messages

---

bin/dapp
config/en/net_status.yml
lib/dapp/dapp.rb
lib/dapp/dapp/deps/base.rb
lib/dapp/dapp/deps/gitartifact.rb
lib/dapp/dimg/builder/chef.rb
lib/dapp/dimg/builder/chef/cookbook.rb
lib/dapp/dimg/dapp/command/cleanup.rb
lib/dapp/dimg/dapp/command/common.rb
lib/dapp/dimg/dapp/command/mrproper.rb
lib/dapp/dimg/dapp/command/stages/cleanup_local.rb
lib/dapp/dimg/dimg.rb
lib/dapp/dimg/image/docker.rb
lib/dapp/dimg/image/stage.rb
spec/integration/artifact_spec.rb
spec/integration/chef_spec.rb
spec/integration/shell_spec.rb
spec/spec_helper/common.rb
spec/unit/git_artifact_spec.rb

docker validation

---

lib/dapp/dapp/logging/base.rb
lib/dapp/dapp/logging/process.rb
lib/dapp/deployment/dapp/command/apply.rb
lib/dapp/deployment/kube_app.rb
lib/dapp/dimg/build/stage/artifact_base.rb
lib/dapp/dimg/dapp/command/build_context/export.rb
lib/dapp/dimg/dapp/command/build_context/import.rb
lib/dapp/dimg/dimg.rb
lib/dapp/kube/dapp/command/dismiss.rb
lib/dapp/kube/dapp/command/minikube_setup.rb

log_process: indent by default

logging: refactor

---

lib/dapp/kube/dapp/command/secret_extract.rb

* reject extra line break in extracted secret file

kube secret extract command

---

lib/dapp/kube/dapp/command/secret_edit.rb
lib/dapp/kube/error/base.rb

* regenerate only modified fields
* reopen changed file if it isn't correct

kube secret edit

---

lib/dapp/kube/dapp/command/common.rb
lib/dapp/kube/dapp/command/secret_edit.rb

* support yaml with nil values (--values)
* update merging new onto old secret values

kube secret

---

lib/dapp/dapp.rb
lib/dapp/dapp/deps/base.rb
lib/dapp/dapp/deps/gitartifact.rb
lib/dapp/dimg/builder/chef.rb
lib/dapp/dimg/builder/chef/cookbook.rb
lib/dapp/dimg/dapp/command/cleanup.rb
lib/dapp/dimg/dapp/command/common.rb
lib/dapp/dimg/dapp/command/mrproper.rb
lib/dapp/dimg/dapp/command/stages/cleanup_local.rb
lib/dapp/dimg/dimg.rb
lib/dapp/dimg/image/docker.rb
lib/dapp/dimg/image/stage.rb
spec/integration/artifact_spec.rb
spec/integration/chef_spec.rb
spec/integration/shell_spec.rb
spec/spec_helper/common.rb
spec/unit/git_artifact_spec.rb

Support custom docker config directory

---

lib/dapp/dimg/dapp/command/stages/cleanup_local.rb

dapp dimg cleanup local --improper-repo-cache мог очистить кеш, собранный параллельным worker'ом.
Сейчас dapp dimg cleanup local --improper-repo-cache очищает только образы старше 2ч.

Исправление очистки кеша, который не успели push'нуть

---

lib/dapp/cli/command/base.rb
lib/dapp/dapp.rb
lib/dapp/dimg/cli/command/base.rb
lib/dapp/dimg/cli/command/dimg/push.rb
lib/dapp/dimg/cli/command/dimg/run.rb
lib/dapp/dimg/cli/command/dimg/stages/cleanup_local.rb
lib/dapp/dimg/cli/command/dimg/stages/flush_local.rb
lib/dapp/dimg/cli/command/dimg/stages/flush_repo.rb
lib/dapp/dimg/cli/command/dimg/stages/pull.rb
lib/dapp/dimg/cli/command/dimg/stages/push.rb
lib/dapp/dimg/cli/command/dimg/tag.rb
lib/dapp/dimg/docker_registry/base/authorization.rb
lib/dapp/kube/cli/command/base.rb
lib/dapp/kube/cli/command/kube/deploy.rb
lib/dapp/kube/cli/command/kube/secret_edit.rb
lib/dapp/kube/cli/command/kube/secret_extract.rb
lib/dapp/kube/cli/command/kube/secret_generate.rb
lib/dapp/kube/cli/command/kube/secret_regenerate.rb
spec/spec_helper.rb

* options `--registry-username`, `--registry-password`

support docker registry credentials

---

bin/dapp
lib/dapp/cli/command/base.rb

При этом dapp update запускается только если в системе нет активных dapp процессов.

Блокировка всех процессов dapp при запуске dapp update

---

lib/dapp/dapp.rb

* generating only if repo argument is passed!

Temporary docker config

---

lib/dapp/dimg/dapp/command/push.rb
lib/dapp/dimg/dimg.rb
lib/dapp/dimg/image/docker.rb

В данной версии фикс "по-быстрому".

Фикс долгой работы push

---

lib/dapp/dimg/config/directive/git_artifact_local.rb
spec/unit/config/dimg/git_artifact_spec.rb

stage_dependencies: multiple stage adding

---

lib/dapp/dimg/build/stage/artifact_base.rb
lib/dapp/dimg/build/stage/before_install.rb
lib/dapp/dimg/build/stage/before_setup.rb
lib/dapp/dimg/build/stage/build_artifact.rb
lib/dapp/dimg/build/stage/docker_instructions.rb
lib/dapp/dimg/build/stage/ga_base.rb
lib/dapp/dimg/build/stage/ga_dependencies_base.rb
lib/dapp/dimg/build/stage/import_artifact.rb
lib/dapp/dimg/build/stage/install/install.rb
lib/dapp/dimg/build/stage/setup/setup.rb
lib/dapp/version.rb

+ Рефакторинг prepare_image: передача блока в super везде

Хранение коммитов в образе с привязкой к git-artifact.paramshash

---

lib/dapp/dimg/git_artifact.rb

Использование ASCII-8BIT для рассчета контрольных сумм git-артефатов.

Фикс проблемы: incompatible character encodings: UTF-8 and ASCII-8BIT

---

.travis.yml
README.md
config/en/net_status.yml
lib/dapp/dapp.rb

Игнорирование Docker version 17.10

---

lib/dapp/kube/helm/release.rb

Тупит в первые моменты после запуска. Профайлинг показал, что это `helm --dry-run`. Заменяем на helm template.

Тупит dapp kube deploy

---

README.md
install.sh
lib/dapp/cli/command/update.rb

* Установка libssl в install.sh, документация

Доработки скрипта установки и автообновления

---

lib/dapp/kube/dapp/command/chart_create.rb
lib/dapp/kube/dapp/command/common.rb
lib/dapp/kube/dapp/command/deploy.rb
lib/dapp/kube/dapp/command/secret_edit.rb

Чтобы генерить чарт в указанное место, а не в tmp.

Для дебага: DAPP_HELM_CHART_DIR

---

lib/dapp/dimg/config/directive/git_artifact_remote.rb
spec/unit/config/dimg/git_artifact_spec.rb

* включение в имя git remote artifact-а пользователя/компании.

Изменение сигнатуры git archive стадии

---

lib/dapp/dimg/config/directive/git_artifact_remote.rb
lib/dapp/dimg/git_repo/remote.rb
spec/unit/git_repo_spec.rb

Использование кеша для git с token'ом в url

---

lib/dapp/dimg/build/stage/base.rb

Проверка по image.built? вместо image.tagged? при получении коммита стадии.

Фикс проблемы с отсутствием файлов после наложения latest патча

---

lib/dapp/cli/command/base.rb
lib/dapp/helper/cli.rb
lib/dapp/kube/dapp/command/common.rb
lib/dapp/kube/dapp/command/deploy.rb
lib/dapp/kube/dapp/command/dismiss.rb

Добавлены файловые блокировки для защиты от параллельного выполнения операций над одним helm релизом.

Возможность параллельного выката helm релиза (deploy/dismiss)

---

config/en/net_status.yml
lib/dapp/dapp/logging/base.rb
lib/dapp/dimg/dapp/command/common.rb
lib/dapp/dimg/dapp/command/stages/cleanup_local.rb
lib/dapp/dimg/dapp/command/stages/common.rb
lib/dapp/dimg/dapp/command/stages/flush_local.rb
lib/dapp/dimg/docker_registry.rb
lib/dapp/dimg/docker_registry/base.rb
lib/dapp/dimg/docker_registry/dimg.rb

* чистка локального кеша посредством родительских образов всех dimg-ей проекта в registry.

dapp dimg stages cleanup repo command: fix

---

lib/dapp/kube/helm/release.rb

* global.dapp.name присутсвует всегда
* global.dapp.is_branch присутсвует всегда
* global.dapp.branch присутствует только если is_branch
* global.dapp.is_tag присутсвует всегда
* global.dapp.tag присутствует только если is_tag
* Для gitlab
* Либо is_branch, либо is_tag
* Без gitlab
* Может быть is_branch=false && is_tag=false если сборка без гита

Новые values для deploy

---

config/en/net_status.yml
lib/dapp/dapp.rb
lib/dapp/dimg/image/argument.rb

close https://github.com/flant/dapp/issues/410

Снято ограничение на использование последних docker версий

---

lib/dapp/dapp/ssh_agent.rb

В случае, если явно не указаны опции --ssh-key и не запущен системный ssh-agent (проверяется по переменной окружения SSH_AUTH_SOCK), dapp автоматом запускает временный ssh-agent и добавляет в него ключи по умолчанию ~/.ssh/id_rsa, ~/.ssh/id_dsa.
Данный агент будет использоваться для операций с git, chef berks, в сборочных контейнерах.

Автодобавление ~/.ssh/id_rsa и запуск ssh-agent

---

lib/dapp/kube/dapp/command/deploy.rb

Job deletion hanging on kubernetes 1.8, because job appeared in jobs list after successful deletion request.
* All related job's pods are deleted explicitly now.
* Job deletion request is now being done with parameter orphanDependents=false.
Also:
* According to the docs: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/,
orphanDependents is deprecated, should be propagationPolicy=Orphan. But it does not work.
* Kubectl still use orphanDependents.: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/delete.go#L388
* https://github.com/kubernetes/kubernetes/issues/46659

(fix) Delete hooks job `site-migrations` ... hangs

---

cmd/dappfile-yml/main.go

* -dapp-project-root param removed
* -dappfile param added

(yaml) dappfile-yml -dappfile param support

---

lib/dapp/dapp/dappfile.rb
lib/dapp/downloader.rb

+ Rename-refactor in downloader.rb.

(yaml fix) Fixup exceptions in dappfile.rb

---

lib/dapp/dapp/dappfile.rb

Common code for temporal debug purposes.

(yaml) DAPP_DUMP_CONFIG=yes dump yml Dapp::Config

---

lib/dapp/dimg/cli/command/dimg/bp.rb
lib/dapp/dimg/dapp/command/bp.rb

Cleanup stages and cleanup subcommands removed from bp.

Repair `dapp dimg bp`

---

lib/dapp/dimg/cli/command/dimg/build.rb

* опции позволяют провести интроспекцию стадии, идущей до переданной аргументом.

dapp dimg build: '--introspect-before' и '--introspect-artifact-before'

---

lib/dapp/kube/dapp/command/deploy.rb
lib/dapp/kube/helm/release.rb

Dapp will purge helm release with `helm delete --purge` on the next run, if last helm release installation was not successful.
If you run dapp on already broken helm release, then dapp will print WARN and exit without running `helm delete --purge`. And on the next run dapp will automatically purge that release. For example, run deploy on already broken helm release:
```
$ helm list
NAME                    REVISION        UPDATED                         STATUS  CHART           NAMESPACE
ex-dapp-25-default      1               Mon Jan 29 16:45:19 2018        FAILED  ex-dapp20-0.1.0 default
$ dapp kube deploy :minikube
Deploy release ex-dapp-25-default                                                                                            [RUNNING]
Upgrade helm release ex-dapp-25-default …
```

(fix) UPGRADE FAILED: ... has no deployed releases

---

lib/dapp/cli/command/options/tag.rb
lib/dapp/dapp/option_tags.rb

For --tag, --tag-slug specified text will be slugified.
For --tag-plain specified text will be used as is.

--tag-plain, --tag-slug options

---

lib/dapp/kube/dapp/command/deploy.rb

Do not use `--output json` parameter for helm status to allow versions of helm older than 2.8.0.

(fix) Helm failed: Error: a release named ... already exists

---

publish.sh

- build gem and binary
- create version on bintray.com
- upload binary and sha to bintray.com
- create release on github.com
- push gem to rubygems.org

Publish script for gem and binary

---

lib/dapp/dimg/dapp/command/common.rb

* падала очистка при большом количестве образов.

cleanup commands: улучшение

---

lib/dapp/dimg/build/stage/before_install.rb
lib/dapp/dimg/builder/ansible.rb
lib/dapp/dimg/config/directive/dimg/instance_methods.rb
lib/dapp/dimg/config/directive/dimg_group_base.rb
playground/test1/ansible-conf.yml

- checksum over json dumped config
- playbook generates in tmp_dir. Useful with --introspect-stage=
- before_install stage skipped if not configured
- ansible-conf.yml dump for testing

WIP: Initial ansible builder

---

pkg/config/raw_ansible_task.go
playground/test2/dappfile.yml

Message then task-section then supported-modules-list then config-doc-dump.

(ansible) Unsupported ansible task error refined

---

lib/dapp/kube/dapp/command/deploy.rb

On helm 2.8 master tiller first failed release will remain in PENDING_INSTALL status.
The expectation was only for FAILED status.
Now condition for auto helm delete --purge is:
* purge trigger file exists (~/.dapp/helm/RELEASE/auto_purge_failed_release_on_next_deploy);
* helm release is in FAILED or PENDING_INSTALL status.

(fix) WARN "will be removed ... on the next run" not working

---

dappdeps/ansible/omnibus/config/projects/dappdeps-ansible.rb
dappdeps/ansible/omnibus/config/software/ansible.rb
lib/dapp/dimg/builder/ansible.rb
pkg/config/raw_ansible_task.go

* openssl_* from crypto-modules category
* ini_file, iso_extract, assemble

(ansible) Extend supported modules

---

lib/dapp/dimg/dapp/command/cleanup_repo.rb
lib/dapp/kube/kubernetes/client.rb

- Support for 1.6, 1.7, 1.8, 1.9 API endpoints
- client get version from cluster on first api call

Cleanup repo: Scan additional resources for used images in cluster.

---

lib/dapp/kube/dapp/command/deploy.rb

(fix) undefined local variable or method `job' for #<Dapp::Dapp...>

---

lib/dapp/kube/kubernetes/client.rb

- minikube returns empty version strings
- api paths for k8s 1.10

Fix minikube setup api calls

---

lib/dapp/core_ext/pathname.rb

* subpath_of? equivalent path returns true
* subpath_of equivalent path equals '.'
relates #684

pathname: change subpath ext logic

---

lib/dapp/dapp.rb

relates https://github.com/flant/dapp/issues/682

Host docker login with password-stdin

---

lib/dapp/dapp.rb

* support docker versions <17.07

UP Host docker login with password-stdin

---

lib/dapp/dimg/dapp/command/common.rb
lib/dapp/dimg/image/stage.rb

closes https://github.com/flant/dapp/issues/694

cleanup commands: delete service containers only

---

lib/dapp/dimg/dapp/command/common.rb
lib/dapp/dimg/dapp/command/flush_local.rb
lib/dapp/dimg/dapp/command/mrproper.rb
lib/dapp/dimg/dapp/command/stages/flush_local.rb

closes https://github.com/flant/dapp/issues/638

dapp dimg flush local: delete used images instead of skipping

---

lib/dapp/kube/dapp/command/lint.rb
lib/dapp/kube/helm/release.rb

> https://github.com/kubernetes/helm/pull/2972
* --namespace
* --set and values 
closes https://github.com/flant/dapp/issues/675

dapp kube lint: refresh according to changes in helm

---

lib/dapp/dapp/dappfile.rb
lib/dapp/dimg/config/directive/artifact.rb
lib/dapp/dimg/config/directive/dimg/validation.rb
spec/unit/config/dimg/dimg_spec.rb

closes https://github.com/flant/dapp/issues/701

Yaml config validation and autoexcluding

---

lib/dapp/dimg/git_artifact.rb
spec/unit/git_artifact_spec.rb

git artifact: up submodule inheritance logic

---

docs/pages/advanced_build/debug.md
lib/dapp/dapp/sentry.rb
lib/dapp/dimg/cli/command/dimg/bp.rb
lib/dapp/dimg/cli/command/dimg/build.rb
lib/dapp/dimg/dimg.rb

closes https://github.com/flant/dapp/issues/705

dapp dimg build: force save cache by default

---

lib/dapp/dimg/dimg/git_artifact.rb
lib/dapp/dimg/git_repo/base.rb

closes https://github.com/flant/dapp/issues/663

git artifact: support empty git repository

---

lib/dapp/dimg/dapp/command/build_context/export.rb
lib/dapp/dimg/dimg.rb
lib/dapp/dimg/dimg/stages.rb
spec/integration/lock_spec.rb

closes https://github.com/flant/dapp/issues/720

dapp dimg stages pull/push: operate with dimg layers and related artifacts layers

---

lib/dapp/dimg/build/stage/artifact_default.rb

closes https://github.com/flant/dapp/issues/690

artifact: create parent directory for artifact-export-path

---

cmd/dappfile-yml/main.go
lib/dapp/dapp/dappfile.rb
pkg/config/dappfile.go
pkg/config/parser.go

closes https://github.com/flant/dapp/issues/709

dappfile yaml: .Files.Get non-existing file warning

---

lib/dapp/kube/dapp/command/minikube_setup.rb

closes https://github.com/flant/dapp/issues/723

dapp kube minikube setup: up restarting

---

lib/dapp/kube/helm/release.rb
lib/dapp/kube/helm/values.rb

closes https://github.com/flant/dapp/issues/662

dapp kube: escape helm set option argument

---

lib/dapp/kube/kubernetes/config.rb

* Use `kubectl config view --raw` command.
* Use kubectl with priority over KUBECONFIG, and pass KUBECONFIG to kubectl, so that kubectl will use KUBECONFIG by itself.
* Read KUBECONFIG only when kubectl is unavailable.

[kube,fix] `OpenSSL::X509::CertificateError: not enough data`

---

lib/dapp/cli/command/sample/list.rb

closes https://github.com/flant/dapp/issues/755

dapp sample list: hide running time log

---

config/en/common.yml
lib/dapp/dimg/git_artifact.rb

closes https://github.com/flant/dapp/issues/664

git artifact: improve stage dependencies not found warning

---

lib/dapp/dimg/build/stage/artifact_base.rb
lib/dapp/dimg/build/stage/from.rb
lib/dapp/dimg/dapp/command/build_context/export.rb
lib/dapp/dimg/dapp/command/common.rb
lib/dapp/dimg/dapp/command/run.rb
lib/dapp/dimg/dapp/command/stage_image.rb
lib/dapp/dimg/dapp/command/stages/common.rb
lib/dapp/dimg/dimg.rb
lib/dapp/dimg/dimg/git_artifact.rb
lib/dapp/dimg/git_artifact.rb
lib/dapp/dimg/git_repo/remote.rb
lib/dapp/kube/helm/values.rb

* local build cache should always have actual project remote repositories

git remote repo: reject ignoring repository fetching

---

bin/dapp

Handle cancel of gitlab job

---

docs/_data/sidebar.yml
docs/_includes/sidebar.html

- меню имеет три уровня вложенности
- разделены гайды и спеки
- обозначено два гайда, которые должны быть

sidebar fix

---

docs/_data/sidebar.yml
docs/pages/faq.md

Added "Dapp Frequently Asked Questions"

[doc] Added FAQ

---

config/en/net_status.yml
lib/dapp/dapp/command/sample/common.rb
lib/dapp/dapp/command/sample/create.rb
lib/dapp/dapp/option_tags.rb
lib/dapp/dapp/sentry.rb
lib/dapp/dimg/config/directive/git_artifact_remote.rb
lib/dapp/dimg/git_artifact.rb
lib/dapp/dimg/git_repo/base.rb
lib/dapp/dimg/git_repo/local.rb
lib/dapp/dimg/git_repo/remote.rb
pkg/config/git_remote_export.go
pkg/config/raw_git.go
pkg/config/ruby_marshal_config/config.go

closes https://github.com/flant/dapp/issues/782

Implement tag parameter for remote git-artifact

---

docs/_includes/sidebar.html
docs/_layouts/default.html

- Исправляем вёрстку шаблона документации
- Вставляем яндекс метрику в документацию

Исправления сайта документации

---

lib/dapp/dapp.rb

Revert "docker: reject host docker version validation"

---

docs/pages/faq.md

https://alexey-igrychev.github.io/dapp/faq.html

Documentation: up FAQ

---

pkg/image/cmd.go

* fix ruby2go image state transition

Fix build error 'assignment to entry in nil map'

---

config/en/common.yml
lib/dapp/dimg/build/stage/from.rb

* log message of fromDimg/fromDimgArtifact/asLayers building

Up logging

---

.travis.yml

Travis cache should make this work fast.

(publish) Do run go-get and go-build for every commit

---

cmd/git-artifact/main.go
cmd/git-repo/main.go

(go-deeper) Fix git-repo, git-artifact cmds initialization

---

lib/dapp/dapp.rb
lib/dapp/dimg/dapp/command/build.rb
lib/dapp/dimg/dapp/command/run.rb

Fix remote git-repository fetching problem

---

docs/pages/how_to/first_application.md

* Fix notice about `composer install`.
* Add push step.

(doc) Complete `Build, run and push` howto article

---

docs/_data/sidebars/not_used.yml
docs/pages/not_used/directives.md
docs/pages/not_used/yaml_directives.md
docs/pages/references/dappfile/git_directive.md
docs/pages/references/directives/directives.md

Translate dappfile directives, git (2)

---

docs/pages/how_to/gitlab_ci_cd_integration.md

Added HowTo "GitLab CI Integration"

[docs] HowTo: Gitlab CI integration

---

docs/pages/reference/deploy/deploy_for_kube.md

If you use self-signed certificate in the time of deploy you should set SSL_CERT_FILE environment.

[doc] Added  info about using self-signed certificates

---

docs/_includes/head.html
docs/css/custom.css
docs/pages/reference/dappfile/definition.md
docs/pages/reference/dappfile/minimal_dappfile.md

Added article "What is dappfile" and "minimal dappfile".

[doc] Reference/Dappfile "What is dappfile?"

---

samples/main/dappfile.yaml

Run `dapp sample create main` in target directory to deploy dapp sample files.

(doc) Main dapp sample

---

docs/_data/sidebars/reference.yml
docs/pages/reference/build/mount_directive.md

Added info about using mounts in the documentation.

[docs] Using mounts

---

lib/dapp/dimg/build/stage/base.rb
lib/dapp/dimg/build/stage/from.rb
lib/dapp/dimg/image/stage.rb

Improve mounts

---

pkg/config/raw_dimg.go

* git sources add after beforeInstall stage
* fix

Improve asLayers

---

lib/dapp/dapp/option_tags.rb

Update gitlab variables that are used in tags

---

lib/dapp/dapp/slug.rb
spec/unit/consistent_uniq_slug_spec.rb

dapp slug: implement DAPP_SLUG_V3

---

docs/pages/reference/registry/tag.md

Added doc registry tag article

(doc) Reference/registry/tag

---

lib/dapp/kube/kubernetes/manager/deployment.rb

Watch ReplicaSet readiness for Deployment (rs ready replicas >= deployment spec replicas).

Wait for Deployment with unavailable-replicas

---

docs/pages/reference/registry/pull.md

[Docs] Pull example

---

docs/pages/reference/registry/cleaning.md

Added example to the Cleaning article

WIP: [docs] Cleaning example

---

docs/pages/reference/build/assembly_instructions.md

- beforeInstall, install, beforeSetup, setup
- shell, ansible
- git.stageDependencies
- cacheVersion

[docs] Reference/Build/Running assembly instructions

---

docs/_data/sidebars/how_to.yml
docs/pages/how_to/artifacts.md

[docs] HOWTO: Using artifacts

---

pkg/image/stage_container.go

docker_instructions: fix USER instruction logic

---

lib/dapp/kube/dapp/command/deploy.rb

Also disable sentry info message for job failure.

[deploy] Raise error on ruby2go deploy-watcher error

---

lib/dapp/dimg/dimg.rb
lib/dapp/dimg/image/stage.rb

dapp dimg tag/push: override existing local image

---

pkg/true_git/diff_parser.go

When file mode changed with content in the git, dapp applies only mode change to the file in the image.

Fix patch error: content change not applied in image

---

pkg/deploy/secret/base_manager.go
pkg/secret/aes_secret.go

 [go deploy] ignore empty string during encoding

---

cmd/build/build.go
pkg/build/build_phase.go
pkg/build/conveyor.go
pkg/build/prepare_images_phase.go
pkg/true_git/init.go

* Initialize ssh auth sock in conveyor
* Fix unlocking of built images

[go build] build fixes

---

pkg/deploy/helm.go

- watch for jobs that are not hooks
- watch for pods, daemonsets, statefulsets
A support of https://github.com/flant/kubedog/pull/33

Add more watchers in deploy command

---

cmd/dapp/bp/bp.go
cmd/dapp/build/build.go
pkg/build/build_phase.go
pkg/build/conveyor.go

Implement error/before error introspection

---

pkg/build/stage/docker_instructions.go
pkg/config/docker.go
pkg/config/raw_docker.go
pkg/image/interface.go
pkg/image/stage_container_options.go

close https://github.com/flant/dapp/issues/950

Support STOPSIGNAL/HEALTHCHECK docker instructions

---

pkg/build/build_phase.go
pkg/build/conveyor.go
pkg/build/initialization_phase.go
pkg/build/prepare_images_phase.go
pkg/build/push_phase.go
pkg/build/renew_phase.go
pkg/build/should_be_built_phase.go
pkg/build/signatures_phase.go
pkg/build/stage/base.go
pkg/build/stage/ga.go
pkg/build/stage/ga_latest_patch.go
pkg/build/stage/git_artifact.go
pkg/build/stage/interface.go
pkg/cleanup/reset.go
pkg/image/interface.go

close https://github.com/flant/dapp/issues/1151

Implement renew phase

---

pkg/deploy/helm.go

Fix default helm 5min timeout: set timeout to 24hours

---

pkg/build/builder/ansible.go

Fix ANSIBLE_ARGS env doesn't work properly

---

cmd/dapp/main.go
cmd/dapp/tag/tag.go
pkg/build/conveyor.go
pkg/build/tag_phase.go

Tag command

---

cmd/dapp/common/tags.go

Validate `--tag` Docker tag parameter

---

pkg/build/build_phase.go

Force save stages cache by default

---

cmd/dapp/flush/flush.go
pkg/cleanup/common.go
pkg/cleanup/flush.go

* force remove running container
* cleanup containers before flushing images
* support :minikube shortcut

Up flush command logic

---

docs/pages/how_to/artifacts.md
docs/pages/how_to/deploy_into_kubernetes.md
docs/pages/how_to/getting_started.md
docs/pages/how_to/mounts.md
docs/pages/how_to/multi_images.md
docs/pages/reference/deploy/minikube.md

Check code in following articles:
[howto] Building multiple images
[howto] Getting started
[howto] Deploy into kubernetes
[howto] Using artifacts
[howto] Using mounts
[reference] Minikube

[doc] Example code checking

---

README.md

Update README, add anchor for docs-and-support

Update README.md, add href for docs-and-support

---

cmd/werf/host/cleanup/cleanup.go
cmd/werf/host/purge/purge.go
cmd/werf/purge/purge.go
cmd/werf/stages/cleanup/cleanup.go
cmd/werf/stages/purge/purge.go
pkg/cleanup/common.go
pkg/cleanup/common_project.go
pkg/cleanup/host_cleanup.go
pkg/cleanup/reset.go
pkg/cleanup/sync.go
pkg/logger/colorize.go
pkg/logger/log.go
pkg/logger/log_base.go
pkg/logger/log_process.go
pkg/tmp_manager/gc.go
pkg/tmp_manager/purge.go

* host cleanup removes dangling images
* host cleanup/purge dry-run mode
* logging

Update cleanup commands logic

---

docs/pages/how_to/artifacts.md
docs/pages/how_to/deploy_into_kubernetes.md
docs/pages/how_to/getting_started.md
docs/pages/how_to/gitlab_ci_cd_integration.md
docs/pages/how_to/mounts.md
docs/pages/how_to/multi_images.md

Howto updates according to the new cli commands

[doc] Howto updates according to the new cli commands

---

cmd/werf/purge/purge.go
pkg/cleaning/cleanup.go
pkg/cleaning/images_cleanup.go
pkg/cleaning/purge.go
pkg/cleaning/stages_cleanup.go
pkg/cleaning/stages_purge.go

Modify stages cleanup command logic
* Purge stages storage if specified images repo is empty
* Modify stages cleanup command lock name (lock only parallel stages cleanup commands)
Unset stages purge command lock
Refactor cleaning pkg

Modify stages cleanup command logic

---

README.md

- add license section
- fix multiwerf script url

feat: Add Backward Compatibility Promise in README

---

cmd/werf/common/common.go
pkg/build/build_stages_phase.go
pkg/build/initialization_phase.go
pkg/build/publish_images_phase.go
pkg/build/signatures_phase.go
pkg/git_repo/base.go
pkg/logger/log_process.go
pkg/ssh_agent/ssh_agent.go

* Split image on repository, tag and image_id in building info block
* Log publishing process instead of pushing
* Log signatures instead of images in signatures phase
* Change some info messages to common
* Reject logger log state format
* Improve git paths logging

Improve logging

---

cmd/werf/cleanup/cleanup.go
cmd/werf/images/cleanup/cleanup.go
pkg/cleaning/images_cleanup.go

close https://github.com/flant/werf/issues/1225

Images cleanup whitelist for multiple k8s contexts

---

docs/pages/how_to/gitlab_ci_cd_integration.md

[doc] HowTo Gitlab CI updated

---

docs/pages/how_to/gitlab_ci_cd_integration.md

[docs] HowTo GitLab CI updates

---

pkg/true_git/archive.go
pkg/true_git/patch.go
pkg/true_git/work_tree.go

(https://docs.gitlab.com/ee/ci/git_submodules.html#using-git-submodules-in-your-ci-jobs)

Fix: submodule authentication required: do submodules sync

---

docs/pages/reference/deploy/secrets.md

Updated section of work with secrets.

[doc] 'Working with secrets' updated

---

docs/_data/sidebars/reference.yml
docs/pages/how_to/getting_started.md
docs/pages/reference/build/base_image.md
docs/pages/reference/build/naming.md
docs/pages/reference/config.md
docs/pages/reference/deploy/deploy_to_kubernetes.md
docs/pages/reference/registry/authorization.md
docs/pages/reference/registry/cleaning.md
docs/pages/reference/registry/image_naming.md
docs/pages/reference/registry/publish.md
docs/pages/reference/registry/tag.md

Fixed some incorrect command syntax.

[doc] Documentation updates

---

pkg/build/stage/docker_instructions.go

Fix docker instructions stage signature

---

go-build.sh
pkg/build/builder/ansible/logger.py
pkg/logger/log_process.go
pkg/pylogger/main.go
playground/python_logger/main.go

Also "*Ln" functions in python has been changed to versions without newline autoprint (removed suffix "Ln").

    Python logger: LogProcessStart, LogProcessEnd, LogProcessStepEnd, LogProcessFail implementation

---

pkg/true_git/init.go

* check only MAJOR.MINOR.PATCH version part
relate https://github.com/flant/werf/issues/1429

Fix git version validation

---

docs/pages/how_to/getting_started.md

Fixed error in Getting started HowTo image build

[doc] Fix build error in Getting started HowTo

---

docs/pages/reference/build/artifact.md
docs/pages/reference/build/base_image.md
docs/pages/reference/build/image_directives.md
pkg/build/conveyor.go
pkg/build/image.go
pkg/build/initialization_phase.go
pkg/build/stage/from.go
pkg/config/image_base.go
pkg/config/raw_image.go

* check base image registry id before pulling
* implement fromLatest directive
* fromLatest: true
* from stage depends on base image id
* base image registry must be available
close https://github.com/flant/werf/issues/1245
close https://github.com/flant/werf/issues/1212

Improve from stage logic

---

cmd/werf/host/purge/purge.go
pkg/cleaning/common.go
pkg/cleaning/host_purge.go

* --force: remove containers that use werf docker images

[cleaning] host purge --force

---

cmd/werf/cleanup/cleanup.go
cmd/werf/images/cleanup/cleanup.go
pkg/cleaning/images_cleanup.go

close https://github.com/flant/werf/issues/1458

[cleaning] Fix images cleanup in non-git project

---

cmd/werf/cleanup/cleanup.go
cmd/werf/common/common.go
cmd/werf/host/cleanup/cleanup.go
cmd/werf/host/purge/purge.go
cmd/werf/images/cleanup/cleanup.go
cmd/werf/images/purge/purge.go
cmd/werf/purge/purge.go
cmd/werf/stages/cleanup/cleanup.go
cmd/werf/stages/purge/purge.go
pkg/cleaning/common.go
pkg/cleaning/common_project.go
pkg/cleaning/host_cleanup.go
pkg/cleaning/host_purge.go
pkg/cleaning/images_purge.go
pkg/cleaning/purge.go
pkg/cleaning/stages_cleanup.go
pkg/cleaning/stages_purge.go
pkg/deploy/helm/templates.go

* add --force option to all purge commands
* add --force option tip in processUsedImages error
* refactor cleaning pkg

[cleaning] Improve cleaning commands

---

go.mod
go.sum
pkg/deploy/helm/release.go
pkg/deploy/helm/resources_waiter.go
pkg/deploy/helm/tiller.go
pkg/deploy/werf_chart/werf_chart.go

* Pass timeout to kubedog multitrack.
* Use LogsFromTime param.

Fix deploy timeout and show logs only since deploy began

---

pkg/deploy/helm/release.go

* handle DELETING release status code

[deploy] Improve auto purge release logic

---

cmd/werf/ci_env/ci_env.go

* $CI_REPOSITORY_URL -> $CI_REPOSITORY_URL

[ci-env] Fix project.werf.io/gitlab-url annotation value

---

pkg/deploy/helm/release.go

The reason: helm brokes deployed release revision in storage on failure. Example below.
Right after successful deploy without errors:
```
$ helm list
NAME                               REVISION    UPDATED                     STATUS      CHART                                APP VERSION    NAMESPACE
ex-dapp-deployment-watcher2-dev    38          Sun Apr 21 15:56:14 2019    DEPLOYED    ex-dapp-deployment-watcher2-0.1.0                   ex-dapp-deployment-watcher2-dev
$ helm get ex-dapp-deployment-watcher2-dev 38
...
containers:
- name: main
...
```
Right after failed deploy:
```
$ helm history ex-dapp-deployment-watcher2-dev
...
38          Sun Apr 21 15:56:14 2019    DEPLOYED      ex-dapp-deployment-watcher2-0.1.0    Upgrade complete
39          Sun Apr 21 15:57:22 2019    FAILED …
```

Run rollback up to 5 times on failures (fix for alpha)

---

pkg/git_repo/base.go
pkg/git_repo/debug.go
pkg/git_repo/local.go
pkg/git_repo/remote.go
pkg/true_git/fsck.go
playground/git-fsck/main.go

Check unreachable git commits in local git clone copy.
Unreachable commit that exists locally should be treated as non existing commit.

Fix git split-brain running werf in parallel

---

go.mod
go.sum
pkg/deploy/helm/release.go
pkg/deploy/helm/resources_waiter.go

relates https://github.com/flant/kubedog/pull/74

[deploy] Prepare multitrack spec

---

docs/pages/how_to/mounts.md

[docs] Howto/Using mounts: Updates

---

docs/pages/reference/build/assembly_instructions.md
docs/pages/reference/build/stage_introspection.md

Updates:
[docs] Reference/Build/stages_introspection
[docs] Reference/Build/assembly_instructions

[docs] Reference/Build/stages_introspection and assembly_instructions: Updates

---

pkg/git_repo/base.go

GitRepo.TagsList contains annotated and non-annotated tags.

Fix images (repo) cleanup deletes images for non-annotated git tags

---

pkg/true_git/archive.go
pkg/true_git/patch.go
pkg/true_git/submodule.go
pkg/true_git/work_tree.go

Do not 'deinit' submodules ever.

Fix submodules 'HTTP Basic: Access denied ... Unable to fetch in submodule path'

---

pkg/deploy/helm/lint.go
pkg/deploy/helm/release.go
pkg/deploy/helm/resources_waiter.go

* werf.io/fail-mode
* werf.io/failures-allowed-per-replica
* werf.io/log-regex
* werf.io/log-regex-for-CONTAINER
* werf.io/skip-logs
* werf.io/skip-logs-for-containers
* werf.io/show-logs-only-for-containers
* werf.io/show-logs-until
* werf.io/skip-events
* werf.io/recreate

Renamed werf deploy annotations

---

pkg/deploy/werf_chart/werf_chart.go

This reverts commit 459b6b579e625c9de8f9a693781783e8e5d0fb55.

Revert "Write stripped version into werf.io/version anno"

---

go.mod
go.sum

This reverts commit 5ad1646e92bf8b8b9f965fdb03afa31828c8f060.

Revert "Update logboek_py dependency"

---

README.md
docs/pages/documentation.md
docs/pages/how_to/deploy_into_kubernetes.md
docs/pages/how_to/getting_started.md
docs/pages/how_to/gitlab_ci_cd_integration.md
docs/pages/how_to/mounts.md
docs/pages/how_to/multi_images.md
docs/pages/reference/build/artifact.md
docs/pages/reference/build/stages_and_images.md
docs/pages/reference/config.md
docs/pages/reference/deploy/chart_configuration.md
docs/pages/reference/deploy/secrets.md
docs/pages/reference/index.md
docs/pages/reference/registry/authorization.md
docs/pages/reference/registry/cleaning.md
docs/pages/reference/registry/image_naming.md
docs/pages/reference/registry/pull.md

* fix broken links and anchors

[docs] Tiny improvements and fixes

---

docs/_includes/footer.html
docs/_includes/topnav.html
docs/css/header.css
docs/js/customscripts.js

Updated some site template files.

[docs] site template updates

---

pkg/docker_registry/main.go

Error: deleting image "registry/user/project@sha256": <nil>

[docker registry] Fix authentication error without message

---

cmd/werf/deploy/main.go
docs/_includes/cli/werf_deploy.md
docs/_includes/readme/features.md
docs/_includes/readme/installation.md
docs/pages/configuration/stapel_artifact.md
docs/pages/reference/deploy_process/deploy_into_kubernetes.md
docs/pages/reference/publish_process.md

[docs] `--tag-git-*` options design rationale added
[docs] Note on artifact stapel usage
[docs] More explanations on `werf deploy --tag-custom` example

[docs] More docs explanations added and small edits

---

docs/_data/stages.yml
docs/pages/configuration/dockerfile_image.md
pkg/build/initialization_phase.go
pkg/build/stage/dockerfile.go
pkg/config/image_from_dockerfile.go
pkg/config/raw_image_from_dockerfile.go

close https://github.com/flant/werf/issues/1690

[dockerfile image] --add-host support

---

docs/pages/configuration/stapel_image/git_directive.md
pkg/build/stage/git_cache.go

* Stage is empty if patch size is lower than patch size step (1MB)
* Patch size is 0 if any git mapping commit from previous built image is not exists

[stapel builder] Improve git cache stage logic

---

pkg/build/initialization_phase.go

* The pattern does not check root files

[dockerignore] Fix pattern with starting double asterisks does not work properly

---

cmd/werf/ci_env/ci_env.go

relates https://github.com/flant/werf/issues/1698

[ci-env] Fix Gitlab 12.1.4+ output: turn off color mode

---

docs/_data/sidebars/documentation.yml
docs/pages/reference/deploy_process/experimental_three_way_merge.md
go.mod
go.sum

https://github.com/flant/helm/pull/12

3-way-merge: annotations mode

---

cmd/werf/ci_env/ci_env.go
docs/pages/guides/unsupported_ci_cd_integration.md
docs/pages/reference/deploy_process/deploy_into_kubernetes.md
docs/pages/reference/deploy_process/differences_with_helm.md
docs/pages/reference/plugging_into_cicd/gitlab_ci.md
docs/pages/reference/plugging_into_cicd/overview.md

* Add annotations
* ci.werf.io/commit
* gitlab.ci.werf.io/job-url
* gitlab.ci.werf.io/pipeline-url
* Rename annotation:
* project.werf.io/gitlab-url to project.werf.io/git

[ci-env] Add extra annotations for GitLab

---

cmd/werf/cleanup/cleanup.go
cmd/werf/images/cleanup/cleanup.go
go.mod
go.sum
pkg/cleaning/images_cleanup.go

relates https://github.com/flant/kubedog/pull/137
closes https://github.com/flant/werf/issues/1716

[cleanup] Log kubernetes context names

---

pkg/true_git/archive.go
pkg/true_git/patch.go
pkg/true_git/submodule.go
pkg/true_git/work_tree.go

This reverts commit 9e64b8154feaa8a392f0edad5f668e92895427c6.

Revert "[speedup git] Optimize git worktree switch procedure"

---

cmd/werf/ci_env/ci_env.go
docs/pages/reference/plugging_into_cicd/gitlab_ci.md
docs/pages/reference/plugging_into_cicd/overview.md

* WERF_ADD_ANNOTATION_GILAB_CI_PIPELINE_URL -> WERF_ADD_ANNOTATION_GITLAB_CI_PIPELINE_URL

[ci-env] Fix typo in environment name of extra anno

---

pkg/deploy/deploy.go
pkg/deploy/lint.go
pkg/deploy/render.go

closes https://github.com/flant/werf/issues/1580

[deploy] Reject auto replace of chart path in helm errors

---

go-build.sh
scripts/lib/release/build.sh

relates https://github.com/flant/werf/issues/1767

[dockerfile] Fix BuildKit RUN --mount flag does not work

---

pkg/build/stage/git_mapping.go

close https://github.com/flant/werf/issues/1771

[stapel builder] Fix `warning: unable to access '/root/.config/git/attributes': Permission denied`

---

docs/pages/guides/advanced_build/artifacts.md
docs/pages/guides/advanced_build/first_application.md
docs/pages/guides/advanced_build/mounts.md
docs/pages/guides/advanced_build/multi_images_application.md

- pin image versions in some examples

Guide examples review

---

cmd/werf/main_test.go
scripts/tests/run_integration_tests_with_coverage.sh

based on https://github.com/flant/werf/pull/1800

[tests] Improve werf test binary with coverage 

---

pkg/git_repo/base.go
pkg/git_repo/local.go
pkg/git_repo/remote.go
pkg/git_repo/work_tree.go
pkg/lock/base.go
pkg/true_git/archive.go
pkg/true_git/patch.go
pkg/true_git/submodule.go
pkg/true_git/work_tree.go

Reverted until https://github.com/flant/werf/issues/1825 fix

Revert git worktree switch 

---

pkg/deploy/deploy.go
pkg/deploy/werf_chart/werf_chart.go

close https://github.com/flant/werf/issues/1811

[deploy] Hide secret values in error

---

go.mod
go.sum

https://github.com/flant/helm/pull/20

[3-way-merge] Create two pass 3wm repair patch: fix false-positive repair patches

---

go.mod
go.sum

- https://github.com/flant/helm/pull/20
- https://github.com/flant/helm/pull/21
- https://github.com/flant/helm/pull/22

[v1.0.4] [3-way-merge] Create two pass 3wm repair patch: fix false-positive repair patches

---

pkg/build/builder/shell.go
pkg/build/initialization_phase.go
pkg/build/stage/git_archive.go
pkg/build/stage/git_mapping.go
pkg/build/stage/git_patch.go
pkg/stapel/stapel.go
tests/integration/build/stapel_image/git/helpers.bash
tests/integration/build/stapel_image/git/main_git_stages.bats
tests/integration/build/stapel_image/git/remove_empty_dirs.bats
tests/integration/guides/deploy_into_kubernetes/deploy_into_kubernetes.bats

[stapel image] Git stages: fix argument list too long error

---

pkg/stapel/stapel.go
scripts/stapel/dev_build.sh
stapel/Dockerfile
tests/integration/ansible/stapel-apt-mark-link-panic-1820/test.bats
tests/integration/ansible/stapel-apt-mark-link-panic-1820/werf.yaml
tests/integration/guides/advanced_build/artifacts/artifacts.bats
tests/integration/guides/advanced_build/first_application/first_application.bats
tests/integration/guides/advanced_build/multi_images/multi_images.bats

fixes https://github.com/flant/werf/issues/1820

[stapel] Fix 'APTPKG_5.0 not defined in file libapt-pkg.so.5.0 with link time reference'

---

docs/pages/reference/deploy_process/differences_with_helm.md
docs/pages/reference/deploy_process/experimental_three_way_merge.md
go.mod
go.sum

https://github.com/flant/helm/pull/23

Fix false-positive repair-patches (part 2)

---

pkg/build/initialization_phase.go
pkg/git_repo/git_repo.go
pkg/git_repo/local.go
pkg/git_repo/remote.go
pkg/git_repo/work_tree.go

fixes https://github.com/flant/werf/issues/1038

[git] Refactor remote git repo clone path; fix 'invalid cross-device link' error

---

cmd/werf/common/common.go
cmd/werf/deploy/main.go
cmd/werf/helm/deploy_chart/main.go
go.mod
go.sum
pkg/deploy/deploy.go
pkg/deploy/helm/release.go
pkg/deploy/helm/tiller.go

https://github.com/flant/helm/pull/24

[3-way-merge] Update option to use 3 way merge patch, adopt existing resource

---

integration/deploytracking/kubedog_multitrack_test.go
integration/deploytracking/suite_test.go
integration/utils/werfexec/werfexec.go

* Build actual or use certain binary (e.g. werf with coverage)
* Random project name

[tests] Upd deploytracking suite

---

go.mod
go.sum
integration/releaseserver/resources_owner_checker_test.go
integration/utils/werfexec/werfexec.go

fixes https://github.com/flant/werf/issues/1902

[3-way-merge] Fix owner release refs inconsistent state on helm rollback

---

pkg/deploy/helm/tiller.go

fixes https://github.com/flant/werf/issues/1900

[v1.0.4] Fix panic in deploy

---

pkg/true_git/work_tree.go

Remove invalid work tree cache dir in that case before work tree switch to target commit.

[git] Handle invalid work tree cache when git repo of the work tree gone (2)

---

pkg/util/secretvalues/mask.go

Previous: https://github.com/flant/werf/pull/1939
Trim spaces and split by newlines secret data.

[deploy] Fix masking of secret values (2)

---

pkg/build/image.go
pkg/build/initialization_phase.go
pkg/build/should_be_built_phase.go

close https://github.com/flant/werf/issues/1666

STAGE is not exist in stages storage: detailed info message

---

docs/_config.yml
docs/_config_ru.yml
docs/_includes/footer.html
docs/pages_ru/index.md
docs/sitemap.xml

Some documentation improvement

[doc] Updates

---

docs/_includes/slack_popup.html
docs/_includes/topnav.html
docs/pages/index.md
docs/pages_ru/index.md

[doc] On pages other than the main, the link to the slack did not work

[doc] Fix slack links

---

go.mod
go.sum
integration/ansible/ansible_test.go

https://github.com/flant/helm/pull/32

[3-way-merge] No additional patches filtering when creating final 3wm patch; fix ansible test typo

---

go.mod
go.sum

https://github.com/flant/kubedog/pull/156

[deploy] Fix sts hangs on warning 'POST operation against Pod could not be completed at this time'

---

docs/_includes/footer.html
docs/pages/index.md
docs/pages_ru/index.md

- Rearrange blocks on the main page
- Fix footer

Documentation improvement

---

cmd/werf/helm/secret/common/edit.go

relate https://github.com/flant/werf/issues/1869
`EDITOR="subl -n -w"`
`EDITOR="code -r -w"`

[secret edit] Fix EDITOR with args

---

docs/pages/releases.md
docs/pages_ru/releases.md

[Doc] Fix releases page

---

docs/_data/channels_info.yml

[doc] Fixed incorrect markup in the Rock-solid channel  description.

[doc] Fix bug

---

docs/pages/reference/toolbox/slug.md
docs/pages/reference/toolbox/ssh.md

Files:
- slug.md
- ssh.md
Please, pay close attention to the https://github.com/flant/werf/blob/docs_reference_toolbox/docs/pages/reference/toolbox/ssh.md#how-werf-works-with-a-ssh-agent 
since I am not sure if I got that right.

[docs] various fixes and improvements

---

docs/_includes/footer.html
docs/js/customscripts.js

Updated the logic of the version menu on the site, due to changes in the release policy (timed to the release of the stable version).

[Docs] Website version menu updates

---

docs/_includes/footer.html
docs/css/index.css
docs/pages/index.md
docs/pages_ru/index.md

Site generation time has been hidden.

[docs] Hide site generation time in the footer

---

.github/workflows/tests.yml

https://github.community/t5/GitHub-Actions/Windows-tests-worked-yesterday-broken-today/m-p/43614#M5449

[ci] Disable windows runner due to configuration changes of runner

---

docs/pages/index.md
docs/pages_ru/index.md

The main page on the website was updated

[docs] Updated the main page

---

pkg/deploy/helm/lint.go
pkg/deploy/helm/resources_waiter.go

fixes https://github.com/flant/werf/issues/2071
refs https://github.com/flant/werf/pull/2072

[deploy] fix werf.io/failures-allowed-per-replica does not affect Job tracking

---

pkg/build/build_phase.go
pkg/build/conveyor.go
pkg/build/phase.go
pkg/build/publish_images_phase.go
pkg/build/should_be_built_phase.go

Refactored runPhases method, added more hooks to Phase interface.

Signatures and stages storage rework: implement build-and-publish, publish, should-be-built

---

pkg/ssh_agent/ssh_agent.go

refs https://github.com/flant/werf/issues/2134

Fix ssh-agent not adding default keys and keys passed by the `--ssh-key` option

---

pkg/build/publish_images_phase.go

fixes https://github.com/flant/werf/issues/2178

Fix publish only specified images

---

cmd/werf/build_and_publish/main.go
cmd/werf/deploy/main.go
cmd/werf/helm/delete/delete.go
cmd/werf/helm/get/get.go
cmd/werf/helm/get_autogenerated_values/main.go
cmd/werf/helm/history/history.go
cmd/werf/helm/lint/lint.go
cmd/werf/helm/list/list.go
cmd/werf/helm/render/render.go
cmd/werf/helm/rollback/rollback.go
cmd/werf/host/cleanup/cleanup.go
cmd/werf/images/publish/cmd_factory/main.go
cmd/werf/run/run.go
cmd/werf/stage/image/main.go
cmd/werf/stages/build/cmd_factory/main.go
pkg/true_git/common.go
pkg/true_git/init.go
pkg/true_git/submodule.go
pkg/true_git/work_tree.go

- 'Switch work tree to commit ...' should be Info, not Default.

[logs] Fix logs excess messages

---

pkg/build/build_phase.go
pkg/logging/main.go

* Hide docker container output in silent mode
* Initialize stapel container before preparing of stage run args

[logging] Tiny improvements

---

cmd/werf/build_and_publish/main.go
cmd/werf/cleanup/cleanup.go
cmd/werf/common/common.go
cmd/werf/deploy/main.go
cmd/werf/helm/common/common.go
cmd/werf/helm/get_autogenerated_values/main.go
cmd/werf/helm/render/render.go
cmd/werf/images/cleanup/cleanup.go
cmd/werf/images/publish/cmd_factory/main.go
cmd/werf/images/purge/purge.go
cmd/werf/managed_images/add/add.go
cmd/werf/managed_images/ls/ls.go
cmd/werf/managed_images/rm/rm.go
cmd/werf/purge/purge.go
cmd/werf/run/run.go
cmd/werf/stage/image/main.go
cmd/werf/stages/build/cmd_factory/main.go
cmd/werf/stages/cleanup/cleanup.go
cmd/werf/stages/purge/purge.go
pkg/build/conveyor.go
pkg/build/publish_images_phase.go
pkg/storage/images_repo.go
pkg/storage/local_stages_storage.go

- Refactor creating of StagesStorage, StagesStorageCache, ImagesRepo and StorageLockManager objects in cmd.
- Added temporal method to get ImagesRepoManager from ImagesRepo for compatibility with an old codebase.

Remote storages support: refactor images-repo and stages-storage objects creation

---

docs/css/index.css
docs/images/icons/rss.svg
docs/pages/feed.xml
docs/pages/releases.md
docs/pages_ru/feed.xml
docs/pages_ru/releases.md

- There is the main feed with all events on all update channels - werf.io/feed.xml
- There are feeds for update channels of all active releases. Ex. werf.io/feed-1.1-alpha.xml
- Added RSS-links on the releases page
Closes: https://github.com/flant/werf/issues/2209

Added rss feeds

---

cmd/werf/ci_env/ci_env.go

[cleanup] Disable stages-signature tagging strategy cleanup by default in werf ci-env

---

cmd/werf/common/common.go
cmd/werf/helm/lint/lint.go

* Add --insecure-registry, --skip-tls-verify-registry for images repo and stages repo by default.
* Change stub "IMAGES_REPO" to "stub/repository".

Fix lint/render panic

---

pkg/build/image.go

Panic occured when base image has been pulled from the registry.

Remote storages support: fix panic 'github.com/flant/werf/pkg/build/stage.(*BaseStage).getServiceMountsFromLabels'

---

pkg/deploy/helm/templates.go

https://github.com/ghodss/yaml/issues/59

Fix extra annotations/labels are not added to k8s resources

---

cmd/werf/common/common.go
pkg/stages_manager/stages_manager.go
pkg/storage/file_stages_storage_cache.go
pkg/storage/stages_storage_cache.go

Implemented StagesManager.DeleteStages method.

Remote storages support: clean stages-storage-cache in stages-cleanup procedure

---

pkg/true_git/diff_parser.go

Handle git-diff patch `index` line in v1.1 compatible manner.

Fix gitLatestPatch signature differs in different worktrees

---

pkg/build/conveyor.go

Isolate rsync server configs properly.

Fix '@ERROR: auth failed on module import' when importing from aritfact stage

---

pkg/storage/file_stages_storage_cache.go

Invalidate stages-storage-cache directory when old cache directory exists. Remove old and current stages-storage-cache directories in this case.

Remote storages support: safe switch between alpha and beta werf versions

---

pkg/build/build_phase.go
pkg/build/conveyor.go
pkg/build/stage/base.go
pkg/build/stage/conveyor.go
pkg/build/stage/git.go
pkg/build/stage/git_patch.go
pkg/build/stage/interface.go
pkg/build/stage/user_with_git_patch.go
pkg/build/stages_iterator.go

- remove git-building-stage map from Conveyor;
- remove AfterSignatureCalculated Stage hook.

Fix gitLatestPatch not built when previous stage has been discarded during build

---

pkg/build/stage/dockerfile.go

* dockerfile stage signature should take into account ONBUILD value;
* dockerfile stage that uses another one with ONBUILD instructions should calculate files checksum for COPY/ADD trigger instruction in addition to ONBUILD value.

[v1.1.8][dockerfile] Fix ONBUILD instruction processing

---

.github/workflows/docs_tests.yml

There was a bug in running htmlproofer.
Fix: #2379

[tests] Fix bug in the Documentation validation test

---

go.mod
go.sum

https://github.com/flant/helm/pull/44
Refs https://github.com/flant/werf/issues/2388

Update flant/helm: fix panic during sub chart validation

---

pkg/build/stage/base.go

Fix compilation error due to failed cherry-pick.

[v1.1.8][2] Fix git-related stages selection when multiple git-mappings by the same url used

---

pkg/slug/slug.go
pkg/slug/slug_test.go

Fix kubernetes namespace slug: should not allow capital letters

---

pkg/slug/slug.go
pkg/slug/slug_test.go

[v1.1.9] Fix kubernetes namespace slug: should not allow capital letters

---

docs/pages/configuration/introduction.md
docs/pages_ru/configuration/introduction.md
pkg/config/parser.go

```
{{ range $path, $content := .Files.Glob ".werf/files/**" }}
{{ $path }}: |
{{ $content | indent 2 }}
{{ end }}
```

[config] Add .Files.Glob Go template function

---

pkg/storage/repo_stages_storage.go

panic: runtime error: index out of range [1] with length 1
github.com/flant/werf/pkg/storage.getSignatureAndUniqueIDFromRepoStageImageTag(0xc000832a88, 0x4, 0x47, 0xc000ff8d58, 0x2, 0x2, 0x0)

Ignore stages storage tags not matching the expected format

---

docs/pages/configuration/introduction.md
docs/pages/guides/gitlab_ci_cd_integration.md
docs/pages_ru/configuration/introduction.md
pkg/config/parser.go

Project file wih template:
```
{{ tpl (.Files.Get "service/werf_partial.yaml") . }}
```
Environment variable with template:
```
{{ tpl (env "EXTERNAL_TEMPLATE") . }}
```

[config] Add tpl function to evaluate strings as templates inside a template

---

pkg/build/publish_images_phase.go

Do not check published docker-image-ID for images being published with content-based `stages-signature`.

Fix publish performance for `--tag-by-stages-signature`

---

go.mod
go.sum
pkg/git_repo/base.go
pkg/git_repo/local.go
pkg/git_repo/remote.go
pkg/true_git/ls_tree/ls_tree.go
pkg/true_git/repository.go

Using distorhead/go-git with the following pending PR: https://github.com/go-git/go-git/pull/88

[git] Update go-git: fix "submodule not initialized" errors

---

docs/pages/index.md

Added articles where necessary, rephrased several sentences.

[docs] Review index page

---

docs/js/customscripts.js
docs/pages/index.md
docs/pages_ru/index.md

Requests will be sent only once an hour

[docs] Fixed github stats api usage

---

pkg/build/build_phase.go
pkg/build/publish_images_phase.go
pkg/image/const.go

- Set image version label: werf-image-version.
- Set stage content signature label: werf-stage-content-signature.

Set content-signature for all stages into label

---

pkg/build/publish_images_phase.go

Check content signature of already existing image in the repo to check if current image changed and there is a need to perform publish again.
This check will only occur for `--tag-custom`, `--tag-git-tag` or `--tag-git-branch` options and does not occur `--tag-by-stages-signature` content based tagging option.

Refine publish procedure: check already existing image by content signature

---

cmd/werf/cleanup/cleanup.go
cmd/werf/images/cleanup/cleanup.go
cmd/werf/stages/cleanup/cleanup.go
docs/_includes/cli/werf_cleanup.md
docs/_includes/cli/werf_images_cleanup.md
go.mod
go.sum
pkg/cleaning/cleanup.go
pkg/cleaning/images_cleanup.go
pkg/cleaning/images_cleanup_reference_to_scan.go
pkg/cleaning/images_cleanup_scanner.go
pkg/cleaning/stages_cleanup.go
pkg/git_repo/local.go
pkg/storage/local_docker_server_stages_storage.go
pkg/storage/repo_stages_storage.go
pkg/true_git/repository.go

https://github.com/werf/werf/issues/2212

[cleanup] Git history based algorithm

---

docs/pages/configuration/stapel_image/git_directive.md

The article underwent an exhaustive review, some phrases were reformulated.

DOCS_review_stapel_git_directive 

---

docs/_data/stages.yml
docs/pages/configuration/stapel_image/assembly_instructions.md
docs/pages/configuration/stapel_image/docker_directive.md

Reviewed the assembly instructions article.

DOCS_review_stapel_assembly_instructions

---

cmd/werf/common/synchronization.go

Fix --synchronization-kube-context param not working.

Added separate kube-connection for synchronization components (part 2, fixes)

---

cmd/werf/common/synchronization.go

Check KUBECONFIG env var setting and print warnings.

Improve validation of kube-connection params validation for synchronization components

---

pkg/build/build_phase.go

close https://github.com/werf/werf/issues/2548

[managed images] Ignore artifact names

---

pkg/build/conveyor.go

The complete commit history is enough for all commands except images cleanup

Do origin fetch only when git shallow clone is detected

---

pkg/storage/synchronization_server/http_helpers.go
pkg/storage/synchronization_server/synchronization_server.go

- GET /health gives `{"err":"","echo":"","status":"OK"}`.
- POST /heath + body `{"echo": "HEY!"}` gives: `{"err":"","echo":"HEY!","status":"OK"}`.

Synchronization server basic health check procedure

---

pkg/docker_registry/gitlab_registry.go

More details in gitlab-org/container-registry documentation:
* https://gitlab.com/gitlab-org/container-registry/-/blob/release/2.9-gitlab/docs/spec/api.md#deleting-a-tag
* https://gitlab.com/gitlab-org/container-registry/-/blob/release/2.9-gitlab/docs/spec/api.md#deleting-an-image
close https://github.com/werf/werf/issues/2570

[cleanup] Gitlab registry implementation: use deleting a tag method instead of an image

---

pkg/git_repo/status/status.go
pkg/true_git/ls_tree/ls_tree.go

close https://github.com/werf/werf/issues/2592

[ls tree] Fix submodule processing fails when its name and path are not equal

---

pkg/git_repo/status/result.go

"Modified" status of file in staging (git) should process as "Added" status.

[dockerfile] Fix handling specific status of a local uncommitted file

---

pkg/docker_registry/gitlab_registry.go

Deleting a tag (https://gitlab.com/gitlab-org/container-registry/-/blob/master/docs/spec/api.md#deleting-a-tag) method is available since the v2.8.0-gitlab version of GitLab Docker registry implementation.

[cleanup] GitLab: fix unrecognized status code during DELETE

---

cmd/werf/common/deploy_params.go
pkg/config/meta_deploy_templates.go
pkg/config/raw_meta_deploy_templates.go

Fix deploy meta config templates defaults.

Fix helm release name not slugged by default anymore

---

pkg/build/build_phase.go
pkg/build/stage/base.go
pkg/build/stage/imports.go
pkg/image/manifest_cache.go
pkg/slug/slug.go
pkg/slug/slug_test.go
pkg/stages_manager/stages_manager.go

```
WARNING: Image REPO:bd249b73e7b93721566e5684ea60f0617e30c098af59920d11441e01-1596714926151 deletion failed: parsing reference "REPO@": could not parse reference: REPO@
```

[cleanup] Fix could not parse reference warning

---

pkg/build/conveyor.go
pkg/build/stage/git_mapping.go

* Synchronize goroutines with mutexes

[git mapping] Fix fatal error: concurrent map writes

---

cmd/werf/common/common.go
docs/_includes/cli/werf_build.md
docs/_includes/cli/werf_build_and_publish.md
docs/_includes/cli/werf_converge.md
docs/_includes/cli/werf_stages_build.md
pkg/build/conveyor.go

- Fix index out of range [0] with length 0
- Maximum 5 parallel tasks by default

Fix parallel tasks limit and set new default (5)

---

pkg/stages_manager/sync_stages.go

Print stages storage address in a werf sync log message

Fix log message format in a werf sync command

---

cmd/werf/common/kubedog.go
docs/pages/guides/advanced_build/first_application.md
docs/pages_ru/guides/advanced_build/first_application.md
pkg/build/build_phase.go
pkg/build/conveyor.go
pkg/container_runtime/stage_image.go
pkg/docker_registry/api.go
pkg/docker_registry/harbor.go

[doc] Fix application in the First application guide as it's built is broken

[doc] Fix the First application guide

---

integration/cleanup/images_cleanup_test.go
pkg/cleaning/images_cleanup.go
pkg/cleaning/images_cleanup_scanner.go

- Reject lazy scanning: check each policy references even it is not needed
- Keep a minimum number of commit hashes in stages storage preserving only the latest commit for each content signature in each policy references

[cleanup] Cleanup meta images 

---

cmd/werf/helm_v3/common.go
cmd/werf/helm_v3/install.go
cmd/werf/helm_v3/upgrade.go
go.mod
go.sum
pkg/deploy/secret/manager.go
pkg/deploy/werf_chart_v2/secret_values.yaml.go
pkg/deploy/werf_chart_v2/werf_chart.go

Refs https://github.com/werf/werf/issues/1606
Refs https://github.com/werf/helm/pull/52

[helm-v3] Secret values support for helm-v3 commands

---

cmd/werf/deploy_v2/main.go
go.mod
go.sum
pkg/deploy/helm/templates.go
pkg/deploy_v2/werf_chart/werf_chart.go

Refs https://github.com/werf/werf/issues/1606
Refs https://github.com/werf/helm/pull/55

[helm-v3] Add support for werf helpers templates and service values

---

pkg/docker_registry/api.go

- The following errors:
- `http2: server sent GOAWAY and closed the connection`
- `http2: Transport received Server's graceful shutdown GOAWAY`
- `REDACTED: UNKNOWN`

[docker registry] Push image with retries when occurring specific error

---

cmd/werf/converge/converge.go
docs/_includes/cli/werf_converge.md
docs/_includes/cli/werf_helm_template.md

Skip building of docker images during converge

werf converge --skip-build support

---

cmd/werf/converge/converge.go
cmd/werf/dismiss/dismiss.go
cmd/werf/helm/helm.go
cmd/werf/helm/install.go
cmd/werf/helm/upgrade.go
pkg/deploy/helm/init.go

Fix initialization of helm release storage namespace.

Fix helm releases created in the default namespace always

---

docs/_data/sidebars/documentation.yml

- moved cli into reference;
- moved development/stapel into internals;
- removed the rest.

[docs][v1.2] Changed sidebar titles

---

docs/_data/sidebars/documentation.yml
docs/pages/documentation/advanced/building_images_with_stapel/artifact.md
docs/pages/documentation/advanced/building_images_with_stapel/assembly_instructions.md
docs/pages/documentation/advanced/building_images_with_stapel/base_image.md
docs/pages/documentation/advanced/building_images_with_stapel/docker_directive.md
docs/pages/documentation/advanced/building_images_with_stapel/git_directive.md
docs/pages/documentation/advanced/building_images_with_stapel/image_directives.md
docs/pages/documentation/advanced/building_images_with_stapel/import_directive.md
docs/pages/documentation/advanced/building_images_with_stapel/mount_directive.md
docs/pages/documentation/advanced/building_images_with_stapel/naming.md
docs/pages/documentation/index.md
docs/pages/documentation/internals/how_ci_cd_integration_works/github_actions.md
docs/pages/documentation/reference/cli/build.md
docs/pages/documentation/reference/cli/ci_env.md
docs/pages/documentation/reference/cli/cleanup.md
docs/pages/documentation/reference/cli/converge.md
docs/pages/documentation/reference/cli/dismiss.md
docs/pages/documentation/reference/cli/purge.md
docs/pages/documentation/reference/cli/run.md
docs/pages/documentation/reference/configuration/cleanup_policies.md
docs/pages/documentation/reference/configuration/image_definition.md
docs/pages/documentation/reference/configuration/introduction.md
docs/pages/documentation/reference/deploy_annotations.md

Also:
- added link to guides;
- fixed broken links.

[docs-v1.2] Reorganize docs sections: added reference

---

docs/_data/sidebars/documentation.yml
docs/pages/documentation/guides.md
docs/pages/documentation/quickstart.md
docs/pages/documentation/using_with_ci_cd_systems.md
docs/pages/index.md
docs/pages/introduction.md

- Guides under-construction page.
- Add quickstart into sidebar.

Small doc refinements

---

pkg/deploy/helm/extra_annotations_and_labels_post_renderer.go

do not inject annotations/labels to empty objects

---

docs/pages/documentation/using_with_ci_cd_systems.md
docs/pages/introduction.md

- define converge process in the introduction;
- refer to converge definition from using-with-ci-cd-systems.

Introduction and using-with-ci-cd-system articles refinements

---

docs/pages/documentation/index.md
docs/pages/documentation/quickstart.md
docs/pages/documentation/using_with_ci_cd_systems.md
docs/pages/introduction.md
docs/pages_ru/documentation/index.md
docs/pages_ru/documentation/quickstart.md
docs/pages_ru/documentation/using_with_ci_cd_systems.md
docs/pages_ru/introduction.md

[DOCS] quickstart + introduction EN-RU

---

cmd/werf/common/common.go
cmd/werf/main.go
cmd/werf/render/render.go
go.mod
go.sum

- render Kubernetes templates.
- repo param is optional: calculate stages digests when passed, build images if not exists;
- render image names stubs if no --repo has been passed.
refs https://github.com/werf/helm/pull/60
refs https://github.com/werf/werf/issues/1606

Introduce 'werf render' command

---

docs/_includes/topnav.html

[web] Make Installation link in the top navigation menu absolute.

[web] Make Installation link in the top navigation menu absolute

---

cmd/werf/docs/md_docs.go
cmd/werf/main.go
cmd/werf/stage/image/main.go
go.sum
integration/build/stapel_image/imports/import_metadata/werf.yaml
integration/build/stapel_image/imports/imports_test.go
integration/cleanup/_fixtures/cleanup_unused_stages/werf.yaml
integration/cleanup/cleanup_test.go
integration/cleanup/purge_test.go
integration/cleanup/suite_test.go
pkg/build/conveyor.go
pkg/build/stage/conveyor.go
pkg/build/stage/imports.go
pkg/cleaning/cleanup.go
pkg/cleaning/purge.go
pkg/image/const.go
pkg/stapel/stapel.go
pkg/storage/import_metadata.go
pkg/storage/local_docker_server_stages_storage.go
pkg/storage/manager/stages_storage.go
pkg/storage/repo_stages_storage.go
pkg/storage/stages_storage.go
pkg/testing/utils/image.go
pkg/testing/utils/storage.go

[stapel] Сaching of imports by files checksum

---

pkg/build/stage/dockerfile.go

fixes https://github.com/werf/werf/issues/2777

[dockerfile] Fix unable to build from scratch (v1.1.22)

---

cmd/werf/docs/md_docs.go
docs/_data/sidebars/_cli.yml
docs/_data/sidebars/_documentation.yml
docs/_data/sidebars/documentation.yml
docs/_includes/sidebar.html
docs/_includes/sidebar_entry.html
docs/pages/documentation/reference/cli/overview.md

- Group commands in the sidebar
- Update overview of command groups: link group of commands to the first command

[docs] Reference/CLI: group commands in sidebar

---

go.mod
go.sum

https://github.com/werf/helm/pull/61

Update helm to v2.17.0

---

go.mod
go.sum

https://github.com/werf/helm/pull/64

Fix 'Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress' error

---

go.mod
go.sum

https://github.com/werf/helm/pull/61

[v1.1.23] Fix 'Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress' error

---

docs/js/installation.js

[docs] Enable beta channel selected by default on the installation page

[docs] Enable beta channel selected by default

---

pkg/config/parser.go

.Files.Get and .Files.Glob now raises an error when specified files has not been found.
Fixes https://github.com/werf/werf/issues/2895
Refs https://github.com/werf/werf/issues/2874

[determinism] Read files from local git repo in .Files.Get and .Files.Glob go-templates directives in the determinism mode

---

pkg/cleaning/git_history_based_cleanup/scanner.go

The keep policy imagesPerReference.last counts several stages that were built on the same commit as one.
Thus, the policy may cover more tags than expected, and this behavior is correct.

[cleanup] Git-history based cleanup improvement

---

pkg/cleaning/cleanup.go
pkg/cleaning/git_history_based_cleanup/scanner.go
pkg/storage/local_docker_server_stages_storage.go

based on #2901 
based on #2896

[cleanup, logging] Update log levels and messages

---

.github/workflows/daily_tests.yml
integration/cleanup/_fixtures/cleanup_unused_stages/werf.yaml
integration/cleanup/cleanup_test.go
integration/cleanup/suite_test.go
integration_k8s/cleanup/cleanup_test.go
integration_k8s/cleanup/suite_test.go

[tests] Cleanup Suite: actualize tests

---

scripts/ci/integration_tests_registries_login.sh

[tests] Update ECR login command

[tests] Update ECR login command

---

pkg/build/conveyor.go
pkg/build/stage/dockerfile.go
pkg/container_runtime/dockerfile_image_builder.go
pkg/docker/image.go
pkg/git_repo/status/result.go

fixes https://github.com/werf/werf/issues/1956

[dockerfile, determinism] Get context and dockerfile from git

---

pkg/build/conveyor.go
pkg/build/stage/dockerfile.go
pkg/config/image_from_dockerfile.go
pkg/config/raw_image_from_dockerfile.go
pkg/context_manager/context_manager.go
pkg/tmp_manager/context.go

- archive contains added files from the project dir;
- tmp archives not cleaned up;
- uncommitted changes warning shows up for addContextFile-s.

Implement addContextFile dockerfile directive: archive only

---

cmd/werf/common/common.go
cmd/werf/common/deploy_params.go
pkg/build/stage/dockerfile.go
pkg/context_manager/context_manager.go

- Fix checking of existance of the `.helm` dir in the local git repo during loading of the chart.
- Fix logging of apply contextAddFile directive procedure: use debug instead of default, add log-process to see consumed time (not much btw).

[determinism] Fixes

---

cmd/werf/common/common.go
cmd/werf/config/render/render.go
pkg/build/conveyor.go
pkg/build/stage/dockerfile.go
pkg/config/parser.go
pkg/deploy/werf_chart/git_loader.go
pkg/git_repo/git_repo.go

- Specific error when env function is used
- Warning message when there is uncommitted werf.yaml
- Warning message when there are uncommitted werf.yaml templates
- Warning message when there are uncommitted helm templates

[logging] Improve feedback in deterministic mode (default)

---

cmd/werf/common/common.go
cmd/werf/common/deploy_params.go
cmd/werf/converge/converge.go
cmd/werf/dismiss/dismiss.go
cmd/werf/helm/helm.go
cmd/werf/helm/install.go
cmd/werf/helm/template.go
cmd/werf/helm/upgrade.go
cmd/werf/render/render.go
pkg/build/conveyor.go
pkg/config/parser.go
pkg/deploy/werf_chart/git_loader.go
pkg/deploy/werf_chart/secret_values.go
pkg/deploy/werf_chart/werf_chart.go
pkg/determinism_inspector/determinism_inspector.go
pkg/git_repo/helpers.go
pkg/werf/global_warnings.go

- Added warnings for uncommitted values-related files and secret files.
- Refactored warnings printing code, added determinism_inspector package.

[determinism] Add more warnings, add determinism-inspector

---

go.mod
go.sum

Refs https://github.com/werf/kubedog/pull/184

Update kubedog: fix Job hanging case, fix color disabled in CI/CD systems

---

go.mod
go.sum

Refs https://github.com/werf/kubedog/pull/184

[v1.1.23] Update kubedog: fix Job hanging case, fix color disabled in CI/CD systems

---

go.mod
go.sum

Refs https://github.com/werf/kubedog/pull/184

[v1.1.22] Update kubedog: fix Job hanging case, fix color disabled in CI/CD systems

---

cmd/werf/common/common.go
cmd/werf/common/deploy_params.go
cmd/werf/run/run.go
pkg/build/conveyor.go
pkg/build/stage/git_latest_patch.go
pkg/config/parser.go
pkg/deploy/secret_manager.go
pkg/deploy/werf_chart/werf_chart.go
pkg/git_repo/helpers.go
pkg/util/file.go

```
$ werf helm upgrade test stable/nginx-ingress --namespace test
Error: unable to decode secret values file "/home/test/.cache/helm/repository/nginx-ingress-1.41.3.tgz/secret-values.yaml": cannot read file "/home/test/.cache/helm/repository/nginx-ingress-1.41.3.tgz/secret-values.yaml": open /home/test/.cache/helm/repository/nginx-ingress-1.41.3.tgz/secret-values.yaml: not a directory
```

[helm] Fix install packaged chart failed

---

cmd/werf/dismiss/dismiss.go
cmd/werf/helm/helm.go
go.mod
go.sum
integration_k8s/releaseserver/resources_adopter_test.go

refs https://github.com/werf/helm/pull/58
refs https://github.com/werf/helm/pull/70

Enable --with-namespace and --with-hooks werf-dismiss options

---

pkg/deploy/helm/templates.go

Removed "status" string field from parser structure.

[v1.1.23] Fix "Error: parsing file ... failed: yaml: unmarshal errors ... cannot unmarshal !!map into string"

---

docs/_includes/head.html
docs/pages/documentation/advanced/configuration/giterminism.md
docs/pages_ru/documentation/advanced/configuration/giterminism.md

Update metainfo in page template.

[web] Update metainfo in page template.

---

cmd/werf/ci_env/ci_env.go
cmd/werf/config/list/list.go
cmd/werf/config/render/render.go
cmd/werf/dismiss/dismiss.go
cmd/werf/helm/get_namespace.go
cmd/werf/helm/get_release.go
cmd/werf/helm/secret/rotate_secret_key/rotate_secret_key.go
cmd/werf/managed_images/add/add.go
cmd/werf/managed_images/ls/ls.go
cmd/werf/managed_images/rm/rm.go
cmd/werf/purge/purge.go

```
Version: dev
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x1a9c289]
github.com/Masterminds/semver.(*Version).Prerelease(...)
/go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:146
```

[dev] Fix not initialized true git package

---

.github/workflows/release_publisher.yml

[CI] Update runner tag in workflow.

---

pkg/docker/image.go

https://github.com/werf/werf/issues/3028

[dockerfile] Force BuildKit deactivation

---

integration/build/stapel_image/git/file_lifecycle_test.go
pkg/true_git/dev_branch.go
pkg/true_git/work_tree.go

fix https://github.com/werf/werf/issues/3033

Fix some issues with developer mode on windows

---

integration/build/stapel_image/git/file_lifecycle_test.go
pkg/true_git/dev_branch.go
pkg/true_git/work_tree.go

based on https://github.com/werf/werf/pull/3037

 [dev] Support staged binary files

---

cmd/werf/bundle/apply/apply.go
cmd/werf/bundle/publish/publish.go
cmd/werf/common/common.go
cmd/werf/common/helpers.go
cmd/werf/converge/converge.go
cmd/werf/main.go
docs/_data/sidebars/_cli.yml
docs/_data/sidebars/documentation.yml
docs/_includes/documentation/reference/cli/werf_bundle_apply.md
docs/_includes/documentation/reference/cli/werf_bundle_apply.short.md
docs/_includes/documentation/reference/cli/werf_bundle_publish.md
docs/_includes/documentation/reference/cli/werf_bundle_publish.short.md
docs/pages/documentation/reference/cli/overview.md
docs/pages/documentation/reference/cli/werf_bundle_apply.md
go.mod
go.sum
pkg/deploy/werf_chart/bundle.go
pkg/deploy/werf_chart/werf_chart.go

Refs https://github.com/werf/helm/pull/75
Refs https://github.com/werf/werf/issues/2712
Refs https://github.com/werf/werf/issues/2694

Introduce initial `werf bundle apply` command

---

go.mod
go.sum

Refs https://github.com/werf/helm/pull/77

Fix "unable to create registry client" error when DOCKER_CONFIG variable is set

---

go.mod
go.sum

Refs https://github.com/werf/helm/pull/78

[bundle] Fix Chart.lock file not unpacked when applying bundle

---

pkg/config/git_remote_export.go
pkg/giterminism_inspector/config/config.go
pkg/giterminism_inspector/config/openapi_spec.go
pkg/giterminism_inspector/config/openapi_spec.yaml
pkg/giterminism_inspector/giterminism_inspector.go

werf-giterminism.yaml
```
giterminismConfigVersion: "1"
config:
stapel:
git:
allowBranch: true
```
rel https://github.com/werf/werf/issues/3046

[giterminism, stapel] Allow git branch

---

cmd/werf/common/common.go
cmd/werf/config/render/render.go
pkg/config/parser.go
pkg/git_repo/base.go
pkg/giterminism_inspector/config/config.go
pkg/giterminism_inspector/config/openapi_spec.go
pkg/giterminism_inspector/config/openapi_spec.yaml
pkg/giterminism_inspector/giterminism_inspector.go
pkg/util/file.go

werf-giterminism.yaml:
```
giterminismConfigVersion: "1"
config:
allowUncommittedTemplates:
- /*/**/
- .werf/template.tmpl
```
rel #3046

[giterminism] Allow uncommitted config templates

---

pkg/deploy/service_values.go

Closes https://github.com/werf/werf/issues/3076

[v1.1] Added .Values.global.werf.version service value with werf cli util version

---

pkg/deploy/werf_chart/service_values.go

Closes https://github.com/werf/werf/issues/3076

Added .Values.global.werf.version service value with werf cli util version

---

docs/_data/channels_versions.json
docs/_includes/installation/binary_linux.md
docs/_includes/installation/binary_macos.md
docs/_includes/installation/binary_windows.md
docs/pages/installation.md
docs/pages_ru/installation.md

[web] Fix links to install a binary package on the install page according to a selected channel

[web] Fix install page

---

pkg/docker_registry/common_api.go
pkg/docker_registry/docker_hub.go
pkg/docker_registry/quay.go

Small cleanups in a `docker_registry` package.

small cleanups in docker_registry

---

docs/_includes/head.html
docs/js/installation.js
docs/pages/installation.md
docs/pages_ru/installation.md
docs/ssi/head.html

[web] Save status of buttons on the install page

[web] Save buttons status on the install page

---

.github/workflows/tests.yml
cmd/werf/bundle/apply/apply.go
cmd/werf/common/common.go
cmd/werf/converge/converge.go
cmd/werf/render/render.go
integration/suites/bundles/bundles_test.go
pkg/deploy/helm/chart_extender/bundle.go
pkg/deploy/helm/chart_extender/extra_values.go
pkg/deploy/helm/chart_extender/werf_chart.go
pkg/deploy/helm/chart_extender/werf_chart_stub.go

Set `.Values.dockerconfigjson` value to be used in the registry Secret to pull images from the repo (https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials).

[bundle] Add --set-docker-config-json-value option

---

go.mod
go.sum
pkg/image/info.go
pkg/storage/local_docker_server_stages_storage.go
pkg/storage/repo_stages_storage.go
pkg/util/strings.go
pkg/util/strings_test.go

Package name suggests that it's something for the reference.
:) https://go-proverbs.github.io/
:) https://www.youtube.com/watch?v=PAAkCSZUG1c&t=9m28s

remove dummy golang/example package

---

pkg/build/conveyor.go

Remove legacy conveyor dockerfile-related functions introduced in the https://github.com/werf/werf/pull/3112

Remove legacy conveyor dockerfile-related functions

---

cmd/werf/common/common.go

Also removed common.GetProjectDir func. Validate project dir is in the git-work-tree in the common.GetGiterminismManager func.

[project-dir] Fix .git lookup should use --dir or process cwd

---

pkg/giterminism_manager/errors/common.go
pkg/giterminism_manager/file_reader/config.go
pkg/giterminism_manager/file_reader/configuration.go
pkg/giterminism_manager/file_reader/errors.go
pkg/giterminism_manager/file_reader/fs.go
pkg/giterminism_manager/file_reader/git.go

- Update error messages
- Uncommitted changes error depends on developer mode and suggests git add command
- build context -> build's context
- The project directory -> the file system
- Remove debug message

[giterminism] Small improvements

---

go.mod
go.sum

https://github.com/werf/helm/pull/81

[1.1] Do not parse values with strict yaml parser to allow usage of anchors

---

docs/_includes/ru/guides/tiles.html

Added the Russian Ruby on Rails guide

[doc] Add Rails guide

---

pkg/git_repo/status/result.go

```
Error: phase build on image jabberchat stage gitArchive handler failed: the submodule "jabberchat" is not clean and must be committed. Do not forget to push the current commit to the submodule remote If this commit exists only locally
Details:
commit:                 "1646050af917404e53b75efa7fcf0ca83a651ea7"
currentWorktreeCommit:  "0000000000000000000000000000000000000000"
expectedWorktreeCommit: "1646050af917404e53b75efa7fcf0ca83a651ea7"
```

[giterminism] Fix processing of an invalid submodule state

---

pkg/build/stage/dockerfile.go
pkg/git_repo/base.go
pkg/git_repo/local.go
pkg/true_git/ls_tree/ls_tree.go
pkg/true_git/ls_tree/result.go

https://github.com/werf/werf/issues/3212

[ls_tree] Do not cache repository and submodule repositories in the result

---

pkg/git_repo/local.go
pkg/git_repo/status/result.go
pkg/git_repo/status/status.go

https://github.com/werf/werf/issues/3212

[status] Do not cache repository and submodules repositories in the result

---

integration/suites/giterminism/suite_test.go
pkg/git_repo/local.go
pkg/giterminism_manager/file_reader/config_go_template.go
pkg/giterminism_manager/file_reader/config_templates.go
pkg/giterminism_manager/file_reader/configuration.go
pkg/giterminism_manager/file_reader/fs.go
pkg/giterminism_manager/file_reader/git.go
pkg/giterminism_manager/file_reader/helm_chart_extender.go
pkg/util/path.go

- Check each file path for the possibility of matching child files
- Get glob prefix without patterns and use it as start directory

[giterminism] Optimize listing files with glob

---

pkg/deploy/helm/chart_extender/service_values.go

Refs https://github.com/werf/werf/issues/3230

Added global .Values.global.werf.name value

---

docs/_includes/ru/guides/tiles.html

[docs] Fix incorrect link to Go guide

[docs] Fix incorrect link to Go guide

---

pkg/git_repo/local.go

Status should always be taken for the user's work tree

[git_repo, status] Fix the use of service work tree when the repository contains submodules

---

cmd/werf/bundle/export/export.go
cmd/werf/bundle/publish/publish.go

Render cmd was used only to initiate loading of chart configuration.
Eliminated render cmd, use loader directly instead.

[bundles] Do not render published chart in bundle-publish and bundle-export commands

---

pkg/deploy/helm/maintenance_helper/maintenance_helper.go

Refs https://github.com/werf/werf/pull/3260

Actualize helm maintenance_helper package changes from v1.1

---

pkg/deploy/helm/maintenance_helper/migrate2to3.go

Do not patch resources to add annotations and labels, because not all resources kinds supports strategic-merge-patch.
Use simple GET, client-side merge, then REPLACE operation (as kubectl edit use).

[helm 2 to 3] Change migration mechanics from PATCH to REPLACE

---

pkg/deploy/helm/maintenance_helper/migrate2to3.go

Changed order of migration steps: first set annotations and labels, then create helm 3 release.

[helm 2 to 3] Fix: ignore resources from helm 2 release which do not exist in kubernetes

---

go.mod
go.sum

- Fix color output in CI jobs
- Update github.com/gookit/color v1.3.5 -> v1.3.7

[go.mod] github.com/werf/logboek v0.5.3

---

integration/suites/giterminism/config_dockerfile_test.go
integration/suites/giterminism/config_go_template_test.go
integration/suites/giterminism/config_stapel_test.go
pkg/giterminism_manager/file_reader/fs.go

Error:
```
unable to locate chart directory: the directory ".helm" not found in the project git repository
```

[giterminism] Fix loose giterminism mode 

---

docs/_includes/topnav-site.html
docs/_includes/topnav.html
docs/_includes/version-menu.html
docs/backend/common.go
docs/backend/handlers.go
docs/backend/main.go

Fix top navigation on the site

[web] Fix topnav

---

.github/workflows/website_converge.yml
docs/_includes/topnav-site.html
docs/backend/httpLog.go

Fix topnav
Add remote IP to backend log

Fix topnav

---

integration/suites/giterminism/config_dockerfile_test.go
integration/suites/giterminism/config_go_template_test.go
integration/suites/giterminism/config_templates_dir_test.go
integration/suites/giterminism/config_test.go
integration/suites/giterminism/giterminism_config_test.go
integration/suites/giterminism/helm_test.go
pkg/git_repo/local.go
pkg/giterminism_manager/file_reader/configuration.go
pkg/giterminism_manager/file_reader/errors.go
pkg/giterminism_manager/file_reader/git.go
pkg/giterminism_manager/inspector/build_context.go
pkg/giterminism_manager/inspector/inspector.go

Refs https://github.com/werf/werf/pull/3303

Revert broken build

---

cmd/werf/bundle/export/export.go
cmd/werf/bundle/publish/publish.go
go.mod
go.sum
pkg/deploy/helm/chart_extender/werf_chart.go

Refs https://github.com/werf/helm/pull/87

[bundles] Fix bundle-publish ignores .helm/values.yaml and uses .helm/secret-values.yaml

---

docs/.werf/feed-group-channel-ru.xml-template
docs/.werf/feed-group-channel.xml-template
docs/pages/banner.html
docs/pages/footer.html
docs/pages/head-common.html
docs/pages/robots.txt
docs/pages/topnav.html
docs/pages_ru/banner.html
docs/pages_ru/footer.html
docs/pages_ru/head-common.html
docs/pages_ru/robots_ru.txt
docs/pages_ru/topnav.html

[docs] Exclude some unnecessary  pages from both sitemaps

[docs] Tune sitemaps

---

.github/workflows/website_converge-tag.yml
.github/workflows/website_converge.yml
.github/workflows/website_review.yml
.github/workflows/website_review_dismiss.yml
docs/_includes/documentation/advanced/ci_cd/github_actions/build_and_publish_note.md
docs/_includes/documentation/advanced/ci_cd/github_actions/cleanup_base.md
docs/_includes/documentation/advanced/ci_cd/github_actions/converge_base.md
docs/_includes/documentation/advanced/ci_cd/github_actions/production_staging_1.md
docs/_includes/documentation/advanced/ci_cd/github_actions/production_staging_2.md
docs/_includes/documentation/advanced/ci_cd/github_actions/production_staging_3.md
docs/_includes/documentation/advanced/ci_cd/github_actions/production_staging_4.md
docs/_includes/documentation/advanced/ci_cd/github_actions/review_1.md
docs/_includes/documentation/advanced/ci_cd/github_actions/review_2.md
docs/_includes/documentation/advanced/ci_cd/github_actions/review_3.md
docs/_includes/documentation/advanced/ci_cd/github_actions/review_base.md
docs/_includes/documentation/advanced/ci_cd/github_actions/review_dismiss_base.md
docs/pages/documentation/advanced/ci_cd/github_actions.md
docs/pages_ru/documentation/advanced/ci_cd/github_actions.md

werf/actions/deploy@master -> werf/actions/deploy@v1.2

Update the version of werf actions

---

docs/_includes/guides/github_ci_cd_integration/build_and_publish_note.md
docs/_includes/guides/github_ci_cd_integration/cleanup_base.md
docs/_includes/guides/github_ci_cd_integration/converge_base.md
docs/_includes/guides/github_ci_cd_integration/production_staging_1.md
docs/_includes/guides/github_ci_cd_integration/production_staging_2.md
docs/_includes/guides/github_ci_cd_integration/production_staging_3.md
docs/_includes/guides/github_ci_cd_integration/production_staging_4.md
docs/_includes/guides/github_ci_cd_integration/review_1.md
docs/_includes/guides/github_ci_cd_integration/review_2.md
docs/_includes/guides/github_ci_cd_integration/review_3.md
docs/_includes/guides/github_ci_cd_integration/review_base.md
docs/_includes/guides/github_ci_cd_integration/review_dismiss_base.md
docs/pages/guides/github_ci_cd_integration.md
docs/pages_ru/guides/github_ci_cd_integration.md

werf/actions/deploy@master -> werf/actions/deploy@v1.1

[v1.1, docs] Update the version of werf actions

---

pkg/build/conveyor.go
pkg/build/stage/dockerfile.go
pkg/build/stage/git_mapping.go
pkg/git_repo/base.go
pkg/git_repo/git_repo.go
pkg/path_matcher/multi_path_matcher.go
pkg/true_git/patch.go

- Fix .dockerignore does not affect on stage digest when using a custom project directory
- Skip files ignored by .dockerignore file creating a context archive
based on #3341

[dockerfile] Skip files ignored by .dockerignore file creating a context archive

---

.github/workflows/website_review.yml
docs/_data/werf_yaml.yml
docs/pages/documentation/advanced/building_images_with_stapel/docker_directive.md
docs/pages/documentation/advanced/ci_cd/gitlab_ci_cd.md
docs/pages/documentation/advanced/supported_container_registries.md
docs/pages/documentation/internals/build_process.md
docs/pages/documentation/internals/development/stapel_image.md
docs/pages/documentation/internals/stages_and_storage.md
docs/werf-site.yaml

[DOCS] Translated two articles

---

docs/_includes/nav-breadcrumbs.html

[web] Fix breadcrumbs

---

pkg/true_git/status/result.go

```
Error: unable to read werf config: the following files must be committed:
- werf.yaml
- werf.yaml
```

[status] Fix duplications in the path list

---

.github/workflows/daily_tests.yml
.github/workflows/docs_tests.yml
.github/workflows/tests.yml
pkg/deploy/helm/maintenance_helper/maintenance_helper.go
scripts/tests/precompiled_tests_binaries.sh

[ci] Tests Workflow: drop out of self-hosted runners

---

.github/workflows/website_converge.yml
.github/workflows/website_converge_tag.yml
.github/workflows/website_converge_test.yml
.github/workflows/website_review.yml
.github/workflows/website_review_dismiss.yml
docs/documentation/.helm/templates/20-ingress.yaml
docs/documentation/werf.yaml
docs/site/.helm/templates/20-ingress.yaml
docs/site/_includes/en/guides/tiles.html
docs/site/_includes/ru/guides/tiles.html
docs/site/_includes/ru/guides_banner.html
docs/site/css/overview.css
docs/site/werf.yaml

[ci] Update workflow
[web] Fix guides style

Update CI, fix guides style

---

docs/_config.yml
docs/_includes/head.html
docs/_includes/nav-breadcrumbs.html
docs/sitemap.xml

[docs] Update page templates to improve SEO

[docs] SEO improvement

---

pkg/host_cleaning/local_docker_server.go

Cleanup only those images/stages, which has been published into REPO stages-storage.
**NOTE.** Werf host cleanup procedure will not cleanup --stages-storage=:local stages, because this is primary stages storage data, and it can only be cleaned by the regular per-project `werf cleanup` command with git-history based algorithm.

[GC] Add support for v1.1 images into host cleanup procedure

---

.github/workflows/validate_repo.yml
.github/workflows/website_converge_test.yml
docs/site/.helm/templates/20-ingress.yaml

[CI] Add commit and PR tests
[CI] Update Certificate template

[CI] Updates

---

pkg/storage/repo_stages_storage.go

This fix particularly needed for the v1.2 host cleanup procedure which can remove freshly built and saved into the stages storage images. In such case should-fetch and stages-storage-manager fetch method will lock an image and perform standard fetch procedure.
Refs https://github.com/werf/werf/pull/3406

[v1.1][GC] Fix StagesStorage ShouldFetch method: perform fresh docker-inspect, do not use cached inspection result from the previous inspect

---

docs/documentation/.werf/nginx.conf
docs/documentation/_includes/sidebar_entry.html
docs/documentation/pages_en/404.md
docs/documentation/pages_ru/404.md

[web] Add a sidebar to the 404 page and make some refactoring.

[web] Update 404 errors reaction

---

docs/site/sitemap.xml

Add sitemap for indexing guide pages

[web] Add guides sitemap

---

pkg/container_runtime/container_runtime.go
pkg/storage/local_docker_server_stages_storage.go
pkg/storage/manager/stages_storage.go
pkg/storage/repo_stages_storage.go
pkg/storage/stages_storage.go

Reject stage when docker-pull have failed with the "blob unknown" error.
Add special record into the stages-storage for such rejected stages.

[v1.1][stapel] Support for rejected stages in the stages storage

---

pkg/storage/manager/stages_storage.go

When some stage has appeared in the repository tags list, but stage image is invalid (due to MANIFEST_UNKNOWN or BLOB_UNKNOWN container registry errors), werf ignores such stage. But this stage-id of such broken stage has been saved into the stages-storage-cache anyway, which is wrong.

[v1.1] Fix saving stages-ids into the stages-storage-cache

---

pkg/build/conveyor_with_retry.go
pkg/docker_registry/api.go
pkg/docker_registry/default.go
pkg/storage/manager/stages_storage.go
pkg/storage/repo_stages_storage.go

Perform rejection of stages for which get-manifest has failed with blob-unknown error.

[builder] Perform rejection of blob-unknown stages

---

.github/workflows/website_converge-tag.yml
.github/workflows/website_converge.yml
.github/workflows/website_review.yml
.github/workflows/website_review_dismiss.yml

[ci] Switch to `ghcr.io` registry. Backport for 1.2.9.

[ci] Switch to GHCR

---

pkg/build/conveyor.go

There is no way to ignore the Dockerfile due to docker limitation when building an image for a compressed context that reads from STDIN.
Add an exception and warning message.

[dockerfile] Automatically reset the Dockerfile exception by .dockerignore file rules

---

pkg/storage/manager/stages_storage.go

During cleanup operation do not raise should-reset-stages-storage-cache error when get stage manifest operation have failed with blob-unknown error.

[cleanup] Ignore blob-unknown errors properly

---

pkg/storage/manager/stages_storage.go

During cleanup operation do not raise should-reset-stages-storage-cache error when get stage manifest operation have failed with blob-unknown error.

[v1.1][cleanup] Ignore blob-unknown errors properly

---

cmd/werf/converge/converge.go
pkg/deploy/helm/maintenance_helper/maintenance_helper.go
pkg/deploy/helm/maintenance_helper/migrate2to3.go

Use history command instead of listing of all releases

[helm2to3] Fix maintenance helper release exists checking procedure performance

---

pkg/build/conveyor.go

First, check for `<DOCKERFILE_DIR>/<DOCKERFILE_BASENAME>.dockerignore`, and if it is found it will be used instead of the `.dockerignore` from the context root.
rel https://github.com/werf/werf/issues/3460

[dockerfile] Add dockerignore override support

---

cmd/werf/compose/main.go

```
werf compose up [options] [--docker-compose-options="OPTIONS"] [--docker-compose-command-options="OPTIONS"] [--] [SERVICE...]
```

[compose] Fix certain service names specified by the user are ignored

---

pkg/git_repo/base.go
pkg/git_repo/git_repo.go
pkg/git_repo/local.go
pkg/git_repo/remote.go

Move common methods from git_repo local/remote to base

---

docs/site/Gemfile
docs/site/Gemfile.lock
docs/site/css/docs.css

- Update the ".details" style
- Update dependencies (Close: https://github.com/werf/werf/pull/3546)

[web] Fix details style, update dependencies

---

docs/documentation/pages_en/quickstart.md
docs/documentation/pages_ru/quickstart.md

https://vote.quickstart-application.example.com
https://result.quickstart-application.example.com

[docs] Improve quickstart: added ingress for registry.example.com and ingress for application

---

go.mod
go.sum

[debug] Catch deployment tracker exited without resource status resolution bug

[v1.1] Revert kubedog debug panic

---

go.mod
go.sum

https://github.com/werf/kubedog/pull/211

feat(kubedog): add support for ErrImageNeverPull

---

cmd/werf/compose/main.go
docs/documentation/_includes/reference/cli/werf_compose_config.md
docs/documentation/_includes/reference/cli/werf_compose_down.md
docs/documentation/_includes/reference/cli/werf_compose_run.md
docs/documentation/_includes/reference/cli/werf_compose_up.md
integration/pkg/utils/docker/container_command.go

Added forgotten cli-options related to host cleanup procedure.

fix(compose): fix host cleanup gc panics in werf compose command

---

cmd/werf/ci_env/ci_env.go
cmd/werf/dismiss/dismiss.go
cmd/werf/managed_images/add/add.go
cmd/werf/managed_images/rm/rm.go
cmd/werf/stage/image/main.go
docs/documentation/_includes/reference/cli/werf_ci_env.md
docs/documentation/_includes/reference/cli/werf_dismiss.md
docs/documentation/_includes/reference/cli/werf_helm_install.md
docs/documentation/_includes/reference/cli/werf_helm_pull.md
docs/documentation/_includes/reference/cli/werf_helm_repo_add.md
docs/documentation/_includes/reference/cli/werf_helm_show_all.md
docs/documentation/_includes/reference/cli/werf_helm_show_chart.md
docs/documentation/_includes/reference/cli/werf_helm_show_readme.md
docs/documentation/_includes/reference/cli/werf_helm_show_values.md
docs/documentation/_includes/reference/cli/werf_helm_template.md
docs/documentation/_includes/reference/cli/werf_helm_upgrade.md
docs/documentation/_includes/reference/cli/werf_managed_images_add.md
docs/documentation/_includes/reference/cli/werf_managed_images_rm.md

Fixed uninitialized --platform param setup code.

fix: panic in ci-env, dismiss, managed-images and stage-image cmds

---

pkg/cleaning/images_cleanup_reference_to_scan.go

```
Error: resolve revision NESTED_TAG_NAME failed: unsupported object type
```
rel https://github.com/go-git/go-git/issues/361

fix(v1.1, cleanup): nested git tag cannot be processed

---

pkg/cleaning/git_history_based_cleanup/reference_to_scan.go

```
Error: resolve revision NESTED_TAG_NAME failed: unsupported object type
```
rel https://github.com/go-git/go-git/issues/361

fix(cleanup): nested git tag cannot be processed

---

pkg/docker_registry/github_packages.go
pkg/docker_registry/github_packages_api.go

rel https://github.community/t/pagination-when-listing-image-tags-does-not-work/194586

fix(container_registry): pagination when listing image tags in ghcr.io repository does not work

---

cmd/werf/bundle/export/export.go
pkg/deploy/helm/chart_extender/werf_chart.go

rel https://github.com/werf/werf/issues/3651

fix(bundles): export failed with stacktrace when destination not defined

---

go.mod
go.sum

https://github.com/helm/helm/pull/10085
https://github.com/werf/helm/pull/101

fix: "... has no deployed releases" error when release history limit reached on initial release installation

---

pkg/host_cleaning/local_docker_server.go

- Remove image by either: RepoTags, RepoDigests or ID.
- Added loop hanging protection for images and containers: do not try to remove image or container by an ID, if we've already tried to delete this object.

fix(host-cleanup): fix host cleanup procedure hangs in a loop

---

cmd/werf/common/synchronization.go
docs/documentation/_includes/reference/cli/werf_bundle_publish.md
pkg/storage/synchronization.go

Refs https://github.com/werf/werf/pull/3705

fix: corrections for KUBECONFIG config path merge list support for --synchronization kubernetes param

---

cmd/werf/cleanup/cleanup.go
cmd/werf/purge/purge.go
docs/documentation/_includes/reference/cli/werf_purge.md
pkg/build/conveyor_with_retry.go
pkg/storage/manager/storage_manager.go

Automatically reset stages storage cache in the werf-cleanup and werf-purge commands as in werf-build.

fix(cleanup): fix "should reset storage cache" error during werf-cleanup and werf-purge

---

pkg/git_repo/base.go

Reinit go-git repository when "object not found" or "packfile not found" error occured

chore(build): debug "object not found" and "packfile not found" errors

---

go.mod
go.sum
integration/suites/deploy/atomic_resources_update_process_test.go

Fixes https://github.com/werf/werf/issues/3461
Fixes https://github.com/werf/werf/issues/3462
Refs https://github.com/werf/helm/pull/119

fix(deploy): fix broken 3 way merge cases

---

cmd/werf/common/common.go

Added WERF_STATUS_PROGRESS_PERIOD and WERF_HOOKS_STATUS_PROGRESS_PERIOD environment variables in addition to WERF_STATUS_PROGRESS_PERIOD_SECONDS and WERF_HOOKS_STATUS_PROGRESS_PERIOD_SECONDS.

fix(deploy): status-progress-period and hooks-status-progress-period params fix

---

multiwerf.json
scripts/werf-in-image/fedora.Dockerfile
scripts/werf-in-image/werf.yaml
trdl_channels.yaml

Also revert fedora to fedora-minimal image.

chore: v1.2 alpha,beta,ea,stable to v1.2.51

---

cmd/werf/build/main.go
cmd/werf/bundle/apply/apply.go
cmd/werf/bundle/publish/publish.go
cmd/werf/converge/converge.go
cmd/werf/run/run.go
pkg/werf/global_warnings/global_warnings.go

feat(multiwerf): print multiwerf deprecation warning if multiwerf outdated

---

cmd/werf/build_and_publish/main.go
cmd/werf/converge/converge.go
cmd/werf/deploy/main.go
cmd/werf/deploy_v2/main.go
cmd/werf/images/publish/cmd_factory/main.go
cmd/werf/run/run.go
cmd/werf/stages/build/cmd_factory/main.go
pkg/werf/global_warnings.go

1.1: feat(multiwerf): print multiwerf deprecation warning if multiwerf outdated

---

cmd/werf/build/main.go
cmd/werf/build_and_publish/main.go
cmd/werf/converge/converge.go
cmd/werf/deploy/main.go
cmd/werf/deploy_v2/main.go
cmd/werf/images/publish/cmd_factory/main.go
cmd/werf/run/run.go
cmd/werf/stages/build/cmd_factory/main.go
pkg/werf/global_warnings.go

1.1: feat(deprecation): add deprecation warning for werf v1.1

---

pkg/true_git/init.go

* Ignore stderr from `git version`
* More reliable git version parsing based on regex

fix: warning in `git version` breaks werf

---

docs/_data/breadcrumbs.yml
docs/_data/sidebars/_documentation.yml
docs/pages_en/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_docker_executor.md
docs/pages_ru/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.md

Adding menu for Russian articles. Fixing menu names for English articles.

docs: Fixing menu for Run in containers articles

---

cmd/werf/common/common.go
pkg/build/stage/git_mapping.go
pkg/config/parser.go
pkg/git_repo/base.go
pkg/git_repo/git_repo.go
pkg/git_repo/local.go
pkg/git_repo/remote.go
pkg/git_repo/repo_handle/handle.go
pkg/git_repo/repo_handle/interface.go

New Map `{{ .Commit }}` available in werf.yaml.

feat(build): expose commit info in werf templates

---

pkg/build/build_phase.go

Expose commit info env vars in build containers.

feat(build): commit info in build container

---

pkg/build/stage/dockerfile.go

fixes https://github.com/werf/werf/issues/3938

fix(build): multi-stage does not work properly with build args

---

docs/pages_en/using_with_ci_cd_systems.md
docs/pages_ru/using_with_ci_cd_systems.md

docs: add missing space in shell command

---

pkg/config/dependency.go

fix(images-dependencies): forbid after/before for dockerfile deps

---

pkg/config/config_suite_test.go

test(config): migrate to ginkgo v2

---

docs/_data/werf_yaml.yml

feat(images-imports): added reference docs

---

multiwerf.json
trdl_channels.yaml

chore(channels): 1.2 alpha/beta 1.2.61

---

pkg/config/raw_image_from_dockerfile_test.go
pkg/config/raw_stapel_image_test.go
pkg/config/stubs_test.go

test(images-dependencies): config integration

---

multiwerf.json
trdl_channels.yaml

chore(channels): 1.2 alpha/beta to 1.2.62

---

pkg/deploy/helm/chart_extender/helpers/chart_template_helpers.go

fix(bundles): remove incompatibility with helm 3

---

trdl_channels.yaml

chore(channels): 1.2 alpha to 1.2.63 (try again)

---

pkg/cleaning/cleanup.go

chore(cleanup): log custom tags info

---

pkg/true_git/git_cmd_test.go
pkg/true_git/service_branch_test.go

refator(test): set default init git branch

---

multiwerf.json
trdl_channels.yaml

chore(channels): 1.2 alpha/beta to 1.2.65

---

docs/pages_en/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.md
docs/pages_ru/advanced/ci_cd/run_in_container/use_gitlab_ci_cd_with_kubernetes_executor.md

docs(kubernetes-executor): fix instructions

---

cmd/werf/common/common.go
docs/_includes/reference/cli/werf_build.md
docs/_includes/reference/cli/werf_bundle_export.md
docs/_includes/reference/cli/werf_bundle_publish.md
docs/_includes/reference/cli/werf_cleanup.md
docs/_includes/reference/cli/werf_converge.md
docs/_includes/reference/cli/werf_purge.md
docs/_includes/reference/cli/werf_render.md

chore(cli): update parallel option description

---

cmd/werf/config/graph/graph.go
cmd/werf/main.go
docs/_data/sidebars/_cli.yml
docs/_data/sidebars/documentation.yml
docs/_includes/reference/cli/werf_config_graph.md
docs/_includes/reference/cli/werf_config_graph.short.md
docs/pages_en/reference/cli/overview.md
docs/pages_en/reference/cli/werf_config_graph.md
pkg/config/werf.go

```yaml
$ werf config graph
- image: app1
dependsOn:
from: baseImage
- image: app2
dependsOn:
from: baseImage
import:
- app1
- image: baseImage
$ werf config graph app
- image: app2
dependsOn:
from: baseImage
import:
- app1
```

feat(config): dependency graph for werf.yaml images

---

pkg/storage/repo_stages_storage.go

fix(cleanup): odd warning message with a nonexistent tag
